---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SANtricity CLI 문서
    url: "/index.html"
  - title: 새로운 소식
    url: "/whats-new.html"
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
