---
permalink: get-started/command-line-parameters.html 
sidebar: sidebar 
keywords: legacy, command line, parameters 
summary: SANtricity OS 11.40 릴리즈에는 웹 서비스가 내장된 E2800 및 E5700 컨트롤러용으로 보안 HTTPS 프로토콜을 사용하여 명령줄에서 상호 작용할 수 있는 기능이 도입되었습니다. 이러한 컨트롤러는 명령줄 상호 작용에 기호 프로토콜을 대신 사용할 수도 있습니다. 
---
= 레거시 SANtricity CLI 명령줄 매개변수에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity OS 11.40 릴리즈에는 웹 서비스가 내장된 E2800 및 E5700 컨트롤러용으로 보안 HTTPS 프로토콜을 사용하여 명령줄에서 상호 작용할 수 있는 기능이 도입되었습니다. 이러한 컨트롤러는 명령줄 상호 작용에 기호 프로토콜을 대신 사용할 수도 있습니다.



== 11.53 및 이전 명령줄 매개변수

기호 프로토콜은 E2700 및 E5600 컨트롤러에서 지원되는 유일한 프로토콜입니다. 기존 스크립트를 보존하고 전환 시간을 최소화하기 위해 CLI 옵션과 문법은 최대한 보존됩니다. 하지만 보안, 인증, AutoSupport, 경고 메시지와 관련하여 해당 컨트롤러에 대해 일부 CLI 문법을 렌더링하는 E2800 및 E5700 컨트롤러의 기능에는 몇 가지 차이가 있습니다. 그러나 새로운 https 프로토콜을 사용할 경우 E2800 또는 E5700에서는 문법이 사용되지 않을 수도 있습니다.

' * https * ' 클라이언트 유형에만 적용되는 새로운 매개 변수의 경우 E2800 또는 E5700 컨트롤러에만 적용됩니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
'-clientType'
 a| 
이 인수를 사용하면 적절한 스크립트 엔진이 생성됩니다. 다음 값 중 하나와 함께 이 선택적 매개 변수를 사용합니다.

* '* auto*' - 적절한 스크립트 엔진 유형을 감지하기 위해 장치 검색이 자동으로 수행됩니다.
* '* https*' - REST 기반 스크립트 엔진이 만들어집니다.
* '* symbol*' - 기호 기반 스크립트 엔진이 만들어집니다.




 a| 
'-u'
 a| 
'_username_' 변수를 사용하여 이 매개변수를 따르십시오. 사용자 이름은 '* https*' 클라이언트 유형에만 필요합니다. 이 인수는 '* symbol*' 클라이언트 유형에 적용할 수 없으며 자동으로 무시됩니다.

username 인수를 지정하면 장치 검색을 수행하여 올바른 클라이언트 유형("* https*" 대)을 확인합니다 ' * symbol * ').



 a| 
'-P'
 a| 
이 인수에는 다음 두 인수 중 하나가 필요합니다.

* '_PASSWORD_FILE_' - 인증에 사용할 암호를 포함합니다.
* '-'(대시 하나) - '스타딘'에서 암호를 읽습니다.


이 인수의 추가는 '* https*' 클라이언트 유형 또는 '* symbol*' 클라이언트 유형의 사용 여부와 관계없이 모든 컨트롤러에 적용됩니다.



 a| 
'-k'
 a| 
이 선택적 인수를 사용하면 '* https*' 클라이언트가 안전하지 않은 모드로 작동할 수 있습니다. 즉, 스토리지 어레이의 인증서가 검증되지 않습니다. 기본적으로 이 인수를 생략하면 적절한 인증이 수행됩니다. 이 인수는 '* symbol*' 클라이언트 유형에 적용할 수 없으며 자동으로 무시됩니다.

|===


== E2700 또는 E5600 컨트롤러에만 적용되는 명령줄 매개 변수입니다

E2700 및 E5600 컨트롤러에는 알림 관리 기능이 내장되어 있지 않으므로 이러한 명령줄 매개 변수를 적용할 수 있습니다. 이러한 매개 변수는 E2800 또는 E5700 컨트롤러에는 적용되지 않습니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
``A’
 a| 
SNMP(Simple Network Management Protocol) 트랩 대상 또는 e-메일 주소 경고 대상을 추가합니다.

* SNMP 트랩 대상을 추가하면 SNMP 커뮤니티가 트랩의 커뮤니티 이름으로 자동 정의되고 "* host*"는 트랩이 전송될 시스템의 IP 주소 또는 DNS(Domain Name Server) 호스트 이름입니다.
* 경고 대상에 대한 이메일 주소를 추가할 때, 경고 메시지를 보낼 이메일 주소는 '* email-address*'입니다.


[NOTE]
====
이 명령줄 옵션은 E2800 및 E5700 스토리지 어레이에 사용되지 않습니다. RESTful API, SANtricity System Manager 또는 curl 명령을 사용합니다.

====


 a| 
'-m'
 a| 
e-메일 경고 알림을 보내는 e-메일 서버의 호스트 이름 또는 IP 주소를 지정합니다.

[NOTE]
====
이 명령줄 옵션은 E2800 및 E5700 스토리지 어레이에 사용되지 않습니다. RESTful API, SANtricity System Manager 또는 curl 명령을 사용합니다.

====


 a| 
'-s'(소문자)
 a| 
는 '-d' 매개변수와 함께 사용할 때 구성 파일의 경고 설정을 표시합니다.

[NOTE]
====
이 명령줄 옵션은 E2800 및 E5700 스토리지 어레이에 사용되지 않습니다. RESTful API, SANtricity System Manager 또는 curl 명령을 사용합니다.

====


 a| 
'-x'(소문자)
 a| 
SNMP 트랩 대상 또는 e-메일 주소 경고 대상을 제거합니다. '_community_'는 트랩의 SNMP 커뮤니티 이름이고, '_host_'는 트랩을 보낼 시스템의 IP 주소 또는 DNS 호스트 이름입니다.

[NOTE]
====
이 명령줄 옵션은 E2800 및 E5700 스토리지 어레이에 사용되지 않습니다. RESTful API, SANtricity System Manager 또는 curl 명령을 사용합니다.

====
|===


== 심볼 클라이언트 유형으로 실행되는 모든 컨트롤러에 적용되는 명령줄 매개 변수입니다

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
'-R'(대문자)
 a| 
암호의 사용자 역할을 정의합니다. 역할은 다음 중 하나일 수 있습니다.

* '* admin*' -- 사용자에게 스토리지 배열 구성을 변경할 수 있는 권한이 있습니다.
* '* monitor*' -- 사용자에게 스토리지 배열 구성을 볼 수 있는 권한이 있지만 변경할 수 없습니다.


'*-R*' 매개변수는 스토리지 배열의 암호를 정의하도록 지정하는 '*–p*' 매개변수와 함께 사용할 때만 유효합니다.

스토리지 배열에서 이중 암호 기능이 활성화된 경우에만 '*-R*' 매개변수가 필요합니다. 다음 조건에서는 '*-R*' 매개변수가 필요하지 않습니다.

* 스토리지 배열에서 이중 암호 기능이 활성화되지 않았습니다.
* 스토리지 시스템에 대해 관리자 역할이 하나만 설정되어 있고 모니터 역할이 설정되어 있지 않습니다.


|===


== 모든 컨트롤러 및 모든 클라이언트 유형에 적용되는 명령줄 매개 변수입니다

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
'_host-name-or-ip-address _'
 a| 
대역내 관리형 스토리지 배열 또는 대역외 관리 스토리지 배열의 호스트 이름 또는 인터넷 프로토콜(IP) 주소('_xxx.xxx.xxx.xxx_')를 지정합니다.

* 대역내 스토리지 관리를 통해 호스트를 사용하여 스토리지 배열을 관리하는 경우 호스트에 둘 이상의 스토리지 배열이 연결되어 있는 경우 '-n' 매개 변수 또는 '-w' 매개 변수를 사용해야 합니다.
* 각 컨트롤러의 이더넷 연결을 통해 대역외 스토리지 관리를 사용하여 스토리지 어레이를 관리하는 경우 컨트롤러의 '_host-name-or-ip-address_'를 지정해야 합니다.
* 이전에 Enterprise Management Window에서 스토리지 배열을 구성한 경우, '-n' 매개변수를 사용하여 사용자가 지정한 이름으로 스토리지 배열을 지정할 수 있습니다.
* 이전에 Enterprise Management Window에서 스토리지 배열을 구성한 경우, '-w' 매개변수를 사용하여 WWID(World Wide Identifier)로 스토리지 배열을 지정할 수 있습니다.




 a| 
``A’
 a| 
구성 파일에 스토리지 배열을 추가합니다. '_host-name-or-ip-address_'가 있는 '-a' 매개 변수를 따르지 않으면 자동 검색 기능이 로컬 서브넷에서 스토리지 배열을 검색합니다.



 a| 
'-c'
 a| 
지정된 스토리지 배열에서 실행할 스크립트 명령을 하나 이상 입력하고 있음을 나타냅니다. 각 명령을 세미콜론(';')으로 종료합니다. 동일한 명령줄에 둘 이상의 '-c' 매개 변수를 배치할 수 없습니다. '-c' 매개 변수 뒤에 둘 이상의 스크립트 명령을 포함할 수 있습니다.



 a| 
'-d'
 a| 
스크립트 구성 파일의 내용을 표시합니다. 파일 내용의 형식은 '_storage-system-name host-name1 host-name2_'입니다



 a| 
'-e'
 a| 
구문 검사를 먼저 수행하지 않고 명령을 실행합니다.



 a| 
'-F'(대문자)
 a| 
모든 알림을 보낼 e-메일 주소를 지정합니다.



 a| 
'-f'(소문자)
 a| 
지정된 스토리지 배열에서 실행할 스크립트 명령이 포함된 파일 이름을 지정합니다. '-f' 파라미터는 스크립트 명령어를 실행하기 위한 것이라는 점에서 '-c' 파라미터와 유사하다. '-c' 매개변수는 개별 스크립트 명령어를 실행합니다. '-f' 파라미터는 스크립트 명령어 파일을 실행한다. 기본적으로 파일에서 스크립트 명령을 실행할 때 발생하는 모든 오류는 무시되고 파일은 계속 실행됩니다. 이 동작을 무시하려면 스크립트 파일에서 'show session errorAction=stop' 명령을 사용합니다.



 a| 
'-g'
 a| 
모든 e-메일 경고 알림에 포함될 e-메일 보낸 사람 연락처 정보가 포함된 ASCII 파일을 지정합니다. CLI에서는 ASCII 파일이 텍스트 전용이며 구분 기호 또는 예상되는 형식이 없다고 가정합니다. userdata.txt 파일이 존재하는 경우에는 '-g' 파라미터를 사용하지 마십시오.



 a| 
'-h'
 a| 
스토리지 배열이 연결되어 있는 SNMP 에이전트를 실행 중인 호스트 이름을 지정합니다. 다음 매개변수와 함께 '-h' 매개변수를 사용합니다.

* ``A’
* '-x'




 a| 
'-I'(대문자)
 a| 
e-메일 알림 알림에 포함할 정보 유형을 지정합니다. 다음 값을 선택할 수 있습니다.

* e메일 내용에는 이벤트 정보만 포함돼 있습니다.
* 프로필=e-메일에는 이벤트와 스토리지 프로필 정보가 포함되어 있습니다.


'-q' 매개 변수를 사용하여 이메일 전달 빈도를 지정할 수 있습니다.



 a| 
'-I'(소문자)
 a| 
에는 알려진 스토리지 시스템의 IP 주소가 나와 있습니다. '-i' 파라미터를 '-d' 파라미터와 함께 사용합니다. 파일 내용은 '_storage-system-name ip-address1 IPaddress2_' 형식으로 되어 있습니다



 a| 
'-n'
 a| 
스크립트 명령을 실행할 스토리지 배열의 이름을 지정합니다. 이 이름은 '_host-name-or-ip-address_'를 사용할 때 선택 사항입니다. 스토리지 배열을 관리하기 위해 대역내 방법을 사용하는 경우, 지정된 주소에 있는 호스트에 둘 이상의 스토리지 배열이 연결되어 있는 경우 '-n' 매개변수를 사용해야 합니다. '_host-name 또는 -ip-address_'를 사용하지 않는 경우 스토리지 배열 이름이 필요합니다. Enterprise Management Window(엔터프라이즈 관리 창)에서 사용하도록 구성된 스토리지 배열의 이름(즉, 구성 파일에 이름이 나열됨)은 구성된 다른 스토리지 배열의 중복 이름이 아니어야 합니다.



 a| 
'-o'
 a| 
스크립트 명령을 실행한 결과에 해당하는 모든 출력 텍스트의 파일 이름을 지정합니다. 다음 매개변수와 함께 '-o' 매개변수를 사용합니다.

* '-c'
* "-f"


출력 파일을 지정하지 않으면 출력 텍스트가 표준 출력(stdout)으로 이동합니다. 스크립트 명령이 아닌 명령의 모든 출력은 이 매개 변수의 설정 여부에 관계없이 stdout에 전송됩니다.



 a| 
'-p'
 a| 
명령을 실행할 스토리지 배열의 암호를 정의합니다. 다음과 같은 조건에서는 암호가 필요하지 않습니다.

* 스토리지 배열에 암호가 설정되어 있지 않습니다.
* 암호는 실행 중인 스크립트 파일에 지정됩니다.
* '-c' 매개변수와 다음 명령을 사용하여 암호를 지정합니다.


[listing]
----
set session password=password
----


 a| 
'-P'
 a| 
이 인수에는 다음 두 인수 중 하나가 필요합니다.

* '_PASSWORD_FILE_' - 인증에 사용할 암호를 포함합니다.
* '-'(대시) - '스댕'에서 암호를 읽습니다.


이 인수의 추가는 '* https*' 클라이언트 유형 또는 '* symbol*' 클라이언트 유형의 사용 여부와 관계없이 모든 컨트롤러에 적용됩니다.



 a| 
'-q'
 a| 
이벤트 알림을 수신할 빈도와 이벤트 알림에 반환되는 정보 유형을 지정합니다. 모든 중요 이벤트에 대해 최소 기본 이벤트 정보가 포함된 e-메일 경고 알림이 항상 생성됩니다. 이 값은 '-q' 파라미터에 유효합니다.

* 모든 이벤트 - e메일 알림 때마다 정보가 반환됩니다.
* 2-2시간마다 한 번 이상 정보가 반환됩니다.
* 4시간=4시간마다 한 번 이상 정보가 반환됩니다.
* 8시간=8시간마다 한 번 이상 정보가 반환됩니다.
* 12시간 -- 12시간마다 한 번 이상 정보가 반환됩니다.
* 24시간=24시간마다 한 번 이상 정보가 반환됩니다.


'-i' 파라미터를 사용하면 e-메일 알림 메시지에 정보 유형을 지정할 수 있습니다.

* '-i' 매개변수를 'eventOnly'로 설정하면 '-q' 매개 변수에 대해 유효한 값은 'everyEvent'뿐입니다.
* '-i' 파라미터를 'profile' 값 또는 'upportBundle' 값으로 설정하면 이 정보가 '-q' 파라미터에 지정된 빈도로 이메일에 포함됩니다.




 a| 
'-quick'
 a| 
단일 라인 작업을 실행하는 데 필요한 시간을 줄입니다. 단일 행 작업의 예로는 "스냅샷 볼륨 생성" 명령을 들 수 있습니다. 이 매개 변수는 명령의 지속 시간 동안 백그라운드 프로세스를 실행하지 않으므로 시간을 줄입니다. 하나 이상의 단일 행 작업이 포함된 작업에는 이 매개 변수를 사용하지 마십시오. 이 명령을 광범위하게 사용하면 컨트롤러가 처리할 수 있는 명령보다 더 많은 명령으로 컨트롤러를 오버런할 수 있으며, 이로 인해 작동 오류가 발생할 수 있습니다. 또한 일반적으로 백그라운드 프로세스에서 수집된 상태 업데이트 및 구성 업데이트는 CLI에서 사용할 수 없습니다. 이 매개 변수는 배경 정보에 의존하는 작업이 실패하도록 합니다.



 a| 
'-S'(대문자)
 a| 
스크립트 명령을 실행할 때 나타나는 명령 진행률을 설명하는 정보 메시지를 표시하지 않습니다. (정보 메시지를 표시하지 않는 것을 무음 모드라고도 합니다.) 이 매개 변수는 다음 메시지를 표시하지 않습니다.

* "구문 검사 수행 중"
* '인두 확인 완료
* "스크립트 실행 중"
* '스크립트 실행 완료'
* 'Mcli가 성공적으로 완료되었습니다.




 a| 
`-useLegacyTransferPort`
 a| 
전송 포트를 로 설정하는 데 사용됩니다 `8443` 기본값 대신 `443`.



 a| 
'-v'
 a| 
'-d' 매개변수와 함께 사용할 경우 구성 파일에 있는 알려진 장치의 현재 전역 상태를 표시합니다.



 a| 
'-w'
 a| 
스토리지 배열의 WWID를 지정합니다. 이 파라미터는 '-n' 파라미터를 대체하는 파라미터이다. 알려진 스토리지 배열의 WWID를 표시하려면 '-d' 매개 변수와 함께 '-w' 매개 변수를 사용합니다. 파일 내용은 '_storage-system-name world-wide-ID IP-address1 IP-address2_' 형식으로 되어 있습니다



 a| 
'-X'(대문자)
 a| 
구성에서 스토리지 배열을 삭제합니다.



 a| 
'-?
 a| 
CLI 명령에 대한 사용 정보를 표시합니다.

|===