---
permalink: get-started/detailed-error-reporting.html 
sidebar: sidebar 
keywords: detailed, error, report 
summary: CLI에서 발생한 오류로부터 수집된 데이터는 파일에 기록됩니다. 
---
= 자세한 오류 보고
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


CLI에서 발생한 오류로부터 수집된 데이터는 파일에 기록됩니다. CLI에서 자세한 오류 보고 기능은 다음과 같습니다.

* CLI 명령 및 스크립트 명령 실행이 비정상적으로 종료되는 경우 CLI가 완료되기 전에 오류 데이터가 수집되고 저장됩니다.
* CLI는 데이터를 표준 파일 이름에 쓰도록 하여 오류 데이터를 저장합니다.
* CLI는 자동으로 데이터를 파일에 저장합니다. 오류 데이터를 저장하기 위해 특수 명령줄 옵션이 필요하지 않습니다.
* 오류 데이터를 파일에 저장하기 위한 작업을 수행할 필요가 없습니다.
* CLI에는 오류 데이터가 포함된 파일의 기존 버전을 과도하게 쓰지 않도록 하는 조항이 없습니다.


오류 처리의 경우 오류는 두 가지 유형으로 나타납니다.

* 입력할 수 있는 터미널 오류 또는 구문 오류입니다.
* 운영 오류로 인해 발생하는 예외입니다.


CLI에서 두 가지 유형의 오류가 발생하면 CLI는 오류를 설명하는 정보를 명령줄에 직접 쓰고 반환 코드를 설정합니다. 반환 코드에 따라 CLI는 오류를 발생시킨 터미널에 대한 추가 정보도 작성할 수 있습니다. 또한 CLI는 명령 구문에서 예상한 내용에 대한 정보를 작성하므로 입력한 구문 오류를 쉽게 식별할 수 있습니다.

명령이 실행되는 동안 예외가 발생하면 CLI에서 오류를 캡처합니다. 명령 처리 완료 시(명령 처리 정보가 명령줄에 기록된 후) CLI는 오류 정보를 파일에 자동으로 저장합니다.

오류 정보가 저장되는 파일의 이름은 excprpt.txt입니다. CLI는 시스템 속성 devmgr.datadir 에 지정된 디렉터리에 excprpt.txt 파일을 배치하려고 합니다. CLI가 devmgr.datadir로 지정된 디렉터리에 파일을 저장할 수 없는 경우 CLI가 실행 중인 디렉터리에 excprpt.txt 파일이 저장됩니다. 파일 이름 또는 위치를 변경할 수 없습니다. 예외가 발생할 때마다 excprpt.txt 파일이 덮어쓰여집니다. 이 정보를 "excprpt.txt" 파일에 저장하려면 새 파일이나 새 디렉토리에 복사해야 합니다.
