---
permalink: get-started/downloadable-smcli-parameters.html 
sidebar: sidebar 
keywords: downloadable, smcli, command line, parameters, identify, devices, SAML, multifactor, authentication, https, certificate, array, 
summary: 'SANtricity OS 11.60 이상 릴리즈에는 SANtricity System Manager를 통해 http 기반 버전의 CLI(Secure CLI 또는 SMcli라고도 함)를 직접 다운로드하고 설치할 수 있는 기능이 포함되어 있습니다.' 
---
= 다운로드 가능한 SANtricity Secure CLI(SMcli) 매개변수에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity OS 11.60 이상 릴리즈에는 SANtricity System Manager를 통해 http 기반 버전의 CLI("Secure CLI" 또는 SMcli라고도 함)를 직접 다운로드하고 설치할 수 있는 기능이 포함되어 있습니다.



== 11.60 이상 다운로드 가능한 SMcli 명령줄 매개변수

SMcli의 다운로드 가능한 버전은 E4000, EF600, EF300, E5700, EF570, E2800, EF280, EF300C 및 EF600C 컨트롤러에서 사용할 수 있습니다. SANtricity 시스템 관리자 내에서 SMcli를 다운로드하려면 * 설정 * * * 시스템 * 및 * 추가 기능 * * 명령줄 인터페이스 * 를 선택합니다.


NOTE: CLI 명령을 실행하려는 관리 시스템에서 Java Runtime Environment(JRE) 버전 8 이상을 사용할 수 있어야 합니다.

이전 버전의 SMcli와 마찬가지로 SANtricity System Manager를 통해 다운로드할 수 있는 SMcli에는 고유한 매개변수 세트가 있습니다. SANtricity OS 11.53 및 이전 릴리스에 대한 명령줄 매개 변수 사용에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/e-series-cli/get-started/command-line-parameters.html["레거시 명령줄 매개변수"].



=== 다단계 인증

SAML(Security Assertion Markup Language)이 활성화된 경우 액세스 토큰만 CLI에서 사용할 수 있습니다. SAML이 활성화되지 않은 경우 사용자 이름/암호 또는 액세스 토큰을 사용할 수 있습니다. 액세스 토큰은 SANtricity 시스템 관리자를 통해 생성할 수 있습니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
`-t`
 a| 
스토리지 시스템에서 인증에 사용할 액세스 토큰을 정의합니다. 액세스 토큰은 사용자 이름과 암호를 제공하는 대체 토큰입니다.



 a| 
`-T` (대문자)
 a| 
이 인수에는 다음 두 인수 중 하나가 필요합니다.

* `access_token-file` - 인증에 사용할 액세스 토큰을 포함합니다
* `-(dash)` - stdin에서 액세스 토큰을 읽습니다




 a| 
'-u'
 a| 
에 이 매개 변수를 따릅니다 `_username_` 변수. 이 매개 변수는 액세스 토큰을 사용하지 않을 때마다 필요합니다.



 a| 
'-p'
 a| 
명령을 실행할 스토리지 배열의 암호를 정의합니다. 다음과 같은 조건에서는 암호가 필요하지 않습니다.

* 스토리지 배열에 암호가 설정되어 있지 않습니다.
* 암호는 실행 중인 스크립트 파일에 지정됩니다.




 a| 
`-P` (대문자)
 a| 
이 인수에는 다음 두 인수 중 하나가 필요합니다.

* '_PASSWORD_FILE_' - 인증에 사용할 암호를 포함합니다.
* '-'(대시 하나) - '스타딘'에서 암호를 읽습니다.


|===


=== 일반 https 모드 명령줄 매개 변수입니다

다운로드 가능한 SMcli는 https 모드만 지원합니다. 다음은 https 모드에 대해 일반적으로 사용되는 명령줄 매개 변수입니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
'_host-name-or-ip-address _'
 a| 
호스트 이름 또는 IP(인터넷 프로토콜) 주소를 지정합니다 (`_xxx.xxx.xxx.xxx_`)를 선택합니다.

각 컨트롤러의 이더넷 연결을 통해 대역외 스토리지 관리를 관리하는 경우 를 지정해야 합니다 `_host-name-or-IP-address_` 합니다.



 a| 
'-k'
 a| 
이 선택적 인수를 사용하면 가 허용됩니다 `*https*` 클라이언트가 안전하지 않은 모드로 작동합니다. 즉, 스토리지 어레이의 인증서가 검증되지 않습니다. 기본적으로 이 인수를 생략하면 적절한 유효성 검사가 수행됩니다.


NOTE: 스토리지 배열 인증서 관리에 대한 자세한 내용은 를 참조하십시오 <<storedcertificates,저장된 인증서 관리 명령줄 매개 변수입니다>>.



 a| 
'-e'
 a| 
구문 검사를 먼저 수행하지 않고 명령을 실행합니다.



 a| 
`-L` (대문자)
 a| 
다운로드 가능한 SMcli에 대한 법적 고지 사항을 표시합니다.



 a| 
'-n'
 a| 
스크립트 명령을 실행할 로컬에 저장된 레이블을 지정합니다. 이 옵션은 를 사용할 때 선택 사항입니다 `_host-name-or-IP-address_`. 에 로컬로 저장된 레이블이 필요합니다 `_host-name-or-IP-address_` 사용되지 않습니다.


NOTE: 로컬에 저장된 레이블을 사용하여 스토리지 배열을 관리하는 방법에 대한 자세한 내용은 을 참조하십시오 <<managearrays,저장된 배열 관리 명령줄 매개변수>>.



 a| 
'-o'
 a| 
스크립트 명령을 실행한 결과에 해당하는 모든 출력 텍스트의 파일 이름을 지정합니다. 다음 매개변수와 함께 '-o' 매개변수를 사용합니다.

* '-c'
* "-f"


출력 파일을 지정하지 않으면 출력 텍스트가 표준 출력으로 이동합니다  `stdout`)를 클릭합니다. 스크립트 명령이 아닌 명령의 모든 출력이 로 전송됩니다 `stdout`, 이 매개 변수의 설정 여부에 관계없이 .



 a| 
'-S'(대문자)
 a| 
스크립트 명령을 실행할 때 나타나는 명령 진행률을 설명하는 정보 메시지를 표시하지 않습니다. (정보 메시지를 표시하지 않는 것을 무음 모드라고도 합니다.) 이 매개 변수는 다음 메시지를 표시하지 않습니다.

* "구문 검사 수행 중"
* '인두 확인 완료
* "스크립트 실행 중"
* '스크립트 실행 완료'
* 'Mcli가 성공적으로 완료되었습니다.




 a| 
`-version`
 a| 
다운로드 가능한 SMcli 버전을 표시합니다



 a| 
'-?
 a| 
CLI 명령에 대한 사용 정보를 표시합니다.

|===


=== 저장된 스토리지 관리

다음 명령줄 매개 변수를 사용하면 로컬에 저장된 레이블을 통해 저장된 배열을 관리할 수 있습니다.


NOTE: 로컬에 저장된 레이블이 SANtricity 시스템 관리자 아래에 표시되는 실제 스토리지 배열 이름과 일치하지 않을 수 있습니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
`SMcli storageArrayLabel show all`
 a| 
로컬에 저장된 모든 레이블 및 관련 주소를 표시합니다



 a| 
`SMcli storageArrayLabel show label <LABEL>`
 a| 
이름이 인 로컬에 저장된 레이블과 연결된 주소를 표시합니다 `<LABEL>`



 a| 
`SMcli storageArrayLabel delete all`
 a| 
로컬에 저장된 모든 레이블을 삭제합니다



 a| 
`SMcli storageArrayLabel delete label <LABEL>`
 a| 
이름이 인 로컬에 저장된 레이블을 삭제합니다 `<LABEL>`



 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] storageArrayLabel add label <LABEL>`
 a| 
* 로컬에 저장된 라벨을 이름과 함께 추가합니다 `<LABEL>` 제공된 주소를 포함합니다
* 업데이트는 직접 지원되지 않습니다. 업데이트하려면 레이블을 삭제한 다음 다시 추가하십시오.



NOTE: SMcli는 로컬에 저장된 레이블을 추가할 때 스토리지 배열에 연결되지 않습니다.

|===
[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
`SMcli localCertificate show all`
 a| 
로컬에 저장된 신뢰할 수 있는 인증서를 모두 표시합니다



 a| 
`SMcli localCertificate show alias <ALIAS>`
 a| 
로컬에 저장된 신뢰할 수 있는 인증서를 별칭과 함께 표시합니다 `<ALIAS>`



 a| 
`SMcli localCertificate delete all`
 a| 
로컬에 저장된 신뢰할 수 있는 인증서를 모두 삭제합니다



 a| 
`SMcli localCertificate delete alias <ALIAS>`
 a| 
로컬로 저장된 신뢰할 수 있는 인증서를 별칭과 함께 삭제합니다 `<ALIAS>`



 a| 
`SMcli localCertificate trust file <CERT_FILE> alias <ALIAS>`
 a| 
* 신뢰할 수 있는 인증서를 별칭과 함께 저장합니다 `<ALIAS>`
* 신뢰할 수 있는 인증서는 웹 브라우저 사용과 같은 별도의 작업으로 컨트롤러에서 다운로드됩니다




 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] localCertificate trust`
 a| 
* 각 주소에 연결하고 반환된 인증서를 신뢰할 수 있는 인증서 저장소에 저장합니다
* 지정한 호스트 이름 또는 IP 주소는 이러한 방식으로 저장된 각 인증서의 별칭으로 사용됩니다
* 사용자는 이 명령을 실행하기 전에 컨트롤러의 인증서를 신뢰할 수 있는지 확인해야 합니다
* 보안을 강화하기 위해 파일을 사용하는 trust 명령을 사용하여 사용자 유효성 검사와 이 명령 실행 간에 인증서가 변경되지 않도록 해야 합니다


|===


=== 장비를 식별합니다

다음 명령줄 매개 변수를 사용하면 호스트에 표시되는 모든 해당 디바이스에 대한 정보를 표시할 수 있습니다.


NOTE: SANtricity 11.81 릴리스부터 SMcli가 지원됩니다 `identifyDevices` 매개 변수는 이전에 SMdevices 도구를 통해 사용할 수 있었던 기능을 대체합니다.

[cols="2*"]
|===
| 매개 변수 | 정의 


 a| 
`identifyDevices`
 a| 
스토리지 어레이와 연결된 모든 SCSI 기본 블록 장치를 찾습니다. 검색된 각 디바이스에 대해 기본 OS별 디바이스 이름, 관련 스토리지 시스템, 볼륨 이름, LUN 정보 등과 같은 다양한 정보를 보고합니다

|===


==== 예

의 예는 다음을 참조하십시오 `-identifyDevices` Linux 및 Windows 운영 체제 내의 매개 변수입니다.

.리눅스
[listing]
----
ICTAE11S05H01:~/osean/SMcli-01.81.00.10004/bin # ./SMcli -identifyDevices
  <n/a> (/dev/sg2) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Alternate Path (Controller-A): Non owning controller - Active/Non-optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdb (/dev/sg3) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
  <n/a> (/dev/sg4) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdc (/dev/sg5) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
SMcli completed successfully.
----
.Windows
[listing]
----
PS C:\Users\Administrator\Downloads\SMcli-01.81.00.0017\bin> .\SMcli -identifyDevices
  \\.\PHYSICALDRIVE1 [Storage Array ICTAG22S08A01, Volume Vol1, LUN 1, Volume ID <600a0980006cee060000592e6564fa6a>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE2 [Storage Array ICTAG22S08A01, Volume Vol2, LUN 2, Volume ID <600a0980006ce727000001096564f9f5>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE3 [Storage Array ICTAG22S08A01, Volume Vol3, LUN 3, Volume ID <600a0980006cee06000059326564fa76>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE4 [Storage Array ICTAG22S08A01, Volume Vol4, LUN 4, Volume ID <600a0980006ce7270000010a6564fa01>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
SMcli completed successfully.
----


==== 추가 참고 사항

* SCSI 기반 호스트 인터페이스를 사용하는 x86-64 플랫폼을 실행하는 Linux 및 Windows 운영 체제에서만 호환됩니다.
+
** NVMe 기반 호스트 인터페이스는 지원되지 않습니다.


* 를 클릭합니다 `identifyDevices` 매개 변수는 OS 수준에서 다시 검색하지 않습니다. OS에 표시되는 기존 장치를 반복합니다.
* 를 실행하려면 충분한 사용자 권한이 있어야 합니다 `identifyDevices` 명령.
+
** 여기에는 OS 네이티브 블록 디바이스에서 읽고 SCSI Inquiry 명령을 수행하는 기능이 포함됩니다.



