---
permalink: get-started/firmware-compatibility-levels.html 
sidebar: sidebar 
keywords: firmware, compatibility, levels 
summary: 다음 섹션의 스크립트 명령에는 스크립트 명령을 실행할 수 있는 최소 펌웨어 레벨이 나열되어 있습니다. 
---
= 펌웨어 호환성 수준
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 섹션의 스크립트 명령에는 스크립트 명령을 실행할 수 있는 최소 펌웨어 레벨이 나열되어 있습니다.

스크립트 명령어와 명령 매개변수는 컨트롤러 펌웨어의 모든 버전에서 실행되지 않습니다. 스크립트 명령어의 펌웨어 레벨은 " Minimum Firmware Level(최소 펌웨어 레벨)" 제목 아래에 나열됩니다. 이 목록은 펌웨어 레벨에 대한 정보를 해석하는 방법을 설명합니다.

* 스크립트 명령에 최소 컨트롤러 펌웨어 레벨이 표시되지 않으면 스크립트 명령과 해당 스크립트 명령과 관련된 모든 매개 변수가 컨트롤러 펌웨어 레벨에서 실행될 수 있습니다.
* 별도의 설명 정보가 없는 컨트롤러 펌웨어 번호는 컨트롤러 펌웨어 레벨이 전체 스크립트 명령과 해당 스크립트 명령에 대한 모든 매개변수에 적용됨을 나타냅니다.
* 매개 변수와 관련된 컨트롤러 펌웨어 번호는 매개 변수를 실행할 수 있는 최소 컨트롤러 펌웨어 레벨을 나타냅니다.


[NOTE]
====
최소 컨트롤러 펌웨어 레벨은 명령을 해제하는 소프트웨어에 대한 지원뿐만 아니라 사용량을 흡입하는 모든 스토리지 관리 소프트웨어에 대한 지원도 나타냅니다. CLI 지원 기능은 사용하는 하드웨어에 따라 다릅니다. 지원되지 않는 명령을 입력하면 오류 메시지가 나타납니다.

====


== 펌웨어 호환성 수준의 예

hostGroup 생성 명령은 다음과 같다.

* 최소 펌웨어 레벨 *

8.10

이 수준은 최소 컨트롤러 펌웨어 버전 8.10에서 전체 스크립트 명령이 실행됨을 나타냅니다.

'create ssdCache' 명령에는 다음과 같은 섹션이 있습니다.

* 최소 펌웨어 레벨 *

7.84

8.20.11 - '* securityType*' 파라미터를 추가했습니다.

이러한 표기법 은 최소 컨트롤러 펌웨어 버전 7.84에서 스크립트 명령어와 '* securityType*'을 제외한 모든 매개변수가 실행됨을 나타냅니다. '* securityType*' 매개변수는 컨트롤러 펌웨어 버전 8.20_M3의 최소값으로 실행됩니다.
