---
permalink: get-started/formatting-rules-for-script-commands.html 
sidebar: sidebar 
keywords: format, rules, script, commands 
summary: 특정 스크립트 명령에 고유한 구문은 각 스크립트 명령 설명 끝에 있는 Notes 섹션에 설명되어 있습니다. 
---
= SANtricity CLI 스크립트 명령에 대한 형식 규칙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 스크립트 명령에 고유한 구문은 각 스크립트 명령 설명 끝에 있는 Notes 섹션에 설명되어 있습니다.

* 대소문자 구분 * -- 스크립트 명령은 대소문자를 구분하지 않습니다. 스크립트 명령을 소문자, 대문자 또는 대/소문자로 입력할 수 있습니다. 다음 명령 설명에서 혼합 사례는 명령 이름을 읽고 명령의 용도를 이해하는 데 도움이 됩니다.

* spaces * -- 명령 설명에 표시된 대로 스크립트 명령에 공백을 입력해야 합니다.

* 대괄호 * - - - 대괄호는 두 가지 방식으로 사용됩니다.

* 명령 구문의 일부로 제공됩니다.
* 매개 변수가 선택사항임을 나타냅니다. 각 매개 변수에 대한 설명은 매개 변수 값을 대괄호로 묶어야 하는지 여부를 나타냅니다.


* 괄호 * -- 명령 구문에 표시된 괄호는 매개 변수에 대한 특정 선택 사항을 포함합니다. 즉, 매개 변수를 사용하려면 괄호 안에 있는 값 중 하나를 입력해야 합니다. 일반적으로 스크립트 명령에는 괄호를 포함하지 않지만, 목록을 입력할 때는 목록을 괄호로 묶어야 합니다. 이러한 목록은 트레이 ID 값 및 슬롯 ID 값 목록일 수 있습니다. 각 매개 변수에 대한 설명은 매개 변수 값을 괄호로 묶어야 하는지 여부를 나타냅니다.

* 수직 막대 * -- 스크립트 명령어의 수직 막대는 "" 또는 ""을 표시하고 매개변수에 대한 유효한 값을 구분합니다. 예를 들어, 명령어 설명의 'raidLevel' 파라미터에 대한 구문은 다음과 같이 나타납니다.

[listing]
----
 raidLevel=(0 | 1 | 3 | 5 | 6)
----
RAID 레벨 5를 설정하기 위해 'raidLevel' 매개변수를 사용하려면 다음 값을 입력합니다.

[listing]
----
 raidLevel=5
----
* 드라이브 위치 * -- 드라이브 위치를 식별하는 CLI 명령은 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다. ID 값은 쉼표로 구분합니다. ID 값 집합을 두 개 이상 입력하는 경우 각 값 집합을 공백으로 구분합니다.

CLI에서는 드라이브를 지정하는 두 가지 규칙이 있습니다. 사용해야 하는 규칙은 각 명령에 지정됩니다. 하나의 규칙에는 등호와 괄호가 사용됩니다.

[listing]
----

        drive=\(trayID,[drawerID,]slotID\)
----
두 번째 규칙은 등호를 사용하지 않고 지정된 드라이브 주위에 중괄호 쌍을 사용합니다.

[listing]
----

        drive \[trayID,[drawerID,]slotID\]
----
다음은 괄호를 사용하는 몇 가지 예입니다.

[listing]
----
(1,1 1,2 1,3 1,4 2,1 2,2 2,3 2,4)
----
또는 대용량 드라이브 트레이의 경우 다음 예를 참조하십시오.

[listing]
----
(1,1,1 1,2,2 1,3,3 1,4,4 2,1,1 2,2,2 2,3,3 2,4,4)
----
명령에서 * 기울임꼴 로 표시된 용어 * - 기울임꼴 로 표시된 용어는 제공해야 하는 값 또는 정보를 나타냅니다. 예를 들어 기울임꼴로 표시된 용어가 나타나는 경우:

[listing]
----

          *numberOfDrives*
----
기울임꼴로 표시된 용어를 script 명령에 포함할 드라이브 수에 대한 값으로 바꿉니다.

세미콜론 * -- 스크립트 명령은 세미콜론(';')으로 끝나야 합니다. 명령줄 또는 스크립트 파일에 스크립트 명령을 두 개 이상 입력할 수 있습니다. 예를 들어 세미콜론을 사용하여 다음 스크립트 파일에서 각 스크립트 명령을 구분합니다.

[listing]
----
create volume drives=(0,2 0,3 1,4 1,5 2,6 2,7) raidLevel=5 userLabel=”v1” capacity=2gb owner=a;
create volume volumeGroup=2 userLabel=”v2” capacity=1gb owner=b;
create volume volumeGroup=2 userLabel=”v3” capacity=1gb owner=a;
----
[listing]
----
create volume drives=(0,4 0,5 1,6 1,7 2,8 2,9) raidLevel=5 userLabel=”v4” capacity=2gb owner=b;
create volume volumeGroup=3 userLabel=”v5” capacity=1gb owner=a;
create volume volumeGroup=3 userLabel=”v6” capacity=1gb owner=b;
----