---
permalink: get-started/formatting-cli-commands-in-windows-powershell.html 
sidebar: sidebar 
keywords: format, rules, cli, commands, windows, powershell 
summary: Windows PowerShell은 명령줄 도구에 대한 액세스를 제공하는 대화형 스크립팅 셸입니다. 
---
= Windows PowerShell의 SANtricity CLI 명령에 대한 형식 규칙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows PowerShell은 명령줄 도구에 대한 액세스를 제공하는 대화형 스크립팅 셸입니다.

Windows PowerShell은 더욱 강력한 명령 세트와 스크립팅 기능을 통해 Windows 명령 프롬프트에서 더욱 향상된 기능을 제공합니다. Windows PowerShell에서 모든 CLI 및 스크립트 명령을 실행할 수 있지만, Windows PowerShell에는 몇 가지 고유한 서식 요구 사항이 있습니다. 요구 사항은 다음과 같습니다.

* 모든 SMcli 명령을 마침표 및 슬래시(./)로 시작합니다.
* SMcli 래퍼는 .exe 확장자(SMcli.exe)를 사용하여 실행 가능한 명령으로 식별되어야 합니다.
* 스크립트 명령은 작은따옴표('')로 묶어야 합니다.
* 이름, 파일 경로 또는 값의 일부인 큰따옴표(\")에는 큰따옴표 문자 앞에 백슬래시가 있어야 합니다.


다음은 Windows PowerShell에서 스토리지 어레이 이름을 생성하는 CLI 명령의 예입니다. 명령 구문에서 "userLabel"으로 식별되는 스토리지 배열 이름 주위의 백슬래시 큰따옴표와 스크립트 명령의 구분 기호로 작은따옴표를 사용합니다.

[listing]
----
PS C:\...\StorageManager\client> ./SMcli.exe 123.45.67.88 123.45.67.89
-c ’set storageArray userLabel=\"Engineering\";’
----
다음은 Windows PowerShell에서 프리미엄 기능을 활성화하는 CLI 명령의 예입니다. 고급 기능 키에 대한 파일 경로 앞에 백슬래시를 큰따옴표로 묶습니다.

[listing]
----
PS C:\...\StorageManager\client> ./SMcli.exe 123.45.67.88 123.45.67.89
-c ’enable storageArray feature file=\"C:\licenseKey.bin\";’
----
이전 예에서는 대문자와 소문자가 모두 사용됩니다. 이렇게 하면 명령의 서식을 명확하게 지정할 수 있습니다. 그러나 Windows PowerShell은 대소문자를 구분하지 않으며 특정 사용 사례가 필요하지 않습니다.
