---
permalink: get-started/learn-about-volume-group-migration.html 
sidebar: sidebar 
keywords: volume, group, migration, learn, data, access, export, import, component 
summary: 볼륨 그룹 마이그레이션을 사용하면 볼륨 그룹을 내보내서 볼륨 그룹을 다른 스토리지 어레이로 가져올 수 있습니다. 데이터를 오프라인으로 저장할 수 있도록 볼륨 그룹을 내보낼 수도 있습니다. 
---
= SANtricity 소프트웨어에서 볼륨 그룹 마이그레이션에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 그룹 마이그레이션을 사용하면 볼륨 그룹을 내보내서 볼륨 그룹을 다른 스토리지 어레이로 가져올 수 있습니다. 데이터를 오프라인으로 저장할 수 있도록 볼륨 그룹을 내보낼 수도 있습니다.

[CAUTION]
====
볼륨 그룹이 NVMe 또는 FIPS 지원 드라이브로 구성된 경우, 대상 어레이로 마이그레이션을 시작하기 전에 드라이브의 잠금을 해제하려면 소스 어레이에서 보안 키 및 암호를 기록/저장해야 합니다. 보안 키 및 암호를 알 수 없거나 데이터 무결성이 필요하지 않은 경우 보안 삭제를 수행할 수 있습니다. E-Series 스토리지 시스템에서는 여러 암호화 보안 드라이브를 혼합하여 사용할 수 없습니다. 보안 키를 사용하여 드라이브의 잠금을 해제하고, FIPS 드라이브를 지우고, 잠긴 NVMe 드라이브를 잠금 해제하거나 재설정하는 방법에 대한 자세한 내용은 SANtricity System Manager 온라인 도움말을 참조하십시오.

====
[NOTE]
====
* 데이터 액세스 손실 가능성 * -- 볼륨 그룹을 이동하거나 볼륨 그룹을 가져오기 전에 볼륨 그룹을 내보내야 합니다.

====


== 볼륨 그룹을 내보냅니다

볼륨 그룹 내보내기 작업은 볼륨 그룹의 드라이브를 제거할 수 있도록 준비합니다. 오프라인 스토리지용 드라이브를 제거하거나 볼륨 그룹을 다른 스토리지 어레이로 가져올 수 있습니다. 볼륨 그룹 내보내기 작업을 완료하면 모든 드라이브가 오프라인 상태가 됩니다. 연결된 볼륨 또는 사용 가능한 용량 노드는 더 이상 스토리지 관리 소프트웨어에 표시되지 않습니다.



== 내보낼 수 없는 구성 요소입니다

볼륨 그룹 내보내기 절차를 완료하려면 내보내기 불가능 구성 요소를 제거해야 합니다. 다음 구성 요소를 제거해야 합니다.

* 영구 예약
* 매핑
* 볼륨 복사본 쌍
* 원격 미러링 쌍
* 저장소 미러링




== 볼륨 그룹에 대한 기본 내보내기 단계입니다

볼륨 그룹 내보내기에는 _source_storage 배열에 이러한 단계가 포함됩니다.

. 스토리지 배열 구성을 저장합니다.
. 모든 I/O를 중지합니다
. 볼륨 그룹의 볼륨에 있는 데이터를 백업합니다.
. 볼륨 그룹의 볼륨에서 파일 시스템을 마운트 해제하거나 분리합니다.
. 볼륨 그룹을 찾아 드라이브에 소스 및 대상 스토리지 이름, 볼륨 그룹 이름 및 볼륨 그룹의 총 드라이브 수를 지정합니다.
. 볼륨 그룹을 오프라인 상태로 전환합니다.
. 트레이 내에서 적절한 공기 흐름을 유지하려면 내보내는 볼륨 그룹과 연결된 드라이브를 제거한 후 드라이브를 교체할 수 있도록 빈 드라이브 캐니스터 또는 새 드라이브를 준비합니다.


볼륨 그룹 내보내기에는 _target_storage 배열에 대한 다음 단계가 포함됩니다.

. 대상 스토리지 배열에 사용 가능한 드라이브 슬롯이 있는지 확인합니다.
. 대상 스토리지 배열이 가져올 드라이브를 지원하는지 확인합니다.
. 타겟 스토리지 어레이가 새 볼륨을 지원할 수 있는지 확인합니다.
. 최신 버전의 펌웨어가 컨트롤러에 설치되어 있는지 확인합니다.
. RAID 레벨 6 볼륨 그룹을 내보내는 경우 타겟 스토리지 어레이가 RAID 레벨 6을 지원하는지 확인하십시오.
. 최신 버전의 스토리지 관리 소프트웨어가 타겟 스토리지 시스템에 설치되어 있는지 확인합니다.
. 드라이브 보안이 설정된 볼륨 그룹을 내보내는 경우 대상 스토리지 어레이에서 드라이브 보안이 설정되어 있는지 확인합니다.




== 볼륨 그룹을 가져옵니다

볼륨 그룹 가져오기 작업은 가져온 볼륨 그룹을 타겟 스토리지 배열에 추가합니다. 볼륨 그룹 가져오기 작업을 완료하면 모든 드라이브의 상태가 최적입니다. 이제 연결된 볼륨 또는 사용 가능한 용량 노드가 타겟 스토리지 어레이에 설치된 스토리지 관리 소프트웨어에 나타납니다.



== 볼륨 그룹의 기본 가져오기 단계

[NOTE]
====
볼륨 그룹을 가져오려면 먼저 볼륨 그룹의 모든 드라이브를 트레이에 삽입해야 합니다.

====
볼륨 그룹을 가져오면 _target_storage 배열에 다음 단계가 포함됩니다.

. 내보낸 드라이브를 사용 가능한 드라이브 슬롯에 삽입합니다.
. 가져올 볼륨 그룹의 개요는 보고서 가져오기 를 참조하십시오.
. 가져올 수 없는 구성 요소가 있는지 확인합니다.
. 가져오기 절차를 진행할지 확인합니다.




== 가져올 수 없는 구성 요소

볼륨 그룹 가져오기 절차 중에는 일부 구성 요소를 가져올 수 없습니다. 이러한 구성 요소는 절차 중에 제거됩니다.

* 영구 예약
* 매핑
* 볼륨 복사본 쌍
* 원격 미러링 쌍
* 저장소 미러링

