---
permalink: get-started/naming-conventions.html 
sidebar: sidebar 
keywords: name, conventions 
summary: CLI 명령에 사용되는 이름에 대해서는 특정 규칙을 준수해야 합니다. 
---
= 명명 규칙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CLI 명령에 사용되는 이름에 대해서는 특정 규칙을 준수해야 합니다.

* 이름에는 최대 30자를 사용할 수 있습니다.
* 다음 구성 요소의 이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다.
+
** 지원합니다
** 호스트 그룹
** 호스트
** 볼륨 그룹
** 동적 디스크 풀
** 볼륨
** HBA 호스트 포트


* 고유한 이름을 사용해야 합니다. 고유한 이름을 사용하지 않으면 컨트롤러 펌웨어에서 오류가 반환됩니다.
* 이름에 단어, 하이픈 또는 밑줄이 두 개 이상 있으면 이름을 큰따옴표로 묶습니다("""). 일부 사용에서는 이름을 대괄호([])로 묶어야 합니다. 각 매개 변수에 대한 설명은 매개 변수를 큰따옴표, 대괄호 또는 둘 모두로 묶어야 하는지 여부를 나타냅니다.
* 이름 문자열에는 새 줄이 포함될 수 없습니다.
* Windows 운영 체제에서는 다른 구분 기호 외에 두 개의 백슬래시(\\) 사이에 이름을 넣어야 합니다. 예를 들어, 다음 이름은 Windows 운영 체제에서 실행되는 명령에 사용됩니다.
+
[listing]
----
[\“Engineering\”]
----
* UNIX 운영 체제의 경우 및 스크립트 파일에서 이 이름을 사용하면 다음 예제와 같이 표시됩니다.
+
[listing]
----
[“Engineering”]
----
* HBA 호스트 포트의 WWID(World Wide Identifier)를 입력할 때 일부 용도를 위해 WWID를 큰따옴표로 묶어야 합니다. 다른 용도에서는 WWID를 꺾쇠 괄호(<>)로 묶어야 합니다. WWID 매개 변수에 대한 설명은 WWID를 큰따옴표 또는 대괄호로 묶어야 하는지 여부를 나타냅니다.




== 숫자 이름 입력

스토리지 관리 소프트웨어가 스토리지 배열을 자동으로 구성할 때, 스토리지 관리 소프트웨어는 숫자로 구성된 이름을 할당합니다. 숫자로만 구성된 이름은 유효한 이름입니다. 그러나 숫자 문자 이름은 영문자로 시작하는 이름과 다르게 취급해야 합니다.

* 1 또는 2와 같은 숫자만 사용하는 이름입니다
* 1디스크 또는 32볼륨과 같이 숫자로 시작하는 이름입니다
* "[\"1\"]"
* "[\"1Disk\"]"


[NOTE]
====
이름의 유효성에 대해 확실치 않은 경우 큰따옴표와 대괄호를 모두 사용하십시오. 두 가지 방법을 모두 사용하면 이름이 제대로 작동하고 어떠한 처리 문제도 발생하지 않습니다.

====