---
permalink: get-started/structure-of-a-script-command.html 
sidebar: sidebar 
keywords: structure, script command 
summary: 성공적으로 실행하려면 스크립트 명령을 적절한 구조로 작성해야 합니다. 
---
= SANtricity CLI 스크립트 명령의 구조에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성공적으로 실행하려면 스크립트 명령을 적절한 구조로 작성해야 합니다.

모든 스크립트 명령에는 다음과 같은 구조가 있습니다.

[listing]
----

      *command operand-data* (*statement-data*)
----
* '명령'은 수행할 동작을 나타냅니다.
* '피연산자 데이터'는 구성하거나 관리할 스토리지 배열과 연결된 개체를 나타냅니다.
* '감소 데이터'는 명령을 수행하는 데 필요한 정보를 제공합니다.


'_FINUIJOR-DATA_' 구문은 다음과 같은 구조를 갖습니다.

[listing]
----
(*object-type* | all *object-types* | [*qualifier*] (*object-type* [*identifier*] (*object-type* [*identifier*] | *object-types* [*identifier-list*])))
----
개체는 다음 네 가지 방법으로 식별할 수 있습니다.

* 개체 형식 -- 명령이 특정 개체를 참조하지 않는 경우에 사용합니다.
* '* all*' 매개 변수 접두사 -- 명령이 스토리지 배열에 지정된 형식의 모든 개체(예: '* allVolumes*')를 참조할 때 사용합니다.
* 대괄호 -- 특정 개체에 대한 명령을 수행하여 개체를 식별할 때 사용합니다(예: " * volume [engineering] * ").
* 식별자 목록 -- 객체의 하위 집합을 지정하는 데 사용합니다. 개체 식별자를 대괄호로 묶습니다(예: " * volumes[sales engineering marketing] * ").


객체를 설명하는 추가 정보를 포함하려면 한정자가 필요합니다.

각 개체 형식과 관련된 개체 형식과 식별자는 이 표에 나열되어 있습니다.

[cols="2*"]
|===
| 개체 유형 | ID입니다 


 a| 
' * controller * '
 a| 
a 또는 b



 a| 
' * 드라이브 * '
 a| 
서랍이 있는 인클로저의 경우 트레이 ID, 서랍 ID 및 슬롯 ID를 사용하십시오. 또는 용지함 ID와 슬롯 ID만 있으면 됩니다.



 a| 
'* 치환 드라이브 * '
 a| 
서랍이 있는 인클로저의 경우 트레이 ID, 서랍 ID 및 슬롯 ID를 사용하십시오. 또는 용지함 ID와 슬롯 ID만 있으면 됩니다.



 a| 
'* 드라이브 채널 * '
 a| 
드라이브 채널 식별자입니다



 a| 
' * host * '
 a| 
사용자 레이블



 a| 
'* hostChannel*'
 a| 
호스트 채널 식별자입니다



 a| 
'* hostGroup*'
 a| 
사용자 레이블



 a| 
'* hostPort*'
 a| 
사용자 레이블



 a| 
' * iscsiInitiator * '
 a| 
사용자 레이블 또는 IQN(iSCSI Qualified Name)



 a| 
' * iscsiTarget * '
 a| 
사용자 레이블 또는 IQN입니다



 a| 
' * storageArray * '
 a| 
해당 없음



 a| 
' * 트레이 * '
 a| 
용지함 ID



 a| 
' * 볼륨 * '
 a| 
볼륨 사용자 레이블 또는 볼륨 WWID(World Wide Identifier)('Set' 명령만 해당)



 a| 
' * volumeCopy * '
 a| 
타겟 볼륨 사용자 레이블 및 소스 볼륨 사용자 레이블(선택 사항



 a| 
' * volumeGroup * '
 a| 
사용자 레이블

유효한 문자는 영숫자, 하이픈 및 밑줄입니다.

|===
문 데이터는 다음 형식으로 되어 있습니다.

* 매개 변수 = 값(' * raidLevel = 5 *' 등)
* Parameter-name(* batteryInstallDate* 등)
* operation-name(* 중복 검사*' 등)


사용자 정의 항목(예: 사용자 레이블)을 변수라고 합니다. 구문에 이탤릭체로 표시되어 있습니다(예: 트레이ID, 볼륨 그룹 이름).
