---
permalink: get-started/synopsis-of-the-script-commands.html 
sidebar: sidebar 
keywords: synopsis, script commands 
summary: '스크립트 명령을 사용하여 스토리지 배열의 다양한 측면(예: 호스트 토폴로지, 드라이브 구성, 컨트롤러 구성, 볼륨 정의 및 볼륨 그룹 정의)을 정의하고 관리할 수 있으므로 실제 명령 수는 광범위합니다.' 
---
= 스크립트 명령의 시놉시스입니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


스크립트 명령을 사용하여 스토리지 배열의 다양한 측면(예: 호스트 토폴로지, 드라이브 구성, 컨트롤러 구성, 볼륨 정의 및 볼륨 그룹 정의)을 정의하고 관리할 수 있으므로 실제 명령 수는 광범위합니다. 그러나 명령은 스토리지 배열을 구성하거나 유지 관리하기 위해 명령을 적용할 때 다시 사용되는 일반 범주에 속합니다. 다음 표에서는 스크립트 명령의 일반적인 형식과 각 명령의 정의를 보여 줍니다.

[cols="2*"]
|===
| 구문 | 설명 


 a| 
[listing]
----
accept object
{statement-data}
---- a| 
보류 중인 작업을 수행합니다.



 a| 
[listing]
----
activate object
{statement-data}
---- a| 
환경이 이미 올바르게 설정된 경우 작업을 수행하거나 작업을 수행할 수 있도록 환경을 설정합니다.



 a| 
[listing]
----
autoConfigure storageArray
{statement-data}
---- a| 
에서는 명령에 지정된 매개 변수를 기반으로 구성을 자동으로 생성합니다.



 a| 
[listing]
----
check object
{statement-data}
---- a| 
동기식 작업인 개체의 오류를 보고하는 작업을 시작합니다.



 a| 
[listing]
----
clear object
{statement-data}
---- a| 
개체의 일부 특성 내용을 삭제합니다. 이 작업은 파괴적이며 되돌릴 수 없습니다.



 a| 
[listing]
----
create object
{statement-data}
---- a| 
지정된 형식의 개체를 만듭니다.



 a| 
[listing]
----
deactivate object
{statement-data}
---- a| 
작업 환경을 제거합니다.



 a| 
[listing]
----
delete object
---- a| 
이전에 만든 개체를 삭제합니다.



 a| 
[listing]
----
diagnose object
{statement-data}
---- a| 
테스트를 실행하고 결과를 표시합니다.



 a| 
[listing]
----
disable object {statement-data}
---- a| 
기능이 작동하지 않도록 합니다.



 a| 
[listing]
----
download object
{statement-data}
---- a| 
스토리지 배열 또는 스토리지 배열에 연결된 하드웨어로 데이터를 전송합니다.



 a| 
[listing]
----
enable object
{statement-data}
---- a| 
작동할 피처를 설정합니다.



 a| 
[listing]
----
load object
{statement-data}
---- a| 
스토리지 배열 또는 스토리지 배열에 연결된 하드웨어로 데이터를 전송합니다. 이 명령은 기능적으로 'download' 명령과 유사합니다.



 a| 
[listing]
----
recopy object
{statement-data}
---- a| 
기존 볼륨 복사본 쌍을 사용하여 볼륨 복사본 작업을 다시 시작합니다. 작업을 다시 시작하기 전에 매개 변수를 변경할 수 있습니다.



 a| 
[listing]
----
recover object
{statement-data}
---- a| 
저장된 구성 데이터와 문 매개 변수에서 개체를 다시 만듭니다. (이 명령은 'create' 명령과 비슷합니다.)



 a| 
[listing]
----
remove object
{statement-data}
---- a| 
개체 간의 관계를 제거합니다.



 a| 
[listing]
----
repair object
{statement-data}
---- a| 
'check' 명령으로 발생한 오류를 복구합니다.



 a| 
[listing]
----
replace object
{statement-data}
---- a| 
지정된 객체는 스토리지 배열의 기존 객체를 대체합니다.



 a| 
[listing]
----
reset object
{statement-data}
---- a| 
하드웨어 또는 개체를 초기 상태로 반환합니다.



 a| 
[listing]
----
resume object
---- a| 
일시 중지된 작업을 시작합니다. 일시 중단되었을 때 작업이 중지된 위치에서 시작됩니다.



 a| 
[listing]
----
revive object
---- a| 
개체를 Failed 상태에서 Optimal 상태로 강제 설정합니다. 이 명령은 오류 복구 절차의 일부로만 사용하십시오.



 a| 
[listing]
----
save object
{statement-data}
---- a| 
개체에 대한 정보를 파일에 씁니다.



 a| 
[listing]
----
set object
{statement-data}
---- a| 
개체 특성을 변경합니다. 명령이 반환되면 모든 변경이 완료됩니다.



 a| 
[listing]
----
show object
{statement-data}
---- a| 
개체에 대한 정보를 표시합니다.



 a| 
[listing]
----
start object
{statement-data}
---- a| 
비동기 작업을 시작합니다. 일부 작업은 시작된 후에 중지할 수 있습니다. 일부 작업의 진행률을 쿼리할 수 있습니다.



 a| 
[listing]
----
stop object
{statement-data}
---- a| 
비동기 작업을 중지합니다.



 a| 
[listing]
----
suspend object
{statement-data}
---- a| 
작업을 중지합니다. 그런 다음 일시 중단된 작업을 다시 시작할 수 있으며 일시 중지된 지점부터 계속됩니다.



 a| 
[listing]
----
validate object
{statement-data}
---- a| 
보안 키를 확인합니다.

|===