---
permalink: commands-a-z/activate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, synchronous mirroring, supported arrays, roles, context, syntax, parameters, data assurance management, minimum firmware level 
summary: activate storageArray feature 명령은 동기 미러링 기능을 활성화하고 미러 저장소 볼륨을 만듭니다. 
---
= 동기식 미러링 활성화 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"activate storageArray feature" 명령은 동기 미러링 기능을 활성화하고 미러 저장소 볼륨을 만듭니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800 및 E5700 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령을 사용하면 다음 세 가지 방법 중 하나로 미러 저장소 볼륨을 정의할 수 있습니다.

* 사용자 정의 드라이브
* 사용자 정의 볼륨 그룹
* 사용자 정의 드라이브 수입니다


드라이브 수를 정의하도록 선택하면 컨트롤러 펌웨어가 미러 저장소 볼륨에 사용할 드라이브를 선택합니다.

[NOTE]
====
이 명령의 이전 버전에서는 피처 식별자가 'remoteMirror'였습니다. 이 기능 식별자는 더 이상 유효하지 않으며 SyncMirror로 대체됩니다.

====


== 구문(사용자 정의 드라이브)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_,pass:quotes[[_drawerIDn_,]pass:quotes[_slotIDn_
[driveType=(fibre | SATA | SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 5 | 6)
repositoryDrives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn)_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== 구문(사용자 정의 볼륨 그룹)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryVolumeGroup=pass:quotes[_volumeGroupName_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== 구문(사용자 정의 드라이브 수)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"RAID 레벨"을 선택합니다
 a| 
미러 저장소 볼륨의 RAID 레벨입니다. 유효한 값은 0, 1, 3, 5, 6입니다.



 a| 
"재구매드라이브"
 a| 
미러 저장소 볼륨의 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
RepositoryVolumeGroupUserLabel'을 참조하십시오
 a| 
미러 저장소 볼륨을 배치할 새 볼륨 그룹에 지정할 이름입니다. 볼륨 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
RepositoryVolumeGroup'을 참조하십시오
 a| 
미러 저장소 볼륨이 있는 미러 저장소 볼륨 그룹의 이름입니다. (스토리지 배열의 볼륨 그룹 이름을 확인하려면 'show storageArray profile' 명령을 실행합니다.)



 a| 
프리커패시터
 a| 
미러 저장소 볼륨을 생성하는 데 사용할 기존 볼륨 그룹의 사용 가능한 공간의 인덱스 번호입니다. 사용 가능한 용량은 볼륨 그룹의 기존 볼륨 간 사용 가능한 용량으로 정의됩니다. 예를 들어, 볼륨 그룹의 영역은 볼륨 1, 사용 가능한 용량, 볼륨 2, 사용 가능한 용량, 볼륨 3, 여유 용량: 볼륨 2 다음에 사용 가능한 용량을 사용하려면 다음을 지정합니다.

[listing]
----
freeCapacityArea=2
----
'show volumeGroup' 명령을 실행하여 사용 가능한 용량 영역이 있는지 확인합니다.



 a| 
재재고필수 DriveCount
 a| 
미러 저장소 볼륨에 사용할 할당되지 않은 드라이브 수입니다.



 a| 
'driveType'입니다
 a| 
정보를 검색할 드라이브 유형입니다. 드라이브 유형을 혼합할 수 없습니다.

유효한 드라이브 유형은 다음과 같습니다.

* 파이버입니다
* 아타
* 'AS'입니다
* NVMe4K


드라이브 유형을 지정하지 않으면 명령이 기본적으로 모든 유형으로 설정됩니다.



 a| 
트레이무손실
 a| 
미러 저장소 볼륨을 생성할 때 트레이 손실 보호를 적용하는 설정입니다. 트레이 손실 방지를 적용하려면 이 매개변수를 "참"으로 설정하십시오. 기본값은 'false'입니다.



 a| 
"손실 방지"를 선택합니다
 a| 
미러 저장소 볼륨을 생성할 때 문서함 손실 보호를 적용하는 설정입니다. 문서함 손실 보호를 적용하려면 이 매개변수를 "참"으로 설정합니다. 기본값은 'false'입니다.

|===


== 참고

"재가용 드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.

"필수 드라이브" 매개 변수에 대해 선택한 드라이브가 다른 매개 변수(예: "RAID 레벨" 매개 변수)와 호환되지 않는 경우 스크립트 명령은 오류를 반환하고 동기식 미러링은 활성화되지 않습니다. 이 오류는 미러 저장소 볼륨에 필요한 공간의 양을 반환합니다. 그런 다음 명령을 다시 입력하고 적절한 크기의 공간을 지정할 수 있습니다.

미러 저장소 볼륨에 비해 너무 작은 저장소 공간의 값을 입력하면 컨트롤러 펌웨어가 미러 저장소 볼륨에 필요한 공간을 제공하는 오류 메시지를 반환합니다. 명령은 동기 미러링을 활성화하지 않습니다. 리포지토리 저장소 공간 값에 대한 오류 메시지의 값을 사용하여 명령을 다시 입력할 수 있습니다.

드라이브를 할당할 때 'trayLossProtect' 매개변수를 'true'로 설정하고 하나의 트레이에서 드라이브를 두 개 이상 선택한 경우 스토리지 배열이 오류를 반환합니다. 'trayLossProtect' 매개 변수를 'false'로 설정하면 스토리지 배열이 작업을 수행하지만 생성한 볼륨 그룹에 트레이 손실 방지 기능이 없을 수 있습니다.

컨트롤러 펌웨어가 드라이브를 할당할 때 "trayLossProtect" 매개변수를 "true"로 설정하면 컨트롤러 펌웨어가 트레이 손실 방지를 갖는 새 볼륨 그룹을 초래하는 드라이브를 제공할 수 없는 경우 스토리지 배열이 오류를 반환합니다. 'trayLossProtect' 매개변수를 'false'로 설정하면 볼륨 그룹에 트레이 손실 방지 기능이 없는 경우에도 스토리지 어레이가 작업을 수행합니다.

drawerLossProtect 매개변수는 문서함에 오류가 발생할 경우 볼륨의 데이터에 액세스할 수 있는지 여부를 결정합니다. 드라이브를 할당할 때 "wrawerLossProtect" 매개변수를 "true"로 설정하고 하나의 드로어에서 드라이브를 두 개 이상 선택하면 스토리지 어레이가 오류를 반환합니다. drawerLossProtect 매개변수를 "false"로 설정하면 스토리지 배열이 작업을 수행하지만 생성하는 볼륨 그룹에 문서함 손실 보호가 적용되지 않을 수 있습니다.



== 데이터 무결성 관리

DA(Data Assurance) 기능은 전체 스토리지 시스템에서 데이터 무결성을 향상시킵니다. DA를 사용하면 호스트와 드라이브 간에 데이터가 이동할 때 발생할 수 있는 오류를 스토리지 시스템에서 확인할 수 있습니다. 이 기능을 활성화하면 스토리지 배열은 볼륨의 각 데이터 블록에 오류 검사 코드(순환 중복 검사 또는 CRC라고도 함)를 추가합니다. 데이터 블록이 이동된 후 스토리지 배열은 이러한 CRC 코드를 사용하여 전송 중에 오류가 발생했는지 확인합니다. 잠재적으로 손상된 데이터는 디스크에 기록되거나 호스트에 반환되지 않습니다.

DA 기능을 사용하려면 DA를 지원하는 드라이브만 포함된 풀 또는 볼륨 그룹으로 시작하십시오. 그런 다음 DA 가능 볼륨을 생성합니다. 마지막으로 DA를 지원하는 I/O 인터페이스를 사용하여 이러한 DA 지원 볼륨을 호스트에 매핑합니다. DA를 지원하는 I/O 인터페이스로는 InfiniBand를 통한 파이버 채널, SAS 및 iSER(RDMA/IB용 iSCSI 확장) 등이 있습니다. DA는 이더넷을 통한 iSCSI 또는 InfiniBand를 통한 SRP에서 지원되지 않습니다.

[NOTE]
====
모든 드라이브가 DA를 지원할 수 있는 경우, DATaAssurance 매개 변수를 "enabled"로 설정한 다음 특정 작업에 DA를 사용할 수 있습니다. 예를 들어, DA 지원 드라이브를 포함하는 볼륨 그룹을 생성한 다음 해당 볼륨 그룹 내에서 DA 지원 볼륨을 생성할 수 있습니다. DA 지원 볼륨을 사용하는 다른 작업에는 DA 기능을 지원하는 옵션이 있습니다.

====
"ataAssurance" 매개 변수를 "Enabled"로 설정하면 볼륨 후보에 대한 데이터 보증 가능 드라이브만 고려되며, 그렇지 않으면 데이터 보증 가능 드라이브와 비 데이터 보증 가능 드라이브가 모두 고려됩니다. 데이터 보증 드라이브만 사용할 수 있는 경우 활성화된 데이터 보증 드라이브를 사용하여 새 볼륨 그룹이 생성됩니다.



== 최소 펌웨어 레벨입니다

7.10은 RAID 레벨 6 기능을 추가합니다.

7.60은 'drawerID' 사용자 입력, 'drivMediaType' 매개변수, 'drawerLossProtect' 매개변수를 추가합니다.

7.75는 '다카Assurance' 파라미터를 추가합니다.

8.10은 drivMediaType 파라미터를 제거합니다.

8.60은 driveType 파라미터를 추가한다.
