---
permalink: commands-a-z/add-drives-to-ssd-cache.html 
sidebar: sidebar 
keywords: add drives ssd cache, supported arrays, syntax, parameters, minimum firmware level 
summary: 'set ssdCache 명령은 SSD(Solid State Disk)를 추가하여 기존 SSD 캐시의 용량을 늘립니다.' 
---
= SSD 캐시에 드라이브 추가 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
세트 ssdCache 명령은 SSD(Solid State Disk)를 추가하여 기존 SSD Cache의 용량을 늘립니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.

[NOTE]
====
E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 지원 관리자 역할이 있어야 합니다.

====


== 구문

[source, cli, subs="+macros"]
----
pass:quotes[set ssdCache [_ssdCacheName_]]
pass:quotes[addDrives=(_trayID1_,[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_,]pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'ssdCache'입니다
 a| 
SSD를 추가할 SSD 캐시의 이름입니다. 이름은 대괄호([ ])로 묶어야 합니다. SSD 캐시 이름에 특수 문자가 포함되어 있거나 숫자로만 구성된 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'addDrives'입니다
 a| 
SSD 캐시에 추가할 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 용지함 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

|===


== 참고

SSD 캐시에는 수많은 SSD가 포함될 수 있습니다. SSD 캐시의 최대 크기는 5TB이지만, 컨트롤러의 기본 캐시의 크기에 따라 달라질 수 있습니다.



== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
