---
permalink: commands-a-z/add-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: add volume, asynchronous, mirror group, supported arrays, roles, context, syntax, parameter, minimum firmware level 
summary: add volume asyncMirrorGroup 명령은 비동기식 미러 그룹에 운영 볼륨을 추가합니다. 
---
= 비동기식 미러 그룹에 볼륨을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'add volume asyncMirrorGroup' 명령은 비동기식 미러 그룹에 운영 볼륨을 추가합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
E2800, E5700, EF600 또는 EF300 어레이에서 명령을 실행하는 경우 클라이언트 유형은 로 설정해야 합니다 `symbol`. 이 명령은 클라이언트 유형이 로 설정된 경우 실행되지 않습니다 `https`.

====


== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 운영 볼륨을 추가할 비동기식 미러 그룹이 포함된 로컬 스토리지 어레이에서만 유효합니다. 비동기식 미러 그룹에는 비동기식 미러 그룹에 속한 모든 시점 이미지의 데이터를 저장하는 데 사용되는 저장소 볼륨이 있습니다. 비동기식 미러 그룹의 각 운영 볼륨에는 원격 스토리지 시스템에 해당하는 미러 볼륨이 있습니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[add volume="_volumeName_" asyncMirrorGroup="_asyncMirrorGroupName_"
remotePassword="_password_"
(repositoryVolume="repos_xxxx" |
repositoryVolume=(_volumeGroupName_ ]pass:quotes[[capacity=_capacityValue_])]
repositoryVolume=pass:quotes[(_diskPoolName_] pass:quotes[[capacity=_capacityValue_]))
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
비동기식 미러 그룹에 추가할 운영 볼륨의 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
아인치마그룹
 a| 
추가할 운영 볼륨이 포함될 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
암호 재입력
 a| 
이 매개 변수는 선택 사항입니다. 원격 스토리지 배열이 암호로 보호되는 경우 이 매개 변수를 사용합니다. 암호는 큰따옴표(" ")로 묶어야 합니다.



 a| 
재량권
 a| 
기본 볼륨의 변경된 데이터를 포함할 저장소 볼륨의 이름입니다.

저장소 볼륨의 이름을 정의하는 두 가지 옵션이 있습니다.

* 기존 리포지토리 볼륨 사용: 이름.
* 이 명령을 실행할 때 새 저장소 볼륨을 생성합니다.


기존 저장소 볼륨의 이름은 다음 두 부분으로 구성됩니다.

* 'Repos'라는 용어가
* 저장소 관리 소프트웨어가 저장소 볼륨 이름에 할당하는 4자리 숫자 식별자입니다.


기존 저장소 볼륨의 이름은 큰따옴표(" ")로 묶어야 합니다.

이 명령을 실행할 때 새 저장소 볼륨을 만들려면 저장소 볼륨을 만들 볼륨 그룹 또는 디스크 풀의 이름을 입력해야 합니다. 필요에 따라 저장소 볼륨의 용량을 정의할 수도 있습니다. 용량을 정의하려면 다음 값을 사용합니다.

* 기본 볼륨 용량의 백분율을 나타내는 정수 값입니다.
* 기본 볼륨 용량의 백분율을 나타내는 10진수 분수입니다.
* 저장소 볼륨의 특정 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.


용량을 정의하지 않으면 스토리지 관리 소프트웨어가 운영 볼륨 용량의 20%로 용량을 설정합니다.

스토리지 관리 소프트웨어는 저장소 볼륨을 생성하고 저장소 볼륨을 운영 볼륨에 연결합니다.

|===


== 참고

* 미러 작업에 사용할 로컬 및 원격 스토리지 시스템에서 비동기식 미러링 기능을 설정 및 활성화해야 합니다.
* 로컬 및 원격 스토리지 시스템은 적절한 Fibre Channel 패브릭 또는 iSCSI 인터페이스를 통해 접속되어야 합니다.
* 원격 스토리지 어레이에는 용량이 로컬 스토리지 배열의 운영 볼륨 용량보다 크거나 같은 볼륨이 있어야 합니다. 원격 스토리지 시스템의 볼륨이 미러 볼륨으로 사용됩니다.




== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
