---
permalink: commands-a-z/check-storagearray-connectivity.html 
sidebar: sidebar 
keywords: check, storage array, connectivity 
summary: 스토리지 배열 연결 검사 명령은 로컬 스토리지 배열과 원격 스토리지 배열에 통신 경로가 있는지 확인하고 로컬 스토리지와 원격 스토리지 배열 간의 접속 세부 정보를 표시합니다. 
---
= 스토리지 배열 연결을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
스토리지 배열 접속 확인 명령은 로컬 스토리지 배열과 원격 스토리지 배열에 통신 경로가 있는지 확인하고 로컬 스토리지와 원격 스토리지 배열 간의 접속 세부 정보를 표시합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
E2800 또는 E5700 어레이에서 명령을 실행하는 경우 클라이언트 유형은 '기호'로 설정해야 합니다. 이 명령은 클라이언트 유형이 'https'로 설정된 경우 실행되지 않습니다.

====


== 역할

E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

비동기식 미러 그룹을 생성하기 전에 로컬 스토리지 어레이와 원격 스토리지 시스템이 서로 통신할 수 있는지 확인해야 합니다. 이 명령을 실행하면 시스템은 모든 유효한 호스트 포트에서 원격 스토리지 시스템을 쿼리하여 원격 스토리지 시스템에 접속된 포트를 확인합니다. 테스트 결과는 로컬 스토리지 배열의 모든 포트 목록과 해당 포트를 통해 액세스할 수 있는 원격 스토리지 배열 포트 주소 목록입니다.

[NOTE]
====
가능한 모든 채널을 사용하여 연결을 테스트하고, 이중 컨트롤러 구성인 경우 각 컨트롤러에서 연결을 확인합니다. 두 스토리지 어레이 간의 연결을 확인하는 데 최대 20분이 걸릴 수 있습니다.

====


== 구문

[listing, subs="+macros"]
----
check storageArray connectivity
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_]|
remoteStorageArrayWwid=<pass:quotes[_wwID_]>)
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"remoteStorageArrayName"입니다
 a| 
접속을 확인할 원격 스토리지 시스템의 이름입니다. 스토리지 배열 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
레모테StorageArrayWid
 a| 
접속을 확인할 스토리지의 WWID(World Wide Identifier)입니다. 스토리지 배열 이름 대신 WWID를 사용하여 스토리지 배열을 식별할 수 있습니다. WWID는 꺾쇠 괄호(<>)로 묶어야 합니다.

|===


== 참고

두 스토리지 시스템 간에 미러를 설정하기 전에 Fibre Channel 접속 또는 iSCSI 접속을 통해 미러를 접속해야 합니다.

미러링 또는 연결 검사를 위해 서로 통신하기 전에 두 스토리지 시스템에서 Fibre Channel 비동기식 미러링을 활성화해야 합니다.

로컬 스토리지 배열이 iSCSI를 지원하는 경우 iSCSI를 통한 연결이 확인됩니다. 로컬 스토리지 어레이에서 Fibre Channel을 지원하고 Fibre Channel을 통한 미러링이 활성화된 경우 Fibre Channel을 통한 접속 구성을 확인합니다. 로컬 스토리지 배열이 iSCSI 또는 Fibre Channel을 지원하지 않는 경우 오류 메시지가 표시되고 작업이 중단됩니다.



== 최소 펌웨어 레벨입니다

7.84
