---
permalink: commands-a-z/check-volume-parity.html 
sidebar: sidebar 
keywords: check, volume, parity 
summary: 볼륨 패리티 검사 명령은 볼륨에 패리티 및 미디어 오류가 있는지 검사한 다음 검사 결과를 파일에 씁니다. 
---
= 볼륨 패리티를 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
볼륨 패리티 검사 명령은 볼륨에 패리티 및 미디어 오류가 있는지 확인한 다음 검사 결과를 파일에 기록합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
check volume pass:quotes[[_volumeName_]] parity
[parityErrorFile=pass:quotes[_filename_]]
[mediaErrorFile=pass:quotes[_filename_]]
[priority=(highest | high | medium | low | lowest)]
[startingLBA=pass:quotes[_LBAvalue_]]
[endingLBA=pass:quotes[_LBAvalue_]]
[verbose=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
패리티를 확인할 특정 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자가 포함되어 있거나 숫자로만 구성된 경우 식별자를 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
"parityErrorFile"
 a| 
패리티 오류 정보를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\parerr.txt"

이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 파일 확장자를 지정해야 합니다.



 a| 
'mediaErrorFile'입니다
 a| 
미디어 오류 정보를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\mederr.txt"

이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 파일 확장자를 지정해야 합니다.



 a| 
우선 순위
 a| 
호스트 입출력 작업과 관련하여 패리티 검사에 있는 우선 순위입니다. 유효값은 최고값, 최고값, 중간 수준, 최저값, 최저치입니다. 최저우선순위는 시스템 성능에 도움이 되지만 패리티 검사는 더 오래 걸립니다. 우선 순위가 가장 높은 비율은 패리티 검사에 도움이 되지만 시스템 성능이 저하될 수 있습니다.



 a| 
'타르팅LBA'
 a| 
시작 논리적 블록 주소입니다.



 a| 
엔딩LBA
 a| 
끝 논리 블록 주소입니다.



 a| 
무당이란
 a| 
완료율 등의 진행률 세부 정보를 캡처하고 볼륨 패리티를 스캔할 때 정보를 표시하는 설정입니다. 진행 상황 정보를 캡처하려면 이 매개변수를 "TRUE"로 설정합니다. 진행 상황 정보를 캡처하지 않으려면 이 매개변수를 FALSE로 설정합니다.

|===


== 참고

시작 논리적 블록 주소와 끝 논리 블록 주소는 매우 큰 단일 볼륨 LUN 또는 네임스페이스에 유용합니다. 매우 큰 단일 볼륨 LUN 또는 네임스페이스에서 볼륨 패리티 검사를 실행하는 데 오랜 시간이 걸릴 수 있습니다. 데이터 블록의 시작 주소와 끝 주소를 정의하여 볼륨 패리티 검사를 완료하는 데 걸리는 시간을 줄일 수 있습니다.
