---
permalink: commands-a-z/check-asyncmirrorgroup-repositoryconsistency.html 
sidebar: sidebar 
keywords: check, asynchronous mirror group, consistency 
summary: asyncMirrorGroup repositoryConsistency 명령은 지정된 비동기 미러 그룹의 기본 저장소 볼륨에 있는 데이터의 분석을 기반으로 보고서를 생성합니다. 
---
= 비동기식 미러 그룹 정합성 보장 확인
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
"check asyncMirrorGroup repositoryConsistency" 명령은 지정된 비동기 미러 그룹의 기본 저장소 볼륨에 있는 데이터의 분석을 기반으로 보고서를 생성합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
check asyncMirrorGrouppass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[[_localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
아인치마그룹
 a| 
정합성 검사를 실행할 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자가 포함되어 있거나 숫자만 포함된 경우에는 대괄호 안에 이름을 큰따옴표(" ")로 묶어야 합니다.



 a| 
재산화 일관성
 a| 
비동기식 미러 그룹이 정합성 보장을 검사하도록 지정합니다.



 a| 
'localVolume'
 a| 
미러 관계에 참여하는 로컬 볼륨의 이름을 지정합니다. 미러 관계의 소스 또는 대상인 로컬 볼륨을 지정할 수 있습니다. 로컬 볼륨 이름에 특수 문자가 포함되어 있거나 숫자만 포함된 경우에는 대괄호 안에 이름을 큰따옴표(" ")로 묶어야 합니다.



 a| 
'파일'
 a| 
일관성 검사를 통해 결과가 도출된 보고서를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

``file="C:\Program Files\CLI\logs\repoConsistency.txt"' 이 매개 변수는 선택적 매개 변수 다음에 마지막에 나타나야 합니다.

|===


== 참고

이 명령으로 생성된 보고서는 기술 지원 부서에서 문제를 분석하는 데 사용됩니다.



== 최소 펌웨어 레벨입니다

7.83

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
