---
permalink: commands-a-z/clear-asyncmirrorfault.html 
sidebar: sidebar 
keywords: clear, asynchronous mirroring, fault 
summary: 'asyncMirrorFault 지우기 명령은 하나 이상의 비동기 미러 그룹과 하나 이상의 비동기 미러 그룹 구성원 볼륨에서 비동기 미러링 "스키" 오류를 지웁니다.' 
---
= 비동기식 미러링 장애를 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
"asyncMirrorFault 지우기" 명령은 하나 이상의 비동기 미러 그룹과 하나 이상의 비동기 미러 그룹 구성원 볼륨에서 비동기 미러링 "sticky" 오류를 지웁니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800 및 E5700 어레이를 포함한 개별 스토리지 어레이에 적용됩니다. 모든 SMcli 패키지가 설치된 경우



== 역할

E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

비동기 미러 그룹과 해당 멤버 볼륨에 단일 시점에서는 발생하지만 미러 기능에는 영향을 주지 않는 비동기 미러링 "고정" 장애가 발생할 수 있습니다. 이러한 유형의 고장을 검토해야 하지만 구성을 변경할 필요가 없습니다.

비동기식 미러 그룹과 해당 구성원 볼륨에는 둘 이상의 연결된 고정 장애가 있을 수도 있고 있을 수도 있습니다. 이 명령을 실행하면 비동기식 미러 그룹 및 해당 구성원 볼륨과 관련된 모든 장애가 지워집니다. 그러나 비동기 미러 그룹에 장애가 있고 해당 구성원 볼륨 중 하나에 장애가 있는 경우 비동기 미러 그룹의 장애를 제거해도 해당 구성원 볼륨의 장애가 지워지지 않습니다.



== 구문

[listing, subs="+macros"]
----
clear asyncMirrorFault(all |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_"asyncMirrorGroupName1"
... "asyncMirrorGroupNameN"_]] |
volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]])
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
모두
 a| 
모든 비동기식 미러 그룹 및 모든 비동기식 미러 그룹 구성원 볼륨에서 모든 비동기식 미러링 장애를 지우려면 이 매개 변수를 사용합니다.



 a| 
아인치마그룹
 a| 
비동기식 미러링 장애를 삭제할 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자가 포함되어 있거나 숫자로만 구성된 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
asyncMirrorGroups라는 두 그룹이 있습니다
 a| 
비동기식 미러링 장애를 삭제할 여러 비동기식 미러 그룹의 이름입니다. 다음 규칙을 사용하여 비동기식 미러 그룹의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
'볼륨'
 a| 
비동기 미러링 장애를 지울 특정 구성원 볼륨(비동기식 미러 그룹)의 이름입니다. 멤버 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자가 포함되어 있거나 숫자로만 구성된 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
비동기 미러링 장애를 삭제할 여러 구성원 볼륨(비동기 미러 그룹)의 이름입니다. 다음 규칙을 사용하여 구성원 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


|===


== 최소 펌웨어 레벨입니다

7.84
