---
permalink: commands-a-z/clear-storagearray-configuration.html 
sidebar: sidebar 
keywords: clear, storage array, configuration 
summary: 스토리지 배열 구성 지우기 명령은 전체 스토리지 배열 구성이나 스토리지 배열 구성의 일부를 지우거나 볼륨 그룹 및 볼륨 구성만 지웁니다. 
---
= 스토리지 배열 구성을 지웁니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"clear storageArray configuration" 명령은 스토리지 배열 구성 전체 또는 스토리지 배열 구성의 일부를 지우거나 볼륨 그룹 및 볼륨 구성만 지웁니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

다음 명령을 사용하여 다음 작업 중 하나를 수행합니다.

* 전체 스토리지 배열 구성을 지우고 초기 설치 상태로 되돌립니다.
* 보안 정보 및 식별 정보를 제외한 구성을 지웁니다.
* 볼륨 그룹 구성 정보 및 볼륨 구성 정보만 지웁니다.


[NOTE]
====
* 스토리지 배열 구성 손상 가능성 * -- 이 명령을 실행하면 기존 스토리지 배열 구성이 삭제됩니다.

====


== 구문

[source, cli]
----
clear storageArray configuration (all | volumeGroups)
----
[source, cli]
----
clear storageArray configuration factoryReset
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
* 없음 *
 a| 
매개 변수를 입력하지 않으면 이 명령은 보안 및 식별과 관련된 정보를 제외하고 스토리지 배열에 대한 모든 구성 정보를 제거합니다.



 a| 
모두
 a| 
보안 정보 및 식별 정보를 포함하여 스토리지 배열의 전체 구성을 제거하는 설정입니다. 모든 구성 정보를 제거하면 스토리지 배열이 초기 상태로 돌아갑니다.



 a| 
볼륨그룹
 a| 
볼륨 구성 및 볼륨 그룹 구성을 제거하는 설정입니다. 나머지 구성은 그대로 유지됩니다.



 a| 
팩터리리셋
 a| 
이 설정은 스토리지 배열의 전체 구성('all' 매개변수와 동일한 기능)을 제거하지만 컨트롤러에 저장된 네트워크 구성 및 암호 정보도 재설정합니다.



 a| 
'업포트 리셋'
 a| 
[NOTE]
====
이 명령은 기술 지원 전용입니다.

====
이 설정은 'factoryReset' 파라미터처럼 동작하지만 모든 번들 키도 지웁니다.

|===


== 참고

이 명령을 사용하면 여러 가지 방법으로 스토리지 배열 구성을 지울 수 있습니다. 볼륨 그룹의 스토리지 배열을 지우면 복구 모드가 자동으로 시작됩니다. 복구 모드에서는 온보드(캐시) 백업(플랫폼에 있는 경우)이 보존됩니다. 스토리지 배열이 복구 모드에 있는 경우 선택적으로 호스트 기반 백업 파일 또는 온보드(캐시) 백업 중 하나에서 스토리지 배열 구성을 복원할 수 있습니다.

이 명령은 스토리지 배열 식별자도 재설정합니다. 키 파일로 활성화된 모든 프리미엄 기능은 무효화되고 새로운 프리미엄 기능 키를 생성하여 적용해야 합니다. 기술 지원 부서에 문의하십시오.

이 명령을 실행하면 스토리지 배열이 응답하지 않고 모든 스크립트 처리가 취소됩니다. 호스트와의 통신을 재개하려면 스토리지 배열을 제거한 후 다시 추가해야 합니다. 응답하지 않는 스토리지 배열을 제거하려면 다음 SMcli 래퍼 명령을 사용합니다.

[listing, subs="+macros"]
----
SMcli -X -n pass:quotes[_storageArrayName_]
----
X는 독특한 SMcli 단말기이며 대문자여야 합니다.

스토리지 배열을 다시 추가하려면 다음 SMcli 래퍼 명령을 사용합니다.

[listing, subs="+macros"]
----
SMcli -A -n pass:quotes[_storageArrayName_]
----
A는 독특한 SMcli 단말기이며 대문자여야 합니다.



== 최소 펌웨어 레벨입니다

7.10은 다음과 같은 매개 변수를 추가합니다.

* 모두
* 볼륨그룹


7.83은 복구 모드 기능을 추가합니다.

11.41은 다음 매개변수를 추가합니다.

* 팩터리리셋
* '업포트 리셋'

