---
permalink: commands-a-z/create-snapshot-volume.html 
sidebar: sidebar 
keywords: create, snapshot, volume 
summary: create snapVolume 명령은 기본 볼륨의 스냅샷 이미지에 대한 읽기-쓰기 기능을 사용하여 스냅샷 볼륨을 생성합니다. 
---
= 스냅샷 볼륨 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"create snapVolume" 명령은 기본 볼륨의 스냅샷 이미지에 대한 읽기-쓰기 기능을 사용하여 스냅샷 볼륨을 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

스냅샷 볼륨을 호스트에 매핑할 수 있으며 모든 호스트 쓰기는 스냅샷 볼륨과 연결된 저장소 볼륨에 상주합니다. 새 스냅샷 볼륨을 기존 저장소 볼륨에 할당하거나 볼륨 그룹 또는 디스크 풀에서 새 저장소 볼륨을 생성할 수 있습니다.

[NOTE]
====
온라인 볼륨 복사본에 사용되는 스냅샷 이미지에는 이 명령을 사용할 수 없습니다.

====


== 구문

[source, cli, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName_" snapImageID="_snapCGID:imageID_"]
[(repositoryVolume="repos_xxxx"]
[repositoryVolume=pass:quotes[_(volumeGroupName_]pass:quotes[[capacity=_capacityValue_]]]
[repositoryVolume=pass:quotes[(_diskPoolName_]pass:quotes[[capacity=_capacityValue_])]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
스냅샷 볼륨에 지정할 이름입니다. 스냅샷 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
나ImageID
 a| 
새 스냅샷 볼륨에 추가할 스냅샷 이미지의 영숫자 식별자입니다. 스냅샷 이미지의 식별자는 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' - 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' - 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
재량권
 a| 
스냅샷 이미지에서 변경된 데이터를 보관하는 저장소 볼륨의 이름입니다.

저장소 볼륨의 이름을 정의하는 두 가지 옵션이 있습니다.

* 기존 저장소 볼륨 이름을 사용합니다
* 이 명령을 실행할 때 새 저장소 볼륨을 생성합니다


기존 저장소 볼륨의 이름은 다음 두 부분으로 구성됩니다.

* 용어 "Repos"
* 저장소 관리 소프트웨어가 저장소 볼륨 이름에 할당하는 4자리 숫자 식별자입니다


기존 저장소 볼륨의 이름은 큰따옴표(" ")로 묶어야 합니다.

이 명령을 실행할 때 새 저장소 볼륨을 만들려면 저장소 볼륨을 만들 볼륨 그룹 또는 디스크 풀의 이름을 입력해야 합니다. 필요에 따라 저장소 볼륨의 용량을 정의할 수도 있습니다. 용량을 정의하려면 다음 값을 사용합니다.

* 기본 볼륨 용량의 백분율을 나타내는 정수 값입니다
* 기본 볼륨 용량의 백분율을 나타내는 10진수 분수입니다
* 저장소 볼륨의 특정 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.


용량 옵션을 사용하지 않으면 스토리지 관리 소프트웨어가 기본 볼륨 용량의 20%로 용량을 설정합니다.

이 명령을 실행하면 스토리지 관리 소프트웨어가 스냅샷 볼륨의 저장소 볼륨을 생성합니다.



 a| 
재허용 FullLimit
 a| 
스냅샷 저장소 볼륨이 거의 꽉 찼다는 경고가 표시되는 저장소 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 기본값은 75입니다.

|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

스냅샷 이미지의 식별자는 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 이미지의 식별자입니다


예를 들어, 스냅샷 그룹의 이름이 snapGroup1이고 저장소 볼륨의 최대 채우기 제한이 80%인 가장 최근 스냅샷 이미지를 사용하여 snapData1이라는 스냅샷 볼륨을 만들려면 다음 명령을 사용합니다.

[listing]
----
create snapVolume userLabel="snapData1" snapImageID="snapGroup1:newest"
repositoryVolume="repos_1234" repositoryFullLimit=80;
----
저장소 볼륨 식별자는 새 스냅샷 그룹을 생성할 때 스토리지 관리 소프트웨어 및 펌웨어에 의해 자동으로 생성됩니다. 저장소 볼륨의 이름을 변경하면 스냅샷 이미지와의 연결이 끊어지므로 저장소 볼륨의 이름을 바꿀 수 없습니다.



== 최소 펌웨어 레벨입니다

7.83
