---
permalink: commands-a-z/create-mapping-cgsnapvolume.html 
sidebar: sidebar 
keywords: create, consistency, group, snapshot, volume, map 
summary: create mapping cgSnapVolume 명령은 정합성 보장 그룹 스냅샷 볼륨에서 호스트 또는 호스트 그룹에 대한 논리적 매핑을 생성합니다. 
---
= 정합성 보장 그룹 스냅샷 볼륨 매핑을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'create mapping cgSnapVolume' 명령은 정합성 보장 그룹 스냅샷 볼륨에서 호스트 또는 호스트 그룹으로 논리적 매핑을 생성합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
create mapping cgSnapVolume=pass:quotes[_"snapVolumeName"_
(host="_hostName_" | hostGroup=("_hostGroupName_" | defaultGroup))]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'cgSnapVolume'
 a| 
논리적 매핑을 생성할 정합성 보장 그룹 스냅샷 볼륨의 이름입니다. 정합성 보장 그룹 스냅샷 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트
 a| 
논리 매핑을 생성할 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트그룹
 a| 
논리 매핑을 생성할 호스트 그룹의 이름입니다. 호스트 그룹 이름은 큰따옴표(" ")로 묶어야 합니다. defaultGroup 키워드를 사용하는 경우 따옴표로 묶지 마십시오.

|===


== 참고

호스트는 스토리지 배열에 연결되어 호스트 포트를 통해 스토리지 배열의 볼륨에 액세스하는 컴퓨터입니다. 개별 호스트에 대한 특정 매핑을 정의할 수 있습니다. 하나 이상의 볼륨에 대한 액세스를 공유하는 호스트 그룹에 호스트를 할당할 수도 있습니다.

호스트 그룹은 동일한 볼륨에 대한 액세스를 공유하는 호스트 컬렉션을 지정할지 여부를 정의할 수 있는 선택적 토폴로지 요소입니다. 호스트 그룹은 논리적 엔터티입니다. 동일한 볼륨에 대한 액세스를 공유하는 호스트가 두 개 이상 있는 경우에만 호스트 그룹을 정의합니다.



== 최소 펌웨어 레벨입니다

7.83
