---
permalink: commands-a-z/create-diskpool.html 
sidebar: sidebar 
keywords: create, disk pool 
summary: create diskpool 명령은 지정된 매개 변수를 기반으로 새 디스크 풀을 생성합니다. 
---
= 디스크 풀을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
"create diskpool" 명령은 지정된 매개 변수를 기반으로 새 디스크 풀을 생성합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

디스크 풀에 사용할 드라이브 목록 또는 드라이브 유형을 입력하여 디스크 풀을 생성할 수 있습니다.

[NOTE]
====
드라이브 목록을 입력하는 경우 모든 드라이브의 용량이 동일해야 합니다. 드라이브의 용량이 동일하지 않은 경우 디스크 풀의 각 드라이브는 가장 작은 드라이브와 동일한 용량을 보고합니다.

====


== 구문

[listing, subs="+macros"]
----
create diskPool
(drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN)_]|
driveType=(fibre | SATA | SAS | NVMe4K))
 userLabel=pass:quotes[_"diskPoolName"_]
[driveCount=pass:quotes[_driveCountValue_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[warningThreshold=(pass:quotes[_warningThresholdValue_] | default)]
[criticalThreshold=(pass:quotes[_criticalThresholdValue_] | default)]
[criticalPriority=(highest|high|medium|low|lowest)]
[backgroundPriority=(highest|high|medium|low|lowest)]
[degradedPriority=(highest|high|medium|low|lowest)]
[securityType=(none | capable | enabled )]
[secureDrives=(fips | fde )]
[driveMediaType=(hdd | ssd | allMedia | unknown)]
[dataAssurance=(none|enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"늑대들"
 a| 
생성하려는 디스크 풀에 할당할 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
'사용자 레이블'
 a| 
새 디스크 풀에 지정할 이름입니다. 디스크 풀 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'driveCount'입니다
 a| 
driveCount 매개변수는 디스크 풀 후보를 지정된 수로 제한합니다. 이 매개변수를 사용할 때 HDD 드라이브에 입력할 수 있는 최소값은 11입니다. SSD 드라이브의 경우 입력할 수 있는 최소 값은 8입니다.

[NOTE]
====
드라이브 수가 11개 미만인 SSD 풀은 RAID 1 볼륨으로 제한됩니다.

====


 a| 
'warningThreshold'
 a| 
디스크 풀이 거의 꽉 찼다는 경고 알림을 받는 스토리지 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어, 값이 60이면 60%를 의미합니다. 최상의 작동을 위해서는 이 파라미터의 값이 'critalThreshold' 파라미터의 값보다 작아야 합니다.

유효한 값은 0에서 100 사이입니다.

기본값은 50입니다.

이 매개 변수를 0(영)으로 설정하면 경고 경고가 비활성화됩니다.

이를 '기본값'으로 설정하면 컨트롤러 펌웨어에 의해 경고 경고 임계값이 결정됩니다.



 a| 
비판역치
 a| 
디스크 풀이 거의 꽉 찼다는 심각한 경고가 발생한 스토리지 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 최상의 작동을 위해서는 이 파라미터의 값이 'warningThreshold' 파라미터의 값보다 커야 합니다.

유효한 값은 0에서 100 사이입니다.

기본값은 85%입니다.

이 매개 변수를 0(영)으로 설정하면 경고 알림과 위험 경고가 모두 비활성화됩니다.

이를 '기본값'으로 설정하면 컨트롤러 펌웨어에 의해 위험 경고 임계값이 결정됩니다.



 a| 
비판우선
 a| 
디스크 풀의 중요 이벤트에 대한 재구성 작업의 우선순위 예를 들어, 드라이브 장애가 2개 이상 발생한 이후에 디스크 풀을 재구성합니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 '가장 높음'입니다.



 a| 
백그라운드 우선 순위
 a| 
디스크 풀의 백그라운드 작업에 대한 우선 순위입니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 'low'(낮음)입니다.



 a| 
"우선 순위"를 선택합니다
 a| 
디스크 풀의 성능 저하 작업에 대한 우선 순위입니다. 예를 들어, 한 드라이브 장애 후에 디스크 풀을 재구성합니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 'high'입니다.



 a| 
'생태형'을 선택합니다
 a| 
디스크 풀을 생성할 때 보안 수준을 지정하는 설정입니다. 디스크 풀의 모든 볼륨 후보에는 지정된 보안 유형이 있습니다.

다음 설정이 유효합니다.

* "없음" -- 후보들이 안전하지 않다.
* "Capable" -- 볼륨 후보는 보안 설정을 할 수 있지만 보안이 활성화되지 않았습니다.
* "활성화됨" -- 볼륨 후보에 대한 보안이 활성화되어 있습니다.


기본값은 '없음'입니다.



 a| 
'괴상드라이브'
 a| 
볼륨 그룹에서 사용할 보안 드라이브 유형입니다. 다음 설정이 유효합니다.

* FIPS는 FIPS 호환 드라이브만 사용합니다.
* FDE -- FDE 호환 드라이브를 사용합니다.


[NOTE]
====
이 파라미터는 'ecurityType' 파라미터와 함께 사용한다. 'ecurityType' 파라미터에 none을 지정하면 비보안 디스크 풀이 보안 드라이브 유형을 지정할 필요가 없으므로 'ecureDrives' 매개 변수의 값이 무시됩니다.

====
[NOTE]
====
이 매개변수는 'driveCount' 매개변수도 사용하지 않는 한 무시됩니다. 개수를 제공하지 않고 디스크 풀에 사용할 드라이브를 지정하는 경우 원하는 보안 유형에 따라 선택 목록에서 적절한 드라이브 유형을 지정합니다.

====


 a| 
"MediaType"입니다
 a| 
디스크 풀에 사용할 드라이브 미디어의 유형입니다.

스토리지 배열에 둘 이상의 드라이브 미디어 유형이 있는 경우 이 매개변수를 사용해야 합니다.

다음 드라이브 미디어가 유효합니다.

* HDD -- 하드 드라이브가 있는 경우 이 옵션을 사용합니다.
* 'SD' -- 솔리드 스테이트 디스크가 있는 경우 이 옵션을 사용합니다.
* 알 수 없음 -- 드라이브 트레이에 어떤 유형의 드라이브 미디어가 있는지 확실하지 않으면 이 옵션을 사용합니다
* AllMedia -- 드라이브 트레이에 있는 모든 유형의 드라이브 미디어를 사용하려면 이 옵션을 사용합니다


기본값은 HDD입니다.

[NOTE]
====
컨트롤러 펌웨어는 선택한 설정에 관계없이 동일한 디스크 풀에서 HDD와 SSD 드라이브 미디어를 혼합하지 않습니다.

====


 a| 
재치 프로비저닝 캐블
 a| 
리소스 프로비저닝 기능이 설정되어 있는지 여부를 지정하는 설정입니다. 리소스 프로비저닝을 비활성화하려면 이 매개 변수를 "false"로 설정합니다. 기본값은 "true"입니다.

|===


== 참고

각 디스크 풀 이름은 고유해야 합니다. 사용자 레이블에는 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 사용자 레이블은 최대 30자까지 가능합니다.

지정한 매개 변수를 사용 가능한 대상 드라이브에서 사용할 수 없는 경우 명령이 실패합니다. 일반적으로 서비스 품질과 일치하는 모든 드라이브는 상위 후보로서 반환됩니다. 그러나 드라이브 목록을 지정하는 경우 지원자로 반환되는 사용 가능한 드라이브 중 일부가 서비스 속성의 품질과 일치하지 않을 수 있습니다.

선택적 매개 변수의 값을 지정하지 않으면 기본값이 할당됩니다.



== 드라이브

driveType 매개변수를 사용하면 해당 드라이브 유형의 할당되지 않은 모든 드라이브가 디스크 풀을 생성하는 데 사용됩니다. 디스크 풀에서 드라이브 유형 매개 변수로 발견되는 드라이브 수를 제한하려면 드라이브 수 매개 변수를 사용하여 드라이브 수를 지정할 수 있습니다. 'driveType' 파라미터를 사용하는 경우에만 'driveCount' 파라미터를 사용할 수 있습니다.

드라이브 트레이 및 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.

고용량 드라이브 트레이의 사양을 입력했지만 드라이브 트레이를 사용할 수 없는 경우 스토리지 관리 소프트웨어에서 오류 메시지를 표시합니다.



== 디스크 풀 경고 임계값

각 디스크 풀에는 디스크 풀의 스토리지 용량이 거의 다 찼을 때 사용자에게 알리기 위해 2개의 점진적으로 심각한 수준의 경고가 있습니다. 알림의 임계값은 디스크 풀의 총 가용 용량에 사용된 용량의 백분율 중 입니다. 경고는 다음과 같습니다.

* 경고 -- 첫 번째 경고 수준입니다. 이 수준은 디스크 풀에서 사용된 용량이 거의 다 찼음을 나타냅니다. 경고 알림 임계값에 도달하면 Needs Attention(주의 필요) 조건이 생성되고 이벤트가 스토리지 관리 소프트웨어에 게시됩니다. 경고 임계값이 위험 임계값으로 대체됩니다. 기본 경고 임계값은 50%입니다.
* 심각 -- 가장 심각한 수준의 경고입니다. 이 수준은 디스크 풀에서 사용된 용량이 거의 다 찼음을 나타냅니다. 중요 알림 임계값에 도달하면 Needs Attention(주의 필요) 조건이 생성되고 이벤트가 스토리지 관리 소프트웨어에 게시됩니다. 경고 임계값이 위험 임계값으로 대체됩니다. 중요 경고의 기본 임계값은 85%입니다.


경고 알림 값이 항상 위험 알림 값보다 작아야 합니다. 경고 알림 값이 위험 알림 값과 같으면 중요 알림만 전송됩니다.



== 디스크 풀 백그라운드 작업입니다

디스크 풀은 다음과 같은 백그라운드 작업을 지원합니다.

* 재구성
* 인스턴트 가용성 형식(iaf)
* 형식
* 동적 용량 확장(DCE)
* DVE(Dynamic Volume Expansion)(디스크 풀의 경우 DVE는 백그라운드 작업이 아니라 동기식 작업으로 지원됩니다.)


디스크 풀은 백그라운드 명령을 대기열에 넣지 않습니다. 여러 개의 백그라운드 명령을 순차적으로 시작할 수 있지만 한 번에 두 개 이상의 백그라운드 작업을 시작하면 이전에 시작한 명령의 완료가 지연됩니다. 지원되는 백그라운드 작업의 상대적 우선 순위 수준은 다음과 같습니다.

. 재구성
. 형식
. iaf
. DCE




== 보안 유형입니다

'ecurityType' 매개 변수를 사용하여 스토리지 배열의 보안 설정을 지정합니다.

'ecurityType' 매개 변수를 'enabled'로 설정하려면 먼저 스토리지 배열 보안 키를 생성해야 합니다. 스토리지 배열 보안 키를 생성하려면 "create storageArray securityKey" 명령을 사용합니다. 이러한 명령은 보안 키와 관련이 있습니다.

* 스토리지 배열 보안 키 만들기
* securityKey 내보내기
* 스토리지 배열 보안 키 가져오기
* 'et storageArray securityKey'를 선택합니다
* 볼륨그룹 [volumeGroupName] 보안 활성화
* 'diskpool [diskPoolName] 보안 설정'




== 드라이브 보안

보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. 'ecureDrives' 매개 변수를 사용하여 사용할 보안 드라이브 유형을 지정합니다. 사용할 수 있는 값은 FIPS와 FDE입니다.



== 명령 예

[listing]
----
create diskPool driveType=SAS userLabel="FIPS_Pool" driveCount=11 securityType=capable secureDrives=fips;
----


== 최소 펌웨어 레벨입니다

7.83

8.20은 다음 매개 변수를 추가합니다.

* 트레이무손실
* "손실 방지"를 선택합니다


8.25는 'ecureDrives' 파라미터를 추가한다.

8.63은 resourceProvisionCapable 매개 변수를 추가합니다.

11.73이 'driveCount' 매개변수를 업데이트합니다.
