---
permalink: commands-a-z/create-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency, group 
summary: create consistencyGroup 명령은 스냅샷 그룹을 포함할 수 있는 비어 있는 새 정합성 보장 그룹을 생성합니다. set encistencyGroup addCGMember 명령을 사용하여 스냅샷 그룹을 추가해야 합니다. 
---
= 일관성 그룹 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'create consistencyGroup' 명령은 스냅샷 그룹을 포함할 수 있는 비어 있는 새 정합성 보장 그룹을 생성합니다. 'Set istencyGroup addCGMember' 명령을 사용하여 스냅샷 그룹을 추가해야 합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
create consistencyGroup userLabel=pass:quotes[_"consistencyGroupName"_]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapSchedule_])]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
생성할 새 일관성 그룹의 이름입니다. 새 정합성 보장 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
재규리풀정책
 a| 
스냅샷 저장소 볼륨이 꽉 찬 경우 스냅샷 처리를 계속할 방법을 지정합니다. 기본 볼륨('failBaseWrites')에 대한 쓰기를 실패하거나 스냅샷 이미지('purgeSnapImages')를 삭제(삭제)할 수 있습니다. 기본 동작은 "purgeSnapImages"입니다.



 a| 
재허용 FullLimit
 a| 
스냅샷 저장소 볼륨이 거의 꽉 찼다는 경고가 표시되는 저장소 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 기본값은 75입니다.



 a| 
자동 삭제 제한
 a| 
각 스냅샷 그룹은 스냅샷 이미지의 자동 삭제를 수행하여 스냅샷 그룹의 총 스냅샷 이미지 수를 지정된 수준 이하로 유지하도록 구성할 수 있습니다. 이 옵션을 설정하면 스냅샷 그룹에 새 스냅샷 이미지가 생성될 때마다 시스템에서 제한 값에 따라 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 삭제합니다. 이렇게 하면 저장소 용량이 확보되므로 나머지 스냅샷 이미지에 대한 지속적인 쓰기 시 복사 요구 사항을 충족하는 데 사용할 수 있습니다.



 a| 
'enableSchedule'
 a| 
스냅샷 작업을 스케줄링할 수 있는 기능이 설정되어 있는지 여부를 나타냅니다. 스냅샷 예약을 설정하려면 이 매개 변수를 "true"로 설정합니다. 스냅샷 예약을 해제하려면 이 매개변수를 "false"로 설정합니다.



 a| 
롤백우선
 a| 
시스템 성능을 희생하여 롤백 작업에 시스템 리소스를 할당할지 여부를 결정합니다. "높음"은 롤백 작업이 다른 모든 호스트 입출력에 우선함을 나타냅니다 "low" 값은 롤백 작업이 호스트 입출력에 미치는 영향을 최소화하면서 수행되어야 함을 나타냅니다

|===


== 참고

정합성 보장 그룹은 컬렉션에 추가하는 모든 스냅샷 이미지를 일괄 형태로 관리할 수 있는 논리적 엔터티입니다. 정합성 보장 그룹은 스냅샷 이미지에 대한 상호 정합성 요구 사항 또는 종속성이 있는 스냅샷 그룹의 모음입니다. 이 컬렉션에 생성 및 사용하는 모든 스냅샷 이미지는 정합성 보장 종속성에 따라 관리해야 합니다.

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

정합성 보장 그룹의 스냅샷 이미지는 정합성 보장 그룹 내에 스냅샷 이미지가 있는지 여부에 따라 추론할 수 있습니다. 정합성 보장 그룹 내에 있는 모든 스냅샷 이미지는 공통 타임 스탬프 및 시퀀스 번호를 공유합니다.

스냅샷 이미지 정합성 보장 그룹의 작업은 단일 요청으로 처리되며, 이로 인해 스냅샷 이미지를 생성하기 전에 각 구성원의 연결된 기본 볼륨에 대해 보류 중인 모든 입출력 작업이 드레이닝되고 일시 중지됩니다. 모든 정합성 보장 그룹 구성원에 대해 스냅샷 이미지 생성을 성공적으로 완료할 수 없는 경우 작업이 실패하고 아무런 영향이 없습니다(즉, 새 스냅샷 이미지가 생성되지 않음).

이 동작을 기반으로 정합성 보장 그룹의 모든 구성원은 일반적으로 동일한 수의 스냅샷 이미지를 갖습니다. 그러나 새 구성원이 일관성 그룹에 추가되면 해당 새 구성원은 일관성 그룹의 설정된 구성원에 이미 생성된 스냅샷 이미지가 없습니다. 스냅샷 이미지 부족은 오류 상태로 간주되지 않습니다. 정합성 보장 그룹 구성원의 하위 집합에만 있는 스냅샷 이미지의 삭제 또는 롤백을 요청하는 후속 요청은 지정된 스냅샷 이미지가 실제로 존재하는 구성원에만 영향을 줍니다.



== 자동 삭제

스냅샷 그룹의 총 스냅샷 이미지 수를 최대 이미지 수 이하로 유지하도록 각 스냅샷 그룹을 자동으로 삭제하도록 구성할 수 있습니다. 스냅샷 그룹의 스냅샷 이미지 수가 최대 제한에 도달했을 때 스냅샷 그룹에 새 스냅샷 이미지가 생성될 때마다 "autoDeleteLimit" 매개 변수는 스냅샷 이미지를 자동으로 삭제합니다. "autoDeleteLimit" 매개 변수는 매개 변수로 정의된 최대 이미지 수가 충족될 때까지 스냅샷 그룹에서 가장 오래된 스냅샷 이미지를 삭제합니다. 이렇게 하면 저장소 용량을 확보함으로써 나머지 스냅샷 이미지에 대한 지속적인 쓰기 중 복제 요구 사항을 충족할 수 있습니다.



== 정합성 보장 그룹에서 스냅샷 이미지를 스케줄링하는 중입니다

'enableSchedule' 매개변수와 'schedule' 매개변수를 사용하여 스냅샷을 예약할 수 있습니다. 이러한 매개 변수를 사용하여 일별, 주별 또는 월별(일별 또는 날짜별)으로 스냅샷을 예약할 수 있습니다. enableSchedule 매개변수는 스냅샷 예약 기능을 켜거나 끕니다. 예약을 활성화할 때 '스케줄' 매개변수를 사용하여 스냅샷을 생성할 시기를 정의합니다.

이 표는 '스케줄' 파라미터의 옵션을 사용하는 방법을 설명합니다.

|===
| 매개 변수 | 설명 


 a| 
스케줄
 a| 
스케줄 매개 변수를 지정하는 데 필요합니다.



 a| 
'즉각'
 a| 
작업을 즉시 시작합니다. 이 항목은 다른 일정 매개 변수와 함께 사용할 수 없습니다.



 a| 
'enableSchedule'
 a| 
TRUE로 설정하면 스케쥴이 설정됩니다. false로 설정하면 일정 설정이 해제됩니다.

[NOTE]
====
기본값은 false 입니다.

====


 a| 
'타르트데이트'입니다
 a| 
작업을 시작할 특정 날짜입니다. 날짜 입력 형식은 MM:DD:YY입니다. 기본값은 현재 날짜입니다. 이 옵션의 예는 '스타날짜=06:27:11'입니다.



 a| 
'예정된 날'
 a| 
작업을 시작할 요일입니다. 다음 값 중 하나 이상이 될 수 있습니다.

* 오늘
* 화요일
* 수요일이라는 것입니다
* "목요일"
* 금요일
* '어투데이'
* '당일날'


[NOTE]
====
값을 괄호로 묶습니다. 예: 'ScheduleDay = (Wednesday)'.

====
날짜를 단일 괄호 집합으로 묶고 각 날짜를 공백으로 분리하여 하루 이상을 지정할 수 있습니다. 예를 들어 'ScheduleDay = (Monday Wednesday Friday)'가 있습니다.

[NOTE]
====
이 매개 변수는 월별 스케줄과 호환되지 않습니다.

====


 a| 
'스타타임'입니다
 a| 
작업을 시작할 날짜의 시간입니다. 시간 입력 형식은 HH:MM이며, 여기서 HH는 시간, MM은 시간 전의 분입니다. 24시간 시계를 사용합니다. 예를 들어 오후 2:00은 14:00입니다. 이 옵션의 예로는 'sttTime=14:27'이 있습니다.



 a| 
'ScheduleInterval'입니다
 a| 
작업 사이의 최소 시간(분)입니다. 스케줄 간격은 1440(24시간)을 초과할 수 없으며 30의 배수여야 합니다.

이 옵션의 예는 'ScheduleInterval=180'입니다.



 a| 
'종료 날짜'
 a| 
작업을 중지할 특정 날짜입니다. 날짜 입력 형식은 MM:DD:YY입니다. 종료 날짜를 원하지 않으면 NOEndDate를 지정할 수 있습니다. 이 옵션의 예는 'endDate=11:26:11'입니다.



 a| 
'타임퍼데이'
 a| 
하루 동안 작업을 수행할 횟수입니다. 이 옵션의 예로는 'timesPerDay=4'가 있습니다.



 a| 
시간대
 a| 
일정에 사용할 시간대를 지정합니다. 다음 두 가지 방법으로 지정할 수 있습니다.

* * GMT ± HH:MM *
+
GMT로부터 시간대 오프셋. 예: 'timezone=GMT-06:00'.

* * 텍스트 문자열 *
+
표준 시간대 텍스트 문자열, 따옴표로 묶어야 합니다. 예: ``시간대="아메리카/시카고"'





 a| 
'ScheduleDate'입니다
 a| 
작업을 수행할 월의 일일입니다. 날짜 값은 숫자 및 1-31 범위입니다.

[NOTE]
====
이 매개 변수는 주간 일정과 호환되지 않습니다.

====
'ScheduleDate' 옵션의 예는 'ScheduleDate = ("15")'입니다.



 a| 
몬스
 a| 
작업을 수행할 특정 월입니다. 월의 값은 다음과 같습니다.

* 1월 1월
* 2월-2월
* 마르 - 3월
* 4월 4월
* 5월
* 준은 6월
* 7월 7월
* 8월 8월
* 'EP' - 9월
* 10월 10월
* 11월-11월
* 12월


[NOTE]
====
값을 괄호로 묶습니다. 예: month=(Jan).

====
월을 단일 괄호 집합으로 묶고 각 월을 공백으로 구분하여 한 달 이상 지정할 수 있습니다. 예: month=(Jan Jul Dec).

이 매개변수를 'ScheduleDate' 매개변수와 함께 사용하여 특정 날짜에 작업을 수행합니다.

[NOTE]
====
이 매개 변수는 주간 일정과 호환되지 않습니다.

====
|===
이 표에는 '시간대' 매개 변수를 사용하는 방법이 설명되어 있습니다.

|===
| 시간대 이름입니다 | GMT 오프셋 


 a| 
'etc/GMT + 12'
 a| 
그리니치 표준시 - 12:00



 a| 
"ETC/GMT + 11"
 a| 
"GMT-11:00"



 a| 
태평양/호놀룰루
 a| 
그리니치 표준시 - 10:00



 a| 
'아메리카/앵커리지'
 a| 
그리니치 표준시 - 09:00



 a| 
'아메리카/산타_이사벨'
 a| 
그리니치 표준시 -08:00



 a| 
미국/로스앤젤레스
 a| 
그리니치 표준시 -08:00



 a| 
'아메리카/피닉스'
 a| 
그리니치 표준시 -07:00



 a| 
'아메리카/치와와'
 a| 
그리니치 표준시 -07:00



 a| 
'아메리카/덴버'
 a| 
그리니치 표준시 -07:00



 a| 
'아메리카/과테말라'
 a| 
"GMT-06:00"



 a| 
미국/시카고
 a| 
"GMT-06:00"



 a| 
'아메리카/멕시코 시티'
 a| 
"GMT-06:00"



 a| 
'아메리카/리자이나'
 a| 
"GMT-06:00"



 a| 
'아메리카/보고타'
 a| 
'GMT-05:00'



 a| 
미국/뉴욕
 a| 
'GMT-05:00'



 a| 
"ETC/GMT + 5"
 a| 
'GMT-05:00'



 a| 
'아메리카/카라카스'
 a| 
그리니치 표준시 -04:30



 a| 
'아메리카/아순시온'
 a| 
그리니치 표준시 -04:00



 a| 
'아메리카/핼리팩스'
 a| 
그리니치 표준시 -04:00



 a| 
'아메리카/쿠이아바'
 a| 
그리니치 표준시 -04:00



 a| 
'아메리카/라 파즈'
 a| 
그리니치 표준시 -04:00



 a| 
'아메리카/산티아고'
 a| 
그리니치 표준시 -04:00



 a| 
'아메리카/세인트 존스'
 a| 
그리니치 표준시 -03:30



 a| 
'아메리카/상파울루'
 a| 
그리니치 표준시 -03:00



 a| 
'아메리카/부에노스아이레스'
 a| 
그리니치 표준시 -03:00



 a| 
'아메리카/카옌'
 a| 
그리니치 표준시 -03:00



 a| 
'아메리카/고타브'
 a| 
그리니치 표준시 -03:00



 a| 
'아메리카/몬테비데오'
 a| 
그리니치 표준시 -03:00



 a| 
'etc/GMT+2'
 a| 
GMT-02:00



 a| 
대서양/아조레스
 a| 
그리니치 표준시 -01:00



 a| 
대서양/카보베르데
 a| 
그리니치 표준시 -01:00



 a| 
아프리카/카사블랑카
 a| 
"GMT"



 a| 
"ETC/GMT"
 a| 
"GMT"



 a| 
'유럽/런던'
 a| 
"GMT"



 a| 
'대서양/레이캬비크'
 a| 
"GMT"



 a| 
유럽/베를린
 a| 
'GMT+01:00'



 a| 
'유럽/부다페스트'
 a| 
'GMT+01:00'



 a| 
유럽/파리
 a| 
'GMT+01:00'



 a| 
유럽/바르샤바
 a| 
'GMT+01:00'



 a| 
아프리카/라고스
 a| 
'GMT+01:00'



 a| 
아프리카/윈드호크
 a| 
'GMT+01:00'



 a| 
아시아/앙만
 a| 
'GMT+02:00'



 a| 
아시아/베이루트
 a| 
'GMT+02:00'



 a| 
아프리카/카이로
 a| 
'GMT+02:00'



 a| 
아시아/다마스커스
 a| 
'GMT+02:00'



 a| 
아프리카/요하네스버그
 a| 
'GMT+02:00'



 a| 
유럽/키예프
 a| 
'GMT+02:00'



 a| 
아시아/예루살렘
 a| 
'GMT+02:00'



 a| 
'유럽/이스탄불'
 a| 
'GMT+03:00'



 a| 
유럽/민스크
 a| 
'GMT+02:00'



 a| 
아시아/바그다드
 a| 
'GMT+03:00'



 a| 
아시아/리야드
 a| 
'GMT+03:00'



 a| 
아프리카/나이로비
 a| 
'GMT+03:00'



 a| 
아시아/테헤란
 a| 
그리니치 +03:30



 a| 
유럽/모스크바
 a| 
'GMT+04:00'



 a| 
아시아/두바이
 a| 
'GMT+04:00'



 a| 
아시아/바쿠
 a| 
'GMT+04:00'



 a| 
인도양 모리셔스
 a| 
'GMT+04:00'



 a| 
아시아/트빌리시
 a| 
'GMT+04:00'



 a| 
아시아/예레반
 a| 
'GMT+04:00'



 a| 
아시아/카불
 a| 
그리니치 +04:30



 a| 
아시아/카라치
 a| 
'GMT+05:00'



 a| 
아시아/타슈켄트
 a| 
'GMT+05:00'



 a| 
아시아/캘커타
 a| 
그리니치 +05:30



 a| 
아시아/콜롬보
 a| 
그리니치 +05:30



 a| 
아시아/카트만두
 a| 
'GMT+05:45'



 a| 
아시아/예카테린부르크
 a| 
'GMT+06:00'



 a| 
아시아/알마티
 a| 
'GMT+06:00'



 a| 
아시아/다카
 a| 
'GMT+06:00'



 a| 
아시아/랑군
 a| 
그리니치 +06:30



 a| 
아시아/노보시비르스크
 a| 
'GMT+07:00'



 a| 
아시아/방콕
 a| 
'GMT+07:00'



 a| 
아시아/크라스노야르스크
 a| 
'GMT+08:00'



 a| 
아시아/상하이
 a| 
'GMT+08:00'



 a| 
아시아/싱가포르
 a| 
'GMT+08:00'



 a| 
호주/퍼스
 a| 
'GMT+08:00'



 a| 
아시아/타이베이
 a| 
'GMT+08:00'



 a| 
아시아/울란바토르
 a| 
'GMT+08:00'



 a| 
아시아/이르쿠츠크
 a| 
'GMT+09:00'



 a| 
아시아/도쿄
 a| 
'GMT+09:00'



 a| 
아시아/서울
 a| 
'GMT+09:00'



 a| 
호주/애들레이드
 a| 
그리니치 +09:30



 a| 
호주/다윈
 a| 
그리니치 +09:30



 a| 
아시아/야쿠츠크
 a| 
"GMT + 10:00"



 a| 
호주/브리즈번
 a| 
"GMT + 10:00"



 a| 
호주/시드니
 a| 
"GMT + 10:00"



 a| 
태평양/포트모르즈비
 a| 
"GMT + 10:00"



 a| 
호주/호바트
 a| 
"GMT + 10:00"



 a| 
아시아/블라디보스토크
 a| 
"GMT + 11:00"



 a| 
'태평양/과달운하
 a| 
"GMT + 11:00"



 a| 
'태평양/오클랜드'
 a| 
'GMT + 12:00'



 a| 
'etc/GMT-12'를 선택합니다
 a| 
'GMT + 12:00'



 a| 
태평양/피지
 a| 
'GMT + 12:00'



 a| 
아시아/캄차카
 a| 
'GMT + 12:00'



 a| 
태평양/통가타푸
 a| 
"GMT + 13:00"

|===
스케줄을 정의하는 코드 문자열은 다음 예제와 비슷합니다.

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
'ScheduleInterval' 옵션을 사용할 경우, 펌웨어는 'timesPerDay' 옵션과 'ScheduleInterval' 옵션 중에서 가장 낮은 값을 선택하여 선택합니다. 펌웨어는 설정한 'ScheduleInterval' 옵션 값으로 1440을 나누어 'ScheduleInterval' 옵션의 정수 값을 계산합니다. 예: 1440/180 = 8. 그런 다음 펌웨어는 'timesPerDay' 정수 값을 계산된 'ScheduleInterval' 정수 값과 비교하여 더 작은 값을 사용합니다.

스케줄을 제거하려면 스케줄 매개 변수와 함께 볼륨 삭제 명령을 사용합니다. '스케줄' 파라미터로 '볼륨 삭제' 명령은 스냅샷 볼륨이 아닌 스케줄만 삭제합니다.

정합성 보장 그룹에서 롤백을 수행할 때 기본 작업은 정합성 보장 그룹의 모든 구성원을 롤백하는 것입니다. 정합성 보장 그룹의 모든 구성원에 대해 롤백을 성공적으로 시작할 수 없으면 롤백이 실패하고 아무런 영향이 없습니다. 스냅샷 이미지는 롤백되지 않습니다.



== 최소 펌웨어 레벨입니다

7.83

7.86은 'ScheduleDate' 옵션과 'month' 옵션을 추가한다.
