---
permalink: commands-a-z/create-storagearray-securitykey.html 
sidebar: sidebar 
keywords: create, storage, array, security, key 
summary: 'create storageArray securityKey 명령은 FDE(전체 디스크 암호화) 드라이브가 있는 스토리지 어레이에 대한 새 보안 키를 생성하거나 변경합니다.' 
---
= 스토리지 어레이 보안 키 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'create storageArray securityKey' 명령은 FDE(전체 디스크 암호화) 드라이브가 있는 스토리지 어레이에 대한 새 보안 키를 생성하거나 변경합니다.



== 지원되는 어레이

외부 키 관리가 활성화된 경우 이 명령은 E4000, E2800, E5700, EF600 및 EF300 어레이에만 적용됩니다. 내부 키 관리가 활성화된 경우 모든 SMcli 패키지가 설치된 경우 명령은 개별 스토리지 배열에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

내부 키 관리의 경우 이 명령은 내부 키 관리 기능을 활성화하고 보안 키를 생성합니다. 키를 만든 후 'set storageArray securityKey' 명령을 사용하여 키를 사용합니다. 이 명령을 사용하여 보안 키를 변경할 수도 있습니다.

외부 키 관리의 경우 이 명령은 기능을 활성화할 때 처음 생성된 키를 대체하는 다른 키를 생성합니다. 'enable storageArray externalKeyManagement' 명령어를 이용하여 External Key Management 기능을 활성화하고 초기 보안 키를 생성한다. 이 명령을 사용하여 보안 키를 변경할 수도 있습니다.



== 구문

[source, cli, subs="+macros"]
----
create storageArray securityKey
[keyIdentifier=pass:quotes[_"keyIdentifierString"_]]
passPhrase=pass:quotes[_"passPhraseString"_
file=_"fileName"_]
[commitSecurityKey=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
키식별자(keyIdentifier) - 내부 키 관리에만 적용됩니다
 a| 
보안 키 주위의 래퍼인 읽을 수 있는 문자열입니다. 키 식별자는 큰따옴표(" ")로 묶어야 합니다.

나중에 키를 식별하는 데 도움이 되도록 내부 보안 키의 키 식별자에 문자를 입력할 수 있습니다. 다음은 서식 규칙입니다.

* 키 식별자는 최대 189자의 영숫자를 입력할 수 있습니다. 키 식별자에는 다음 문자를 사용할 수 없습니다.
+
** 공백
** 구두점
** 기호


* 내부 키에 대한 keyIdentifier 매개변수를 입력하지 않으면 컨트롤러가 자동으로 keyIdentififer 매개변수를 생성합니다.


키 식별자에 대해 입력한 문자열 끝에 추가 문자가 자동으로 생성되고 추가됩니다. keyIdentifier 파라미터에 대한 문자열을 입력하지 않으면 자동으로 생성되는 문자만 키 식별자로 구성됩니다.

[NOTE]
====
키 식별자가 자동으로 생성되므로 외부 키 관리에서는 이 매개 변수가 무시됩니다. 스토리지 배열에 사용자 레이블이 있는 경우 자동으로 생성되는 이 문자열은 'a'와 스토리지 배열 사용자 레이블, 스토리지 배열 식별자 및 임의로 생성된 문자열로 구성됩니다. 사용자 레이블에 영숫자가 아닌 문자는 밑줄('_')로 변환됩니다. 예를 들어 abc #8의 사용자 레이블은 나머지 키 식별자에 앞에 붙기 전에 'sa.abc_8'으로 변환됩니다. 사용자 레이블이 없는 스토리지의 경우 키 식별자는 스토리지 배열 식별자와 임의로 생성된 문자열로 구성됩니다.

====


 a| 
패스프레이즈
 a| 
외부 파일에 보안 키를 저장할 수 있도록 보안 키를 암호화하는 문자열입니다. 암호는 큰따옴표(" ")로 묶어야 합니다.

올바른 암호 구문을 만들기 위한 올바른 양식에 대한 자세한 내용은 이 명령 설명의 참고 사항을 참조하십시오.

암호는 다음 기준을 충족해야 합니다.

* 8자에서 32자 사이여야 합니다.
* 공백이 없어야 합니다.
* 대문자를 하나 이상 포함해야 합니다.
* 소문자가 하나 이상 포함되어야 합니다.
* 하나 이상의 숫자를 포함해야 합니다.
* 영숫자가 아닌 문자를 하나 이상 포함해야 합니다(예: <>@+).


[NOTE]
====
암호문이 이러한 기준을 충족하지 않으면 오류 메시지가 표시되고 명령을 다시 시도하라는 메시지가 표시됩니다.

====


 a| 
'파일'
 a| 
보안 키를 저장할 파일 경로와 파일 이름입니다. 예를 들면 다음과 같습니다.

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
파일 이름의 확장명은 .slk이어야 합니다.

====
파일 경로와 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
CommitSecurityKey - 내부 키 관리에만 적용됩니다
 a| 
이 매개 변수는 모든 FDE 드라이브와 컨트롤러에 대한 보안 키를 스토리지 어레이에 커밋합니다. 보안 키를 커밋한 후에는 스토리지 배열의 Security Enabled 드라이브에 있는 데이터에 액세스하는 데 키가 필요합니다. 데이터는 키를 통해서만 읽거나 변경할 수 있으며, 데이터를 쓸모 없게 렌더링하거나 드라이브를 완전히 지우지 않으면 비보안 모드에서 드라이브를 사용할 수 없습니다.

기본값은 false 입니다. 이 매개 변수가 false로 설정되어 있으면 별도의 'set storageArray securityKey' 명령을 보내 보안 키를 스토리지 배열에 커밋합니다.

|===


== 최소 펌웨어 레벨입니다

7.40, 내부 키 관리를 위해 도입되었습니다

8.40, 외부 키 관리를 위해 도입되었습니다
