---
permalink: commands-a-z/create-raid-volume-manual-drive-select.html 
sidebar: sidebar 
keywords: create, raid, volume, manual, drive, select 
summary: create volume 명령은 새 볼륨 그룹과 볼륨을 생성하고 볼륨에 대한 드라이브를 지정할 수 있습니다. 
---
= RAID 볼륨 생성(수동 드라이브 선택)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'create volume' 명령을 실행하면 새 볼륨 그룹과 볼륨이 생성되고 볼륨의 드라이브를 지정할 수 있습니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
create volume drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeName"_]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----
[listing, subs="+macros"]
----
create volume drives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_)]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
raidLevel=(0 | 1 | 5 | 6)
userLabel=pass:quotes[_"volumeName"_]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"늑대들"
 a| 
생성할 볼륨에 할당할 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
'볼륨 그룹 사용자 레이블'
 a| 
새 볼륨 그룹에 지정할 이름입니다. 볼륨 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.

[NOTE]
====
볼륨 그룹의 사용자 레이블을 지정하지 않으면 컨트롤러 펌웨어가 번호를 할당합니다.

====


 a| 
레이드레벨
 a| 
볼륨이 포함된 볼륨 그룹의 RAID 레벨입니다. 유효한 값은 0, 1, 3, 5, 6입니다.



 a| 
'사용자 레이블'
 a| 
새 볼륨에 지정할 이름입니다. 새 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.

[NOTE]
====
이 매개 변수는 필수입니다.

====


 a| 
용량
 a| 
스토리지 배열에 추가할 볼륨의 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.



 a| 
오너
 a| 
볼륨을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 소유자를 지정하지 않으면 컨트롤러 펌웨어가 소유자를 결정합니다.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다.



 a| 
'크기'
 a| 
다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 양(KB)입니다. 유효한 값은 ''4(SSD만 해당)''8','16','32','64','128', 256, 512.



 a| 
'usageHint'
 a| 
cacheReadPrefetch 매개변수와 'egmentSize' 매개 변수의 설정이 기본값으로 되어 있습니다. 기본값은 볼륨을 사용하는 애플리케이션의 일반적인 I/O 사용 패턴을 기반으로 합니다. 유효한 값은 파일 시스템, 다타베이스 또는 멀티미디어 입니다.



 a| 
트레이무손실
 a| 
리포지토리를 만들 때 트레이 손실 보호를 적용하는 설정입니다. 트레이 손실 방지를 적용하려면 이 매개변수를 "참"으로 설정하십시오. 기본값은 'false'입니다.



 a| 
"손실 방지"를 선택합니다
 a| 
미러링된 저장소 볼륨을 생성할 때 문서함 손실 보호를 적용하는 설정입니다. 문서함 손실 보호를 적용하려면 이 매개변수를 "참"으로 설정합니다. 기본값은 'false'입니다.



 a| 
드슈프리알Locate
 a| 
예약 용량이 향후 세그먼트 크기에 할당되도록 하는 설정입니다. 이 기본값은 "true"입니다.



 a| 
'생태형'을 선택합니다
 a| 
볼륨 그룹 및 연결된 모든 볼륨을 생성할 때 보안 수준을 지정하는 설정입니다. 다음 설정이 유효합니다.

* "없음" -- 볼륨 그룹과 볼륨이 안전하지 않습니다.
* "Capable(기능)" -- 볼륨 그룹과 볼륨에 보안 설정이 가능하지만 보안이 활성화되지 않았습니다.
* "활성화됨" -- 볼륨 그룹과 볼륨에 보안이 설정되어 있습니다.




 a| 
재치 프로비저닝 캐블
 a| 
리소스 프로비저닝 기능이 설정되어 있는지 여부를 지정하는 설정입니다. 리소스 프로비저닝을 비활성화하려면 이 매개 변수를 "false"로 설정합니다. 기본값은 "true"입니다.

|===


== 참고

드라이브 트레이 및 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.

'raidLevel' 매개변수를 RAID 레벨 1로 설정하는 경우:

* 그룹에 RAID 1 정의에 따라 짝수의 드라이브가 있습니다
* 그룹의 첫 번째 절반은 나열된 순서(및 스트라이프 순서)로 기본 드라이브입니다
* 그룹의 후반부(및 스트라이프 순서)는 해당 미러 드라이브입니다


이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

소유자 매개변수는 볼륨을 소유하는 컨트롤러를 정의합니다. 볼륨의 기본 컨트롤러 소유권은 현재 볼륨 그룹을 소유한 컨트롤러입니다.

'capacity' 매개 변수를 사용하여 용량을 지정하지 않으면 볼륨 그룹에서 사용할 수 있는 모든 드라이브 용량이 사용됩니다. 용량 단위를 지정하지 않으면 "바이트"가 기본값으로 사용됩니다.



== 트레이 손실 방지 및 드로어 손실 방지

트레이 손실 방지 기능이 작동하려면 구성이 다음 지침을 준수해야 합니다.

|===
| 레벨 | 트레이 손실 방지 기준 | 필요한 최소 용지함 수입니다 


 a| 
"디스크 풀"
 a| 
디스크 풀에는 하나의 트레이에 두 개 이상의 드라이브가 포함되어 있지 않습니다
 a| 
6



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 트레이에 두 개 이상의 드라이브를 포함하지 않습니다
 a| 
3



 a| 
RAID 3, RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 트레이에 있습니다
 a| 
3



 a| 
RAID 1
 a| 
RAID 1 쌍의 각 드라이브는 별도의 트레이에 있어야 합니다
 a| 
2



 a| 
RAID 0
 a| 
트레이 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===
드로어 손실 방지 기능이 작동하려면(고밀도 엔클로저 환경에서) 다음 지침을 준수해야 합니다.

|===
| 레벨 | 서랍 손실 방지 기준 | 필요한 최소 드로어 수입니다 


 a| 
"디스크 풀"
 a| 
이 풀에는 5개의 드로어 모두에서 드라이브가 포함되며 각 드로어에 동일한 수의 드라이브가 있습니다. 디스크 풀에 15, 20, 25, 30, 35가 포함된 경우 60개 드라이브 트레이가 드로어 손실 방지를 달성할 수 있습니다. 40, 45, 50, 55 또는 60개 드라이브.
 a| 
5



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다.
 a| 
3



 a| 
RAID 3, RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 드로어에 있습니다.
 a| 
3



 a| 
RAID 1
 a| 
미러링된 쌍의 각 드라이브는 별도의 드로어에 위치해야 합니다.
 a| 
2



 a| 
RAID 0
 a| 
문서함 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===


== 세그먼트 크기

세그먼트 크기에 따라 다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 블록 수가 결정됩니다. 각 데이터 블록에는 512바이트의 데이터가 저장됩니다. 데이터 블록은 가장 작은 스토리지 단위입니다. 세그먼트의 크기에 따라 포함된 데이터 블록의 수가 결정됩니다. 예를 들어 8KB 세그먼트에는 16개의 데이터 블록이 있습니다. 64KB 세그먼트에는 128개의 데이터 블록이 있습니다.

세그먼트 크기에 대한 값을 입력하면 이 값은 런타임에 컨트롤러에서 제공하는 지원되는 값과 비교하여 확인됩니다. 입력한 값이 유효하지 않으면 컨트롤러가 유효한 값 목록을 반환합니다. 단일 요청에 단일 드라이브를 사용하면 다른 드라이브를 사용할 수 있어 다른 요청을 동시에 처리할 수 있습니다. 볼륨이 단일 사용자가 대용량 데이터(예: 멀티미디어)를 전송하는 환경에 있는 경우 단일 데이터 전송 요청을 단일 데이터 스트라이프로 처리할 때 성능이 극대화됩니다. (데이터 스트라이프는 세그먼트 크기로, 볼륨 그룹의 데이터 전송에 사용되는 드라이브 수를 곱합니다.) 이 경우 여러 드라이브가 동일한 요청에 사용되지만 각 드라이브는 한 번만 액세스됩니다.

다중 사용자 데이터베이스 또는 파일 시스템 스토리지 환경에서 최적의 성능을 얻으려면 세그먼트 크기를 설정하여 데이터 전송 요청을 충족하는 데 필요한 드라이브 수를 최소화하십시오.



== 사용 힌트

[NOTE]
====
"cacheReadPrefetch" 매개 변수 또는 'egmentSize' 매개 변수의 값을 입력할 필요가 없습니다. 값을 입력하지 않으면 컨트롤러 펌웨어는 파일 시스템이 있는 usageHint 매개변수를 기본값으로 사용합니다. usageHint 파라미터의 값과 cacheReadPrefetch 파라미터의 값 또는 'egmentSize' 파라미터의 값을 입력해도 오류가 발생하지 않습니다. cacheReadPrefetch 파라미터나 'egmentSize' 파라미터에 입력하는 값은 usageHint 파라미터의 값보다 우선합니다. 다양한 용도에 대한 세그먼트 크기 및 캐시 읽기 프리페치 설정은 다음 표에 나와 있습니다.

====
|===
| 사용 힌트 | 세그먼트 크기 설정 | 동적 캐시 읽기 프리페치 설정 


 a| 
파일 시스템
 a| 
128KB
 a| 
활성화됨



 a| 
데이터베이스
 a| 
128KB
 a| 
활성화됨



 a| 
멀티미디어
 a| 
256KB
 a| 
활성화됨

|===


== 캐시 읽기 프리페치

캐시 읽기 프리페치를 사용하면 컨트롤러는 추가 데이터 블록을 캐시로 복사하는 한편, 컨트롤러는 호스트에서 요청한 데이터 블록을 드라이브에서 캐시로 읽고 복사합니다. 이 작업을 수행하면 캐시에서 향후 데이터 요청을 처리할 수 있는 가능성이 높아집니다. 캐시 읽기 프리페치는 순차 데이터 전송을 사용하는 멀티미디어 응용 프로그램에 중요합니다. cacheReadPrefetch 파라미터의 유효한 값은 TRUE나 FALSE입니다. 기본값은 true입니다.

"cacheReadPrefetch" 매개 변수 또는 'egmentSize' 매개 변수의 값을 입력할 필요가 없습니다. 값을 입력하지 않으면 컨트롤러 펌웨어는 파일 시스템이 있는 usageHint 매개변수를 기본값으로 사용합니다. usageHint 파라미터의 값과 cacheReadPrefetch 파라미터의 값 또는 'egmentSize' 파라미터의 값을 입력해도 오류가 발생하지 않습니다. cacheReadPrefetch 파라미터나 'egmentSize' 파라미터에 입력하는 값은 usageHint 파라미터의 값보다 우선합니다.



== 보안 유형입니다

'ecurityType' 매개 변수를 사용하여 스토리지 배열의 보안 설정을 지정합니다.

'ecurityType' 매개 변수를 'enabled'로 설정하려면 먼저 스토리지 배열 보안 키를 생성해야 합니다. 스토리지 배열 보안 키를 생성하려면 "create storageArray securityKey" 명령을 사용합니다. 이러한 명령은 보안 키와 관련이 있습니다.

* 스토리지 배열 보안 키 만들기
* securityKey 내보내기
* 스토리지 배열 보안 키 가져오기
* 'et storageArray securityKey'를 선택합니다
* 볼륨그룹 [volumeGroupName] 보안 활성화
* 'diskpool [diskPoolName] 보안 설정'




== 최소 펌웨어 레벨입니다

7.10은 RAID 레벨 6 기능과 dssPreAllocate 매개변수를 추가합니다.

7.50은 'ecurityType' 파라미터를 추가한다.

7.60은 _drawerID_user 입력과 DrawerLossProtect 매개변수를 추가합니다.

7.75는 '다카Assurance' 파라미터를 추가합니다.

8.63은 resourceProvisionCapable 매개 변수를 추가합니다.
