---
permalink: commands-a-z/create-volumecopy.html 
sidebar: sidebar 
keywords: create, volume, copy 
summary: create volumeCopy 명령은 볼륨 복사본을 생성하고 볼륨 복사 작업을 시작합니다. 이 명령은 스냅샷 이미지 볼륨 복사본 쌍에 대해 유효합니다. 
---
= 볼륨 복사본 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create volumeCopy 명령은 볼륨 복사본을 생성하고 볼륨 복사 작업을 시작합니다. 이 명령은 스냅샷 이미지 볼륨 복사본 쌍에 대해 유효합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
볼륨 복사본 작업을 시작하면 타겟 볼륨의 기존 데이터가 모두 덮어쓰여집니다. 그러면 타겟 볼륨이 호스트에 대해 읽기 전용이 되고 타겟 볼륨과 연결된 모든 스냅샷 이미지 볼륨에 장애가 발생합니다. 이전에 타겟 볼륨을 복제본으로 사용한 경우 더 이상 데이터가 필요하지 않거나 백업되지 않았는지 확인하십시오.

====
이 명령은 두 가지 방법으로 볼륨 복사본을 생성합니다.

* 스냅샷 이미지가 없는 볼륨 복사본, _ offline_volume 복사본이라고도 합니다
* 스냅샷 이미지가 있는 볼륨 복사본, _ online_volume 복사본이라고도 합니다


스냅샷 이미지 없이 볼륨 복제를 사용하는 경우 복제 작업이 완료될 때까지 소스 볼륨에 쓸 수 없습니다. 복제 작업이 완료되기 전에 소스 볼륨에 쓸 수 있도록 하려면 스냅샷 이미지와 함께 볼륨 복제를 사용합니다. 명령 구문에서 선택적 매개 변수를 사용하여 스냅샷 이미지가 있는 볼륨 복사본을 선택할 수 있습니다.

스냅샷 이미지 작업이 있는 볼륨 복사가 완료되면 스냅샷 이미지가 삭제되고 스냅샷 볼륨이 비활성화됩니다.

[NOTE]
====
한 번에 최대 8개의 볼륨 복사본을 생성할 수 있습니다. 한 번에 8개 이상의 볼륨 복사본을 생성하려고 하면 진행 중인 볼륨 복사본 중 하나가 완료되고 완료 상태가 반환될 때까지 컨트롤러가 보류 상태로 돌아갑니다.

====


== 구문

[source, cli, subs="+macros"]
----
create volumeCopy source=pass:quotes[_"sourceName"_
target="_targetName_"]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
[copyType=(offline | online)]
[repositoryPercentOfBase=(20 | 40 | 60 | 120 | default)]
[repositoryGroupPreference=(sameAsSource | otherThanSource | default)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'소스'입니다
 a| 
소스 볼륨으로 사용할 기존 볼륨의 이름입니다. 소스 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
표적
 a| 
타겟 볼륨으로 사용할 기존 볼륨의 이름입니다. 타겟 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
카피프라이어리티
 a| 
볼륨 복사본의 우선 순위는 호스트 I/O 활동과 관련이 있습니다. 유효한 값은 '가장 높음', '높음', '중간', '낮음' 또는 '가장 낮음'입니다.



 a| 
targetReadOnlyEnabled
 a| 
타겟 볼륨에 쓰거나 타겟 볼륨에서만 읽을 수 있도록 하는 설정입니다. 타겟 볼륨에 쓰려면 이 매개변수를 'false'로 설정합니다. 타겟 볼륨에 쓰지 않으려면 이 매개 변수를 "true"로 설정합니다.



 a| 
카피타입
 a| 
스냅샷 이미지를 사용하여 볼륨 복사본을 생성하려면 이 매개 변수를 사용합니다. 스냅샷 이미지를 사용하여 볼륨 복사본을 생성하면 볼륨 복사본을 생성하는 동안 소스 볼륨에 계속 쓸 수 있습니다. 스냅샷 이미지를 사용하여 볼륨 복사본을 생성하려면 이 매개 변수를 "온라인"으로 설정합니다. 스냅샷 이미지 없이 볼륨 복사본을 생성하려면 이 매개 변수를 "오프라인"으로 설정합니다.

이 매개 변수를 사용하지 않으면 스냅샷 이미지 없이 볼륨 복사본이 생성됩니다.



 a| 
재소유주의 페르centOfBase
 a| 
이 매개 변수는 스냅샷 이미지를 사용하여 볼륨 복사본을 생성할 때 스냅샷 이미지에 대한 저장소 볼륨의 크기를 결정합니다. 저장소 볼륨의 크기는 소스 볼륨의 백분율로 표현되며, 이를 기본 볼륨이라고도 합니다. 이 파라미터의 유효한 값은 20분 40초 60초 120분 기본값(기본값)입니다. 기본값은 20입니다. 이 매개변수를 사용하지 않으면 펌웨어가 20%의 값을 사용합니다.

'copyType' 매개 변수를 'RepositoryPercentOfBase' 매개 변수와 함께 사용해야 합니다.



 a| 
재구매그룹 선호
 a| 
이 매개 변수는 스냅샷 이미지 저장소 볼륨이 기록되는 볼륨 그룹을 결정합니다. 다음과 같은 옵션이 있습니다.

* 'sameAsSource' -- 공간이 사용 가능한 경우 스냅샷 이미지 볼륨이 소스 볼륨과 동일한 볼륨 그룹에 기록됩니다.
* 'otherThanSource' -- 사용되지 않는 매개 변수입니다. 사용하지 마십시오
* 기본값 -- 스냅샷 이미지 저장소 볼륨은 공간이 있는 모든 볼륨 그룹에 기록됩니다.


최상의 성능을 얻으려면 '메이트 소스' 옵션을 사용하십시오.

'copyType' 파라미터를 'repositoryGroupPreference' 파라미터와 함께 사용해야 합니다.

|===


== 참고

이름에 영숫자, 발생, 밑줄의 조합을 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

복사 우선 순위는 소스 볼륨과 볼륨 복사본 쌍의 타겟 볼륨 간의 데이터를 복사하는 데 사용되는 시스템 리소스의 양을 정의합니다. 가장 높은 우선 순위 수준을 선택하면 볼륨 복사본은 대부분의 시스템 리소스를 사용하여 볼륨 복사본을 수행하므로 호스트 데이터 전송 성능이 저하됩니다.
