---
permalink: commands-a-z/create-initiator.html 
sidebar: sidebar 
keywords: create, initiator 
summary: create initiator 명령은 이니시에이터 객체를 생성합니다. 
---
= 이니시에이터를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'이니시에이터 생성' 명령은 이니시에이터 객체를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령은 사용되지 않는 를 대체합니다 xref:create-iscsiinitiator.adoc[iSCSI 이니시에이터를 생성합니다] 명령.

====
[NOTE]
====
이 명령은 iSCSI, iSER, NVMe over RoCE, NVMe over InfiniBand 및 NVMe over Fibre Channel에만 적용할 수 있습니다.

====


== 구문

[source, cli]
----
create initiator identifier="initiatorQualifiedName" userLabel="initiatorName" host="hostName"
interfaceType=(iscsi | iser | nvmeof) [chapSecret="securityKey"]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'식별자'
 a| 
이니시에이터를 생성할 식별자 정규화된 이름(예: iqn 또는 nqn)을 지정할 수 있습니다. 식별자는 큰따옴표(" ")로 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
이니시에이터의 사용자 레이블을 지정할 수 있습니다. 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트
 a| 
이니시에이터가 설치된 호스트 이름을 지정할 수 있습니다. 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'InterfaceType'
 a| 
이니시에이터가 사용할 인터페이스 유형을 지정할 수 있습니다. 유효한 선택 항목은 iSCSI, iser 또는 nvmeof입니다.



 a| 
'챕시크릿
 a| 
피어 연결을 인증하는 데 사용할 보안 키를 입력할 수 있습니다. 보안 키는 큰따옴표(" ")로 묶어야 합니다. 이 매개 변수는 iSCSI 및 iSER 호스트 인터페이스 유형에만 적용할 수 있습니다.

|===


== 최소 펌웨어 레벨입니다

8.41
