---
permalink: commands-a-z/create-ssdcache.html 
sidebar: sidebar 
keywords: create, ssd, cache 
summary: 'create ssdCache 명령은 SSD(Solid State Disk)를 사용하여 스토리지 배열에 대한 읽기 캐시를 생성합니다.' 
---
= SSD 캐시를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'create ssdCache' 명령은 SSD(Solid State Disk)를 사용하여 스토리지 어레이에 대한 읽기 캐시를 생성합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 지원 관리자 역할이 있어야 합니다.



== 상황

고성능 SSD를 사용하여 읽기 데이터를 캐싱하면 애플리케이션 I/O 성능과 응답 시간이 향상되고, 다양한 워크로드, 특히 높은 IOP 워크로드에 대해 일관된 성능 개선이 제공됩니다. SSD 캐시는 고가의 고속 SSD 사용을 극대화합니다. SSD 캐시는 컨트롤러 DRAM의 기본 캐시와 함께 작동합니다. 컨트롤러 캐시를 사용하면 호스트 읽기 후 데이터가 DRAM에 저장됩니다. SSD 캐시를 사용하면 데이터가 사용자 지정 기본 볼륨에서 복사되고 SSD에 캐싱됩니다.



== 구문

[listing, subs="+macros"]
----
create ssdCache userLabel=pass:quotes[_"ssdCacheName"_]
drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,[drawerIDn,_]]pass:quotes[_slotIDn_)]
[updateExistingVolumes=(TRUE|FALSE)]
[securityType=(none|capable|enabled)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
새 SSD 캐시의 이름을 지정할 이름입니다. SSD 캐시 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"늑대들"
 a| 
SSD 캐시를 생성하는 데 사용할 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
업데이트 볼륨
 a| 
이 선택적 매개 변수는 스토리지 배열의 모든 기존 볼륨에 대해 SSD 캐시를 설정해야 하는지 여부를 지정합니다. 모든 기존 볼륨에 대해 SSD 캐시를 활성화하려면 이 매개 변수를 "true"로 설정합니다. 나중에 개별 볼륨에 대해 SSD 캐시를 활성화하려면 이 매개 변수를 "false"로 설정하십시오. 기본값은 "true"입니다.



 a| 
'생태형'을 선택합니다
 a| 
이 선택적 매개 변수는 SSD 캐시를 생성할 때 보안 수준을 지정합니다. 다음 설정이 유효합니다.

* "없음" - SSD 캐시가 안전하지 않습니다.
* "Capable" - SSD Cache는 보안 설정을 할 수 있지만 보안이 설정되지 않았습니다.
* "활성화됨" - SSD 캐시에 보안이 설정되어 있습니다.


|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

스토리지 어레이에는 SSD 캐시가 하나만 있을 수 있습니다.

하드 디스크 드라이브를 사용하여 생성된 볼륨만 SSD 캐시를 사용할 수 있습니다. 스냅샷 이미지에는 SSD 캐시를 설정할 수 없습니다.

SSD 캐시의 모든 SSD가 DA(Data Assurance)를 지원하며 DA 기능을 활성화하면 SSD 캐시에 대해 DA가 자동으로 설정되며 비활성화할 수 없습니다. 또한 DA를 지원하지 않는 SSD를 DA 지원 SSD 캐시에 추가할 수 없습니다.



== 최소 펌웨어 레벨입니다

7.84

이제 8.20_M3-FDE 드라이브가 지원됩니다. 'ecurityType' 파라미터를 추가했다.

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
