---
permalink: commands-a-z/create-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: create, asynchronous, mirror, group 
summary: create asyncMirrorGroup 명령은 로컬 스토리지 시스템과 원격 스토리지 시스템 모두에 비어 있는 새 비동기식 미러 그룹을 생성합니다. 
---
= 비동기 미러 그룹 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create asyncMirrorGroup 명령은 로컬 스토리지 시스템과 원격 스토리지 시스템 모두에 비어 있는 새 비동기식 미러 그룹을 생성합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
이 명령은 E4000, E2800, E5700, EF600 및 EF300 플랫폼에서는 지원되지 않습니다.

====


== 역할

해당 없음



== 상황

비동기 미러 그룹은 여러 미러링된 쌍을 하나의 개체로 관리할 수 있도록 저장할 수 있는 컨테이너입니다. 비동기식 미러 그룹을 생성하여 그룹 내의 모든 미러링된 쌍에 대한 동기화 설정을 정의합니다. 비동기 미러 그룹의 각 미러링 쌍은 동일한 동기화 설정, 1차 및 2차 역할, 쓰기 모드를 공유합니다.

비동기식 미러 그룹은 미러링에 사용되는 로컬 스토리지 시스템 및 원격 스토리지 시스템에 연결됩니다. 로컬 스토리지 시스템은 비동기 미러 그룹의 기본 측이고 원격 스토리지 시스템은 비동기 미러 그룹의 보조 측입니다. 로컬 스토리지 시스템의 비동기식 미러 그룹에 추가된 모든 볼륨은 미러 관계에서 1차 역할을 수행합니다. 그런 다음 원격 스토리지 시스템의 비동기식 미러 그룹에 추가된 모든 볼륨은 미러 관계에서 2차 역할을 수행합니다.

로컬 스토리지 시스템에서 'Create Asynchronous Mirror Group' 명령을 실행해야 합니다. 비동기식 미러 그룹 생성은 미러 관계에서 1차 역할을 가진 볼륨이 포함된 스토리지 시스템에서 시작됩니다. "Create Asynchronous Mirror Group" 명령을 사용하여 미러 관계에서 2차 역할을 가진 볼륨이 포함된 원격 스토리지 배열의 ID를 지정합니다.



== 구문

[source, cli, subs="+macros"]
----
create asyncMirrorGroup userLabel=pass:quotes[_"asyncMirrorGroupName"_]
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_] | remoteStorageArrayWWN=pass:quotes[_"wwID"_])
[remotePassword=pass:quotes[_"password"_]
interfaceType=(FC | iSCSI)
[syncInterval=pass:quotes[_integer_](minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningRecoveryThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[autoResync=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
생성할 새 비동기식 미러 그룹의 이름입니다. 새 비동기식 미러 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.

이름은 로컬 및 원격 스토리지 시스템에서 고유해야 합니다.



 a| 
"remoteStorageArrayName"입니다
 a| 
비동기식 미러 그룹을 미러링할 원격 스토리지 시스템의 이름입니다. 스토리지 배열 이름은 큰따옴표(" ")로 묶어야 합니다.

원격 스토리지 시스템의 접속 유형은 로컬 스토리지 시스템과 동일해야 합니다.



 a| 
"remoteStorageArrayWWN"입니다
 a| 
비동기식 미러 그룹을 미러링하는 원격 스토리지 시스템의 WWID(World Wide Identifier)입니다. 스토리지 배열 이름 대신 WWID를 사용하여 스토리지 배열을 식별할 수 있습니다. WWID는 꺾쇠 괄호(<>)로 묶어야 합니다.

원격 스토리지 시스템의 접속 유형은 로컬 스토리지 시스템과 동일해야 합니다.



 a| 
암호 재입력
 a| 
원격 스토리지 시스템의 암호입니다. 원격 스토리지 배열이 암호로 보호되는 경우 이 매개 변수를 사용합니다. 암호는 큰따옴표(" ")로 묶어야 합니다.



 a| 
'InterfaceType'
 a| 
사용할 접속 유형(Fibre Channel Fabric 또는 iSCSI 인터페이스)을 지정합니다. (기본값은 Fibre Channel입니다.) 로컬 스토리지 어레이와 원격 스토리지 시스템은 적절한 Fibre Channel Fabric 또는 iSCSI 인터페이스를 통해 접속되어야 합니다.



 a| 
'동기화 간격'
 a| 
로컬 스토리지 시스템에서 원격 스토리지 시스템으로 수정된 데이터의 업데이트를 자동으로 보내는 시간 간격을 지정합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.

[NOTE]
====
정수와 시간 사이에 공백을 추가하지 마십시오.

====
예: '10분'



 a| 
"warningSyncThreshold"를 선택합니다
 a| 
비동기식 미러 그룹 내의 모든 볼륨의 동기화가 정의된 시간보다 오래 걸리는 경우 경고가 트리거될 때까지 대기하는 시간을 지정합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.

[NOTE]
====
정수와 시간 사이에 공백을 추가하지 마십시오.

====
예: 30분



 a| 
'warningRecoveryThreshold'
 a| 
원격 스토리지 배열의 특정 시점 이미지에 대한 자동 데이터 업데이트가 정의된 시간보다 오래된 경우 경고가 트리거될 때까지 대기하는 시간을 지정합니다. 이전 업데이트 종료 시 임계값을 정의합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.

[NOTE]
====
복구 지점 임계값 을 동기화 간격 임계값의 두 배로 설정해야 합니다.

====
[NOTE]
====
정수와 시간 사이에 공백을 추가하지 마십시오.

====
예: 60분



 a| 
"warningThresholdPercent"를 참조하십시오
 a| 
미러 저장소 볼륨의 용량이 정의된 비율에 도달할 때 경고가 트리거될 때까지 대기하는 시간을 지정합니다. 남은 용량의 백분율(%)을 기준으로 임계값을 정의합니다.



 a| 
자동 재동기화
 a| 
비동기식 미러 그룹 내에 있는 비동기식 미러링된 쌍의 보조 볼륨과 운영 볼륨 간의 자동 재동기화를 위한 설정입니다. 이 매개 변수에는 다음 값이 있습니다.

* "활성화됨" -- 자동 재동기화가 켜져 있습니다. 기본 볼륨과 보조 볼륨을 다시 동기화하기 위해 더 이상 수행할 작업은 없습니다.
* 비활성화 -- 자동 재동기화가 해제됩니다. 기본 볼륨과 보조 볼륨을 재동기화하려면 'reSUME asyncMirrorGroup' 명령을 실행해야 합니다.


|===


== 참고

* 비동기식 미러링 기능은 미러 작업에 사용할 로컬 및 원격 스토리지 시스템에서 설정 및 활성화해야 합니다.
* 이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.
* 로컬 및 원격 스토리지 시스템은 Fibre Channel 패브릭 또는 iSCSI 인터페이스를 통해 접속되어야 합니다.
* 암호는 관리 도메인의 각 스토리지 배열에 저장됩니다. 이전에 암호를 설정하지 않은 경우 암호가 필요하지 않습니다. 암호는 최대 30자의 영숫자 문자를 조합하여 사용할 수 있습니다. (Set storageArray 명령어를 이용하여 스토리지 배열 비밀번호를 정의할 수 있다.)
* 구성에 따라 스토리지 배열에 생성할 수 있는 최대 비동기식 미러 그룹 수가 있습니다.
* 비동기 미러 그룹은 비어 있고 미러링된 쌍이 나중에 추가됩니다. 비동기 미러 그룹에는 미러링된 쌍만 추가할 수 있습니다. 각 미러링된 쌍은 정확히 하나의 비동기식 미러 그룹과 연결됩니다.
* 비동기 미러링 프로세스는 정의된 동기화 간격에서 시작됩니다. 변경된 데이터만 복사되고 전체 볼륨은 복사되지 않으므로 주기적 시점 이미지가 복제됩니다.




== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
