---
permalink: commands-a-z/create-raid-volume-free-extent-based-select.html 
sidebar: sidebar 
keywords: create, raid, volume, free, extent, based, select 
summary: 볼륨 생성 명령은 볼륨 그룹의 여유 공간에 볼륨을 생성합니다. 
---
= RAID 볼륨 생성(사용 가능한 익스텐트 기반 선택)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 생성 명령은 볼륨 그룹의 여유 공간에 볼륨을 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
create volume volumeGroup=pass:quotes[_"volumeGroupName"_
userLabel="_volumeName"_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[dataAssurance=(none | enabled)]
[blockSize=blockSizeValue]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
볼륨그룹
 a| 
스토리지 배열에 있는 특정 볼륨 그룹의 이름입니다. 볼륨 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
새 볼륨에 지정할 이름입니다. 새 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.

[NOTE]
====
이 매개 변수는 필수입니다.

====


 a| 
프리커패시터
 a| 
새 볼륨을 생성하는 데 사용할 기존 볼륨 그룹의 사용 가능한 공간의 인덱스 번호입니다. 사용 가능한 용량은 볼륨 그룹의 기존 볼륨 간 사용 가능한 용량으로 정의됩니다. 예를 들어, 볼륨 그룹의 영역은 볼륨 1, 사용 가능한 용량, 볼륨 2, 사용 가능한 용량, 볼륨 3, 여유 용량: 볼륨 2 다음에 사용 가능한 용량을 사용하려면 이 인덱스 번호를 입력합니다.

자유 용량=2

[NOTE]
====
'show volumeGroup' 명령을 실행하여 사용 가능한 용량 영역이 있는지 확인합니다.

====
[NOTE]
====
이 매개 변수를 지정하지 않으면 볼륨이 볼륨에 충분한 용량을 가진 가장 낮은 번호의 사용 가능 용량 영역에 생성됩니다.

====


 a| 
용량
 a| 
스토리지 배열에 추가할 볼륨의 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.



 a| 
오너
 a| 
볼륨을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 소유자를 지정하지 않으면 컨트롤러 펌웨어가 소유자를 결정합니다.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다.



 a| 
'크기'
 a| 
다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 양(KB)입니다. 유효한 값은 8인치, 16인치, 32인치, 64인치, 128입니다. 256, 512.



 a| 
'usageHint'
 a| 
cacheReadPrefetch 매개변수와 'egmentSize' 매개 변수의 설정이 기본값으로 되어 있습니다. 기본값은 볼륨을 사용하는 애플리케이션의 일반적인 I/O 사용 패턴을 기반으로 합니다. 유효한 값은 파일 시스템, 다타베이스 또는 멀티미디어 입니다.



 a| 
드슈프리알Locate
 a| 
예약 용량이 향후 세그먼트 크기에 할당되도록 하는 설정입니다. 기본값은 "true"입니다.



 a| 
'생태형'을 선택합니다
 a| 
볼륨 그룹 및 연결된 모든 볼륨을 생성할 때 보안 수준을 지정하는 설정입니다. 다음 설정이 유효합니다.

"없음" -- 볼륨 그룹과 볼륨이 안전하지 않습니다.

"Capable(기능)" -- 볼륨 그룹과 볼륨에 보안 설정이 가능하지만 보안이 활성화되지 않았습니다.

"활성화됨" -- 볼륨 그룹과 볼륨에 보안이 설정되어 있습니다.



 a| 
박수
 a| 
이 매개 변수를 사용하여 볼륨을 호스트에 매핑할 수 있습니다. 나중에 매핑하려면 이 매개 변수를 로 설정합니다 `none`. 지금 매핑하려면 이 매개 변수를 로 설정합니다 `default`. 볼륨은 스토리지 풀에 대한 액세스 권한이 있는 모든 호스트에 매핑됩니다. 기본값은 입니다 `none`.



 a| 
블록사이즈
 a| 
이 매개 변수는 생성할 볼륨의 블록 크기를 설정합니다. 0 또는 설정되지 않은 매개 변수는 기본 블록 크기를 사용합니다.

|===


== 참고

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

소유자 매개변수는 볼륨을 소유하는 컨트롤러를 정의합니다. 볼륨의 기본 컨트롤러 소유권은 현재 볼륨 그룹을 소유한 컨트롤러입니다.

'capacity' 매개 변수를 사용하여 용량을 지정하지 않으면 볼륨 그룹의 여유 용량 영역에서 사용 가능한 모든 용량이 사용됩니다. 용량 단위를 지정하지 않으면 "바이트"가 기본값으로 사용됩니다.



== 세그먼트 크기

세그먼트 크기에 따라 다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 블록 수가 결정됩니다. 각 데이터 블록에는 512바이트의 데이터가 저장됩니다. 데이터 블록은 가장 작은 스토리지 단위입니다. 세그먼트의 크기에 따라 포함된 데이터 블록의 수가 결정됩니다. 예를 들어 8KB 세그먼트에는 16개의 데이터 블록이 있습니다. 64KB 세그먼트에는 128개의 데이터 블록이 있습니다.

세그먼트 크기에 대한 값을 입력하면 이 값은 런타임에 컨트롤러에서 제공하는 지원되는 값과 비교하여 확인됩니다. 입력한 값이 유효하지 않으면 컨트롤러가 유효한 값 목록을 반환합니다. 단일 요청에 단일 드라이브를 사용하면 다른 드라이브를 사용할 수 있어 다른 요청을 동시에 처리할 수 있습니다. 볼륨이 단일 사용자가 대용량 데이터(예: 멀티미디어)를 전송하는 환경에 있는 경우 단일 데이터 전송 요청을 단일 데이터 스트라이프로 처리할 때 성능이 극대화됩니다. (데이터 스트라이프는 세그먼트 크기로, 볼륨 그룹의 데이터 전송에 사용되는 드라이브 수를 곱합니다.) 이 경우 여러 드라이브가 동일한 요청에 사용되지만 각 드라이브는 한 번만 액세스됩니다.

다중 사용자 데이터베이스 또는 파일 시스템 스토리지 환경에서 최적의 성능을 얻으려면 세그먼트 크기를 설정하여 데이터 전송 요청을 충족하는 데 필요한 드라이브 수를 최소화하십시오.



== 사용 힌트

[NOTE]
====
"cacheReadPrefetch" 매개 변수 또는 'egmentSize' 매개 변수의 값을 입력할 필요가 없습니다. 값을 입력하지 않으면 컨트롤러 펌웨어는 파일 시스템이 있는 usageHint 매개변수를 기본값으로 사용합니다. usageHint 파라미터의 값과 cacheReadPrefetch 파라미터의 값 또는 'egmentSize' 파라미터의 값을 입력해도 오류가 발생하지 않습니다. cacheReadPrefetch 파라미터나 'egmentSize' 파라미터에 입력하는 값은 usageHint 파라미터의 값보다 우선합니다. 다양한 용도에 대한 세그먼트 크기 및 캐시 읽기 프리페치 설정은 다음 표에 나와 있습니다.

====
|===
| 사용 힌트 | 세그먼트 크기 설정 | 동적 캐시 읽기 프리페치 설정 


 a| 
파일 시스템
 a| 
128KB
 a| 
활성화됨



 a| 
데이터베이스
 a| 
128KB
 a| 
활성화됨



 a| 
멀티미디어
 a| 
256KB
 a| 
활성화됨

|===


== 캐시 읽기 프리페치

캐시 읽기 프리페치를 사용하면 컨트롤러는 추가 데이터 블록을 캐시로 복사하는 한편, 컨트롤러는 호스트에서 요청한 데이터 블록을 드라이브에서 캐시로 읽고 복사합니다. 이 작업을 수행하면 캐시에서 향후 데이터 요청을 처리할 수 있는 가능성이 높아집니다. 캐시 읽기 프리페치는 순차 데이터 전송을 사용하는 멀티미디어 응용 프로그램에 중요합니다. cacheReadPrefetch 파라미터의 유효한 값은 TRUE나 FALSE입니다. 기본값은 true입니다.



== 보안 유형입니다

'ecurityType' 매개 변수를 사용하여 스토리지 배열의 보안 설정을 지정합니다.

'ecurityType' 매개 변수를 'enabled'로 설정하려면 먼저 스토리지 배열 보안 키를 생성해야 합니다. 스토리지 배열 보안 키를 생성하려면 "create storageArray securityKey" 명령을 사용합니다. 이러한 명령은 보안 키와 관련이 있습니다.

* 스토리지 배열 보안 키 만들기
* securityKey 내보내기
* 스토리지 배열 보안 키 가져오기
* 'et storageArray securityKey'를 선택합니다
* 볼륨그룹 [volumeGroupName] 보안 활성화
* 'diskpool [diskPoolName] 보안 설정'




== 최소 펌웨어 레벨입니다

7.10은 dssPreAllocate 파라미터를 추가한다.

7.50은 'ecurityType' 파라미터를 추가한다.

7.75는 '다카Assurance' 파라미터를 추가합니다.

11.70이 를 추가합니다 `blockSize` 매개 변수.
