---
permalink: commands-a-z/create-cgsnapimage-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency group, snapshot image 
summary: cgSnapImage ConsistencyGroup 명령을 생성하면 스냅샷 정합성 보장 그룹의 구성원인 각 기본 볼륨에 대한 새 스냅샷 이미지가 생성됩니다. 
---
= 일관성 그룹 스냅샷 이미지 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"create cgSnapImage ConsistencyGroup" 명령은 스냅샷 정합성 보장 그룹의 구성원인 각 기본 볼륨에 대해 새 스냅샷 이미지를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
create cgSnapImage consistencyGroup=pass:quotes[_"consistencyGroupName"_]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
일관성 그룹
 a| 
스냅샷 이미지를 생성할 정합성 보장 그룹의 이름입니다. 정합성 보장 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

명령을 실행하면 스냅샷 이미지를 생성하기 전에 정합성 보장 그룹의 구성원인 각 기본 볼륨에 대해 보류 중인 모든 입출력 작업이 드레이닝되고 일시 중지됩니다. 모든 정합성 보장 그룹 구성원에 대해 모든 스냅샷 이미지 생성을 성공적으로 완료할 수 없는 경우 작업이 실패하고 새 스냅샷 이미지가 생성되지 않습니다.

일반적으로 스냅샷 정합성 보장 그룹의 모든 구성원은 동일한 수의 스냅샷 이미지를 갖습니다. 스냅샷 정합성 보장 그룹에 새 구성원을 추가하면 해당 새 구성원은 이전에 스냅샷 정합성 보장 그룹의 설정된 구성원에 생성된 스냅샷 이미지가 없습니다. 이는 오류 상태가 아닙니다. 스냅샷 정합성 보장 그룹 구성원의 하위 집합에만 있는 스냅샷 이미지의 삭제 또는 롤백 요청은 지정된 스냅샷 이미지가 실제로 존재하는 구성원에만 영향을 줍니다.



== 최소 펌웨어 레벨입니다

7.83
