---
permalink: commands-a-z/create-read-only-snapshot-volume.html 
sidebar: sidebar 
keywords: create, read only, snapshot, volume 
summary: create snapVolume 명령은 기본 볼륨의 스냅샷 이미지에 대한 읽기 전용 스냅샷 볼륨을 생성합니다. 읽기 전용 스냅샷 볼륨을 읽기/쓰기 볼륨으로 변경하려면 set snapVolume convertToReadWrite 명령을 사용합니다. 
---
= 읽기 전용 스냅샷 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
create snapVolume 명령은 기본 볼륨의 스냅샷 이미지에 대한 읽기 전용 스냅샷 볼륨을 생성합니다. 읽기 전용 스냅샷 볼륨을 읽기/쓰기 볼륨으로 변경하려면 '스냅 볼륨 변환기 ToReadWrite 설정' 명령을 사용합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
온라인 볼륨 복사본에 사용되는 스냅샷 이미지에는 이 명령을 사용할 수 없습니다.

====


== 구문

[listing, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName"_
snapImageID="_snapCGID:imageID"_]
readOnly
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
스냅샷 볼륨에 지정할 이름입니다. 스냅샷 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
나ImageID
 a| 
새 읽기 전용 스냅샷 볼륨에 추가할 스냅샷 이미지의 이름입니다. 스냅샷 이미지의 이름은 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' - 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' - 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"재만"을 선택합니다
 a| 
이 매개변수는 스냅샷 볼륨을 읽기 전용으로 설정합니다. 이 매개 변수는 실제로 부울이지만 이 명령의 컨텍스트에서 부울 값은 항상 "true"입니다.

[NOTE]
====
"readOnly" 매개 변수를 사용하면 스냅샷 볼륨이 생성되지 않습니다.

====
|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

스냅샷 이미지의 식별자는 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 이미지의 식별자입니다


예를 들어 snapGroup1 이라는 이름의 스냅샷 그룹에서 가장 최근의 스냅샷 이미지를 사용하여 engData1이라는 읽기 전용 볼륨을 만들려면 다음 명령을 사용합니다.

[listing]
----
create snapVolume userLabel="engData1" snapImageID="snapGroup1:newest" readOnly;
----


== 최소 펌웨어 레벨입니다

7.83
