---
permalink: commands-a-z/create-host.html 
sidebar: sidebar 
keywords: create, host 
summary: create host 명령은 새 호스트를 생성합니다. 
---
= 호스트 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create host 명령은 새 호스트를 만듭니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

E2700 및 E5600 스토리지 어레이의 경우, 새 호스트를 생성할 호스트 그룹을 지정하지 않을 경우 기본 그룹에 새 호스트가 생성됩니다.



== 구문

[source, cli, subs="+macros"]
----
create host userLabel=pass:quotes[_"hostName"_]
[hostGroup=pass:quotes[(_"hostGroupName"_] | defaultGroup)]
[hostType=(hostTypeIndexLabel | hostTypeIndexNumber)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'사용자 레이블'
 a| 
생성 중인 호스트에 지정할 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트그룹
 a| 
새 호스트를 생성할 호스트 그룹의 이름입니다. 호스트 그룹 이름은 큰따옴표(" ")로 묶어야 합니다. (호스트 그룹이 없는 경우 'create hostGroup' 명령을 사용하여 새 호스트 그룹을 생성할 수 있습니다.) "defaultGroup" 옵션은 볼륨이 매핑되는 호스트가 포함된 호스트 그룹입니다.



 a| 
호스트 유형
 a| 
호스트 유형을 식별하는 인덱스 레이블 또는 인덱스 번호입니다. 사용 가능한 호스트 유형 식별자 목록을 생성하려면 'show storageArray hostTypeTable' 명령을 사용합니다. 호스트 유형에 특수 문자가 있는 경우 호스트 유형을 큰따옴표(" ")로 묶습니다.

|===


== 참고

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

호스트는 스토리지 배열에 연결되어 호스트 포트를 통해 스토리지 배열의 볼륨에 액세스하는 컴퓨터입니다. 개별 호스트에 대한 특정 매핑을 정의할 수 있습니다. 하나 이상의 볼륨에 대한 액세스를 공유하는 호스트 그룹에 호스트를 할당할 수도 있습니다.

호스트 그룹은 동일한 볼륨에 대한 액세스를 공유하는 호스트 컬렉션을 지정할지 여부를 정의할 수 있는 선택적 토폴로지 요소입니다. 호스트 그룹은 논리적 엔터티입니다. 동일한 볼륨에 대한 액세스를 공유하는 호스트가 두 개 이상 있는 경우에만 호스트 그룹을 정의합니다.

생성 중인 호스트를 배치할 호스트 그룹을 지정하지 않으면 새로 정의된 호스트가 기본 호스트 그룹에 속합니다.



== 최소 펌웨어 레벨입니다

5.20

7.10은 HostType 파라미터를 추가한다.
