---
permalink: commands-a-z/create-snapimage.html 
sidebar: sidebar 
keywords: create, snapshot, image 
summary: SnapImage 생성 명령은 하나 이상의 기존 스냅샷 그룹에 새 스냅샷 이미지를 생성합니다. 
---
= 스냅샷 이미지 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"SnapImage 생성" 명령은 하나 이상의 기존 스냅샷 그룹에 새 스냅샷 이미지를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

스냅샷 이미지를 생성하려면 먼저 스냅샷 이미지를 배치할 스냅샷 그룹이 하나 이상 있어야 합니다. 스냅샷 그룹을 생성하려면 "SnapGroup 생성" 명령을 사용합니다.



== 구문

[source, cli, subs="+macros"]
----
create snapImage (snapGroup=pass:quotes[_"snapGroupName" |
snapGroups=("_snapGroupName1"... "snapGroupNamen_"))]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
스냅그룹
 a| 
스냅샷 이미지를 포함할 스냅샷 그룹의 이름입니다. 스냅샷 그룹의 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'냅그룹'
 a| 
스냅샷 이미지를 포함할 여러 스냅샷 그룹의 이름입니다. 다음 규칙을 사용하여 스냅샷 그룹의 이름을 입력합니다.

* 모든 이름은 괄호로 묶습니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

스냅샷 이미지는 연관된_base_volume의 내용에 대한 논리적 시점 이미지입니다. 스냅샷 이미지가 즉시 생성되고 이 시점에 기본 볼륨의 상태를 기록합니다. 모든 스냅샷 이미지는 정확히 one_snapshot group_의 컨텍스트에서 생성됩니다. 스냅샷 그룹은 연결된 기본 볼륨의 스냅샷 이미지 시퀀스입니다. 스냅샷 그룹에는 스냅샷 이미지의 모든 데이터를 저장하는 데 사용되는 one_repository volume_이 있습니다. 스냅샷 그룹의 스냅샷 이미지는 특정 순서를 갖습니다. 스냅샷 이미지의 특정 순서를 사용하면 특정 스냅샷 이미지를 기본 볼륨으로 복원하거나 더 이상 필요하지 않은 스냅샷 이미지를 삭제하는 등의 스냅샷 이미지를 관리할 수 있습니다.

정합성 보장 그룹의 스냅샷 이미지를 생성한 결과는 정합성 보장 그룹의 모든 구성원 볼륨에 대한 스냅샷 이미지입니다.



== 최소 펌웨어 레벨입니다

7.83
