---
permalink: commands-a-z/create-syncmirror.html 
sidebar: sidebar 
keywords: create, synchronous, mirroring 
summary: 'create SyncMirror 명령은 동기 원격 미러링 쌍의 운영 볼륨과 2차 볼륨을 모두 생성합니다. 또한 이 명령은 쓰기 모드(동기식 쓰기 모드 또는 비동기식 쓰기 모드)와 동기화 우선 순위를 설정합니다.' 
---
= 동기 미러링을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'create SyncMirror' 명령은 동기식 원격 미러링 쌍의 운영 볼륨과 2차 볼륨을 모두 생성합니다. 또한 이 명령은 쓰기 모드(동기식 쓰기 모드 또는 비동기식 쓰기 모드)와 동기화 우선 순위를 설정합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
E2800 또는 E5700 어레이에서 명령을 실행하는 경우 클라이언트 유형은 '기호'로 설정해야 합니다. 이 명령은 클라이언트 유형이 'https'로 설정된 경우 실행되지 않습니다.

====


== 역할

E2800 또는 E5500스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령의 이전 버전에서는 기능 식별자가 'remoteMirror'였습니다. 이 기능 식별자는 더 이상 유효하지 않으며 SyncMirror로 대체됩니다.

====


== 구문

[listing, subs="+macros"]
----
create syncMirror primary=pass:quotes[_"primaryVolumeName_"
secondary="_secondaryVolumeName_"
(remoteStorageArrayName="_storageArrayName_" |
remoteStorageArrayWwn="_wwID_")]
[remotePassword="password"]
[syncPriority=(highest | high | medium | low | lowest)]
[autoResync=(enabled | disabled)]
[writeOrder=(preserved | notPreserved)]
[writeMode=(synchronous | asynchronous)]
[role=(primary | secondary)]
[force=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
1차
 a| 
운영 볼륨에 사용할 로컬 스토리지 배열의 기존 볼륨 이름입니다. 기본 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
2차
 a| 
보조 볼륨에 사용할 원격 스토리지 시스템의 기존 볼륨 이름입니다. 보조 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"remoteStorageArrayName"입니다
 a| 
원격 스토리지 시스템의 이름입니다. 원격 스토리지 배열 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"모테StorageArrayWwn"
 a| 
원격 스토리지 시스템의 WWID(World Wide Identifier)입니다. WWID는 큰따옴표(" ")로 묶어야 합니다.



 a| 
암호 재입력
 a| 
원격 스토리지 시스템의 암호입니다. 원격 스토리지 배열이 암호로 보호되는 경우 이 매개 변수를 사용합니다. 암호는 큰따옴표(" ")로 묶어야 합니다.



 a| 
'두 우선 순위'입니다
 a| 
전체 동기화가 호스트 I/O 작업과 관련된 우선 순위입니다. 유효한 값은 '가장 높음', '높음', '중간', '낮음' 또는 '가장 낮음'입니다.



 a| 
자동 재동기화
 a| 
운영 볼륨과 원격 미러 쌍의 보조 볼륨 간의 자동 재동기화를 위한 설정입니다. 이 매개 변수에는 다음 값이 있습니다.

* "활성화됨" -- 자동 재동기화가 켜져 있습니다. 기본 볼륨과 보조 볼륨을 다시 동기화하기 위해 더 이상 수행할 작업은 없습니다.
* 비활성화 -- 자동 재동기화가 해제됩니다. 기본 볼륨과 보조 볼륨을 재동기화하려면 'RESSUME SyncMirror' 명령을 실행해야 합니다.




 a| 
"쓰기 순서"
 a| 
운영 볼륨과 보조 볼륨 간의 데이터 전송 순서 유효한 값은 '보존' 또는 'notPreserved'입니다.



 a| 
"쓰기 모드"
 a| 
운영 볼륨이 보조 볼륨에 쓰는 방식 유효한 값은 '동기식' 또는 '비동기식'입니다.



 a| 
역할
 a| 
이 매개 변수를 사용하여 비동기식 미러 그룹을 운영 역할로 프로모션하거나 비동기식 미러 그룹을 보조 역할로 하향 이동합니다. 비동기식 미러 그룹을 기본 역할로 정의하려면 이 매개 변수를 "primary"로 설정합니다. 비동기식 미러 그룹을 2차 역할로 정의하려면 이 매개 변수를 '2차'로 설정합니다.



 a| 
"힘"
 a| 
스토리지 시스템 간의 통신 링크가 다운되고 로컬 측의 상향 이동 또는 하향 이동이 이중 1차 상태 또는 2차 상태를 초래하면 역할 반전이 강제 적용됩니다. 역할 반전을 강제하려면 이 매개 변수를 "true"로 설정합니다. 기본값은 'false'입니다.

|===


== 참고

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

운영 볼륨과 2차 볼륨을 선택할 경우 2차 볼륨의 크기가 운영 볼륨보다 크거나 같아야 합니다. 보조 볼륨의 RAID 레벨은 운영 볼륨과 같을 필요가 없습니다.

암호는 관리 도메인의 각 스토리지 배열에 저장됩니다. 이전에 암호를 설정하지 않은 경우 암호가 필요하지 않습니다. 암호는 최대 30자의 영숫자 문자를 조합하여 사용할 수 있습니다. (Set storageArray 명령어를 이용하여 스토리지 배열 비밀번호를 정의할 수 있다.)

동기화 우선 순위는 운영 볼륨과 미러 관계의 보조 볼륨 간에 데이터를 동기화하는 데 사용되는 시스템 리소스의 양을 정의합니다. 가장 높은 우선 순위 수준을 선택하면 데이터 동기화는 대부분의 시스템 리소스를 사용하여 전체 동기화를 수행하므로 호스트 데이터 전송 성능이 저하됩니다.

"writeOrder" 매개 변수는 비동기 쓰기 모드에만 적용되고 미러링된 쌍이 일관성 그룹의 일부가 되도록 합니다. "writeOrder" 매개 변수를 "Preserved"로 설정하면 원격 미러링 쌍이 운영 볼륨에 쓰는 순서와 동일한 순서로 운영 볼륨에서 2차 볼륨으로 데이터를 전송합니다. 전송 링크에 오류가 발생하면 전체 동기화가 발생할 때까지 데이터가 버퍼링됩니다. 이 작업을 수행하려면 버퍼링된 데이터를 유지 관리하기 위한 추가적인 시스템 오버헤드가 필요하며 이로 인해 작업이 느려집니다. "writeOrder" 매개 변수를 "notPreserved"로 설정하면 시스템이 버퍼에 있는 데이터를 유지 관리할 필요가 없지만 보조 볼륨이 기본 볼륨과 동일한 데이터를 가지도록 전체 동기화를 수행해야 합니다.



== 최소 펌웨어 레벨입니다

6.10
