---
permalink: commands-a-z/create-volume-diskpool.html 
sidebar: sidebar 
keywords: create, volume, disk pool 
summary: create volume diskpool 명령은 기존 디스크 풀에 새 표준 RAID 볼륨 또는 씬 볼륨을 생성합니다. 
---
= 디스크 풀에서 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'create volume diskpool' 명령은 기존 디스크 풀에 새로운 표준 RAID 볼륨 또는 씬 볼륨을 생성합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
볼륨 그룹에서 표준 RAID 볼륨을 만들기 위한 일부 매개 변수는 디스크 풀에 모든 유형의 볼륨을 만드는 데 호환되지 않습니다. 이전 스크립트를 사용하여 디스크 풀에 볼륨을 생성할 때는 모든 매개 변수가 디스크 풀에 대해 유효한지 확인하십시오. 잘못된 매개 변수를 사용하면 스크립트가 올바르게 실행되지 않고 오류가 게시될 수 있습니다.

====


== 표준 볼륨 생성 구문

[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[dataAssurance=(none|enabled)]
[cacheReadPrefetch=(TRUE | FALSE)]
[raidLevel=(1 | 6)]
----
[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[raidLevel=(1 | 6)]
----


== 씬 프로비저닝된 볼륨 생성을 위한 구문입니다

[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[dataAssurance=(none|enabled)]
[(existingRepositoryLabel=pass:quotes[_existingRepositoryName_] |
[newRepositoryCapacity=pass:quotes[_newRepositoryCapacityValue_] (KB | MB | GB | TB | Bytes)]
[repositoryMaxCapacity=pass:quotes[_repositoryMaxCapacityValue_](KB|MB|GB|TB|Bytes)]
[warningThresholdPercent=pass:quotes[_warningThresholdPercentValue_]
[repositoryExpansionPolicy=(automatic|manual)]
[cacheReadPrefetch=(TRUE | FALSE)]
----
[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[(existingRepositoryLabel=pass:quotes[_existingRepositoryName_] |
[newRepositoryCapacity=pass:quotes[_newRepositoryCapacityValue_] (KB | MB | GB | TB | Bytes)]
[repositoryMaxCapacity=pass:quotes[_repositoryMaxCapacityValue_](KB|MB|GB|TB|Bytes)]
[warningThresholdPercent=pass:quotes[_warningThresholdPercentValue_]]
[repositoryExpansionPolicy=(automatic|manual)]
[cacheReadPrefetch=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
디즈크풀
 a| 
새 볼륨을 생성할 디스크 풀의 이름입니다. 디스크 풀 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
새 볼륨에 지정할 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
용량
 a| 
생성 중인 볼륨의 크기입니다.

표준 RAID 볼륨의 경우 볼륨에 할당되는 용량입니다.

씬 볼륨의 경우 씬 볼륨이 노출할 가상 용량 값입니다.

크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다. 다음은 구문의 예입니다.

* 용량 = 500MB
* "용량 = 2GB"




 a| 
'얇은 프로비저닝'
 a| 
이 매개 변수는 새 볼륨에 대한 씬 프로비저닝을 설정합니다. 씬 프로비저닝을 사용하려면 이 매개 변수를 "true"로 설정합니다. 씬 프로비저닝을 원하지 않는 경우 이 매개 변수를 "false"로 설정합니다.



 a| 
오너
 a| 
볼륨을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 소유자를 지정하지 않으면 컨트롤러 펌웨어가 소유자를 결정합니다.



 a| 
박수
 a| 
이 매개 변수를 사용하여 볼륨을 호스트에 매핑할 수 있습니다. 나중에 매핑하려면 이 매개변수를 '없음'으로 설정합니다. 지금 매핑하려면 이 매개 변수를 'default'로 설정합니다. 볼륨은 스토리지 풀에 대한 액세스 권한이 있는 모든 호스트에 매핑됩니다.

기본값은 '없음'입니다.



 a| 
기존 리포지터리 라벨
 a| 
이 매개변수는 씬 볼륨의 기존 리포지토리를 식별합니다. 저장소 볼륨에는 씬 볼륨의 물리적 용량이 있습니다. 이 매개 변수는 씬 프로비저닝에만 적용됩니다. 'existingRepositoryLabel' 매개 변수를 사용하는 경우 'newRepositoryCapacity' 매개 변수를 사용해서는 안 됩니다.



 a| 
'newRepositoryCapacity'
 a| 
이 매개변수는 씬 볼륨에 대한 새 리포지토리를 생성합니다. 저장소 볼륨에는 씬 볼륨의 물리적 용량이 있습니다. 이 매개변수는 'thinProvisioned' 매개 변수의 값을 'true'로 설정한 경우에만 사용합니다.

크기는 'MB', 'GB' 또는 'TB' 단위로 정의됩니다. 다음은 구문의 예입니다.

* 용량 = 500MB
* "용량 = 2GB"


기본값은 가상 용량의 50%입니다.



 a| 
재량 최대 용량
 a| 
이 매개 변수는 씬 볼륨의 리포지토리에 대한 최대 용량을 정의합니다. 이 매개변수는 'thinProvisioned' 매개 변수의 값을 'true'로 설정한 경우에만 사용합니다.

크기는 'MB', 'GB' 또는 'TB' 단위로 정의됩니다. 다음은 구문의 예입니다.

* 용량 = 500MB
* "용량 = 2GB"




 a| 
"warningThresholdPercent"를 참조하십시오
 a| 
씬 볼륨이 거의 꽉 찼다는 경고 메시지가 표시되는 씬 볼륨 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다.

유효한 값은 1에서 100 사이의 값입니다.

이 매개 변수를 100으로 설정하면 경고 경고가 비활성화됩니다.



 a| 
재확대정책
 a| 
이 매개변수는 확장 정책을 자동 또는 수동 으로 설정합니다. 정책을 '자동'에서 '수동'으로 변경하면 최대 용량 값(할당량)이 저장소 볼륨의 물리적 용량으로 변경됩니다.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다.



 a| 
레이드레벨
 a| 
디스크 풀에서 생성되는 볼륨의 RAID 레벨을 설정합니다. RAID1을 지정하려면 1로 설정합니다. RAID6를 지정하려면 6으로 설정합니다. RAID 레벨이 설정되지 않은 경우 기본적으로 디스크 풀에 RAID6가 사용됩니다.

|===


== 참고

각 볼륨 이름은 고유해야 합니다. 사용자 레이블에는 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 사용자 레이블은 최대 30자까지 가능합니다.

씬 볼륨의 경우 'capacity' 매개변수는 볼륨의 가상 용량을 지정하고 'RepositoryCapacity' 매개변수는 리포지토리 볼륨으로 생성된 볼륨의 용량을 지정합니다. 새 볼륨을 생성하는 대신 기존의 미사용 저장소 볼륨을 지정하려면 "existingRepositoryLabel" 매개 변수를 사용합니다.

씬 볼륨을 생성할 때 최상의 결과를 얻으려면 저장소 볼륨이 이미 존재하거나 이미 존재하는 디스크 풀에 생성되어야 합니다. 씬 볼륨을 생성할 때 선택적 매개 변수 중 일부를 지정하지 않으면 스토리지 관리 소프트웨어가 저장소 볼륨 생성을 시도합니다. 가장 적합한 대상 볼륨은 이미 존재하고 크기 요구 사항 내에 있는 저장소 볼륨입니다. 다음으로 가장 적합한 대상 볼륨은 디스크 풀 사용 가능 범위에서 생성되는 새 저장소 볼륨입니다.

씬 볼륨의 저장소 볼륨은 볼륨 그룹에서 생성할 수 없습니다.



== 데이터 무결성 관리

DA(Data Assurance) 기능은 전체 스토리지 시스템에서 데이터 무결성을 향상시킵니다. DA를 사용하면 호스트와 드라이브 간에 데이터가 이동할 때 발생할 수 있는 오류를 스토리지 시스템에서 확인할 수 있습니다. 이 기능을 활성화하면 스토리지 배열은 볼륨의 각 데이터 블록에 오류 검사 코드(순환 중복 검사 또는 CRC라고도 함)를 추가합니다. 데이터 블록이 이동된 후 스토리지 배열은 이러한 CRC 코드를 사용하여 전송 중에 오류가 발생했는지 확인합니다. 잠재적으로 손상된 데이터는 디스크에 기록되거나 호스트에 반환되지 않습니다.

DA 기능을 사용하려면 DA를 지원하는 드라이브만 포함된 풀 또는 볼륨 그룹으로 시작하십시오. 그런 다음 DA 가능 볼륨을 생성합니다. 마지막으로 DA를 지원하는 I/O 인터페이스를 사용하여 이러한 DA 지원 볼륨을 호스트에 매핑합니다. DA를 지원하는 I/O 인터페이스로는 InfiniBand를 통한 파이버 채널, SAS 및 iSER(RDMA/IB용 iSCSI 확장) 등이 있습니다. DA는 이더넷을 통한 iSCSI 또는 InfiniBand를 통한 SRP에서 지원되지 않습니다.

[NOTE]
====
모든 드라이브가 DA를 지원할 수 있는 경우, DATaAssurance 매개 변수를 "enabled"로 설정한 다음 특정 작업에 DA를 사용할 수 있습니다. 예를 들어, DA 지원 드라이브를 포함하는 볼륨 그룹을 생성한 다음 해당 볼륨 그룹 내에서 DA 지원 볼륨을 생성할 수 있습니다. DA 지원 볼륨을 사용하는 다른 작업에는 DA 기능을 지원하는 옵션이 있습니다.

====
"aAssurance" 매개 변수를 "Enabled"로 설정하면 볼륨 후보에 대한 데이터 보증 가능 드라이브만 고려되며, 그렇지 않으면 데이터 보증 가능 드라이브와 비 데이터 보증 가능 드라이브가 모두 고려됩니다. 데이터 보증 드라이브만 사용할 수 있는 경우 활성화된 데이터 보증 드라이브를 사용하여 새 볼륨이 생성됩니다.



== 최소 펌웨어 레벨입니다

7.83

8.70은 '_raidLevel_' 매개변수를 추가합니다.
