---
permalink: commands-a-z/create-hostport.html 
sidebar: sidebar 
keywords: create, host, port 
summary: 'create hostPort 명령은 호스트 버스 어댑터(HBA) 또는 호스트 채널 어댑터(HCA)에 새 호스트 포트 ID를 생성합니다.' 
---
= 호스트 포트 생성 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"create hostPort" 명령은 호스트 버스 어댑터(HBA) 또는 호스트 채널 어댑터(HCA)에 새 호스트 포트 ID를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

호스트 포트 식별은 컨트롤러에 대한 물리적 HBA 또는 HCA 호스트 포트를 나타내는 소프트웨어 값입니다. 올바른 호스트 포트 ID가 없으면 컨트롤러는 호스트 포트에서 지침 또는 데이터를 수신할 수 없습니다.



== 구문

[source, cli, subs="+macros"]
----
create hostPort identifier=pass:quotes[_("wwID"_ | "_gid"_)
userLabel="_portLabel"_]
[host=pass:quotes[_"hostName"_]]
[interfaceType=(FC | SAS | IB)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'식별자'
 a| 
HBA 또는 HCA 호스트 포트의 8바이트 WWID(World Wide Identifier) 또는 16바이트 GID(Group Identifier)입니다. WWID 또는 GID는 큰따옴표(" ")로 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
새 HBA 또는 HCA 호스트 포트에 지정할 이름입니다. 호스트 포트 레이블은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트
 a| 
HBA 또는 HCA 호스트 포트를 정의하는 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'InterfaceType'
 a| 
호스트 포트에 대한 인터페이스 유형의 식별자입니다.

호스트 포트 인터페이스 유형에 대한 선택 사항은 다음과 같습니다.

* FC -- Fibre Channel
* Sas -- 직렬 연결 SCSI
* IB-InfiniBand


FC 또는 SAS를 선택하려면 8바이트 WWID가 필요합니다. IB를 선택하려면 16바이트 GID(그룹 식별자)가 필요합니다.

인터페이스 유형을 지정하지 않으면 FC가 호스트 포트의 기본 인터페이스로 사용됩니다.

|===


== 참고

HBA 호스트 포트 또는 HCA 호스트 포트는 호스트 버스 어댑터 또는 호스트 컴퓨터에 상주하는 호스트 채널 어댑터의 물리적 연결입니다. HBA 호스트 포트 또는 HCA 호스트 포트는 스토리지 시스템의 볼륨에 대한 호스트 액세스를 제공합니다. HBA 또는 HCA에 물리적 연결이 하나만 있는 경우(호스트 포트 1개) 호스트 포트 및 호스트 버스 어댑터 또는 호스트 채널 어댑터라는 용어는 동의어입니다.

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.



== 최소 펌웨어 레벨입니다

5.20

7.10 HostType 매개 변수를 사용하지 않습니다. 호스트 유형 파라미터가 호스트 생성 명령에 추가되었습니다.

7.32는 'InterfaceType' 매개 변수를 추가합니다.
