---
permalink: commands-a-z/delete-snapimage.html 
sidebar: sidebar 
keywords: delete, snapimage, command, snapshot, images, group, support, array, roles 
summary: SnapImage 삭제 명령은 스냅샷 그룹에서 하나 이상의 스냅샷 이미지를 삭제합니다. 
---
= 스냅샷 이미지를 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"SnapImage 삭제" 명령은 스냅샷 그룹에서 하나 이상의 스냅샷 이미지를 삭제합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
pass:quotes[delete snapImage (snapGroup="snapGroupName" |
snapGroups=("_snapGroupName1"
... "snapGroupNamen_"))]
[deleteCount=numberOfSnapImages]
[retainCount=numberOfSnapImages]
[ignoreSnapVolume=(TRUE | FALSE)]
[snapImageID=OLDEST]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
스냅그룹
 a| 
삭제할 스냅샷 이미지가 있는 스냅샷 그룹의 이름입니다. 스냅샷 그룹의 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'냅그룹'
 a| 
삭제할 스냅샷 이미지가 있는 여러 스냅샷 그룹의 이름입니다. 다음 규칙을 사용하여 스냅샷 그룹의 이름을 입력합니다.

* 모든 이름은 괄호로 묶습니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
'deleteCount'입니다
 a| 
스냅샷 그룹에서 삭제할 스냅샷 이미지 수입니다. 정수 값을 사용합니다.

이 매개변수는 가장 오래된 스냅샷 이미지를 먼저 삭제하고 입력한 숫자에 도달할 때까지 가장 오래된 스냅샷 이미지를 계속 삭제합니다.

입력한 숫자가 스냅샷 그룹에 있는 모든 스냅샷 이미지의 실제 수보다 크면 모든 스냅샷 이미지가 삭제됩니다. 스냅샷 그룹이 비어 있습니다.



 a| 
'컨테이너 카운트'
 a| 
스냅샷 그룹에 유지할 스냅샷 이미지 수입니다. 정수 값을 사용합니다.

이 매개 변수는 스냅샷 그룹에 최신 스냅샷 이미지를 유지하고 오래된 스냅샷 이미지를 삭제합니다.

스냅샷 그룹의 기존 스냅샷 이미지 수가 입력한 수보다 적은 경우 스냅샷 이미지는 삭제되지 않습니다.



 a| 
'이그노레스냅볼륨'
 a| 
스냅샷 이미지와 연결된 스냅샷 볼륨이 있는 스냅샷 이미지를 삭제하지 않도록 하려면 이 매개 변수를 사용합니다. 다음 값 중 하나를 사용할 수 있습니다.

* "참" - 스냅샷 이미지에 연결된 스냅샷 볼륨이 있더라도 이 값을 사용하여 스냅샷 이미지를 삭제합니다.
* "false" - 스냅샷 이미지에 연결된 스냅샷 볼륨이 있을 때 이 값을 사용하여 스냅샷 이미지를 유지합니다.


기본값은 "true"입니다.



 a| 
나ImageID
 a| 
나프ImageID 파라미터는 가장 오래된 옵션만을 받아들인다. 이 매개변수는 생성된 가장 빠른 스냅샷 이미지를 삭제합니다.

|===


== 참고

스냅샷 그룹 저장소 볼륨에서 가장 오래된 스냅샷 이미지를 삭제할 수 있습니다. 삭제한 스냅샷 이미지의 정의가 시스템에서 제거됩니다. 스냅샷 그룹 저장소 볼륨에서 삭제한 스냅샷 이미지가 차지하는 공간이 해제되어 스냅샷 그룹 내에서 다시 사용할 수 있게 됩니다.

'스냅샷 그룹' 매개 변수 또는 '스냅샷 그룹' 매개 변수와 함께 다른 매개 변수를 사용하지 않으면 기본적으로 가장 오래된 스냅샷 이미지가 삭제됩니다.

스냅샷 이미지가 삭제될 때 스냅샷 이미지 전환을 위해 존재하는 모든 스냅샷 볼륨은 중지됨 상태로 전환됩니다.

컨트롤러가 잠금 모드일 때는 이 명령이 실행되지 않습니다.



== 최소 펌웨어 레벨입니다

7.83
