---
permalink: commands-a-z/delete-volume.html 
sidebar: sidebar 
keywords: delete, volume, command, one, standard, volume, supported, array, role 
summary: delete volume 명령은 하나 이상의 표준 볼륨을 삭제합니다. 
---
= 볼륨 삭제 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Delete volume(볼륨 삭제) 명령은 하나 이상의 표준 볼륨을 삭제합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
* 스토리지 배열 구성 손상 가능성 * -- 이 명령을 실행하면 볼륨의 모든 데이터가 즉시 손실됩니다.

====
[NOTE]
====
볼륨이 지정된 크기(현재 128TB)를 초과할 경우 백그라운드에서 삭제가 수행되고 있으며 확보된 공간을 즉시 사용할 수 없습니다.

====


== 구문

[source, cli]
----
delete (allVolumes) |
volume [volumeName] |
volumes [volumeName1 ... volumeNameN]
[removeVolumeGroup=(TRUE | FALSE)]
[force=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'올볼륨'
 a| 
이 매개 변수는 스토리지 배열의 모든 볼륨을 삭제합니다.



 a| 
'볼륨'
 a| 
삭제할 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자가 있거나 숫자만 포함된 경우 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
삭제할 여러 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자가 있거나 숫자만 포함된 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
'removeVolumeGroup'을 선택합니다
 a| 
볼륨 그룹의 마지막 볼륨을 삭제해도 볼륨 그룹은 삭제되지 않습니다. 독립형 볼륨 그룹을 가질 수 있습니다(모든 볼륨 제외). 독립 실행형 볼륨 그룹을 제거하려면 이 매개 변수를 "true"로 설정합니다. 독립 실행형 볼륨 그룹을 그대로 유지하려면 이 매개 변수를 'false'로 설정하십시오.



 a| 
"힘"
 a| 
컨트롤러가 다른 작업을 수행 중인 경우에도 이 매개 변수를 사용하여 볼륨을 즉시 삭제합니다. 볼륨을 즉시 강제로 삭제하려면 이 매개변수를 "TRUE"로 설정합니다. 컨트롤러가 다른 작업을 완료할 때까지 대기하려면 이 매개변수를 사용하거나 이 매개변수를 "false"로 설정하지 마십시오.

|===


== 참고

'allVolumes' 매개 변수를 사용하면 모든 볼륨이 제거되거나 오류가 발생할 때까지 볼륨이 삭제됩니다. 오류가 발생하면 이 명령은 나머지 볼륨을 삭제하지 않습니다. 다른 볼륨 그룹에서 볼륨을 삭제할 수 있습니다. 'removeVolumeGroup' 매개변수를 'true'로 설정하면 비어 있는 모든 볼륨 그룹이 삭제됩니다.

전체 볼륨 그룹을 삭제하려면 'Delete volumeGroup' 명령을 사용할 수도 있습니다.



== 최소 펌웨어 레벨입니다

6.10

7.10은 'removeVolumeGroup' 파라미터를 추가합니다.
