---
permalink: commands-a-z/delete-cgsnapimage-consistencygroup.html 
sidebar: sidebar 
keywords: delete, consistency, group, snapshot, image 
summary: delete cgSnapImage ConsistencyGroup 명령은 정합성 보장 그룹의 스냅샷 이미지를 삭제합니다. 
---
= 정합성 보장 그룹 스냅샷 이미지를 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Delete cgSnapImage ConsistencyGroup' 명령은 정합성 보장 그룹의 스냅샷 이미지를 삭제합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
delete cgSnapImage consistencyGroup=pass:quotes[_"consistencyGroupName"_]
pass:quotes[[deleteCount=_numberOfSnapImages_]
[retainCount=pass:quotes[_numberOfSnapImages_]
[ignoreSnapVolume=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
일관성 그룹
 a| 
스냅샷 이미지를 삭제할 일관성 그룹의 이름입니다. 정합성 보장 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'deleteCount'입니다
 a| 
일관성 그룹에서 삭제할 스냅샷 이미지의 수입니다. 정수 값을 사용합니다.

이 매개변수는 가장 오래된 스냅샷 이미지를 먼저 삭제하고 입력한 숫자에 도달할 때까지 가장 오래된 스냅샷 이미지를 계속 삭제합니다.



 a| 
'컨테이너 카운트'
 a| 
정합성 보장 그룹에 유지할 스냅샷 이미지 수입니다. 정수 값을 사용합니다.

이 매개 변수는 가장 최근의 스냅샷 이미지를 정합성 보장 그룹에 유지합니다.



 a| 
'이그노레스냅볼륨'
 a| 
연결된 정합성 보장 그룹 스냅샷 볼륨의 유지 또는 삭제 여부를 결정합니다. 이 매개 변수는 정합성 보장 그룹 스냅샷 이미지가 정합성 보장 그룹 스냅샷 볼륨과 연결된 경우에만 적용됩니다. 스냅샷 볼륨을 유지하려면 이 매개 변수를 "true"로 설정합니다. 스냅샷 볼륨을 삭제하려면 이 매개변수를 "false"로 설정합니다. 기본값은 'false'입니다.

|===


== 참고

정합성 보장 그룹의 모든 관련 구성원 볼륨에 대해 스냅샷 이미지를 삭제할 수 없는 경우 작업이 실패하고 스냅샷 이미지가 삭제되지 않습니다.

정합성 보장 그룹 스냅샷 볼륨과 연결된 정합성 보장 그룹 스냅샷 이미지를 삭제하면 정합성 보장 그룹 스냅샷 볼륨의 해당 스냅샷 볼륨 구성원이 중지됨 상태로 전환됩니다. 중지됨 상태의 스냅샷 볼륨 구성원은 삭제된 스냅샷 이미지의 스냅샷 그룹과 더 이상 관계가 없습니다. 그러나 중지됨 상태의 스냅샷 볼륨 구성원은 정합성 보장 그룹 스냅샷 볼륨과의 관계를 유지합니다.



== 최소 펌웨어 레벨입니다

7.83
