---
permalink: commands-a-z/delete-volume-from-disk-pool.html 
sidebar: sidebar 
keywords: delete, volume, command, normal, thin, disk pool, roles, support 
summary: 볼륨 삭제 명령은 디스크 풀에서 일반 볼륨 또는 씬 볼륨을 삭제합니다. 
---
= 디스크 풀에서 볼륨을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Delete volume(볼륨 삭제) 명령은 디스크 풀에서 일반 볼륨 또는 씬 볼륨을 삭제합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령을 사용하여 볼륨과 관련된 모든 일정을 삭제할 수도 있습니다. 스케줄을 삭제하면 볼륨이 삭제되지 않습니다.

[]
====
* 스토리지 배열 구성 손상 가능성 * -- 이 명령을 실행하면 볼륨의 모든 데이터가 즉시 손실됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
delete (allVolumes |
volume [volumeName] |
pass:quotes[volumes ["_volumeName1_" ... "_volumeNameN_"]]
[force=(TRUE | FALSE)]
[schedule]
[retainRepositoryMembers=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'올볼륨'
 a| 
이 매개 변수는 디스크 풀의 모든 볼륨을 삭제합니다.



 a| 
'볼륨'
 a| 
삭제할 특정 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자가 포함되어 있거나 숫자만 포함된 경우 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
삭제할 여러 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
"힘"
 a| 
컨트롤러가 다른 작업을 수행 중인 경우에도 이 매개 변수를 사용하여 볼륨을 즉시 삭제합니다. 볼륨을 즉시 강제로 삭제하려면 이 매개변수를 "TRUE"로 설정합니다. 컨트롤러가 다른 작업을 완료할 때까지 대기하려면 이 매개변수를 사용하거나 이 매개변수를 "false"로 설정하지 마십시오.



 a| 
스케줄
 a| 
이 매개변수는 특정 디스크 풀 볼륨과 관련된 모든 스케줄을 삭제합니다. 스케줄만 삭제되고 디스크 풀 볼륨은 유지됩니다.



 a| 
RetainRepositoryMembers(리포지토리 구성원)
 a| 
씬 볼륨을 삭제하면 연결된 저장소 볼륨은 기본적으로 삭제됩니다. 그러나 RetainRepositoryMembers가 true로 설정되면 저장소 볼륨은 유지됩니다. 일반 볼륨의 경우 이 매개 변수는 영향을 주지 않습니다.

|===


== 참고

'allVolumes' 매개 변수를 사용하면 모든 볼륨이 제거되거나 오류가 발생할 때까지 볼륨이 삭제됩니다. 오류가 발생하면 이 명령은 나머지 볼륨을 삭제하지 않습니다. 다른 볼륨 그룹에서 볼륨을 삭제할 수 있습니다. 'removeVolumeGroup' 매개변수를 'true'로 설정하면 비어 있는 모든 볼륨 그룹이 삭제됩니다.



== 최소 펌웨어 레벨입니다

7.83
