---
permalink: commands-a-z/diagnose-controller.html 
sidebar: sidebar 
keywords: diagnose, controller, command, run, diagnostic, tests, arrays, roles, context 
summary: diagnose controller 명령은 컨트롤러에서 진단 테스트를 실행합니다. 
---
= 컨트롤러를 진단합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
dagivose controller 명령은 컨트롤러에 대한 진단 테스트를 실행합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

진단 테스트는 드라이브에 데이터를 쓰고 드라이브에서 데이터를 읽는 루프백 테스트로 구성됩니다.



== 구문

[listing, subs="+macros"]
----
diagnose controller [(a| b)]
loopbackDriveChannel=(allchannels | (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8))
testID=(1 | 2 | 3 | discreteLines)
pass:quotes[[patternFile="_filename_"]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
진단 테스트를 실행할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.



 a| 
루백드라이브채널
 a| 
진단 테스트를 실행할 드라이브 채널입니다. 모든 채널에서 진단 프로그램을 실행하거나 진단 프로그램을 실행할 특정 채널을 선택할 수 있습니다. 특정 채널을 선택하면 드라이브 채널의 유효한 값은 1, 2, 3, 4, 5, 6, 7, 8.



 a| 
'testID'입니다
 a| 
실행할 진단 테스트의 식별자입니다. 식별자 및 해당 테스트는 다음과 같습니다.

* 1--읽기 테스트
* 2-쓰기 테스트
* 3루백 테스트
* 디크레티라인 -- 이산 라인 진단 테스트




 a| 
'pattern File'
 a| 
테스트 데이터로 사용할 데이터 패턴이 포함된 파일 경로 및 파일 이름입니다. 데이터 패턴의 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\sup\patfile.txt"

|===


== 참고

데이터 루프 백 테스트를 실행할 때 데이터 패턴이 포함된 파일을 선택적으로 지정할 수 있습니다. 파일을 지정하지 않으면 컨트롤러 펌웨어가 기본 패턴을 제공합니다.

개별 줄은 컨트롤러 트레이의 두 컨트롤러 사이에 연결된 제어 라인과 상태 선입니다 이산 라인 진단 테스트를 통해 각 컨트롤러는 대체 컨트롤러의 제어 입력에서 제어 신호 전환을 관찰할 수 있는지 점검합니다. 개별 라인 진단 테스트는 각 전원 사이클 또는 각 컨트롤러 재설정 후에 자동으로 실행됩니다. 초기 이산 라인 진단 테스트에 실패한 구성 요소를 교체한 후 이산 라인 진단 테스트를 실행할 수 있습니다. 이산 라인 진단 테스트에서는 다음 메시지 중 하나를 반환합니다.

* 이산 라인 진단 테스트가 성공적으로 실행되면 다음 메시지가 나타납니다.
+
[listing]
----
The controller discrete lines successfully passed the diagnostic
test. No failures were detected.
----
* 이산 라인 진단 테스트에 실패하면 다음 메시지가 나타납니다.
+
[listing]
----
One or more controller discrete lines failed the diagnostic test.
----
* CLI에서 이산 라인 진단 테스트를 실행할 수 없는 경우 CLI는 오류 270을 반환합니다. 즉, 이산 라인 진단 테스트를 시작하거나 완료할 수 없습니다.




== 최소 펌웨어 레벨입니다

6.10은 읽기 테스트, 쓰기 테스트 및 데이터 루프 백 테스트를 추가합니다.

6.14는 이산 라인 진단 테스트를 추가합니다.

7.30은 업데이트된 드라이브 채널 식별자를 추가합니다.
