---
permalink: commands-a-z/diagnose-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: diagnose, command, tests, possible, communication, problems, local, storage, array, remote, asynchronous, mirror, group 
summary: Diagnose asyncMirrorGroup 명령은 로컬 스토리지 시스템과 비동기 미러 그룹에 연결된 원격 스토리지 시스템 간의 통신 문제를 테스트합니다. 
---
= 비동기식 미러 그룹 접속을 테스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
"iagfose asyncMirrorGroup" 명령은 로컬 스토리지 시스템과 비동기식 미러 그룹과 연결된 원격 스토리지 시스템 간에 발생할 수 있는 통신 문제를 테스트합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
이 명령은 E2800, E5700, EF600 및 EF300 플랫폼에서는 지원되지 않습니다.

====


== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[diagnose asyncMirrorGroup [_asyncMirrorGroupName_]]
testID=(all | connectivity | latency | bandwidth | portConnections)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
아인치마그룹
 a| 
테스트할 기존 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 비동기 미러 그룹 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'testID'입니다
 a| 
실행할 진단 테스트의 식별자입니다. 식별자 및 해당 테스트는 다음과 같습니다.

* * ALL * -- 이 명령과 관련된 모든 테스트를 수행합니다.
* * 연결 * -- 두 컨트롤러가 통신 경로를 가지고 있는지 확인합니다. 연결 테스트에서는 스토리지 시스템 간에 컨트롤러 간 메시지를 보낸 다음 원격 스토리지 시스템에 해당하는 비동기식 미러 그룹이 있는지 확인합니다. 또한 원격 시스템에 있는 비동기식 미러 그룹의 볼륨 멤버가 로컬 시스템에 있는 비동기식 미러 그룹의 볼륨 멤버와 일치하는지 확인합니다.
* * Latency * -- 비동기식 미러 그룹에 연결된 원격 스토리지 시스템의 각 볼륨에 SCSI 테스트 유닛 명령을 보내 최소, 평균 및 최대 지연 시간을 테스트합니다.
* * 대역폭 * -- 원격 스토리지 어레이로 두 개의 컨트롤러 간 메시지를 전송하여 테스트를 수행하는 컨트롤러에서 포트의 협상된 링크 속도와 최소, 평균 및 최대 대역폭을 테스트합니다.
* * 포트 연결 * -- 로컬 스토리지 배열의 미러링에 사용되는 포트와 원격 스토리지 배열의 미러링된 데이터를 수신하는 포트를 표시합니다.


|===


== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
