---
permalink: commands-a-z/diagnose-controller-iscsihostport.html 
sidebar: sidebar 
keywords: diagnose, controller, hostport, command, diagnostic, tests, copper, cable, host, interface, cards, support, roles 
summary: diagnose controller iscsiHostPort 명령은 iSCSI 호스트 인터페이스 카드와 컨트롤러 사이의 구리 케이블에 대한 진단 테스트를 실행합니다. 
---
= 컨트롤러 iSCSI 호스트 케이블을 진단합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
dagivose controller iscsiHostPort 명령은 iSCSI 호스트 인터페이스 카드와 컨트롤러 사이의 구리 케이블에 대한 진단 테스트를 실행합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

선택한 포트 또는 모든 포트에서 진단 유틸리티를 실행할 수 있습니다. 포트가 케이블 진단 프로그램을 지원할 수 있어야 합니다. 포트가 케이블 진단을 지원하지 않으면 오류가 반환됩니다.



== 구문

[listing]
----
diagnose controller [(a|b)]
iscsiHostPort ([all] | [portLabel])
testID=cableDiagnostics
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
케이블 진단 테스트를 실행할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.



 a| 
iscsiHostPort를 선택합니다
 a| 
진단 테스트를 실행할 iSCSI 호스트 포트입니다. 모든 iSCSI 호스트 포트에 대해 진단 유틸리티를 실행하거나 특정 iSCSI 호스트 포트에 대해 진단 유틸리티를 실행할 수 있습니다.

자세한 내용은 다음을 참조하십시오.

<<iSCSI 호스트 포트 레이블 식별,"iSCSI 호스트 포트 레이블 식별">>



 a| 
'testID'입니다
 a| 
실행할 진단 테스트의 식별자입니다. 이 진단검사에서는 배추진단만 선택할 수 있다.

|===


== iSCSI 호스트 포트 레이블 식별

호스트 포트의 레이블을 지정해야 합니다. 다음 단계에 따라 호스트 포트 레이블을 지정합니다.

. iSCSI 호스트 포트의 포트 레이블을 모르는 경우 'show controller' 명령을 실행합니다.
. 결과의 호스트 인터페이스 섹션에서 선택할 호스트 포트를 찾습니다.
+
[NOTE]
====
Port 레이블은 Port 필드에 대해 반환되는 전체 값입니다.

====
. 포트 레이블의 전체 값을 따옴표로 묶고 대괄호는 ["portLabel"] 로 묶습니다. 예를 들어 포트 레이블이 "Ch 2"인 경우 다음과 같이 iSCSI 호스트 포트를 지정합니다.
+
[listing]
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
Windows 명령줄을 사용하고 있고 레이블에 파이프(|)가 포함되어 있는 경우 문자는 이스케이프되어야 합니다({캐럿} 사용). 그렇지 않으면 명령으로 해석됩니다. 예를 들어 포트 레이블이 "e0b|0b"인 경우 다음과 같이 iSCSI 호스트 포트를 지정합니다.

====
+
[listing]
----
iscsiHostPort[\"e0b^|0b\"]
----


[NOTE]
====
이전 버전과의 호환성을 위해, E2700, E5600 또는 EF560 컨트롤러(및 이전 세대의 E-Series 또는 EF-Series 컨트롤러)에는 견적 및 중괄호["]가 아닌 중괄호로 묶인 iscsiPortNumber를 사용할 수 있습니다. 이러한 컨트롤러의 경우 iscsiPortNumber에 유효한 값은 다음과 같습니다.

* 호스트 포트가 통합된 컨트롤러의 경우 번호 매기는 3, 4, 5 또는 6입니다.
* 호스트 인터페이스 카드에 호스트 포트가 있는 컨트롤러의 경우 1번, 2번, 3번 또는 4번 번호가 매겨집니다.


이전 구문의 예는 다음과 같습니다.

[listing]
----
iscsiHostPort[3]
----
====


== 참고

케이블 진단 테스트를 실행하면 펌웨어가 다음 정보를 반환합니다.

* * 호스트 포트 *: 진단 테스트가 실행된 포트입니다.
* HIC *: 이 포트와 연결된 호스트 인터페이스 카드
* 테스트가 실행된 날짜 및 시간입니다.
* * 상태 *:
+
** * 정상 *: 모든 케이블 쌍이 양호하며 결함이 없습니다.
** * 열기 *: 4개 케이블 쌍 중 하나 이상이 열려 있습니다.
** * 단락 *: 4개 케이블 쌍 중 하나 이상이 단락되었습니다.
** * 불완전 *: 4개 쌍 중 하나 이상이 불완전하거나 잘못된 테스트 결과를 반환했습니다.


* * 길이 *: 케이블 길이는 미터 단위로 표시되며 케이블에 대한 다음 정보가 반환됩니다.
+
** 케이블 상태가 정상이면 케이블 쌍의 대략적인 길이가 반환됩니다. 케이블 쌍의 길이는 범위(L1-L2)로 표시되며, 이 범위는 케이블 쌍의 가장 짧은 길이와 가장 긴 길이입니다.
** 케이블 상태가 단선 또는 단선 인 경우, 케이블 쌍선의 고장까지의 대략적인 거리. 오류가 하나 있는 경우 해당 케이블 쌍의 길이가 보고됩니다. 오류가 두 개 이상 있는 경우 반환된 정보는 가장 짧거나 가장 긴 오류 길이입니다. 길이가 L1 < L2인 범위(L1 - L2)로 나열됩니다.
** 케이블 상태가 완전하지 않은 경우, 반환된 정보는 펌웨어가 성공적으로 테스트할 수 있는 가장 짧은 케이블 쌍과 가장 긴 케이블 쌍의 길이입니다. 유효한 케이블 쌍의 길이는 L1 < L2인 범위(L1 - L2)로 나열됩니다.


* 케이블 진단 레지스터의 값을 등록합니다. 값은 16진수 형식입니다.
+
** 2바이트는 결합된 케이블 상태를 나타냅니다(포트당 4비트).
** 4개의 2바이트 숫자는 각 채널의 길이를 나타냅니다.






== 최소 펌웨어 레벨입니다

7.77

8.10은 iSCSI 호스트 포트에 대한 번호 지정 시스템을 다시 확인합니다.
