---
permalink: commands-a-z/download-tray-firmware-file.html 
sidebar: sidebar 
keywords: download, tray, firmware, file, command, environmental, service, module, array, role, context 
summary: 'download tray firmware file 명령은 환경 서비스 모듈(ESM) 펌웨어를 다운로드합니다.' 
---
= 환경 카드 펌웨어를 다운로드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
"download tray firmware file" 명령은 환경 서비스 모듈(ESM) 펌웨어를 다운로드합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

[IMPORTANT]
====
시스템 관리자(예: E2800)가 관리하는 이중 시스템에는 IOM 펌웨어가 컨트롤러에 로드된 SANtricity OS 번들에 포함된 버전과 자동으로 동기화되는 IOM 자동 동기화 서비스가 컨트롤러에서 실행되고 있습니다. IOM 펌웨어를 컨트롤러에 로드된 버전과 일치하도록 되돌리지 않으려면 이 서비스를 비활성화해야 합니다. IOM 자동 동기화 서비스는 System Manager 또는 REST API를 사용하여 일시 중지할 수 있습니다. 이 서비스를 일시 중단할 때 자동 동기화를 사용하도록 설정하면 IOM 펌웨어가 최신 상태로 유지됩니다.

====


== 구문

[listing, subs="+macros"]
----
download (allTrays | tray [trayID])
pass:quotes[firmware file="_filename_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
올트레이
 a| 
이 매개변수는 스토리지 배열의 모든 호환 가능한 트레이에 새 펌웨어를 다운로드합니다. 선택한 펌웨어 패키지에 따라 호환되는 용지함이 결정됩니다. 호환되지 않는 급지대는 건너뜁니다. 호환되지 않는 급지대에 대한 오류 메시지가 표시되지 않습니다.



 a| 
트레이
 a| 
새 펌웨어를 로드할 ESM 카드가 들어 있는 드라이브 트레이. 용지함 ID 값은 0 ~ 99입니다. 트레이 ID 값은 대괄호([])로 묶어야 합니다.

[NOTE]
====
용지함 ID에 선행 0이 없습니다. 예를 들어, 표시된 용지함 ID가 "02"인 경우 이 명령을 사용하려면 [02]가 아니라 [2]로 지정해야 합니다.

====


 a| 
'파일'
 a| 
펌웨어 이미지가 포함된 파일의 파일 경로 및 파일 이름입니다. 펌웨어 이미지의 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

``file="C:\Program Files\CLI\DNLD\esmfrm.esm"`

유효한 파일 이름의 확장명은 .esm입니다.

|===


== 참고

트레이 매개변수는 새 펌웨어를 특정 드라이브 트레이에 다운로드합니다 모든 드라이브 트레이가 아닌 두 개 이상의 드라이브 트레이에 새 펌웨어를 다운로드해야 하는 경우 각 드라이브 트레이에 대해 이 명령을 입력해야 합니다



== 최소 펌웨어 레벨입니다

5.20
