---
permalink: commands-a-z/download-storagearray-nvsram.html 
sidebar: sidebar 
keywords: download, storagearray, down, values, controller, support, role, command, array 
summary: download storageArray NVSRAM 명령은 스토리지 배열 컨트롤러의 NVSRAM 값을 다운로드합니다. 
---
= 스토리지 배열 NVSRAM을 다운로드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
download storageArray NVSRAM' 명령어는 스토리지 배열 컨트롤러의 NVSRAM 값을 다운로드합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[download storageArray NVSRAM file="_filename_"]
[healthCheckMelOverride=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
NVSRAM 값이 포함된 파일 경로 및 파일 이름입니다. NVSRAM 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\DNLD\afrm.DLP"

유효한 파일 이름은 확장자가 .DLP입니다.



 a| 
'healthCheckMelOverride'
 a| 
MEL(주 이벤트 로그)의 상태 점검 결과를 재정의하는 설정입니다. Mel 유효성 검사는 여전히 발생하며 무시되지 않습니다. MEL check이 실패하는 경우, 명령어를 실행할 때 이 parameter를 이용하여 장애를 우회할 수 있다.

다운로드하기 전에 컨트롤러는 이벤트 로그를 확인하여 새 NVSRAM을 성공적으로 다운로드하지 못할 수 있는 이벤트가 발생했는지 확인합니다. 이러한 이벤트가 발생한 경우 컨트롤러는 일반적으로 새 NVSRAM을 다운로드하지 않습니다.

이 매개변수는 컨트롤러에서 새 NVSRAM을 다운로드하도록 합니다. 기본값은 'false'입니다. 컨트롤러에서 새 NVSRAM을 다운로드하도록 하려면 이 값을 "true"로 설정합니다.

|===


== 최소 펌웨어 레벨입니다

6.10

8.10은 healthCheckMelOverride 매개 변수를 추가합니다.
