---
permalink: commands-a-z/download-storagearray-firmware.html 
sidebar: sidebar 
keywords: download, storage, array, firmware, command, downloads, optionally, values, controllers, role, context, parameter 
summary: 'download storageArray firmware 명령어는 스토리지 배열 컨트롤러의 펌웨어 및 NVSRAM 값을 다운로드합니다(선택 사항).' 
---
= 스토리지 어레이 펌웨어/NVSRAM을 다운로드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
download storageArray firmware(storageArray 펌웨어 다운로드) 명령은 펌웨어를 다운로드하고 선택적으로 스토리지 배열 컨트롤러의 NVSRAM 값을 다운로드합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

NVSRAM 값만 다운로드하려면 download storageArray NVSRAM' 명령을 사용하십시오.



== 구문

[listing, subs="+macros"]
----
download storageArray firmware [, NVSRAM ]
pass:quotes[file="_filename_" [, "_NVSRAM-filename_"]]
[downgrade=(TRUE | FALSE)
activateNow=(TRUE | FALSE)
healthCheckMelOverride=(TRUE | FALSE)
healthCheckNeedsAttnOverride=(TRUE | FALSE)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
NVSRAM
 a| 
이 매개변수는 펌웨어 파일을 다운로드할 때 NVSRAM 값이 있는 파일을 다운로드합니다. 이 매개 변수에 대괄호를 포함하지 마십시오. "firmware(펌웨어)" 매개변수 뒤에 쉼표를 포함합니다.



 a| 
'파일'
 a| 
이 매개변수는 펌웨어가 포함된 파일 경로와 파일 이름을 지정합니다. 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\DNLD\safrm.DLP"

유효한 파일 이름은 확장자가 .DLP입니다.



 a| 
NVSRAM - 파일 이름
 a| 
이 매개변수는 NVSRAM 값이 포함된 파일 경로와 파일 이름을 지정합니다. NVSRAM 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

파일 = "C:\Program Files\CLI\DNLD\safrm.dnp" 유효한 파일 이름의 확장명은 .dmp입니다.

펌웨어 및 NVSRAM을 모두 다운로드할 때 파일 이름 앞에 쉼표를 포함합니다.



 a| 
'다운로드'를 클릭합니다
 a| 
[CAUTION]
====
*스토리지 배열 구성 손상 가능성*--이전 버전의 컨트롤러 펌웨어 또는 NVSRAM을 잘못 다운로드하면 컨트롤러가 손상되거나 데이터 액세스가 손실될 수 있습니다. 이 매개 변수를 사용하기 전에 기술 지원 부서에 문의하십시오.

====
이 설정을 사용하면 이전 버전의 펌웨어를 로드할 수 있습니다. 기본값은 'false'입니다. 이전 버전의 펌웨어를 다운로드하려면 "다운로드 등급" 매개 변수를 "참"으로 설정하십시오.

[NOTE]
====
NVSRAM만 다운로드하는 경우 이 매개 변수는 유효하지 않습니다.

====


 a| 
활동가현재
 a| 
이 설정은 펌웨어 이미지와 NVSRAM 이미지를 활성화합니다. 기본값은 "true"입니다. activeNow 매개변수를 false로 설정하면 나중에 펌웨어와 NVSRAM을 활성화하려면 activate storageArray firmware 명령어를 실행해야 합니다.

[NOTE]
====
NVSRAM만 다운로드한 경우에는 이 매개 변수가 유효하지 않습니다.

====


 a| 
'healthCheckMelOverride'
 a| 
이 설정은 MEL(주 이벤트 로그)의 상태 점검 결과를 재정의합니다. Mel 유효성 검사가 여전히 발생하고 무시되지 않습니다. MEL check이 실패하는 경우, 명령어를 실행할 때 이 parameter를 이용하여 장애를 우회할 수 있다.

다운로드하기 전에 컨트롤러는 이벤트 로그를 확인하여 새 컨트롤러 펌웨어의 다운로드를 방해할 수 있는 이벤트가 발생했는지 확인합니다. 이러한 이벤트가 발생한 경우 컨트롤러는 일반적으로 새 펌웨어를 다운로드하지 않습니다.

이 매개변수는 컨트롤러가 새 펌웨어를 다운로드하도록 합니다. 기본값은 'false'입니다. 컨트롤러에서 새 컨트롤러 펌웨어를 다운로드하도록 하려면 이 값을 "참"으로 설정합니다.



 a| 
'healthCheckNeedsAttnOverride'
 a| 
이 설정은 특정 주의 필요 조건의 상태 검사 결과를 무시합니다. 특정 조건 집합에 대한 주의 유효성 검사가 계속 수행되지만 무시되지는 않습니다. Needs Attention(주의 필요) 검사에 실패하면 명령을 실행할 때 이 매개 변수를 사용하여 실패를 건너뛸 수 있습니다.

다운로드하기 전에 컨트롤러는 특정 요구 사항 조건을 확인하여 새 컨트롤러 펌웨어의 다운로드를 방해할 수 있는 장애가 발생했는지 확인합니다. 이러한 이벤트가 발생한 경우 컨트롤러는 일반적으로 새 펌웨어를 다운로드하지 않습니다.

이 매개변수는 컨트롤러가 새 펌웨어를 다운로드하도록 합니다. 기본값은 'false'입니다. 컨트롤러에서 새 컨트롤러 펌웨어를 다운로드하도록 하려면 이 값을 "참"으로 설정합니다.

|===


== 최소 펌웨어 레벨입니다

5.00

8.10은 '* healthCheckMelOverride*' 매개변수를 추가합니다.

8.70은 `* healthCheckNeedsAttnOverride*' 매개 변수를 추가합니다.
