---
permalink: commands-a-z/download-storagearray-drivefirmware-file.html 
sidebar: sidebar 
keywords: download, storage, array, drive, firmware, command, images, roles, supported 
summary: download storageArray driveFirmware file 명령은 스토리지 배열의 모든 드라이브에 펌웨어 이미지를 다운로드합니다. 
---
= 스토리지 어레이 드라이브 펌웨어 다운로드 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
download storageArray driveFirmware file 명령을 실행하면 펌웨어 이미지가 스토리지 배열의 모든 드라이브에 다운로드됩니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
pass:quotes[download storageArray driveFirmware file="_filename_"]
pass:quotes[[file="_filename2_"... file="_filenameN_"]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
펌웨어 이미지가 포함된 파일의 파일 경로 및 파일 이름입니다. 펌웨어 이미지의 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\DNLD\sadrvfrm.DLP"

유효한 파일 이름은 확장자가 .DLP입니다.

|===


== 참고

이 명령을 실행하면 스토리지 배열의 드라이브에 둘 이상의 펌웨어 이미지 파일을 다운로드할 수 있습니다. 다운로드할 수 있는 펌웨어 이미지 파일 수는 스토리지 배열에 따라 다릅니다. 스토리지 어레이에서 허용할 수 있는 것보다 더 많은 펌웨어 이미지 파일을 다운로드하려고 하면 스토리지 관리 소프트웨어에서 오류를 반환합니다.

중복 볼륨 그룹의 여러 드라이브를 포함하여 여러 드라이브에 대한 다운로드를 동시에 예약할 수 있습니다. 각 펌웨어 이미지 파일에는 펌웨어 이미지가 실행되는 드라이브 유형에 대한 정보가 들어 있습니다. 지정된 펌웨어 이미지는 호환 드라이브에만 다운로드할 수 있습니다. 드라이브 펌웨어 다운로드 명령을 사용하여 펌웨어 이미지를 특정 드라이브에 다운로드합니다.

download storageArray driveFirmware 명령은 각 대상 드라이브에 대해 다운로드 시도를 하거나 'stop storageArray downloadDriveFirmware' 명령을 실행할 때까지 모든 I/O 작업을 차단합니다. "download storageArray driveFirmware" 명령이 펌웨어 이미지 다운로드를 완료하면 각 대상 드라이브에 대한 다운로드 상태가 표시됩니다. 다음 상태 중 하나가 반환됩니다.

* 성공했습니다
* 이유와 함께 실패
* 이유를 가지고 시도해본 적이 없습니다




== 최소 펌웨어 레벨입니다

5.20
