---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: 드라이브 펌웨어 다운로드 명령은 펌웨어 이미지를 드라이브에 다운로드합니다. 
---
= 드라이브 펌웨어 다운로드 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 펌웨어 다운로드 명령은 펌웨어 이미지를 드라이브에 다운로드합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

[CAUTION]
====
* 스토리지 배열 구성 손상 가능성 * -- 드라이브 펌웨어를 잘못 다운로드하면 드라이브가 손상되거나 데이터 액세스가 손실될 수 있습니다.

====
[NOTE]
====
콘텐츠 매개 변수는 더 이상 사용되지 않습니다. 대신 펌웨어 매개변수를 사용하십시오.

====
이 명령은 한 번에 하나의 드라이브 모델에만 펌웨어 이미지를 다운로드하기 위한 것입니다. 스크립트에 이 명령을 사용하는 경우 이 명령은 한 번만 사용해야 합니다. 이 명령을 두 번 이상 사용하면 작업이 실패할 수 있습니다. "download storageArray driveFirmware" 명령을 사용하여 스토리지 배열의 모든 드라이브에 펌웨어 이미지를 한 번에 다운로드할 수 있습니다.



== 구문

[source, cli, subs="+macros"]
----
download (drive [trayID,[drawerID,]slotID] | drives [trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn])
[online|offline] firmware file="filename"
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'늑대'나 '늑대'가 있습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
온라인 또는 오프라인
 a| 
온라인 드라이브 펌웨어 다운로드를 수행하려면 온라인 을 선택하고, 그렇지 않으면 오프라인 을 선택합니다. 기본값은 '오프라인'입니다.



 a| 
'파일'
 a| 
펌웨어 이미지가 포함된 파일의 파일 경로 및 파일 이름입니다. 펌웨어 이미지의 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\DNLD\drvfrm.DLP"

유효한 파일 이름은 확장자가 .DLP입니다.



 a| 
펌웨어
 a| 
컨트롤러 펌웨어를 다운로드함을 나타냅니다.

|===


== 참고

드라이브 펌웨어를 다운로드하기 전에 다음 지침을 따르십시오.

* "온라인" 매개 변수를 사용하지 않는 경우 펌웨어 이미지를 다운로드하기 전에 스토리지 배열에 대한 모든 I/O 작업을 중지하십시오. "온라인" 매개 변수가 없는 "드라이브 펌웨어 다운로드" 명령은 다운로드가 완료되거나 실패할 때까지 모든 I/O 작업을 차단하지만, 예방 조치로 드라이브에 영향을 줄 수 있는 모든 I/O 작업이 중지되었는지 확인합니다.
* 펌웨어 이미지 파일이 드라이브 트레이와 호환되는지 확인합니다 선택한 드라이브 트레이와 호환되지 않는 펌웨어 이미지 파일을 다운로드하면 드라이브 트레이를 사용할 수 없게 될 수 있습니다.
* 드라이브 펌웨어를 다운로드하는 동안 스토리지 배열의 구성을 변경하지 마십시오. 구성을 변경하려고 하면 펌웨어 다운로드가 실패하고 선택한 드라이브를 사용할 수 없게 될 수 있습니다.
* 이 명령을 사용하여 실행된 온라인 드라이브 펌웨어 업데이트 요청의 경우 컨트롤러는 새 펌웨어를 다운로드할 드라이브 목록에서 RAID 0 볼륨 그룹 드라이브를 제거합니다. 개별 드라이브 반환 상태는 "이유 없는 시도"로 설정됩니다.


펌웨어를 드라이브에 다운로드할 때 시스템에 저장된 펌웨어 이미지에 전체 경로와 파일 이름을 제공해야 합니다.

스토리지 배열의 모든 드라이브에 펌웨어를 설치하기 전에 드라이브 다운로드 명령을 사용하여 한 드라이브에서 펌웨어를 테스트할 수 있습니다. 다운로드는 다음 상태 중 하나를 반환합니다.

* 성공했습니다
* 이유와 함께 실패
* 이유를 가지고 시도해본 적이 없습니다


"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 최소 펌웨어 레벨입니다

7.60은 drawerID 사용자 입력을 추가합니다.

8.25는 온라인매개 변수를 추가한다.
