---
permalink: commands-a-z/enable-storagearray-externalkeymanagement-file.html 
sidebar: sidebar 
keywords: enable, storage, array, external, key, management, file, command, security, disk, encryption, initial, roles, context, support 
summary: enable storageArray externalKeyManagement file 명령을 사용하면 전체 디스크 암호화 드라이브가 있는 스토리지 배열에 대한 외부 보안 키 관리가 가능하며 초기 드라이브 보안 키를 생성할 수 있습니다. 
---
= 외부 보안 키 관리 활성화 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"enable storageArray externalKeyManagement file" 명령을 사용하면 전체 디스크 암호화 드라이브가 있는 스토리지 배열에 대한 외부 보안 키 관리가 가능하며 초기 드라이브 보안 키를 생성할 수 있습니다.



== 지원되는 어레이

이 명령은 개별 E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에 적용됩니다. E2700 또는 E5600 스토리지 어레이에서는 작동하지 않습니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령은 외부 키 관리에만 적용됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
enable storageArray externalKeyManagement
pass:quotes[file="_fileName_"]
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[saveFile=_(TRUE | FALSE)_]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
새 보안 키가 저장될 파일 경로 및 파일 이름입니다. 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
파일 이름의 확장명은 .slk이어야 합니다.

====


 a| 
패스프레이즈
 a| 
외부 파일에 보안 키를 저장할 수 있도록 보안 키를 암호화하는 문자열입니다. 암호문 문자열을 큰따옴표(" ")로 묶습니다.



 a| 
'SaveFile
 a| 
보안 키를 확인하고 파일에 저장합니다. 파일을 저장하지 않고 보안 키를 확인하려면 "false"로 설정합니다. 기본값은 "true"입니다.

|===


== 참고

암호는 다음 기준을 충족해야 합니다.

* 8자에서 32자 사이여야 합니다.
* 대문자를 하나 이상 포함해야 합니다.
* 소문자가 하나 이상 포함되어야 합니다.
* 하나 이상의 숫자를 포함해야 합니다.
* 영숫자가 아닌 문자를 하나 이상 포함해야 합니다(예: <>@+).


[NOTE]
====
암호문이 이러한 기준을 충족하지 않으면 오류 메시지가 표시됩니다.

====


== 최소 펌웨어 레벨입니다

8.40

8.70은 '_SaveFile_' 매개 변수를 추가합니다.
