---
permalink: commands-a-z/establish-asyncmirror-volume.html 
sidebar: sidebar 
keywords: establish, asynmirror, volume, asynchronous, mirrored, remote, storage, array, secondary, existing 
summary: asyncMirror volume 설정 명령은 기존 비동기식 미러 그룹에 2차 볼륨을 추가하여 원격 스토리지 시스템에서 비동기식 미러링 쌍을 완료합니다. 
---
= 비동기 미러링 쌍을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'asyncMirror 볼륨 설정' 명령은 기존 비동기식 미러 그룹에 2차 볼륨을 추가하여 원격 스토리지 시스템에서 비동기식 미러링 쌍을 완료합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령을 실행하기 전에 비동기식 미러 그룹이 있어야 하며 비동기식 미러 그룹에 운영 볼륨이 있어야 합니다. 이 명령이 성공적으로 완료되면 비동기식 미러링이 운영 볼륨과 2차 볼륨 사이에 시작됩니다.

비동기 미러링 쌍을 구성하는 두 볼륨은 단일 엔터티로 작동합니다. 비동기 미러링된 쌍을 설정하면 두 개의 개별 볼륨에 비해 전체 미러링된 쌍에 대한 작업을 수행할 수 있습니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[establish asyncMirror volume="_secondaryVolumeName_"]
pass:quotes[asyncMirrorGroup="_asyncMirrorGroupName_"]
pass:quotes[primaryVolume="_primaryVolumeName_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
보조 볼륨에 사용할 원격 스토리지 시스템의 기존 볼륨 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
아인치마그룹
 a| 
비동기식 미러링 쌍을 포함하는 데 사용할 기존의 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'주 볼륨'
 a| 
운영 볼륨에 사용할 로컬 스토리지 배열의 기존 볼륨 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

비동기식 미러링된 쌍은 동일한 데이터의 복사본이 포함된 2개의 볼륨, 즉 운영 볼륨과 2차 볼륨으로 구성됩니다. 미러링된 쌍은 비동기 미러 그룹의 일부이며, 이 그룹을 사용하면 비동기 미러 그룹 내의 다른 미러링된 쌍과 동시에 미러링된 쌍을 동기화할 수 있습니다.

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

운영 볼륨과 2차 볼륨을 선택할 경우 2차 볼륨의 크기가 운영 볼륨보다 크거나 같아야 합니다. 보조 볼륨의 RAID 레벨은 운영 볼륨과 같을 필요가 없습니다.



== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
