---
permalink: commands-a-z/export-storagearray-securitykey.html 
sidebar: sidebar 
keywords: export, storage, array, security, key, command, save, drive, securitykey, file, context, role 
summary: export storageArray securityKey 명령은 드라이브 보안 키를 파일에 저장합니다. 
---
= 스토리지 배열 보안 키를 내보냅니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
export storageArray securityKey 명령은 드라이브 보안 키를 파일에 저장합니다.



== 지원되는 어레이

외부 키 관리를 사용하는 경우 이 명령은 E2800, E5700, EF600 및 EF300 어레이에만 적용됩니다. 내부 키 관리가 활성화된 경우 모든 SMcli 패키지가 설치된 경우 명령은 개별 스토리지 배열에 적용됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

키 파일을 한 스토리지 배열에서 내보낼 때 해당 키를 다른 스토리지 배열로 가져올 수 있습니다. 이를 통해 스토리지 시스템 간에 보안 가능 드라이브를 이동할 수 있습니다.

[NOTE]
====
이 명령은 내부 및 외부 키 관리에 모두 적용됩니다.

====


== 구문

[listing, subs="+macros"]
----
export storageArray securityKey
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[file="_fileName_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
패스프레이즈
 a| 
외부 파일에 보안 키를 저장할 수 있도록 보안 키를 암호화하는 문자열입니다. 암호는 큰따옴표(" ")로 묶어야 합니다.



 a| 
'파일'
 a| 
보안 키를 저장할 파일 경로와 파일 이름입니다. 예를 들면 다음과 같습니다.

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
파일 이름의 확장명은 .slk이어야 합니다.

====
|===


== 참고

드라이브를 이동할 스토리지 배열에 가져올 드라이브와 같거나 큰 용량이 있는 드라이브가 있어야 합니다.

컨트롤러 펌웨어는 FDE(전체 디스크 암호화) 드라이브에 대한 액세스를 제한하는 잠금을 생성합니다. FDE 드라이브는 Security Capable이라는 상태를 가집니다. 보안 키를 생성할 때 상태가 보안 사용으로 설정되고, 이는 스토리지 어레이 내에 있는 모든 FDE 드라이브에 대한 액세스를 제한합니다.

암호는 다음 기준을 충족해야 합니다.

* 8자에서 32자 사이여야 합니다.
* 공백이 없어야 합니다.
* 대문자를 하나 이상 포함해야 합니다.
* 소문자가 하나 이상 포함되어야 합니다.
* 하나 이상의 숫자를 포함해야 합니다.
* 영숫자가 아닌 문자를 하나 이상 포함해야 합니다(예: <>@+).


[NOTE]
====
암호문이 이러한 기준을 충족하지 않으면 오류 메시지가 표시되고 명령을 다시 시도하라는 메시지가 표시됩니다.

====


== 최소 펌웨어 레벨입니다

7.40
