---
permalink: commands-a-z/load-storagearray-dbmdatabase.html 
sidebar: sidebar 
keywords: load, storage array, database, command, management 
summary: 'load storageArray dbmDatabase 명령은 파일 또는 캐시에서 이미지를 검색하여 데이터베이스 관리(dBm) 데이터베이스 이미지를 복원합니다.' 
---
= 스토리지 어레이 DBM 데이터베이스 로드 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Load storageArray dbmDatabase 명령은 파일 또는 캐시에서 이미지를 검색하여 데이터베이스 관리(dBm) 데이터베이스 이미지를 복원합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

이 명령어는 'Save storageArray dbmDatabase' 명령어를 이용하여 데이터베이스 이미지를 캡처할 때 존재했던 정확한 구성으로 스토리지 배열 dbm 데이터베이스를 복구한다. 파일의 데이터에는 RAID 구성, 볼륨 그룹 및 디스크 풀에 대한 데이터가 포함됩니다.

'file' 옵션과 함께 이 명령을 사용하기 전에 먼저 기술 지원 부서에서 유효성 검사기 문자열(보안 코드)을 구해야 합니다. 유효성 검사기를 가져오려면 'Save storageArray dbmValidatorInfo' 명령을 사용하여 유효성 검사기 정보가 포함된 XML 파일을 생성합니다. 기술 지원 부서에서는 XML 파일을 사용하여 이 명령에 필요한 유효성 검사기 문자열을 생성합니다.



== 구문

[source, cli, subs="+macros"]
----
load storageArray dbmDatabase
pass:quotes[((file="_filename_" validator="_validatorValue_") | sourceLocation=onboard)]
[controller [(a|b)]]
[contentType= all]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
업로드할 DBM 데이터베이스의 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

``file="C:\Array backups\DBMbackup_03302010.dBm" 이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 파일 확장자를 지정해야 합니다.



 a| 
검증자
 a| 
스토리지 배열을 기존 구성으로 복원하는 데 필요한 영숫자 보안 코드입니다.

기술 지원 부서에서 검증기를 받아야 합니다. 유효성 검사기를 가져오려면 'Save storageArray dbmValidatorInfo' 명령을 실행하여 필요한 유효성 검사 정보 XML 파일을 생성합니다. 유효성 검사 정보 XML 파일을 사용할 수 있으면 기술 지원 부서에 문의하여 유효성 검사기를 가져옵니다.

유효성 검사기는 큰따옴표(" ")로 묶습니다.



 a| 
'소스 위치'
 a| 
이 매개변수는 백업 데이터베이스 정보를 검색할 위치를 지정합니다. 일관성을 위해 매개 변수를 포함해야 하지만 허용되는 유일한 값은 '온보드'입니다.



 a| 
컨트롤러
 a| 
이 매개 변수는 데이터를 독점적으로 검색할 컨트롤러를 지정합니다. 컨트롤러 식별자를 대괄호([ ])로 묶습니다. controller 매개 변수를 지정하지 않으면 두 컨트롤러 중 하나에서 데이터를 검색할 수 있습니다.

유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다



 a| 
만족형
 a| 
이 매개변수는 검색할 데이터의 콘텐츠 유형을 지정합니다.

Disk Pool 구성 데이터를 포함한 모든 데이터를 조회할 수 있도록 default로 설정되어 있다.

|===


== 참고

데이터베이스 이미지 크기에 따라 데이터베이스를 복원하는 데 최대 30분이 걸릴 수 있습니다. 데이터베이스 이미지 로드에 대한 모든 작업이 컨트롤러에서 완료될 때까지 호스트 소프트웨어는 컨트롤러를 최적의 상태로 표시하지 않습니다.



== 최소 펌웨어 레벨입니다

7.75

7.83은 다음과 같은 매개 변수를 추가합니다.

* '소스 위치'
* 컨트롤러
* 만족형

