---
permalink: commands-a-z/recover-volume.html 
sidebar: sidebar 
keywords: recover, raid, volume 
summary: recover volume 명령은 드라이브의 사용자 데이터 영역을 초기화하지 않고 지정된 속성을 사용하여 RAID 볼륨을 생성합니다. 
---
= RAID 볼륨을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
recover volume 명령은 드라이브의 사용자 데이터 영역을 초기화하지 않고 지정된 속성을 사용하여 RAID 볼륨을 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

매개 변수 값은 스토리지 배열의 복구 프로파일 데이터 파일(recoby-profile.csv')에서 파생됩니다. 이 명령을 사용하여 기존 볼륨 그룹에 복구 볼륨을 생성하거나 새 볼륨 그룹을 생성할 수 있습니다.

[NOTE]
====
이 명령은 명령줄에서만 실행할 수 있습니다. GUI 스크립트 편집기에서 이 명령을 실행할 수 없습니다. 스토리지 관리 GUI를 사용하여 볼륨을 복구할 수는 없습니다.

====
[NOTE]
====
DDP(동적 디스크 풀) 볼륨에는 이 명령을 사용할 수 없습니다.

====


== 구문

[source, cli, subs="+macros"]
----
recover volume (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_])) |
(drives=pass:quotes[_trayID1_,pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,_]pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])) |
volumeGroup=pass:quotes[_volumeGroupName_]))
[newVolumeGroup=pass:quotes[_volumeGroupName_]]
userLabel=pass:quotes["_volumeName_" volumeWWN="_volumeWWN_"
capacity=_volumeCapacity_
offset=_offsetValue_
raidLevel=(0 | 1 | 3 | 5 | 6)
segmentSize=_segmentSizeValue_
dssPreAllocate=(TRUE | FALSE)
SSID=_subsystemVolumeID_]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
[hostUnmapEnabled=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'늑대'나 '늑대'가 있습니다
 a| 
복구할 볼륨이 포함될 볼륨 그룹에 할당할 드라이브입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
볼륨그룹
 a| 
볼륨을 생성할 기존 볼륨 그룹의 이름입니다. (스토리지 배열의 볼륨 그룹 이름을 확인하려면 'show storageArray profile' 명령을 실행합니다.)



 a| 
newVolumeGroup
 a| 
새 볼륨 그룹에 지정할 이름입니다. 새 볼륨 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
복구할 볼륨의 이름입니다. 사용자 레이블에는 두 개의 부품이 있습니다.

* 볼륨 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.
* 볼륨의 전역 이름인 볼륨 WWN은 16바이트 식별자 형식으로 지정됩니다(예: 60080E500017B4320000000049887D77). 식별자는 큰따옴표(" ")로 묶어야 합니다.


볼륨의 볼륨 이름과 전역 이름을 모두 입력해야 합니다. 먼저 볼륨 이름을 입력해야 합니다. 예를 들면 다음과 같습니다.

[listing]
----
userLabel="engdata"
volumeWWN=60080E500017B4320000000049887D77
----


 a| 
용량
 a| 
스토리지 배열에 추가할 볼륨의 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.



 a| 
"오프셋"
 a| 
볼륨 그룹의 시작에서 참조 볼륨의 시작까지 블록 수.



 a| 
레이드레벨
 a| 
드라이브가 포함된 볼륨 그룹의 RAID 레벨입니다. 유효한 값은 0, 1, 3, 5, 6입니다.



 a| 
'크기'
 a| 
다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨 그룹의 단일 드라이브에 쓰는 데이터 양(KB)입니다. 유효한 값은 8인치, 16인치, 32인치, 64인치, 128입니다. 256, 512.



 a| 
드슈프리알Locate
 a| 
향후 세그먼트 크기 변경을 위해 볼륨 스토리지 용량 할당을 설정하거나 해제하는 설정입니다. 할당을 켜려면 이 매개변수를 'true'로 설정하십시오. 할당을 해제하려면 이 매개변수를 'false'로 설정합니다.



 a| 
'SSID'입니다
 a| 
볼륨의 스토리지 배열 하위 시스템 식별자입니다. 'show volume' 명령을 사용하여 스토리지 배열 하위 시스템 식별자를 결정합니다.



 a| 
오너
 a| 
볼륨을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 소유자를 지정하지 않으면 컨트롤러 펌웨어가 소유자를 결정합니다.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다.



 a| 
'hostUnmapEnabled'(hostUnmapEnabled)
 a| 
이 매개 변수를 "True"로 설정하면 호스트에서 볼륨에 매핑 해제 명령을 실행할 수 있습니다. 매핑 해제 명령은 리소스가 프로비저닝된 볼륨에서만 사용할 수 있습니다.



 a| 
블록사이즈
 a| 
이 설정은 볼륨 블록 크기(바이트)입니다.

|===


== 참고

스토리지 관리 소프트웨어는 모니터링되는 스토리지 시스템의 복구 프로파일을 수집하고 스토리지 관리 스테이션에 프로파일을 저장합니다.

"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.

드라이브 매개변수 또는 드라이브 매개변수를 사용하여 볼륨을 복구하려고 하면 컨트롤러가 자동으로 새 볼륨 그룹을 생성합니다. 새 볼륨 그룹의 이름을 지정하려면 'newVolumeGroup' 매개 변수를 사용합니다.

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

소유자 매개변수는 볼륨을 소유하는 컨트롤러를 정의합니다. 볼륨의 기본 컨트롤러 소유권은 현재 볼륨 그룹을 소유한 컨트롤러입니다.



== 스토리지 용량을 사전 할당 중입니다

dssPreAllocate 매개변수를 사용하면 볼륨 재구축에 사용되는 정보를 저장하기 위해 볼륨에 용량을 할당할 수 있습니다. dssPreallocate 매개변수를 true로 설정하면 컨트롤러 펌웨어의 스토리지 공간 할당 로직에서 향후 세그먼트 크기 변경을 위해 볼륨의 공간을 미리 할당합니다. 사전 할당된 공간은 허용되는 최대 세그먼트 크기입니다. 컨트롤러 데이터베이스에서 검색할 수 없는 볼륨 구성을 제대로 복구하려면 DssPreAllocate 매개 변수가 필요합니다. 사전 할당 기능을 끄려면 'dssPreAllocate'를 'false'로 설정합니다.



== 세그먼트 크기

세그먼트 크기에 따라 다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 블록 수가 결정됩니다. 각 데이터 블록에는 512바이트의 데이터가 저장됩니다. 데이터 블록은 가장 작은 스토리지 단위입니다. 세그먼트의 크기에 따라 포함된 데이터 블록의 수가 결정됩니다. 예를 들어 8KB 세그먼트에는 16개의 데이터 블록이 있습니다. 64KB 세그먼트에는 128개의 데이터 블록이 있습니다.

세그먼트 크기에 대한 값을 입력하면 이 값은 런타임에 컨트롤러에서 제공하는 지원되는 값과 비교하여 확인됩니다. 입력한 값이 유효하지 않으면 컨트롤러가 유효한 값 목록을 반환합니다. 단일 요청에 단일 드라이브를 사용하면 다른 드라이브를 사용할 수 있어 다른 요청을 동시에 처리할 수 있습니다.

볼륨이 단일 사용자가 대용량 데이터(예: 멀티미디어)를 전송하는 환경에 있는 경우 단일 데이터 전송 요청을 단일 데이터 스트라이프로 처리할 때 성능이 극대화됩니다. (데이터 스트라이프는 세그먼트 크기로, 볼륨 그룹의 데이터 전송에 사용되는 드라이브 수를 곱합니다.) 이 경우 여러 드라이브가 동일한 요청에 사용되지만 각 드라이브는 한 번만 액세스됩니다.

다중 사용자 데이터베이스 또는 파일 시스템 스토리지 환경에서 최적의 성능을 얻으려면 세그먼트 크기를 설정하여 데이터 전송 요청을 충족하는 데 필요한 드라이브 수를 최소화하십시오.



== 캐시 읽기 프리페치

캐시 읽기 프리페치를 사용하면 컨트롤러는 추가 데이터 블록을 캐시로 복사하는 한편, 컨트롤러는 호스트에서 요청한 데이터 블록을 디스크에서 캐시로 읽고 복사합니다. 이 작업을 수행하면 캐시에서 향후 데이터 요청을 처리할 수 있는 가능성이 높아집니다. 캐시 읽기 프리페치는 순차 데이터 전송을 사용하는 멀티미디어 응용 프로그램에 중요합니다. 사용하는 스토리지 배열의 구성 설정에 따라 컨트롤러가 캐시로 읽는 추가 데이터 블록의 수가 결정됩니다. cacheReadPrefetch 파라미터의 유효한 값은 TRUE나 FALSE입니다.



== 최소 펌웨어 레벨입니다

5.43

7.10은 RAID 6 레벨 기능 및 'newVolumeGroup' 매개변수를 추가합니다.

7.60은 drawerID 사용자 입력을 추가합니다.

7.75는 '다카Assurance' 파라미터를 추가합니다.

8.78은 hostUnmapEnabled 매개변수를 추가합니다.

11.70.1은 'blocksize' 파라미터를 추가합니다.
