---
permalink: commands-a-z/recover-sasport-miswire.html 
sidebar: sidebar 
keywords: recover, sas, port, mis-wire 
summary: recover sasPort miscWire 명령은 컨트롤러에 잘못된 연결 상태에서 복구하기 위해 수정 조치가 취해되었음을 알려줍니다. 
---
= SAS 포트 오선을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
recover sasPort miswire' 명령은 잘못된 연결 상태에서 복구하기 위해 수정 조치가 취해되었음을 컨트롤러에 알립니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

그런 다음 잘못된 배선이 감지되어 비활성화된 모든 SAS 포트를 컨트롤러에서 다시 활성화할 수 있습니다. SAS 미연결 상태를 수정한 후 이 명령을 실행합니다.

SAS 미연결 상태는 다음 중 하나일 수 있습니다.

* SAS 토폴로지가 잘못되었습니다
* 확장 트레이 연결을 위한 컨트롤러 호스트 포트입니다
* 이니시에이터와 드라이브 사이의 토폴로지 연결
* ESM 오배선




== 구문

[source, cli]
----
recover sasPort miswire
----


== 매개 변수

없음.



== 참고

유선 연결 상태가 감지되면 컨트롤러 펌웨어가 다음을 보고합니다.

* 오배선 상태를 나타내는 심각한 MEL 이벤트입니다
* "주의 필요" 조건
* 오선을 나타내는 회수 조치


또한 컨트롤러는 잘못 배선되어 하나의 액세스 경로만 있는 드라이브, ESMS 및 트레이에 대한 ""이중화 손실" 정보를 보고합니다(예: 스토리지 배열의 하단 두 트레이). 이중화 손실 정보는 SAS 토폴로지에 고유하지 않습니다.

SAS 포트 미연결 관련 이벤트 알림은 다음과 같습니다.

* SAS 오선이 감지되었습니다
* HBA가 드라이브 채널에 연결되어 있습니다
* 드라이브 채널이 교차 배선됩니다


SAS 도메인의 무결성을 보호하기 위해 컨트롤러가 하나 이상의 SAS 포트를 사용하지 않도록 설정하는 오연결 상태의 경우 다음 단계를 수행하여 상태를 복구합니다.

. 어떤 케이블이 잘못된 위치에 있는지 확인하고 제거합니다. 마지막 조치가 새 케이블을 설치하는 것이라면 가장 가능성이 높은 것입니다. 그렇지 않은 경우 스토리지 배열에 포함되지 않은 장치에 연결된 케이블 또는 채널 사이에 연결된 케이블을 찾습니다. 복구 이벤트는 오선이 감지된 채널과 가능한 경우 트레이를 보고해야 합니다
. 케이블을 분리하거나 케이블을 올바른 위치로 이동한 후, recover sasPort miswire' 명령을 실행합니다. 잘못된 배선이 감지될 때 컨트롤러가 비활성화된 모든 SAS 포트를 다시 활성화하려고 시도합니다.
. 컨트롤러에서 비활성화된 포트에만 액세스할 경우 케이블을 분리 또는 이동하여 케이블을 잘못 연결한 경우 비활성화된 SAS 포트를 다시 사용할 수 없습니다. 복구를 완료하려면 스토리지 배열의 트레이에 전원을 공급해야 합니다.




== 최소 펌웨어 레벨입니다

8.10
