---
permalink: commands-a-z/recopy-volumecopy-target.html 
sidebar: sidebar 
keywords: volumecopy, target, command, operation, volume, copy, pair, reinitiate, array, role, context 
summary: recopy volumeCopy target 명령은 기존 볼륨 복사본 쌍을 사용하여 볼륨 복사본 작업을 다시 시작합니다. 
---
= 볼륨 복사본을 다시 복사합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
recopy volumeCopy target' 명령은 기존 볼륨 복사본 쌍을 사용하여 볼륨 복사 작업을 다시 시작합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
펌웨어 버전 7.83에서는 'copyType=(online|offline)' 매개변수가 더 이상 사용되지 않습니다.

====
이 명령은 스냅샷 이미지 볼륨 복사본 쌍에 대해 유효합니다.

이 명령은 스냅샷 이미지 볼륨으로 생성한 볼륨 복사본 쌍과 함께 작동합니다.

[NOTE]
====
볼륨 복사본 작업을 시작하면 타겟 볼륨의 기존 데이터가 모두 덮어쓰여집니다. 그러면 타겟 볼륨이 호스트에 대해 읽기 전용이 되고 타겟 볼륨과 연결된 모든 스냅샷 이미지 볼륨에 장애가 발생합니다. 이전에 타겟 볼륨을 복제본으로 사용한 경우 더 이상 데이터가 필요하지 않거나 백업되지 않았는지 확인하십시오.

====


== 구문

[listing]
----
recopy volumeCopy target [targetName]
[source [sourceName]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
표적
 a| 
볼륨 복제 작업을 다시 시작할 타겟 볼륨의 이름입니다. 타겟 볼륨 이름은 대괄호([])로 묶어야 합니다. 타겟 볼륨 이름에 특수 문자가 있는 경우 타겟 볼륨 이름을 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'소스'입니다
 a| 
볼륨 복제 작업을 다시 시작할 소스 볼륨의 이름입니다. 소스 볼륨 이름은 대괄호([])로 묶어야 합니다. 소스 볼륨 이름에 특수 문자가 있는 경우 소스 볼륨 이름을 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
카피프라이어리티
 a| 
볼륨 복사본의 우선 순위는 호스트 I/O 활동과 관련이 있습니다. 유효한 값은 '가장 높음', '높음', '중간', '낮음' 또는 '가장 낮음'입니다.



 a| 
targetReadOnlyEnabled
 a| 
타겟 볼륨에 쓰거나 타겟 볼륨에서만 읽을 수 있도록 하는 설정입니다. 타겟 볼륨에 쓰려면 이 매개변수를 'false'로 설정합니다. 타겟 볼륨에 쓰지 않으려면 이 매개 변수를 "true"로 설정합니다.

|===


== 참고

복사 우선 순위는 소스 볼륨과 볼륨 복사본 쌍의 타겟 볼륨 간의 데이터를 복사하는 데 사용되는 시스템 리소스의 양을 정의합니다. 가장 높은 우선 순위 수준을 선택하면 볼륨 복사본은 대부분의 시스템 리소스를 사용하여 볼륨 복사본을 수행하므로 호스트 데이터 전송 성능이 저하됩니다.



== 최소 펌웨어 레벨입니다

6.10

7.83은 'copyType=(online|offline)' 파라미터를 제거합니다.
