---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: set diskpool 명령은 풀에서 드라이브를 논리적으로 제거하여 디스크 풀의 용량을 줄입니다. 
---
= 디스크 풀 용량을 줄입니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'show diskpool' 명령을 사용하면 풀에서 드라이브를 논리적으로 제거하여 디스크 풀의 용량을 줄일 수 있습니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 DCR(Dynamic Capacity Reduction) 기능을 사용하여 디스크 풀에서 선택한 드라이브를 제거하고 필요에 따라 제거된 드라이브를 다시 사용할 수 있습니다.

단일 DCR 작업에서 디스크 풀에서 제거할 수 있는 최대 드라이브 수는 60개입니다. 디스크 풀을 최소 디스크 풀 크기 이하로 줄일 수는 없습니다.



== 구문

[listing, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
디즈크풀
 a| 
용량을 줄일 디스크 풀의 이름입니다. 디스크 풀 이름은 대괄호([ ])로 묶어야 합니다.



 a| 
레모브드라이브
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

|===


== 참고

각 디스크 풀 이름은 고유해야 합니다. 사용자 레이블에는 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 사용자 레이블은 최대 30자까지 가능합니다.

별도의 그룹을 생성하거나 스토리지 배열에서 불필요한 용량을 제거해야 하는 경우 디스크 풀에서 선택한 드라이브를 제거할 수 있습니다. 제거된 드라이브는 할당되지 않은 드라이브가 되며 해당 드라이브에 있던 데이터는 디스크 풀의 나머지 드라이브에 재배포됩니다. 디스크 풀의 용량은 제거하는 드라이브의 용량에 따라 감소합니다. 디스크 풀에서 드라이브를 제거하는 작업은 항상 백그라운드 작업으로 수행되므로 이 작업 중에 볼륨을 완전히 액세스할 수 있습니다. 제거 작업의 진행률이 장시간 실행 중인 작업 상태의 일부로 보고됩니다.

디스크 풀에서 제거한 드라이브에 있던 모든 데이터를 저장하기 위해 디스크 풀에 남아 있는 드라이브에 사용 가능한 용량이 충분하지 않으면 이 명령이 실패합니다. 디스크 풀의 예비 용량은 디스크 풀에서 제거한 드라이브에 있던 데이터를 저장하는 데 사용될 수 있습니다. 그러나 예약 용량이 중요 임계값 아래로 떨어지면 중요한 이벤트가 주요 이벤트 로그에 기록됩니다.

디스크 풀 크기를 줄이면 필요한 예약 용량이 작아질 수 있습니다. 경우에 따라 이 명령이 실패할 가능성을 줄이려면 디스크 풀 데이터에 사용할 수 있는 공간을 늘리기 위해 이 명령을 실행하기 전에 예약 용량을 줄이십시오.

컨트롤러 펌웨어는 제거할 수 있는 드라이브 수를 결정하고 제거할 특정 드라이브를 선택할 수 있습니다. 컨트롤러 펌웨어는 재구성을 위해 예약된 용량을 사용하지 않고 나머지 드라이브에서 데이터를 재배포하는 데 필요한 여유 공간의 양을 기준으로 합니다. 디스크 풀의 사용 가능한 용량이 이미 예약된 재구성 드라이브 용량보다 작은 경우 컨트롤러는 DCR 작업을 시작할 수 없습니다.

DCR 작업을 수행하면 구성된 용량이 풀 사용률 임계값 중 하나 또는 둘 다를 초과할 수 있습니다. 이 경우 일반 임계값 알림이 실행됩니다.



== 최소 펌웨어 레벨입니다

8.10
