---
permalink: commands-a-z/remove-lunmapping.html 
sidebar: sidebar 
keywords: remove, volume, lun map 
summary: 'remove lunMapping 명령은 하나 이상의 볼륨에서 LUN(Logical Unit Number) 또는 NSID(Namespace ID) 매핑을 제거합니다.' 
---
= 볼륨 LUN 매핑을 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'remove lunMapping' 명령은 하나 이상의 볼륨에서 LUN(Logical Unit Number) 또는 NSID(Namespace ID) 매핑을 제거합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
remove (volume pass:quotes[[_"volumeName"_]] | accessVolume) lunMapping
(host=pass:quotes[_"hostName_" | hostGroup=(_"hostGroupName"_] | defaultGroup)
----


== 둘 이상의 볼륨 LUN 또는 NSID 매핑에서 LUN 또는 NSID 매핑을 제거하는 구문

[source, cli, subs="+macros"]
----
remove (allVolumes | volumes pass:quotes[[_volumeName1 ... volumeNameN_]])
lunMapping
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
LUN 또는 NSID 매핑을 제거할 볼륨의 이름입니다. 볼륨 이름은 큰따옴표(" ")를 대괄호([])로 묶습니다.



 a| 
'accessVolume'
 a| 
이 매개 변수는 액세스 볼륨을 제거합니다.



 a| 
'올볼륨'
 a| 
이 매개 변수는 모든 볼륨에서 LUN 매핑을 제거합니다.



 a| 
'볼륨'
 a| 
LUN 또는 NSID 매핑을 제거하려는 여러 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자가 있거나 숫자만 포함된 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
호스트
 a| 
볼륨이 매핑되는 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.

이 매개 변수는 한 볼륨에서 LUN 또는 NSID 매핑을 제거하는 경우에만 작동합니다.



 a| 
호스트그룹
 a| 
볼륨이 매핑되는 호스트가 포함된 호스트 그룹의 이름입니다. 호스트 그룹 이름은 큰따옴표(" ")로 묶어야 합니다. defaultGroup 값은 볼륨이 매핑되는 호스트가 포함된 호스트 그룹입니다.

이 매개 변수는 한 볼륨에서 LUN 또는 NSID 매핑을 제거하는 경우에만 작동합니다.

|===


== 참고

액세스 볼륨은 스토리지 관리 소프트웨어와 스토리지 어레이 컨트롤러 간의 통신에 사용되는 SAN 환경의 볼륨입니다. 액세스 볼륨은 LUN 또는 NSID 주소를 사용하며 애플리케이션 데이터 스토리지에 사용할 수 없는 20MB의 스토리지 공간을 사용합니다. 액세스 볼륨은 대역내 관리형 스토리지 어레이에만 필요합니다.

[NOTE]
====
* 액세스 볼륨을 제거하면 구성이 손상될 수 있습니다. * -- 에이전트는 액세스 볼륨을 사용하여 스토리지 배열과 통신합니다. 에이전트가 실행되고 있는 호스트에서 스토리지 배열에 대한 액세스 볼륨 매핑을 제거하면 스토리지 관리 소프트웨어가 더 이상 에이전트를 통해 스토리지 배열을 관리할 수 없습니다.

====
액세스 볼륨이 아닌 볼륨 또는 액세스 볼륨을 지정할 때는 "host" 매개 변수와 "hostGroup" 매개 변수를 사용해야 합니다. "allVolumes" 매개 변수 또는 "volumes" 매개 변수를 사용하면 Script Engine은 "host" 매개 변수 또는 "hostGroup" 매개 변수를 무시합니다.



== 최소 펌웨어 레벨입니다

6.10
