---
permalink: commands-a-z/remove-drives-from-ssd-cache.html 
sidebar: sidebar 
keywords: remove, drives, ssd, cache 
summary: 'set ssdCache 명령은 SSD(Solid State Disk)를 제거하여 SSD 캐시 용량을 줄입니다.' 
---
= SSD 캐시에서 드라이브를 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
세트 ssdCache 명령은 SSD(Solid State Disk)를 제거하여 SSD 캐시 용량을 줄입니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 지원 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'ssdCache'입니다
 a| 
SSD를 제거하려는 SSD 캐시의 이름입니다. SSD 캐시 이름은 대괄호([ ])로 묶어야 합니다. SSD 캐시 이름에 특수 문자가 있거나 숫자로만 구성된 경우 SSD 캐시 이름을 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
레모브드라이브
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

|===


== 참고

이 명령을 사용하여 SSD 캐시에서 모든 SSD를 제거할 수 없으며 SSD를 하나 이상 SSD 캐시에 유지해야 합니다. SSD 캐시를 완전히 제거하려면 대신 ddelete ssdCache 명령을 사용하십시오.



== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
