---
permalink: commands-a-z/reset-drive.html 
sidebar: sidebar 
keywords: reset, drive 
summary: reset drive 명령은 일관성 없거나 최적화되지 않은 동작을 보이는 드라이브의 복구를 지원하기 위해 볼륨 그룹 또는 디스크 풀의 드라이브를 순환합니다. 
---
= 드라이브 재설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'reset drive' 명령은 정합성이 보장되지 않거나 최적화되지 않은 동작을 보이는 드라이브의 복구를 지원하기 위해 볼륨 그룹 또는 디스크 풀의 드라이브를 순환합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

드라이브 전원을 껐다가 켜면 일정하지 않거나 최적화되지 않은 동작을 일으키는 일부 오류를 지울 수 있습니다. 이렇게 하면 치명적이지 않은 일시적인 오류만 발생하고 드라이브가 계속 작동할 수 있는 경우 드라이브를 교체하지 않아도 됩니다. 이렇게 드라이브를 재설정하면 작업 중단이 줄어들고 드라이브 교체가 방지됩니다.

드라이브 전원을 껐다가 다시 켜도 문제를 해결할 수 없는 경우 드라이브에서 데이터가 복사되고 드라이브 전원이 꺼져 교체가 필요한 것입니다.

[NOTE]
====
용제에 의해 제조된 SSD 드라이브에는 이 명령을 사용할 수 없습니다. 'show storageArray profile' 명령 또는 'show drive' 명령을 사용하여 드라이브 제조업체를 표시합니다.

====


== 구문

[source, cli]
----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"내가 한 일"이라고 말했습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
"내가 한 일"이라고 말했습니다
 a| 
교체하려는 드라이브의 WWID(World Wide Identifier)입니다. WWID는 큰따옴표(" ")로 꺽쇠 괄호(<>)로 묶습니다.

|===


== 참고

"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.

드라이브 전원을 껐다가 켠 후, 컨트롤러는 드라이브를 다시 사용하기 전에 드라이브가 작동하는지 확인해야 합니다. 드라이브를 확인할 수 없는 경우, 장애가 발생한 드라이브로 표시됩니다. 장애가 발생한 드라이브의 전원을 껐다가 켜려면 글로벌 핫 스페어 드라이브가 필요하며, 서비스가 시작된 후 교체 드라이브로 전체 복제가 필요합니다.

장애가 발생한 드라이브는 24시간 동안 전원 사이클로 한 번 이상 재설정할 수 없으며, 경우에 따라 두 번 이상 재설정할 수 없습니다. 드라이브 전원 사이클의 임계값과 카운터는 영구 저장소에 보관되며 상태 캡처 데이터에 포함됩니다. 정보 이벤트는 드라이브의 전원을 껐다가 켤 때 기록됩니다.



== 최소 펌웨어 레벨입니다

8.20
