---
permalink: commands-a-z/reset-iscsiipaddress.html 
sidebar: sidebar 
keywords: reset, iscsi, ip address 
summary: reset iscsiIpAddress 명령은 로컬 스토리지 배열과의 연결을 다시 설정하기 위해 원격 스토리지 배열의 IP 주소를 재설정합니다. 
---
= iSCSI IP 주소를 재설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
reset iscsiIpAddress 명령은 로컬 스토리지 어레이와의 연결을 다시 설정하기 위해 원격 스토리지 배열의 IP 주소를 재설정합니다.



== 지원되는 어레이

이 명령은 일부 제한이 있는 개별 스토리지 배열에 적용됩니다. E2700 또는 E5600 어레이에서 명령을 실행하는 경우에는 제한이 없습니다.

[NOTE]
====
E2800, E5700, EF600 및 EF300 어레이에서 명령을 실행하는 경우 클라이언트 유형은 로 설정해야 합니다 `symbol`. 이 명령은 클라이언트 유형이 로 설정된 경우 실행되지 않습니다 `https`.

====


== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령을 사용하여 원격 스토리지 배열의 iSCSI IP 주소가 변경되어 업데이트해야 함을 로컬 스토리지 배열에 알릴 수 있습니다.

iSCSI 접속과 비동기 미러링 관계를 설정할 때 로컬 및 원격 스토리지 배열은 비동기 미러링 구성에서 원격 스토리지 배열의 IP 주소에 대한 레코드를 저장합니다. iSCSI 포트의 IP 주소가 변경되면 해당 포트를 사용하려는 원격 스토리지 어레이에 통신 오류가 발생합니다.

IP 주소가 변경된 스토리지 배열은 iSCSI 연결을 통해 미러링하도록 구성된 비동기 미러 그룹과 연결된 각 원격 스토리지 배열에 메시지를 보냅니다. 이 메시지를 수신하는 스토리지 어레이는 원격 대상 IP 주소를 자동으로 업데이트합니다.

변경된 IP 주소를 가진 스토리지 배열이 원격 스토리지 배열에 컨트롤러 간 메시지를 보낼 수 없는 경우, 시스템은 연결 문제에 대한 경고를 보냅니다. "reset" 명령을 사용하여 로컬 스토리지 어레이와의 연결을 다시 설정합니다.



== 구문

[listing]
----
reset (remoteStorageArrayName="storageArrayName" | remoteStorageArrayWwid=<wwID>)
iscsiIpAddress
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
"remoteStorageArrayName"입니다
 a| 
iSCSI IP 주소를 재설정하는 원격 스토리지 배열의 이름입니다. 스토리지 배열 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
레모테StorageArrayWid
 a| 
iSCSI IP 주소를 재설정하는 스토리지 배열의 WWID(World Wide Identifier)입니다. 스토리지 배열 이름 대신 WWID를 사용하여 스토리지 배열을 식별할 수 있습니다. WWID는 꺾쇠 괄호(<>)로 묶어야 합니다.

|===


== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
