---
permalink: commands-a-z/reset-controller.html 
sidebar: sidebar 
keywords: reset, controller 
summary: RESET controller 명령은 컨트롤러를 재설정하고 I/O 작업을 중단한다. 
---
= 컨트롤러를 재설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
reset controller" 명령은 컨트롤러를 재설정하고 I/O 작업을 중단한다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
컨트롤러를 재설정하면 데이터 경로에서 컨트롤러가 제거되고 재설정 작업이 완료될 때까지 I/O 작업에 사용할 수 없습니다. 호스트가 재설정 중인 컨트롤러에서 소유하는 볼륨을 사용하는 경우 컨트롤러에 대한 I/O가 거부됩니다. 컨트롤러를 재설정하기 전에 컨트롤러가 소유하는 볼륨이 사용 중이 아닌지 확인하거나 이러한 볼륨을 사용하는 모든 호스트에 다중 경로 드라이버가 설치되어 있는지 확인하십시오.

====
[CAUTION]
====
대역내 관리를 사용하는 경우 어떤 컨트롤러에도 명령을 전송할 수 없으며 이 명령에 예기치 않은 결과가 발생할 수 있습니다.

====


== 구문

[listing]
----
reset controller [(a|b)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
재설정할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.

|===


== 참고

reset controller 명령을 수신하는 컨트롤러는 지정된 컨트롤러를 재설정합니다. 예를 들어, 컨트롤러 A의 재설정을 요청하기 위해 컨트롤러 A로 컨트롤러 재설정 명령을 전송할 경우 컨트롤러 A는 소프트 재부팅을 수행하여 자체를 재부팅합니다. 컨트롤러 B의 재설정을 요청하기 위해 컨트롤러 A로 컨트롤러 재설정 명령을 보내면 컨트롤러 A는 컨트롤러 B를 리셋 후 컨트롤러 B를 리셋(하드 재부팅)에서 해제합니다. 일부 제품의 소프트 재부팅은 IOC 칩만 재설정합니다. 하드 재부팅은 IOC와 컨트롤러의 확장기 칩을 모두 재설정합니다.



== 최소 펌웨어 레벨입니다

5.20
