---
permalink: commands-a-z/resume-snapvolume.html 
sidebar: sidebar 
keywords: resume, snapshot, volume 
summary: resume snapVolume 명령은 중지된 스냅샷 볼륨 작업을 다시 시작합니다. 
---
= 스냅샷 볼륨을 재개합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'reSUME snapVolume' 명령은 중지된 스냅샷 볼륨 작업을 다시 시작합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
resume snapVolume pass:quotes[[_"snapVolumeName"_]] snapImage=pass:quotes[_"snapCGID:imageID"_]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
'냅볼륨'
 a| 
작업을 재개할 스냅샷 볼륨의 이름입니다. 스냅샷 볼륨 이름은 큰따옴표(" ")로 대괄호([ ]) 안에 묶어야 합니다.



 a| 
'냅이미지'
 a| 
스냅샷 볼륨 작업을 재개할 스냅샷 이미지의 이름입니다. 스냅샷 이미지의 이름은 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' - 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' - 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

스냅샷 이미지의 이름은 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 식별자입니다
* 스냅샷 이미지의 식별자입니다


예를 들어 이름이 snapGroup1인 스냅샷 그룹에서 스냅샷 이미지 12345에 대한 스냅샷 볼륨 작업을 재개하려면 다음 명령을 사용합니다.

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:12345";
----
스냅샷 그룹의 이름이 snapGroup1인 가장 최근 스냅샷 이미지에 대한 스냅샷 볼륨 작업을 재개하려면 다음 명령을 사용합니다.

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:newest";
----


== 최소 펌웨어 레벨입니다

7.83
