---
permalink: commands-a-z/resume-syncmirror.html 
sidebar: sidebar 
keywords: resume, synchronous, mirroring 
summary: resume SyncMirror 명령은 일시 중단된 동기식 미러링 작업을 재개합니다. 
---
= 동기식 미러링 재개 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
reSUME SyncMirror 명령은 일시 중단된 동기 미러링 작업을 다시 시작합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800 및 E5700 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령의 이전 버전에서는 피처 식별자가 'remoteMirror'였습니다. 이 기능 식별자는 더 이상 유효하지 않으며 SyncMirror로 대체됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
resume syncMirror (primary pass:quotes[[_volumeName_]] |
primaries pass:quotes[[_volumeName1 ... volumeNameN_]])
[writeConsistency=(TRUE | FALSE)]
----


== 매개 변수

|===
| 매개 변수 | 설명 


 a| 
1차
 a| 
동기 미러링 작업을 재개할 기본 볼륨의 이름입니다. 기본 볼륨 이름은 대괄호([])로 묶어야 합니다. 기본 볼륨 이름에 특수 문자나 숫자가 있는 경우 기본 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'경선대회'
 a| 
동기 미러링 작업을 다시 시작할 여러 운영 볼륨의 이름입니다. 다음 규칙을 사용하여 운영 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


기본 볼륨 이름에 특수 문자가 있거나 숫자만 포함된 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
쓰기 일관성
 a| 
이 명령에서 쓰기 정합성 보장 그룹에 있거나 별도의 볼륨을 식별하는 설정입니다. 볼륨이 동일한 쓰기 정합성 보장 그룹에 있도록 하려면 이 매개 변수를 "true"로 설정합니다. 볼륨을 분리하려면 이 매개변수를 "false"로 설정합니다.

|===


== 참고

"writeConsistency" 매개 변수를 "true"로 설정하면 볼륨은 쓰기 정합성 보장 그룹(또는 그룹)에 있어야 합니다. 이 명령은 볼륨이 포함된 모든 쓰기 정합성 보장 그룹을 다시 시작합니다. 예를 들어, 볼륨 A, B, C가 쓰기 정합성 보장 그룹에 있고 원격 대응인 A, B, C가 있는 경우 RESUME SyncMirror 볼륨 ["A"] writeConsistency = true "명령은 A-A", B-B" 및 C-C를 다시 시작합니다.



== 최소 펌웨어 레벨입니다

6.10
