---
permalink: commands-a-z/save-storagearray-iscsistatistics.html 
sidebar: sidebar 
keywords: save, storage, array, iscsi, statistics 
summary: save storageArray iscsiStatistics 명령은 스토리지 배열의 iSCSI 성능 통계를 파일에 저장합니다. 
---
= 스토리지 배열 iSCSI 통계를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Save storageArray iscsiStatistics' 명령어는 스토리지 배열의 iSCSI 성능 통계를 파일에 저장한다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.

[NOTE]
====
이 명령은 더 이상 사용되지 않으며 로 대체됩니다 xref:save-storagearray-hostportstatistics.adoc[스토리지 배열 호스트 포트 통계를 저장합니다] 명령.

====


== 구문

[listing, subs="+macros"]
----
save storageArray iscsiStatistics [(raw | baseline)] file=pass:quotes["_filename_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
날것
 a| 
수집된 통계는 컨트롤러 시작 날짜의 모든 통계입니다. 매개 변수는 대괄호([ ])로 묶어야 합니다.



 a| 
베이스라인입니다
 a| 
수집된 통계는 "reset storageArray ibsBaseline" 명령을 사용하여 컨트롤러가 0으로 재설정된 시간부터 모든 통계입니다. 매개 변수는 대괄호([ ])로 묶어야 합니다.



 a| 
'파일'
 a| 
성능 통계를 저장할 파일 경로와 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\isistat.csv"

iSCSI 성능 통계를 포함하는 파일의 기본 이름은 iSCSI-statistics.csv입니다. 파일 이름은 사용할 수 있지만 확장명은 .csv여야 합니다.

|===


== 참고

컨트롤러 시작 시간 이후 iSCSI 기본 통계를 재설정하지 않은 경우 시작 시점의 시간이 기본 기준선 시간입니다.



== 최소 펌웨어 레벨입니다

7.10

8.41 이 명령은 사용되지 않습니다.
