---
permalink: commands-a-z/save-storagearray-supportdata.html 
sidebar: sidebar 
keywords: save, storage, array, support, data 
summary: save storageArray supportData 명령은 스토리지 배열의 지원 관련 정보를 파일에 저장합니다. 
---
= 스토리지 배열 지원 데이터를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Save storageArray supportData' 명령어는 스토리지 배열의 지원 관련 정보를 파일에 저장한다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

다음 표에는 수집할 수 있는 지원 데이터 유형이 나와 있습니다.

[cols="2*"]
|===
| 데이터 유형입니다 | 파일 이름 및 설명입니다 


 a| 
자동 로드 밸런싱 통계
 a| 
"ALB-statistics-A.txt"입니다

ALB-STATISTICS-B.txt입니다

이 파일은 컨트롤러당 하나씩 오프라인 분석 도구를 통해 추가 분석을 수행할 수 있는 자동 로드 밸런싱 기능과 관련된 다양한 통계를 지정합니다.



 a| 
코어 덤프 메타데이터
 a| 
올코어 덤프 XML

이 파일에는 스토리지에 대한 코어 덤프 메타데이터가 들어 있습니다.

[NOTE]
====
8.25 릴리스부터 core-dump-info.xml 이름이 All-coredump.xml로 변경되었습니다.

====


 a| 
AutoSupport 상태입니다
 a| 
자동 지원 .xml입니다

이 파일은 지정된 어레이에 대한 ASUP의 현재 상태를 지정합니다.



 a| 
AutoSupport 기록 파일
 a| 
autosupport-history.xml입니다

이 파일은 지정된 어레이에 대한 표준 및 AutoSupport OnDemand 메시지 모두의 ASUP 메시지를 지정합니다. 표의 각 항목은 지정된 어레이의 저장소 중 하나에 현재 있는 ASUP 메시지에 해당합니다.



 a| 
AutoSupport 로그
 a| 
'sASUP-transmission-logs.txt'입니다

이 파일에는 전송된 모든 AutoSupport 메시지가 들어 있습니다.



 a| 
웹 서버 클라이언트 정보
 a| 
'client-info.txt'입니다

이 파일은 다양한 웹 서비스 클라이언트 정보를 지정합니다.

[NOTE]
====
E2700 및 E5600 어레이에는 적용되지 않습니다.

====


 a| 
드라이브 케이블 연결 토폴로지
 a| 
connection.txt 이 파일에는 드라이브 트레이 환경 서비스 모듈(ESM)과 컨트롤러 쌍 사이의 연결에 대한 정보가 들어 있습니다.



 a| 
누적 통계 번들
 a| 
'cumulative-drive-vol-stats.xml'

이 파일에는 컨트롤러의 누적 통계가 들어 있습니다.



 a| 
드라이브 로그가 제대로 작동하지 않습니다
 a| 
컨트롤러-드라이브-오류-이벤트-로그.txt

이 파일에는 스토리지 배열 컨트롤러 드라이브 측 오류 및 이벤트 로그 메시지가 들어 있습니다.



 a| 
컨트롤러 상태 이미지 메타데이터
 a| 
올코어 덤프 XML

이 파일에는 DPL 컨트롤러 상태 이미지 정보가 들어 있습니다.

[NOTE]
====
8.25 릴리스부터 core-dump-info.xml 이름이 All-coredump.xml로 변경되었습니다.

====


 a| 
컨트롤러 A용 DOM 0 저널 파일(E2800 또는 E5700만 해당)
 a| 
dom0-complete-jour저널-a.7z

이 파일에는 자세한 Linux 시스템 로그가 들어 있습니다. 여기에는 Linux 패키지 및 표준 Linux 유틸리티 및 서비스에 대한 로그가 포함됩니다.



 a| 
컨트롤러 B용 DOM 0 저널 파일(E2800 또는 E5700 전용)
 a| 
dom0-complete-jour저널-B.7z

이 파일에는 자세한 Linux 시스템 로그가 들어 있습니다. 여기에는 Linux 패키지 및 표준 Linux 유틸리티 및 서비스에 대한 로그가 포함됩니다.



 a| 
컨트롤러 A용 기타 DOM 0 로그 파일(E2800 또는 E5700 전용)
 a| 
dom0-misc-logs-a.7z

이 파일은 컨트롤러당 1개씩 업무 일지에 포함할 수 없는 시스템 로그를 포함합니다. 여기에는 RAID 응용 프로그램의 직렬 로그 및 하이퍼바이저의 디버그 로그가 포함됩니다.



 a| 
컨트롤러 B용 기타 DOM 0 로그 파일(E2800 또는 E5700 전용)
 a| 
dom0-misc-logs-b.7z

이 파일은 컨트롤러당 1개씩 업무 일지에 포함할 수 없는 시스템 로그를 포함합니다. 여기에는 RAID 응용 프로그램의 직렬 로그 및 하이퍼바이저의 디버그 로그가 포함됩니다.



 a| 
드라이브 명령 에이징 시간 초과 값
 a| 
drive-command-aging-timeout.txt 이 파일에는 모든 드라이브에 대한 명령 에이징 시간 초과 필드의 기본값 및 현재 값이 들어 있습니다.



 a| 
드라이브 상태 로그
 a| 
drive-health-data.bin 이 파일에는 드라이브 상태와 관련된 다양한 드라이브 정보가 들어 있습니다.

[NOTE]
====
이 파일은 이진 파일이며 사람이 읽을 수 있는 형식으로 변환하려면 오프라인 파서가 필요합니다.

====


 a| 
드라이브 성능 분석기 데이터
 a| 
"drive-performance-log.txt"입니다

이 파일에는 아래의 기대치를 충족하는 드라이브를 식별하는 데 도움이 되는 드라이브 성능 데이터가 포함되어 있습니다.



 a| 
Enterprise Management Window 구성
 a| 
엠비데이터_v04.BIN

이 파일에는 EMW 구성 데이터 저장소 파일이 들어 있습니다.

[NOTE]
====
E2800 및 E5700용 지원 번들에는 이 파일이 없습니다.

====


 a| 
트레이 이벤트 로그
 a| 
확장 트레이-log.txt

ESM 이벤트 로그.



 a| 
리포지토리 분석에 실패했습니다
 a| 
'failed-repository-analysis.txt'입니다

이 파일에는 실패한 리포지토리 분석 정보가 포함되어 있습니다.



 a| 
스토리지 어레이의 기능입니다
 a| 
Feature-bundle.txt 이 파일에는 스토리지 배열에서 허용되는 볼륨, 드라이브 및 드라이브 트레이 수와 사용 가능한 기능 및 제한 목록이 들어 있습니다.



 a| 
펌웨어 인벤토리
 a| 
"firmware-inventory.txt" 이 파일에는 스토리지 배열의 모든 구성 요소에 대한 모든 펌웨어 버전 목록이 들어 있습니다.



 a| 
InfiniBand 인터페이스 통계(InfiniBand만 해당)
 a| 
IB-statistics.csv입니다

이 파일에는 InfiniBand 인터페이스 통계가 포함되어 있습니다.



 a| 
I/O 경로 통계
 a| 
IO-PATH-statistics.7z 이 파일에는 응용 프로그램 성능 문제를 분석하는 데 사용할 수 있는 각 컨트롤러의 원시 성능 데이터가 들어 있습니다.



 a| 
호스트 인터페이스 칩에 대한 IOC 덤프 정보입니다
 a| 
IOC-dump-info.txt 이 파일에는 호스트 인터페이스 칩에 대한 IOC 덤프 정보가 들어 있습니다.



 a| 
호스트 인터페이스 칩에 대한 IOC 덤프 로그
 a| 
IOC-dump.gz 이 파일에는 컨트롤러의 호스트 인터페이스 칩의 로그 덤프가 들어 있습니다. 파일이 gz 형식으로 압축됩니다. zip 파일은 고객 지원 번들 내에 파일로 저장됩니다.



 a| 
iSCSI 연결(iSCSI만 해당)
 a| 
"iscsi-session-connections.txt" 이 파일에는 현재 모든 iSCSI 세션 목록이 포함되어 있습니다.



 a| 
iSCSI 통계(iSCSI만 해당)
 a| 
ISCSI-statistics.csv 이 파일에는 이더넷 미디어 액세스 제어(MAC), 이더넷 전송 제어 프로토콜(TCP)/인터넷 프로토콜(IP) 및 iSCSI 대상에 대한 통계가 들어 있습니다.



 a| 
iSER 인터페이스 통계(iSER over InfiniBand만 해당)
 a| 
iser-statistics.csv 이 파일에는 InfiniBand를 통해 iSER을 실행하는 호스트 인터페이스 카드의 통계가 들어 있습니다.



 a| 
주요 이벤트 로그
 a| 
major-event-log.txt" 이 파일에는 스토리지 배열에서 발생하는 자세한 이벤트 목록이 들어 있습니다. 이 목록은 스토리지 배열의 디스크의 예약된 영역에 저장됩니다. 이 목록에는 스토리지 시스템의 구성 이벤트 및 구성 요소 장애가 기록됩니다.



 a| 
매니페스트 파일
 a| 
'가장 빠른 XML'입니다

이 파일에는 보관 파일에 포함된 파일과 각 파일의 수집 상태를 설명하는 표가 들어 있습니다.



 a| 
스토리지 관리 소프트웨어 런타임 정보입니다
 a| 
mSW-runtime-info.txt

이 파일에는 스토리지 관리 소프트웨어 응용 프로그램 런타임 정보가 들어 있습니다. 스토리지 관리 소프트웨어에서 현재 사용하는 JRE 버전이 포함되어 있습니다.



 a| 
NVMe - 통계
 a| 
nvmeof-statistics.csv입니다

이 파일에는 NVMe 컨트롤러 통계, NVMe 대기열 통계, 전송 프로토콜(예: InfiniBand)에 대한 인터페이스 통계 등의 통계 목록이 포함되어 있습니다.



 a| 
NVSRAM 데이터
 a| 
nvsram-data.txt 이 컨트롤러 파일은 컨트롤러의 기본 설정을 지정합니다.



 a| 
오브젝트 번들
 a| 
객물묶음.빈 객물묶음.json

이 번들에는 스토리지 배열 및 해당 구성 요소의 상태에 대한 자세한 설명이 포함되어 있으며, 이 정보는 파일이 생성된 시점에 유효합니다.



 a| 
성능 통계 요약
 a| 
perf-stat-daily-summary-a.csv의 perf-stat-daily-summary-b.csv입니다

이 파일에는 다양한 컨트롤러 성능 통계, 컨트롤러당 한 개의 파일이 들어 있습니다.



 a| 
지속적인 예약 및 등록
 a| 
"persistent-reservations.txt" 이 파일에는 영구 예약 및 등록을 통해 스토리지 배열의 볼륨 목록이 자세히 나와 있습니다.



 a| 
스토리지 관리 소프트웨어 사용자 기본 설정
 a| 
프리프-01.빈

이 파일에는 사용자 기본 설정 영구 데이터 저장소가 들어 있습니다.

[NOTE]
====
E2800 또는 E5700 지원 번들에는 이 파일이 없습니다.

====


 a| 
Recovery Guru 절차
 a| 
이 파일에는 스토리지 배열에서 감지된 문제에 대응하여 발행되는 모든 복구 전문가 항목의 자세한 목록이 들어 있습니다. E2800 및 E5700 어레이의 경우 이 파일에는 HTML 파일이 아니라 복구 전문가 세부 정보만 포함됩니다.



 a| 
복구 프로파일
 a| 
RECOVERY-PROFILE.CSV 이 파일에는 최신 복구 프로파일 레코드 및 내역 데이터에 대한 자세한 설명이 들어 있습니다.



 a| 
SAS PHY 오류 로그
 a| 
AS-PHY-ERROR-LOGS.csv로 표시됩니다

이 파일에는 SAS PHY에 대한 오류 정보가 들어 있습니다.



 a| 
상태 캡처 데이터
 a| 
'STATE-CAPTURE-DATA.txt' 이 파일에는 스토리지 배열의 현재 상태에 대한 자세한 설명이 들어 있습니다.



 a| 
스토리지 배열 구성
 a| 
'storage-array-configuration.cfg' 이 파일에는 스토리지 배열의 논리적 구성에 대한 자세한 설명이 들어 있습니다.



 a| 
스토리지 배열 프로파일
 a| 
'storage-array-profile.txt' 이 파일에는 스토리지 배열의 모든 구성 요소와 속성에 대한 설명이 들어 있습니다.



 a| 
버퍼 내용을 추적합니다
 a| 
''TRACE-BUFFERS.7z' 이 파일에는 디버그 정보를 기록하는 데 사용되는 컨트롤러의 추적 버퍼의 내용이 들어 있습니다.



 a| 
용지함 캡처 데이터
 a| 
"tray-component-state-capture.7z" 용지함에 서랍이 들어 있으면 진단 데이터가 압축된 파일에 보관됩니다. Zip 파일에는 서랍이 들어 있는 용지함마다 별도의 텍스트 파일이 들어 있습니다. Zip 파일은 고객 지원 번들 내에 파일로 저장됩니다.



 a| 
읽을 수 없는 섹터
 a| 
읽을 수 없는 섹터 txt 이 파일에는 스토리지 배열에 기록된 읽을 수 없는 모든 섹터의 상세 목록이 들어 있습니다.



 a| 
웹 서비스 추적 로그(E2800 또는 E5700만 해당)
 a| 
웹서버-추적-로그-A.7z

웹서버-추적-로그-B.7z

이 파일은 컨트롤러당 하나씩 디버그 정보를 기록하는 데 사용되는 웹 서비스 추적 버퍼를 포함합니다.



 a| 
워크로드 캡처 분석 로그 파일
 a| 
wlc-analytics-a.lz4 wlc-analytics-b.lz4

이 파일은 컨트롤러당 하나로, 모든 활성 볼륨에서 LBA 히스토그램, 읽기/쓰기 비율, I/O 처리량 등 계산된 주요 워크로드 특성을 포함합니다.



 a| 
X-헤더 데이터 파일
 a| 
"x-header-data.txt" 이 AutoSupport 메시지 헤더는 배열 및 메시지 유형에 대한 정보를 포함하는 일반 텍스트 키 값 쌍으로 구성됩니다.

|===


== 구문

[listing, subs="+macros"]
----
save storageArray supportData file=pass:quotes["_filename_"] [force=(TRUE | FALSE)]
----
[listing, subs="+macros"]
----
save storageArray supportData file=pass:quotes["_filename_"]
[force=(TRUE | FALSE) |
csbSubsetid=(basic | weekly | event | daily | complete) |
csbTimeStamp=pass:quotes[_hh:mm_]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
스토리지 배열에 대한 지원 관련 데이터를 저장할 파일 경로 및 파일 이름입니다. 파일 경로와 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\supdat.7z"



 a| 
"힘"
 a| 
이 매개 변수는 컨트롤러 작동 시 잠금 장치 보안에 오류가 있을 경우 지원 데이터 수집을 강제로 수행할 수 있습니다. 지원 데이터 수집을 강제로 하려면 이 매개변수를 "true"로 설정합니다. 기본값은 'false'입니다.

|===


== 참고

펌웨어 버전 7.86부터 파일 이름 확장자는 Windows를 실행하는 시스템에서 .7z여야 합니다. Windows 시스템에서 7.86 이전 버전의 펌웨어를 실행하는 경우 파일 확장자는 '.zip'이어야 합니다. Windows를 실행하지 않는 시스템에서는 시스템에 맞는 모든 파일 확장명을 사용할 수 있습니다.



== 최소 펌웨어 레벨입니다

7.80은 하중 파라미터를 추가합니다.

8.30은 E2800 스토리지 어레이에 대한 정보를 추가합니다.
