---
permalink: commands-a-z/save-ioclog.html 
sidebar: sidebar 
keywords: save, input, output, controller, ioc, dump 
summary: save IOCLog 명령은 스토리지 배열의 컨트롤러에서 호스트의 파일로 IOC 덤프를 저장합니다. 
---
= 입력 출력 컨트롤러(IOC) 덤프를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'IOCLog 저장' 명령은 IOC 덤프를 스토리지 배열의 컨트롤러에서 호스트의 파일로 저장합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
save IOCLog [file=pass:quotes["_filename_"]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
IOC 덤프를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

[listing]
----
file="C:\Array Backups\IOCcoredump1.7z"
----
이 명령은 데이터를 압축된 파일에 저장하고 파일 확장자 .7z를 저장된 파일에 추가합니다. 스토리지 시스템의 컨트롤러에 대한 IOC 관련 데이터가 포함된 파일의 기본 이름은 스토리지 어레이의 WWN을 사용합니다.

|===


== 참고

이 명령은 두 컨트롤러 모두에서 IOC 덤프 로그 데이터와 IOC 덤프 메타데이터를 검색합니다. 7zip 파일 형식을 사용하면 검색된 데이터가 보관되어 선택한 파일 이름으로 단일 파일로 압축됩니다. 7zip 아카이브 파일에는 다음 항목이 포함되어 있습니다.

* 파일 이름 + "IOCLog" + [A|B].gz -- 컨트롤러 A 또는 컨트롤러 B에서 검색된 IOC 로그(사용 가능한 경우
* 파일 이름 + "IOCLogInfo" + [A|B].txt -- IOC는 컨트롤러 A 또는 컨트롤러 B에서 검색된 메타데이터 정보를 기록합니다. IOC 로그 데이터를 컨트롤러에서 검색할 수 없는 경우 metadata.txt 파일에 오류 조건 및 이유가 포함됩니다.


다음은 오류 조건입니다.

* 컨트롤러 플랫폼 및 HIC는 IOC 덤프를 지원하지 않습니다.
* 컨트롤러가 IOC 덤프 데이터를 수집하지 않았습니다.


압축된 로그는 사람이 읽을 수 있는 형식이 아닙니다. 평가를 위해 기술 지원 부서에 로그를 반환해야 합니다.



== 최소 펌웨어 레벨입니다

8.20
