---
permalink: commands-a-z/save-storagearray-dbmvalidatorinfo.html 
sidebar: sidebar 
keywords: save, storage, array, dbm, validator, information, file 
summary: 'save storageArray dbmValidatorInfo 명령은 XML 파일의 스토리지 배열에 대한 데이터베이스 관리(dBm) 유효성 검사 정보를 저장합니다.' 
---
= 스토리지 어레이 DBM 검증기 정보 파일 저장 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Save storageArray dbmValidatorInfo' 명령은 스토리지 배열의 데이터베이스 관리(dBm) 유효성 검사 정보를 XML 파일에 저장합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

기술 지원 부서에서는 이 XML 파일을 사용하여 유효성 검사기 문자열(보안 코드)을 생성할 수 있습니다. 스토리지 배열을 기존 구성으로 복원할 때 유효성 검사기 문자열은 "load storageArray dbmDatabase" 명령에 포함되어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
save storageArray dbmValidatorInfo file=pass:quotes["_filename_"] dbmDatabase=pass:quotes["_filename_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
기술 지원에 필요한 dBm 검증기의 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

``file="C:\Array backups\DBMvalidator.xml"' 이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 .xml 파일 확장명을 지정해야 합니다.



 a| 
DbmDatabase
 a| 
XML 정보 파일을 생성하려는 DBM 데이터베이스의 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

dbmDatabase="C:\Array backups\DBMbackup_03302010.dBm" 이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 .dbm 파일 확장명을 지정해야 합니다.

|===


== 참고

유효성 검사기 문자열을 얻기 위해 XML 정보 파일을 생성하는 경우 데이터베이스를 복원하려는 컨트롤러에 연결되어 있는 동안 이 명령을 실행해야 합니다. 다음 예제에서는 XML 파일의 형식을 보여 줍니다.

[listing]
----
<?xml version="1.0" encoding="utf-8"?>
<DbmImageMetadata>
<Controllers>
<A>1IT0nnnnnnnnnABCD</A>
<B>1T0nnnnnnnnnABCD</B>
</Controllers>
<Header>
<ImageVersion>1</ImageVersion>
<TimeStamp>1269388283</TimeStamp>
</Header>
<Trailer>
<CRC>nnnnnnnnnn</CRC><
/Trailer>
</DbmImageMetadata>
----


== 최소 펌웨어 레벨입니다

7.75
