---
permalink: commands-a-z/save-storage-array-diagnostic-data.html 
sidebar: sidebar 
keywords: save, storage, array, diagnostic, data 
summary: 'save storageArray diagnosticData 명령은 컨트롤러 또는 환경 서비스 모듈(ESM)의 스토리지 어레이 진단 데이터를 파일에 저장합니다.' 
---
= 스토리지 배열 진단 데이터를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'storageArray diagnosticData' 명령은 컨트롤러 또는 환경 서비스 모듈(ESM)의 스토리지 배열 진단 데이터를 파일에 저장합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

나중에 파일 내용을 검토할 수 있습니다. 또한 기술 지원 부서에 파일을 보내 추가 검토를 수행할 수도 있습니다.

진단 데이터를 저장한 후 이전 데이터를 덮어쓸 수 있도록 진단 데이터가 포함된 NVSRAM 레지스터를 재설정할 수 있습니다. 진단 데이터 레지스터를 재설정하려면 reset storageArray diagnosticData' 명령을 사용합니다.

[NOTE]
====
이 명령은 기술 지원 부서의 도움을 받아야 합니다.

====


== 구문

[source, cli, subs="+macros"]
----
save storageArray diagnosticData [(controller | tray)]
file=pass:quotes["_filename_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
진단 데이터
 a| 
이 매개 변수를 사용하면 컨트롤러 또는 ESM에서 진단 데이터를 다운로드할 수 있습니다.



 a| 
'파일'
 a| 
스토리지 배열 진단 데이터를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\sadiag.zip"

이 명령은 압축된 파일에 데이터를 자동으로 저장하지만 이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 '.zip' 확장자를 지정해야 합니다.

|===


== 참고

7.77 이전 버전에서는 사용자 옵션이 트레이 대신 ESM으로 되어 이었습니다. 7.77년부터 트레이는 ESM을 대체합니다. ESM의 사용은 여전히 지원되지만 향후 릴리스와 가장 잘 호환되도록 ESM을 트레이(tray)로 대체한다.



== 최소 펌웨어 레벨입니다

6.16

7.77 트레이는 ESM을 대체합니다.
