---
permalink: commands-a-z/save-storagearray-arvmstats-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: save, asynchronous, mirror, group, statistics 
summary: save storageArray arvmStats asyncMirrorGroup 명령은 비동기 미러 그룹에 있는 하나 이상의 멤버 볼륨에 대한 동기화 통계를 파일에 저장합니다. 
---
= 비동기식 미러 그룹 통계를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Save storageArray arvmStats asyncMirrorGroup' 명령어는 동기화 통계를 비동기 미러 그룹의 하나 이상의 멤버 볼륨에 대한 파일에 저장한다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800 및 E5700 어레이를 포함한 개별 스토리지 어레이에 적용됩니다. 모든 SMcli 패키지가 설치된 경우



== 역할

E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

수집된 통계는 로컬 스토리지 시스템의 기본 역할에 있는 비동기식 미러 그룹 구성원 볼륨에 대해서만 사용할 수 있습니다.

동기화 프로세스 중에 미러 구성이 얼마나 잘 작동하는지 평가하는 데 사용할 수 있는 데이터 세트가 수집됩니다. 데이터는 _ samples _ 세트로 수집됩니다. 동기화 프로세스가 시작될 때 샘플이 생성되고 동기화 프로세스가 진행되는 동안 정기적으로 업데이트됩니다.

샘플은 동기화 프로세스가 완료될 때까지 또는 볼륨 소유권 전송 또는 재쓰기 오류와 같은 동기화 프로세스가 중단될 때까지 데이터를 수집합니다. 동기화 프로세스 중단이 해결되면(예: 볼륨이 대체 컨트롤러로 전송됨) 동기화 프로세스가 계속되면서 새 샘플이 생성되고 업데이트됩니다.



== 구문

[listing, subs="+macros"]
----
save storageArray arvmStats asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
arvmStats file=pass:quotes["_filename_"]
"
[volume=pass:quotes["_volumeName_"]]
[sampleType=(all | mostRecent | longestSyncTime | errors)]
[recordLimit=(1-90)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
아인치마그룹
 a| 
동기화 통계를 저장하는 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 비동기 미러 그룹 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'파일'
 a| 
동기화 통계를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\asynchdata.csv"

이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름은 사용할 수 있지만 확장명은 .csv여야 합니다.



 a| 
'볼륨'
 a| 
이 매개 변수는 선택 사항입니다. 동기화 통계를 검색할 비동기식 미러 그룹의 특정 구성원 볼륨의 이름입니다. 볼륨을 지정하지 않으면 비동기식 미러 그룹의 모든 구성원 볼륨에 대한 통계가 저장됩니다.

비동기식 미러 그룹에서 두 개 이상의 볼륨에 대한 통계가 수집되면 모든 데이터가 동일한 파일에 기록됩니다.

볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'서미타입'
 a| 
이 매개 변수는 선택 사항입니다. 'ExampleType'의 기본값은 'all'입니다.

* 모두 -- 세 가지 샘플 유형에 대한 데이터가 모두 수집되어 동일한 파일에 기록됩니다.
* '최고' -- 최근 50개의 재동기화 샘플에 대한 통계가 기록됩니다.
* longestSyncTime -- 최근 20개의 가장 긴 재동기화 샘플에 대한 통계가 수집됩니다.
* 오류 -- 최근 실패한 재동기화 샘플 20개에 대한 통계가 기록됩니다. 이러한 샘플에는 오류 코드가 포함되어 있습니다.




 a| 
재제한
 a| 
이 매개 변수는 선택 사항입니다. 레코드 제한의 기본값은 '제한 없음'입니다. 'recordLimit'는 0보다 크고 90보다 작거나 같아야 합니다.

|===


== 참고

기본 역할의 미러링된 볼륨에 대한 통계가 캡처됩니다. 수집된 통계에는 다음 데이터가 포함됩니다.

* 동기화 시작 시간입니다
* 동기화 유형(수동 또는 주기적)
* 동기화 기간
* 전송된 바이트 수입니다
* 최대 쓰기 시간(단일 쓰기의 경우)
* 최소 쓰기 시간(단일 쓰기의 경우)
* 최소 동기화 데이터 속도
* 최대 동기화 데이터 속도
* 총 쓰기 시간입니다
* 저장소 사용률(%)
* 회복 시점 기간


초기 동기화 중에는 약 15분마다 통계 샘플이 캡처됩니다.

동기화 통계는 지원 번들에 포함되어 있습니다.



== 최소 펌웨어 레벨입니다

7.84
