---
permalink: commands-a-z/save-storagearray-dbmdatabase.html 
sidebar: sidebar 
keywords: save, storage, array, dbm, database 
summary: save storageArray dbmDatabase 명령은 RAID 구성 데이터나 모든 데이터를 호스트의 파일에 백업합니다. 여러 데이터 위치 및 컨트롤러를 지정할 수 있습니다. 
---
= 스토리지 배열 DBM 데이터베이스를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'save storageArray dbmDatabase' 명령은 RAID 구성 데이터나 모든 데이터를 호스트의 파일에 백업합니다. 여러 데이터 위치 및 컨트롤러를 지정할 수 있습니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 구문

[listing]
----
save storageArray dbmDatabase
[sourceLocation=(disk | onboard)]
[controller [(a|b)]]
[contentType= all]
 file="fileName"
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'파일'
 a| 
데이터베이스를 저장할 파일 경로와 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\dbmdata.zip"

이 매개 변수는 선택적 매개 변수 다음에 마지막에 나타나야 합니다.

이 명령은 .zip 파일을 만들며 파일 확장명을 지정할 필요가 없습니다.



 a| 
'소스 위치'
 a| 
이 매개 변수는 백업 데이터베이스 정보를 가져올 위치를 지정합니다.

* "디스크"는 데이터가 드라이브의 데이터베이스에서 직접 나온다는 것을 나타냅니다
* 'Onboard'는 RPA 메모리 위치에서 데이터가 제공됨을 나타냅니다


기본 위치는 '온보드'입니다.



 a| 
컨트롤러
 a| 
'소스 위치'가 '온보드'로 설정된 경우, 데이터를 독점적으로 검색할 컨트롤러를 지정합니다. controller 매개 변수를 지정하지 않으면 두 컨트롤러 중 하나에서 데이터를 검색할 수 있습니다.

유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다



 a| 
만족형
 a| 
이 매개변수는 검색할 데이터의 콘텐츠 유형을 지정합니다.

Disk Pool 구성 데이터를 포함한 모든 데이터를 조회할 수 있도록 default로 설정되어 있다.

|===


== 참고

이 명령을 사용하여 호스트에 저장하는 데이터는 필요한 경우 컨트롤러에 복원할 수 있습니다. 그러나 호스트의 파일에서 데이터를 복원하려면 유효성 검사기가 필요합니다.



== 최소 펌웨어 레벨입니다

7.75

7.83은 다음과 같은 매개 변수를 추가합니다.

* '소스 위치'
* 컨트롤러
* 만족형

