---
permalink: commands-a-z/save-storagearray-warningevents.html 
sidebar: sidebar 
keywords: save, storage, array, events 
summary: save storageArray warningEvents 명령은 주 이벤트 로그의 이벤트를 파일에 저장합니다. 
---
= 스토리지 배열 이벤트를 저장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'save storageArray warningEvents' 명령어는 Major Event Log의 이벤트를 파일로 저장한다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 주요 이벤트 로그의 이벤트를 파일에 저장합니다. 다음 이벤트를 저장할 수 있습니다.

* * Critical events * -- 스토리지 배열에서 오류가 발생하여 즉시 처리해야 합니다. 오류를 즉시 수정하지 않으면 데이터 액세스가 손실될 수 있습니다.
* * 경고 이벤트 * -- 스토리지 배열에서 오류가 발생하여 성능이 저하되거나 다른 오류에서 복구할 수 있는 기능이 저하됩니다. 데이터에 대한 액세스가 손실되지 않았지만 다른 오류가 발생할 경우 데이터 액세스 손실을 방지하기 위해 오류를 수정해야 합니다.
* * 정보 이벤트 * -- 정상 작동에 영향을 주지 않는 스토리지 배열에서 이벤트가 발생했습니다. 이벤트는 스토리지 배열의 성능 여부를 평가하는 데 유용할 수 있는 구성 또는 기타 정보의 변경을 보고합니다.
* * 디버그 이벤트 * -- 스토리지 배열에서 발생한 이벤트로, 오류를 발생시키는 단계 또는 상태를 확인하는 데 사용할 수 있는 정보를 제공합니다. 오류 원인을 확인할 수 있도록 이 정보가 포함된 파일을 기술 지원 부서에 보낼 수 있습니다.


[NOTE]
====
일부 스토리지 어레이에서는 네 가지 유형의 이벤트를 모두 지원하지 못할 수 있습니다.

====


== 구문

[source, cli, subs="+macros"]
----
save storageArray (allEvents | criticalEvents |
warningEvents | infoEvents | debugEvents)
file=pass:quotes["_filename_"]
[count=pass:quotes[_numberOfEvents_]]
[forceSave=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
올이벤트
 a| 
모든 이벤트를 파일에 저장하는 매개 변수입니다.



 a| 
비판행사
 a| 
중요 이벤트만 파일에 저장하는 매개 변수입니다.



 a| 
'워닝이벤트'
 a| 
경고 이벤트만 파일에 저장하는 매개 변수입니다.



 a| 
인포이벤트
 a| 
정보 이벤트만 파일에 저장하는 매개 변수입니다.



 a| 
debugEvents를 선택합니다
 a| 
디버그 이벤트만 파일에 저장하는 매개 변수입니다.



 a| 
'파일'
 a| 
이벤트를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\events.txt"

주 이벤트 로그의 내용이 들어 있는 파일의 기본 이름은 major-event-log.txt입니다. 이 명령은 저장된 파일에 파일 확장명을 자동으로 추가하지 않습니다. 파일 이름을 입력할 때 파일 확장자를 지정해야 합니다.



 a| 
카운트
 a| 
파일에 저장할 이벤트 수입니다. 카운트에 값을 입력하지 않으면 지정한 이벤트 유형과 일치하는 모든 이벤트가 파일에 저장됩니다. 카운트에 대한 값을 입력하면 해당 이벤트 수(마지막으로 입력한 이벤트부터 시작)만 파일에 저장됩니다. 정수 값을 사용합니다.



 a| 
포세세이브
 a| 
보기에서 파일로 필터링된 디버그 이벤트를 강제로 저장하는 매개 변수입니다. 이벤트를 강제로 저장하려면 이 매개 변수를 "true"로 설정합니다. 기본값은 'false'입니다.

[NOTE]
====
이 매개 변수를 사용하면 SANtricity 이벤트 뷰어에서 필터링된 디버그 이벤트가 저장됩니다.

====
|===


== 최소 펌웨어 레벨입니다

7.77 다음 매개 변수를 추가합니다.

* '워닝이벤트'
* 인포이벤트
* debugEvents를 선택합니다
* 포세세이브

