---
permalink: commands-a-z/set-controller-dnsservers.html 
sidebar: sidebar 
keywords: set, controller, dns 
summary: 'set controller DNSServers 명령은 컨트롤러의 DNS(Domain Name System) 설정을 업데이트합니다. DNS는 컨트롤러 및 NTP(Network Time Protocol) 서버의 정규화된 도메인 이름을 확인하는 데 사용됩니다.' 
---
= 컨트롤러 DNS 설정을 지정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Set controller DNSServers 명령은 컨트롤러의 DNS(Domain Name System) 설정을 업데이트합니다. DNS는 컨트롤러 및 NTP(Network Time Protocol) 서버의 정규화된 도메인 이름을 확인하는 데 사용됩니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

시작하기 전에 다음 사항을 확인하십시오.

* DNS 서버가 구성되었습니다.
* 1차 DNS 서버에 장애가 발생할 경우 1차 DNS 서버 및 백업 DNS 서버의 주소를 알 수 있습니다. 이러한 주소는 IPv4 주소 또는 IPv6 주소일 수 있습니다.


[NOTE]
====
이 명령을 두 컨트롤러 모두에 전송해야 합니다. 이 명령은 컨트롤러에만 적용됩니다.

====
[NOTE]
====
DHCP(Dynamic Host Configuration Protocol)를 사용하여 어레이의 관리 포트를 이미 구성했고 DHCP 설정과 연결된 하나 이상의 DNS 또는 NTP 서버가 있는 경우 DNS/NTP를 수동으로 구성할 필요가 없습니다. 이 경우 스토리지는 이미 DNS/NTP 서버 주소를 자동으로 가져가야 합니다.

====


== 구문

[source, cli]
----
set controller[a] DNSServers=(auto|(Address1 [Address2]))
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'dNSServers'를 선택합니다
 a| 
이 매개변수는 컨트롤러의 DNS 서버를 구성합니다. DHCP에서 제공하는 DNS 서버를 사용하려면 auto를 지정합니다. 그렇지 않으면 하나 또는 두 개의 DNS 서버로 구성된 공백으로 구분된 목록을 사용합니다.

[NOTE]
====
스토리지의 관리 이더넷 포트는 IPv4 또는 IPv6 프로토콜을 동시에 지원할 수 있습니다. 주소는 IPv4 주소 또는 IPv6 주소일 수 있습니다. 둘 이상의 주소를 지정하는 경우 주소 유형이 일치하지 않아도 됩니다.

====
둘 이상의 주소가 지정된 경우 지정된 순서대로 사용됩니다(첫 번째는 기본, 두 번째는 백업).



 a| 
AddressX
 a| 
IPv4Address | IPv6Address 를 참조하십시오

|===


== 예

[listing]
----

set controller[a] DNSServers=auto;
set controller[a] DNSServers=(192.168.1.1);
set controller[b] DNSServers=(192.168.1.1 192.168.1.105);
set controller[b] DNSServers=(2001:0db8:85a3:0000:0000:8a2e:0370:7334 192.168.1.1)
----


== 최소 펌웨어 레벨입니다

8.25
