---
permalink: commands-a-z/set-tray-identification.html 
sidebar: sidebar 
keywords: set, tray, identification 
summary: 트레이 설정 명령은 스토리지 배열의 컨트롤러 트레이, 컨트롤러 드라이브 트레이 또는 드라이브 트레이의 트레이 ID를 설정합니다. 
---
= 용지함 ID를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'트레이 설정' 명령은 스토리지 배열의 컨트롤러 트레이, 컨트롤러 드라이브 트레이 또는 드라이브 트레이의 트레이 ID를 설정합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 컨트롤러 펌웨어를 통해 설정할 수 있는 트레이 ID가 있는 컨트롤러 트레이, 컨트롤러 드라이브 트레이 또는 드라이브 트레이에만 유효합니다. 스위치로 설정한 용지함 ID가 있는 컨트롤러 트레이, 컨트롤러 드라이브 트레이 또는 드라이브 트레이에는 이 명령을 사용할 수 없습니다.



== 구문

[listing, subs="+macros"]
----
set tray pass:quotes[["_serialNumber_"]] pass:quotes[id=_trayID_]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
트레이
 a| 
컨트롤러 트레이, 컨트롤러 드라이브 트레이 또는 트레이 ID를 설정할 드라이브 트레이의 일련 번호입니다. 일련 번호는 영숫자와 길이를 조합하여 사용할 수 있습니다. 일련 번호는 큰따옴표(" ")로 묶어야 합니다.



 a| 
"아이드"
 a| 
컨트롤러 트레이 트레이 ID, 컨트롤러 드라이브 트레이 ID 또는 드라이브 트레이 트레이 ID의 값입니다. 트레이 ID 값은 0부터 9까지, 10에서 99까지.

[NOTE]
====
DE5600, DE1600 및 DE6600 엔클로저의 경우 일련 번호 앞에 텍스트 문자열 "SN" 및 공간이 있어야 합니다. 예: SN SV23802522.

====
[NOTE]
====
트레이 ID 값은 괄호로 묶지 않아도 됩니다.

====
[NOTE]
====
00 에서 09 사이의 트레이 값은 컨트롤러에 의해 거부됩니다. 0부터 9까지 값을 지정합니다.

====
|===


== 참고

이 명령은 원래 CE6998 컨트롤러 트레이를 지원했습니다 CE6998 시리즈 컨트롤러 트레이는 스위치에 의해 트레이 ID가 설정된 트레이를 포함하여 다양한 드라이브 트레이에 연결할 수 있습니다. 스위치로 트레이 ID를 설정한 드라이브 트레이에 CE6998 시리즈 컨트롤러 트레이를 연결할 때 컨트롤러 트레이의 트레이 ID 값은 80에서 99까지입니다. 이 범위는 연결된 드라이브 트레이에 사용되는 용지함 ID와 충돌을 방지합니다.
