---
permalink: commands-a-z/set-storagearray-traypositions.html 
sidebar: sidebar 
keywords: set, storage, array, tray, positions 
summary: set storageArray trayPositionions 명령은 스토리지 배열에서 트레이의 위치를 정의합니다. 이 명령을 입력할 때 스토리지 어레이에 모든 트레이를 포함해야 합니다. 
---
= 스토리지 배열 트레이 위치를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'et storageArray traPositionions' 명령어는 스토리지 배열에서 트레이의 위치를 정의합니다. 이 명령을 입력할 때 스토리지 어레이에 모든 트레이를 포함해야 합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
set storageArray trayPositions=pass:quotes[(controller | _trayID_ ... _trayIDn_)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'묘사를'
 a| 
모든 용지함 ID의 목록입니다. 목록의 트레이 ID 순서는 컨트롤러 트레이 및 스토리지 배열의 드라이브 트레이 위치를 정의합니다. 유효한 값은 0에서 99까지입니다. 공백으로 구분된 용지함 ID 값을 입력하십시오. 트레이 ID 값 목록을 괄호로 묶습니다. 컨트롤러 트레이에 유효한 트레이 위치 값 범위에 없는 미리 정의된 식별자가 있는 스토리지 배열의 경우 "컨트롤러" 값을 사용합니다.

|===


== 참고

이 명령어는 스토리지 배열의 트레이 위치를 "트레이 위치" 목록에서 트레이 ID의 위치에 따라 정의합니다. 예를 들어, ID가 84로 설정된 컨트롤러 트레이 및 ID가 1, 12로 설정된 드라이브 트레이가 있는 경우, 그리고 50의 "트레이포지션" 시퀀스("84 1 12 50")는 컨트롤러 트레이를 첫 번째 위치에 배치하고, 드라이브 트레이 1을 두 번째 위치에 배치하고, 드라이브 트레이 12를 세 번째 위치에 배치하고, 드라이브 트레이 50을 네 번째 위치에 배치합니다. 트레이 위치 순서('1 84 50 12')는 컨트롤러 트레이를 두 번째 위치에 배치하고, 드라이브 트레이 1을 첫 번째 위치에 배치하고, 드라이브 트레이 50을 세 번째 위치에 배치하고, 드라이브 트레이 12를 네 번째 위치에 배치합니다.

[NOTE]
====
"트레이" 매개 변수에 의해 정의된 목록에 스토리지 배열의 모든 트레이를 포함해야 합니다. 목록의 트레이 수가 스토리지 배열의 총 트레이 수와 일치하지 않으면 오류 메시지가 나타납니다.

====
[NOTE]
====
관리 소프트웨어는 맨 위에 첫 번째 위치가 표시되고 다른 위치는 맨 아래에 마지막 위치가 있는 상대적 순서로 표시됩니다.

====


== 최소 펌웨어 레벨입니다

6.10

6.14, 6.16의 경우 컨트롤러 값이 유효하지 않습니다.
