---
permalink: commands-a-z/set-consistency-group-attributes.html 
sidebar: sidebar 
keywords: set, consistency, group, attributes 
summary: set consistencyGroup 명령은 스냅샷 정합성 보장 그룹의 속성을 정의합니다. 
---
= 정합성 보장 그룹 특성을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Set ConsistencyGroup' 명령은 스냅샷 정합성 보장 그룹의 속성을 정의합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
set consistencyGroup pass:quotes[["_consistencyGroupName_"]]
[userLabel=pass:quotes["_consistencyGroupName_"]]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
일관성 그룹 이름
 a| 
속성을 설정할 일관성 그룹의 이름입니다. 일관성 그룹 이름은 큰따옴표(" ")로 대괄호([ ]) 안에 묶어야 합니다.



 a| 
'사용자 레이블'
 a| 
스냅샷 정합성 보장 그룹에 지정할 새 이름입니다. 새 정합성 보장 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
재규리풀정책
 a| 
스냅샷 저장소 볼륨이 꽉 찬 경우 스냅샷 처리를 계속할 방법을 지정합니다. 기본 볼륨('failBaseWrites')에 대한 쓰기를 실패하거나 스냅샷 이미지('purgeSnapImages')를 삭제(삭제)할 수 있습니다. 기본 동작은 "purgeSnapImages"입니다.



 a| 
재허용 FullLimit
 a| 
스냅샷 저장소 볼륨이 거의 꽉 찼다는 경고가 표시되는 저장소 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 기본값은 75입니다.



 a| 
자동 삭제 제한
 a| 
각 정합성 보장 그룹은 스냅샷 이미지의 자동 삭제를 수행하여 스냅샷 그룹의 총 스냅샷 이미지 수를 지정된 수준 이하로 유지하도록 구성할 수 있습니다. 이 옵션을 설정하면 스냅샷 그룹에 새 스냅샷 이미지가 생성될 때마다 시스템에서 제한 값에 따라 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 삭제합니다. 이렇게 하면 저장소 용량이 확보되므로 나머지 스냅샷 이미지에 대한 지속적인 쓰기 시 복사 요구 사항을 충족하는 데 사용할 수 있습니다.



 a| 
롤백우선
 a| 
스토리지 배열이 작동하는 동안 정합성 보장 그룹에 대한 롤백 작업의 우선 순위입니다. 유효한 값은 '가장 높음', '높음', '중간', '낮음' 또는 '가장 낮음'입니다.

|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

이 명령을 사용할 때 하나 이상의 매개 변수를 지정할 수 있습니다. 그러나 모든 매개 변수를 사용할 필요는 없습니다.

롤백 우선 순위는 시스템 성능을 희생하여 롤백 작업에 할당해야 하는 시스템 리소스의 양을 정의합니다. "높음"은 롤백 작업이 다른 모든 호스트 입출력에 우선함을 나타냅니다 "low" 값은 롤백 작업이 호스트 입출력에 미치는 영향을 최소화하면서 수행되어야 함을 나타냅니다



== 자동 삭제

각 스냅샷 그룹을 구성하여 스냅샷 이미지의 자동 삭제를 수행하여 스냅샷 그룹의 총 스냅샷 이미지 수를 최대 이미지 수 이하로 유지할 수 있습니다. 스냅샷 그룹의 스냅샷 이미지 수가 최대 제한에 도달했을 때 스냅샷 그룹에 새 스냅샷 이미지가 생성될 때마다 "autoDeleteLimit" 매개 변수는 스냅샷 이미지를 자동으로 삭제합니다. "autoDeleteLimit" 매개 변수는 매개 변수로 정의된 최대 이미지 수가 충족될 때까지 스냅샷 그룹에서 가장 오래된 스냅샷 이미지를 삭제합니다. 이렇게 하면 스냅샷 이미지를 삭제하여 저장소 용량을 확보함으로써 나머지 스냅샷 이미지에 대한 지속적인 쓰기 시 복사 요구 사항을 충족할 수 있습니다.



== 최소 펌웨어 레벨입니다

7.83
