---
permalink: commands-a-z/set-snmpuser-username.html 
sidebar: sidebar 
keywords: update, snmpv3, usm, user 
summary: 'set snmpUser username 명령은 기존의 SNMP(Simple Network Management Protocol) USM 사용자를 업데이트합니다. 변경할 USM 사용자는 사용자 이름을 가진 사용자가 한 명뿐인 경우 사용자 이름을 사용하여 식별됩니다. 동일한 사용자 이름과 다른 엔진 ID를 가진 사용자가 두 명 이상인 경우 사용자 이름과 엔진 ID를 사용하여 사용자를 식별합니다.' 
---
= SNMPv3 USM 사용자를 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set snmpUser username 명령은 기존 SNMP(Simple Network Management Protocol) USM 사용자를 업데이트합니다. 변경할 USM 사용자는 사용자 이름을 가진 사용자가 한 명뿐인 경우 사용자 이름을 사용하여 식별됩니다. 동일한 사용자 이름과 다른 엔진 ID를 가진 사용자가 두 명 이상인 경우 사용자 이름과 엔진 ID를 사용하여 사용자를 식별합니다.



== 지원되는 어레이

이 명령은 개별 E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에 적용됩니다. E2700 또는 E5600 스토리지 어레이에서는 작동하지 않습니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 구문

[source, cli]
----
set snmpUser userName="snmpUserName" [engineId=(local | engineId)]
[newUserName="newSnmpUserName"] [newEngineId=(local | engineId)]
[authProtocol=(none | sha | sha256 | sha512) authPassword="authPassword"]
[privProtocol=(none | aes128) privPassword="privPassword"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'사용자 이름'
 a| 
업데이트할 SNMP USM 사용자의 이름입니다. SNMP USM 사용자 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
엔진 ID
 a| 
업데이트할 SNMP USM 사용자의 엔진 ID입니다. 동일한 사용자 이름을 가진 USM 사용자가 두 명 이상인 경우 엔진 ID가 필요합니다. 로컬 SNMP 에이전트가 신뢰할 수 있는 에이전트이거나 원격 SNMP 에이전트 엔진 ID를 지정하는 16진수 문자열인 "local" 값을 지정할 수 있습니다.



 a| 
newSnmpUserName입니다
 a| 
SNMP 사용자에게 부여할 새 이름입니다. SNMP 사용자 이름은 큰따옴표(" ")로 묶어야 합니다. 기본값은 이전에 정의된 사용자 이름입니다.



 a| 
newEngineId
 a| 
사용자의 권한 있는 SNMP 엔진 ID의 식별자로 사용할 새 엔진 ID입니다. 값은 "[.code] local"일 수 있습니다. 로컬 SNMP 에이전트를 권한 있는 에이전트로 지정하거나 16진수 문자열을 지정하여 원격 SNMP 에이전트 엔진 ID를 지정할 수 있습니다. 기본값은 사용자에 대해 이전에 정의된 엔진 ID입니다.



 a| 
진정한 의정입니다
 a| 
사용자에게 사용할 인증 프로토콜(HMAC). 값은 다음 중 하나일 수 있습니다.

* "없음" - SNMP 메시지 인증 없음(기본값)
* 'ha'-SHA-1 인증
* sha256-SHA-256 인증
* 'sha512'-SHA-512 인증


기본값은 사용자에 대해 이전에 정의된 인증 프로토콜입니다.



 a| 
'authPassword
 a| 
사용자의 인증에 사용할 암호입니다. 인증 프로토콜이 'ha', 'hay256', 'ha512'인 경우 반드시 지정해야 합니다



 a| 
사규약
 a| 
사용자에게 사용되는 개인 정보 보호 프로토콜(암호화) 값은 다음 중 하나일 수 있습니다.

* "없음" - SNMP 메시지 암호화 없음(기본값)
* aes128 - AES-18 암호화


기본값은 이전에 정의한 사용자에 대한 개인 정보 보호 프로토콜입니다.



 a| 
"privPassword"
 a| 
사용자의 개인 정보 보호/암호화에 사용할 암호입니다. 개인 정보 보호 프로토콜이 "[.code]"aes128""인 경우 지정해야 합니다.

|===


== 최소 펌웨어 레벨입니다

8.72
