---
permalink: commands-a-z/set-tray-drawer.html 
sidebar: sidebar 
keywords: set, drawer, service, action, allowed, indicator 
summary: 트레이 드로어 설정 명령은 드라이브를 보관하는 드로어에서 서비스 작업 허용 표시등을 켜거나 끕니다. 
---
= 문서함 서비스 조치 허용 표시기 설정
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
세트 트레이 드로어 명령은 드라이브를 보관하는 드로어에서 서비스 조치 허용 표시등을 켜거나 끕니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

서랍은 고용량 드라이브 트레이에 사용됩니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 용지함을 사용하는 드라이브 트레이에만 이 명령을 사용합니다. 스토리지 배열이 Service Action Allowed 표시등 기능을 지원하지 않는 경우 이 명령은 오류를 반환합니다. 스토리지 배열이 명령을 지원하지만 표시등을 켜거나 끌 수 없는 경우 이 명령은 오류를 반환합니다.



== 구문

[listing, subs="+macros"]
----
set tray pass:quotes[[_trayID_]] drawer pass:quotes[[_drawerID_]]
serviceAllowedIndicator=(on | off | forceOnWarning)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
트레이
 a| 
용지함이 있는 용지함입니다. 용지함 ID 값은 0 ~ 99입니다. 트레이 ID 값은 대괄호([])로 묶어야 합니다. 용지함 ID 값을 입력하지 않으면 컨트롤러 트레이의 트레이 ID가 기본값입니다.



 a| 
"와어"
 a| 
서비스 작업 허용 표시등을 켜거나 끌 문서함의 위치입니다. 문서함 ID 값은 1에서 5까지. 문서함 ID 값은 대괄호([])로 묶습니다.



 a| 
저빙AllowedIndicator를 선택합니다
 a| 
Service Action Allowed(서비스 작업 허용) 표시등을 켜거나 끄는 설정입니다. Service Action Allowed(서비스 작업 허용) 표시등을 켜려면 이 매개변수를 "On(켜짐)"으로 설정합니다. Service Action Allowed(서비스 작업 허용) 표시등을 끄려면 이 매개변수를 "off(꺼짐)"로 설정합니다.

forceOnWarning 사용에 대한 자세한 내용은 참고를 참조하십시오.

|===


== 참고

이 명령을 입력하기 전에 드라이브 트레이가 다음 조건을 충족해야 합니다.

* 드라이브 트레이가 과열될 수 없습니다.
* 팬은 Optimal(최적) 상태여야 합니다.
* 모든 드라이브 트레이 구성 요소가 제자리에 있어야 합니다.
* 드라이브 드로어의 볼륨은 성능 저하 상태일 수 없습니다. 드라이브 드로어에서 드라이브를 제거하고 볼륨이 이미 문제 발생 상태인 경우 볼륨이 실패할 수 있습니다.


[NOTE]
====
이러한 조건을 충족할 수 없는 경우 이 명령을 실행하지 마십시오.

====
명령을 전송하기 전에 영향을 받는 드라이브 드로어에 드라이브가 있는 모든 볼륨을 검사하여 볼륨에 드로어 손실 방지 기능이 있는지 확인합니다. 볼륨에 문서함 손실 보호가 있는 경우 Set Service Action allowed 명령이 볼륨에 대한 I/O 활동을 중지하지 않고 진행됩니다.

영향을 받는 드로어에 있는 볼륨에 드로어 손실 방지 기능이 없는 경우 해당 볼륨에 대한 I/O 활동을 중지해야 합니다. 이 명령을 완료할 수 없음을 나타내는 경고가 나타납니다.

전체 대용량 드라이브 트레이에 대해 Service Action Allowed 표시등을 켜거나 끄려면 'Set tray serviceAllowedIndicator' 명령을 사용합니다.



== forceOnWarning 매개 변수 사용

제거할 구성 요소를 준비하는 중에 볼륨에 문서함 손실 보호가 없다는 경고를 무시하려면 다음 매개 변수를 입력합니다.

[listing]
----
serviceAllowedIndicator=forceOnWarning
----
forceOnWarning 매개변수는 컨트롤러 펌웨어로 구성 요소 제거 준비 요청을 전송하고, 'et drawer serviceAllowedIndicator' 명령을 강제로 진행하도록 한다.

[NOTE]
====
이 매개 변수는 드로어의 모든 드라이브에 액세스할 수 없도록 표시하고 호스트를 재부팅해야 하는 경우를 비롯하여 볼륨 장애 및 복잡한 복구를 초래할 수 있습니다. 이 매개 변수는 주의하여 사용하십시오.

====


== 최소 펌웨어 레벨입니다

7.60
