---
permalink: commands-a-z/set-event-alert.html 
sidebar: sidebar 
keywords: set, event, alert, filter 
summary: set event alert 명령은 특정 alertable 이벤트와 관련된 알림을 비활성화하거나 활성화하여 경고 이벤트 알림을 관리합니다. 특정 경계 이벤트에 대한 알림을 방지하려면 해당 이벤트를 차단해야 합니다. 특정 경보 가능 이벤트에 대한 알림을 활성화하려면 차단을 해제합니다. 
---
= 이벤트 알림 필터링 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Set event alert 명령은 특정 alertable event와 관련된 notification을 비활성화하거나 활성화함으로써 alert event notification을 관리한다. 특정 alertable 이벤트에 대한 알림을 방지하려면 _block_it을 사용합니다. 특정 경보 가능 이벤트에 대한 알림을 활성화하려면 _UNBLOCK_IT를 사용합니다.



== 지원되는 어레이

이 명령은 E2700 및 E5600 스토리지 어레이에만 적용됩니다.



== 상황

[NOTE]
====
이 명령은 스크립트 명령이 아니라 SMcli 명령입니다. 명령줄에서 이 명령을 실행해야 합니다. 스토리지 관리 소프트웨어의 스크립트 편집기에서 이 명령을 실행할 수 없습니다

====


== 상황

스토리지 배열을 정의할 때 경고를 구성하고 이벤트 경고를 관리하는 방법을 정의할 수 있습니다. 경고를 보내도록 스토리지 배열을 구성한 경우, alertable 이벤트가 발생할 때 지정된 수신자에게 알림이 전송됩니다. 이 알림은 다음 유형 중 하나 또는 모두가 될 수 있습니다.

* 이메일
* Syslog를 클릭합니다
* SNMP 트랩 알림입니다


set event alert CLI 명령은 단일 스토리지 어레이에서 작동합니다. 스토리지 어레이에서 명령을 실행하면 해당 스토리지 어레이만 명령의 영향을 받습니다. CLI 명령을 실행하지 않은 다른 스토리지 어레이에는 기본 동작이 있습니다.

[NOTE]
====
이벤트 경고를 차단해도 이벤트가 시스템 이벤트 로그에 게시되는 것을 막을 수 없습니다. 모든 이벤트는 이벤트 로그에 계속 게시됩니다.

====
[NOTE]
====
이 명령을 사용하여 딜러할 수 없는 이벤트를 처리할 수 없습니다.

====


== 이벤트 알림을 차단하는 구문

[source, cli, subs="+macros"]
----
set blockEventAlert pass:quotes[_eventType_]
----


== 이벤트 알림을 차단 해제하는 구문

[source, cli, subs="+macros"]
----
set unBlockEventAlert pass:quotes[_eventType_]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
`_ eventType _ '
 a| 
이 매개 변수는 이벤트의 정수 값입니다. 이벤트 값을 16진수 형식으로 입력합니다(예: 0x280D). 16진수 값이 16진수 형식임을 나타내기 위해 항상 *0x*로 16진수 값을 시작합니다. 0x 를 사용하지 않으면 이 값은 십진수로 해석되어 16진수 값으로 변환된 후 block 또는 unblock 명령을 적용합니다. 이로 인해 잘못된 이벤트가 차단되거나 차단되지 않을 수 있습니다.

잘못된 이벤트를 입력하면 오류가 표시됩니다.

|===


== 최소 펌웨어 레벨입니다

8.10
