---
permalink: commands-a-z/set-storagearray-autoloadbalancingenable.html 
sidebar: sidebar 
keywords: set, storage, array, enable, disable, automatic, load, balance 
summary: set storageArray autoLoadBalancingEnable 명령은 자동 로드 밸런싱 기능을 설정하거나 해제합니다. 
---
= 자동 로드 밸런싱을 사용하거나 사용하지 않도록 스토리지 배열을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'set storageArray autoLoadBalancingEnable' 명령은 자동 로드 밸런싱 기능을 활성화하거나 비활성화합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing]
----
set storageArray autoLoadBalancingEnable=(TRUE | FALSE)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'토르ageArray'
 a| 
이 매개 변수가 스토리지 배열에서 작동함을 나타냅니다.



 a| 
'autoLoadBalancingEnable'
 a| 
이 매개변수는 컨트롤러의 자동 로드 밸런싱을 켜거나 끕니다. 자동 로드 밸런싱을 켜려면 매개 변수를 'true'로 설정합니다. 자동 로드 밸런싱을 해제하려면 매개변수를 'false'로 설정하십시오.

|===


== 자동 로드 밸런싱이란 무엇입니까?

자동 로드 밸런싱 기능은 시간이 지남에 따라 로드 변화에 동적으로 반응하여 볼륨 컨트롤러 소유권을 자동으로 조정하여 컨트롤러 간에 워크로드가 이동할 때 발생하는 로드 불균형 문제를 해결하여 I/O 리소스 관리를 향상시킵니다.

각 컨트롤러의 워크로드는 지속적으로 모니터링되며 호스트에 설치된 다중 경로 드라이버의 협력을 통해 필요할 때마다 자동으로 균형을 맞출 수 있습니다. 컨트롤러 간에 워크로드가 자동으로 재조정되면 스토리지 관리자는 스토리지 어레이의 로드 변경을 수용하기 위해 볼륨 컨트롤러 소유권을 수동으로 조정해야 하는 부담을 덜 수 있습니다.

자동 로드 밸런싱이 활성화되면 다음 기능을 수행합니다.

* 컨트롤러 리소스 활용률을 자동으로 모니터링 및 균형 조정
* 필요한 경우 볼륨 컨트롤러 소유권을 자동으로 조정하여 호스트와 스토리지 어레이 간의 I/O 대역폭을 최적화합니다.




== 자동 로드 밸런싱 활성화 및 비활성화

자동 로드 밸런싱은 SANtricity OS(컨트롤러 소프트웨어) 8.30 이상과 함께 제공되는 모든 스토리지 어레이에서 기본적으로 활성화됩니다. Linux, Windows 및 VMware 다중 경로 드라이버는 자동 로드 밸런싱 기능을 사용할 수 있습니다. 컨트롤러를 SANtricity OS(컨트롤러 소프트웨어) 8.25 이전 버전에서 8.30 이상으로 업그레이드하는 경우 스토리지 어레이에서 자동 로드 밸런싱은 기본적으로 사용되지 않습니다.

다음과 같은 이유로 스토리지 어레이에서 자동 로드 밸런싱을 사용하지 않도록 설정할 수 있습니다.

* 워크로드의 균형을 맞추기 위해 특정 볼륨의 컨트롤러 소유권을 자동으로 변경하지 않으려는 경우
* 부하 분산이 의도적으로 설정된 고도로 조정된 환경에서 컨트롤러 간에 특정 분포를 이룰 수 있습니다.


SANtricity 저장소 관리자에서 * 스토리지 배열 * > * 구성 * > * 자동 로드 밸런싱 * 메뉴 옵션을 선택하여 개별 저장소 배열에 대한 자동 로드 밸런싱 기능을 활성화하거나 비활성화합니다.

SANtricity 시스템 관리자에서 * 설정 * > * 시스템 * 을 선택하고 * 추가 설정 * 섹션으로 스크롤한 다음 E** 가능/자동 로드 밸런싱 비활성화** 링크를 클릭하고 ** 자동 로드 밸런싱 활성화/비활성화** 확인란을 선택하여 개별 스토리지 어레이에 대한 기능을 활성화하거나 비활성화합니다.



== 예

[listing]
----
SMcli -n Array1 -c "set storageArray autoLoadBalancingEnable=true;"

SMcli completed successfully.
----
[NOTE]
====
활성 "드라이브 손실 기본 경로" 조건이 되면 자동 로드 밸런싱이 작업 부하의 균형을 맞출 수 없게 됩니다. 이 조건은 자동 로드 밸런싱 기능을 통해 워크로드가 균형 조정되도록 하기 위해 비활성 상태여야 합니다.

====


== 최소 펌웨어 레벨입니다

8.30
