---
permalink: commands-a-z/set-iscsiinitiator.html 
sidebar: sidebar 
keywords: set, iscsi, initiator 
summary: set iscsiInitiator 명령은 iSCSI 이니시에이터에 대한 속성을 설정합니다. 
---
= iSCSI 이니시에이터를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
iscsiInitiator 설정 명령은 iSCSI 초기자에 대한 속성을 설정합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.

[NOTE]
====
이 명령은 더 이상 사용되지 않으며 로 대체됩니다 xref:set-initiator.adoc[초기자를 설정합니다] 명령.

====


== 구문

[listing, subs="+macros"]
----
set iscsiInitiator (pass:quotes[["_initiatorUserLabel_"]] | <"_iscsiInitiatorName_">)
(userLabel=pass:quotes["_newName_"] |
host=pass:quotes["_newHostName_"] |
chapSecret=pass:quotes["_newSecurityKey_"])
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
이니셜사용자레이블
 a| 
속성을 설정할 iSCSI 이니시에이터의 iSCSI 이니시에이터 사용자 레이블입니다. iSCSI 이니시에이터 사용자 레이블은 대괄호([ ]) 안에 큰따옴표(" ")로 묶어야 합니다.

[NOTE]
====
이니시에이터 사용자 레이블을 호스트 포트가 연결되는 호스트 이름으로 시작합니다. 호스트에 둘 이상의 호스트 포트 식별자가 있을 수 있으므로 호스트 포트 ID에 고유한 접미사를 사용합니다. 호스트 이름이 ICTM1590S02H1인 경우 이니시에이터 레이블은 다음과 같이 표시됩니다.

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
iscsiInitialatorName입니다
 a| 
특성을 설정할 이니시에이터의 이름입니다. "iscsiInitialatorName"은 큰따옴표("")로 꺽쇠 괄호(<>)로 묶습니다.

[NOTE]
====
iscsiInitialatorName은 iqn(iSCSI Qualified Name)입니다. 예를 들면 다음과 같습니다.

====
[listing]
----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----


 a| 
'사용자 레이블'
 a| 
iSCSI 이니시에이터에 사용할 새 사용자 레이블입니다. 새 사용자 레이블은 큰따옴표(" ")로 묶어야 합니다.

[NOTE]
====
모범 사례는 호스트 포트가 연결되는 호스트 이름으로 이니시에이터 사용자 레이블을 시작하는 것입니다. 호스트에 둘 이상의 호스트 포트 식별자가 있을 수 있으므로 호스트 포트 ID에 고유한 접미사를 사용합니다. 호스트 이름이 "ICTM1590S02H1"인 경우 이니시에이터 사용자 레이블의 예가 아래에 표시됩니다.

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
호스트
 a| 
호스트 포트가 접속된 새 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다. 예는 다음과 같습니다.

[listing]
----
["ICTM1590S02H2"]
----


 a| 
'챕시크릿
 a| 
피어 연결을 인증하는 데 사용할 보안 키입니다. 보안 키는 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

CHAP(Challenge Handshake Authentication Protocol)는 연결의 피어를 인증하는 프로토콜입니다. CHAP는 a_secret_을 공유하는 피어를 기반으로 합니다. 비밀은 비밀번호와 유사한 보안 키입니다.

chapSecret 매개 변수를 사용하여 상호 인증이 필요한 초기자의 보안 키를 설정합니다. CHAP 암호는 12자에서 57자 사이여야 합니다. 이 표에는 유효한 문자가 나열되어 있습니다.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
공간
 a| 
!
 a| 
"
 a| 
번호
 a| 
$
 a| 
%
 a| 
및
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
를 누릅니다
 a| 
=
 a| 
를 누릅니다
 a| 
?
 a| 
@
 a| 
A
 a| 
B
 a| 
c



 a| 
D
 a| 
e
 a| 
F
 a| 
g
 a| 
h
 a| 
나는
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
해당 없음
 a| 
o



 a| 
P
 a| 
Q
 a| 
R
 a| 
s.(초
 a| 
T
 a| 
U
 a| 
V
 a| 
w
 a| 
X
 a| 
예
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
A
 a| 
B
 a| 
c
 a| 
D
 a| 
e
 a| 
F
 a| 
g



 a| 
h
 a| 
나는
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
해당 없음
 a| 
o
 a| 
P
 a| 
Q
 a| 
R
 a| 
s.(초



 a| 
T
 a| 
U
 a| 
V
 a| 
w
 a| 
X
 a| 
예
 a| 
Z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== 최소 펌웨어 레벨입니다

7.10

8.41 이 명령은 사용되지 않습니다.
