---
permalink: commands-a-z/set-storagearray-directoryserver-roles.html 
sidebar: sidebar 
keywords: set, storage, array, directory, server, role, map 
summary: set storageArray DirectoryServer roles 명령을 사용하면 지정된 디렉터리 서버에 대한 역할 매핑을 정의할 수 있습니다. 이러한 역할 매핑은 다양한 SMcli 명령을 실행하는 사용자를 인증하는 데 사용됩니다. 
---
= 스토리지 배열 디렉토리 서버 역할 매핑을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Set storageArray DirectoryServer roles' 명령을 사용하면 지정된 디렉터리 서버에 대한 역할 매핑을 정의할 수 있습니다. 이러한 역할 매핑은 다양한 SMcli 명령을 실행하는 사용자를 인증하는 데 사용됩니다.



== 지원되는 어레이

이 명령은 개별 E2800, E5700, EF600 또는 EF300 스토리지 어레이에 적용됩니다. E2700 또는 E5600 스토리지 어레이에서는 작동하지 않습니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 필요한 것

매핑할 수 있는 역할은 다음과 같습니다.

* * 스토리지 관리자 * -- 스토리지 객체(예: 볼륨 및 디스크 풀)에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
* * 보안 관리자 * -- 액세스 관리, 인증서 관리, 감사 로그 관리 및 레거시 관리 인터페이스(기호)를 켜거나 끌 수 있는 기능의 보안 구성에 액세스합니다.
* * 지원 관리자 * -- 스토리지 어레이의 모든 하드웨어 리소스, 장애 데이터, MEL 이벤트 및 컨트롤러 펌웨어 업그레이드에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
* * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.




== 구문

[listing, subs="+macros"]
----

set storageArray directoryServer pass:quotes[["_domainId_"]]
    groupDN=pass:quotes["_groupDistinguishedName_"] roles=pass:quotes[("_role1_"..."_roleN_")]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
디르토리서버다
 a| 
역할 매핑을 설정할 ID로 도메인을 지정할 수 있습니다.



 a| 
그룹DN
 a| 
매핑 목록에 추가할 그룹의 고유 이름(DN)을 지정할 수 있습니다.



 a| 
역할
 a| 
정의된 그룹에서 사용자에 대해 하나 이상의 역할을 지정할 수 있습니다. 둘 이상의 역할을 입력하는 경우 값을 공백으로 구분합니다. 유효한 선택 항목은 다음과 같습니다.

* "모니터 보관.
* 'storage.admin'
* '보안.관리'
* 'upport.admin'입니다


|===


== 예

[listing]
----

SMcli -n Array1 -c "set storageArray directoryServer ["domain1"]
                    groupDN="CN=ng-hsg-bc-madridsecurity,OU=Managed,
                    OU=MyCompanyGroups,DC=hq,DC=mycompany,DC=com"
                    roles=("storage.monitor" "security.admin" "storage.admin");"

SMcli -n Array1 -c "set storageArray directoryServer ["domain1"]
                    groupDN="CN=ng-epg-engr-manageability,OU=Managed,
                    OU=MyCompanyGroups,DC=hq,DC=mycompany,DC=com"
                    roles=("support.admin");"

SMcli completed successfully.
----