---
permalink: commands-a-z/set-storagearray-odxenabled.html 
sidebar: sidebar 
keywords: enable, disable, odx 
summary: 'set storageArray odxEnabled 명령은 스토리지 어레이에 대한 ODX(Offloaded Data Transfer)를 설정하거나 해제합니다.' 
---
= ODX 활성화 또는 비활성화 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'set storageArray odxEnabled' 명령은 스토리지 어레이에 대한 ODX(Offloaded Data Transfer)를 설정하거나 해제합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 한 E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 및 EF80 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600, EF300, EF50 또는 EF80 스토리지 어레이에서 이 명령을 실행하려면 Storage Admin 또는 Support Admin 역할이 있어야 합니다.



== 상황

스토리지 어레이에 ODX를 사용하도록 설정한 상태로 제공됩니다. ODX를 실행하지 않거나 ODX로 인해 스토리지 어레이에 문제가 발생하는 경우 이 명령을 사용하여 ODX를 해제합니다. 영향을 받는 유일한 스토리지 어레이는 명령이 실행되는 스토리지 배열입니다.



== 구문

[source, cli]
----
set storageArray odxEnabled=(TRUE | FALSE)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'odxEnabled'
 a| 
ODX를 설정하거나 해제하는 설정입니다. ODX를 켜려면 이 매개 변수를 'true'로 설정합니다. ODX를 끄려면 이 매개변수를 'false'로 설정합니다. 기본 설정은 ODX가 켜져 있는 것입니다.

|===


== 참고

ODX는 버퍼링된 읽기 및 쓰기 작업을 사용하지 않고 데이터를 전송하는 방법을 제공하며, 데이터 전송 작업에 호스트가 직접 개입할 필요가 없습니다. ODX가 활성화되지 않은 경우, 데이터는 소스 스토리지에서 호스트로 읽어온 다음 호스트에서 대상 스토리지로 기록됩니다. ODX가 활성화되면 데이터 전송 작업은 스토리지 인프라에 의해 직접 관리됩니다. 데이터는 호스트를 거치지 않고 동일한 어레이 내에서 소스 스토리지에서 대상 스토리지로 직접 이동됩니다.



== 최소 펌웨어 레벨입니다

8.20
