---
permalink: commands-a-z/set-isertarget.html 
sidebar: sidebar 
keywords: set, iser, target 
summary: iserTarget 설정 명령은 iSER 타겟의 속성을 정의합니다. 
---
= iSER 대상을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Set iserTarget' 명령어는 iSER Target의 속성을 정의한다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.

[NOTE]
====
이 명령은 더 이상 사용되지 않으며 로 대체됩니다 xref:set-target.adoc[대상 속성을 설정합니다] 명령.

====


== 구문

[source, cli, subs="+macros"]
----
set iserTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'iserTarget'
 a| 
속성을 설정할 iSER 대상. '_userLabel_'은 큰따옴표(")로 묶습니다. 사용자 레이블이 IQN(iSCSI Qualified Name)인 경우 사용자 레이블이 대상 별칭 또는 꺾쇠 괄호(<>)인 경우에는 '_userLabel_'도 대괄호([])로 묶어야 합니다.



 a| 
인증 방법
 a| 
iSCSI 세션을 인증하는 방법입니다.



 a| 
'챕시크릿
 a| 
피어 연결을 인증하는 데 사용할 보안 키입니다.



 a| 
'targetAlias'
 a| 
대상에 사용할 새 이름입니다. 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

CHAP(Challenge Handshake Authentication Protocol)는 연결의 피어를 인증하는 프로토콜입니다. CHAP는 a_secret_을 공유하는 피어를 기반으로 합니다. 비밀은 비밀번호와 유사한 보안 키입니다.

chapSecret 매개 변수를 사용하여 상호 인증이 필요한 초기자의 보안 키를 설정합니다. CHAP 암호는 12자에서 57자 사이여야 합니다. 이 표에는 유효한 문자가 나열되어 있습니다.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
공간
 a| 
!
 a| 
"
 a| 
번호
 a| 
$
 a| 
%
 a| 
및
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
를 누릅니다
 a| 
=
 a| 
를 누릅니다
 a| 
?
 a| 
@
 a| 
A
 a| 
B
 a| 
c



 a| 
D
 a| 
e
 a| 
F
 a| 
g
 a| 
h
 a| 
나는
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
해당 없음
 a| 
o



 a| 
P
 a| 
Q
 a| 
R
 a| 
s.(초
 a| 
T
 a| 
U
 a| 
V
 a| 
w
 a| 
X
 a| 
예
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
A
 a| 
B
 a| 
c
 a| 
D
 a| 
e
 a| 
F
 a| 
g



 a| 
h
 a| 
나는
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
해당 없음
 a| 
o
 a| 
P
 a| 
Q
 a| 
R
 a| 
s.(초



 a| 
T
 a| 
U
 a| 
V
 a| 
w
 a| 
X
 a| 
예
 a| 
Z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== 최소 펌웨어 레벨입니다

8.20

8.41 이 명령은 사용되지 않습니다.
