---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: set storageArray controllerHealthImageAllowOverWrite 명령은 컨트롤러의 상태 이미지 기능을 지원하는 스토리지 배열의 기존 컨트롤러 상태 이미지를 새 컨트롤러 상태 이미지로 덮어쓸 수 있도록 컨트롤러에 플래그를 설정합니다. 
---
= 스토리지 어레이 컨트롤러 상태 이미지의 덮어쓰기 허용 설정을 지정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'set storageArray controllerHealthImageAllowOverWrite' 명령은 컨트롤러의 상태 이미지를 새 컨트롤러 상태 이미지로 덮어써서 컨트롤러 상태 이미지 기능을 지원하는 스토리지 어레이의 기존 컨트롤러 상태 이미지를 덮어쓸 수 있도록 컨트롤러에 플래그를 설정합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

스토리지 어레이에서 컨트롤러 상태 이미지 기능을 지원하지 않으면 명령을 실행하면 오류가 반환됩니다.

[NOTE]
====
펌웨어 버전 8.20에서는 coreDumpAllowOverWrite 매개 변수가 controllerHealthImageAllowOverWrite 매개 변수로 대체됩니다.

====


== 구문

[listing]
----
set storageArray controllerHealthImageAllowOverWrite
----


== 매개 변수

없음.



== 참고

컨트롤러 상태 이미지가 검색되면 덮어쓰기 허용 플래그가 설정됩니다. 컨트롤러 상태 이미지가 검색되지 않으면 48시간 후 덮어쓰기 허용 플래그가 설정된 상태로 만료됩니다. Set storageArray controllerHealthImageAllowOverWrite 명령을 사용하여 "allow overwrite" 플래그를 설정하면 이미지가 검색되는 것처럼 48시간 만료가 면제됩니다.



== 최소 펌웨어 레벨입니다

7.86

8.20은 '* coreDumpAllowOverWrite*' 매개 변수를 controllerHealthImageAllowOverWrite" 매개 변수로 대체합니다.
