---
permalink: commands-a-z/set-disk-pool-modify-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool, modify 
summary: 'set diskpool 명령은 디스크 풀(동적 용량 확장 또는 DCE)에 용량을 추가하거나 전체 디스크 풀의 컨트롤러 소유권을 변경합니다.' 
---
= 디스크 풀 설정(디스크 풀 수정) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'디스크 풀 설정' 명령은 디스크 풀(동적 용량 확장 또는 DCE)에 용량을 추가하거나 전체 디스크 풀의 컨트롤러 소유권을 변경합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 두 작업은 상호 배타적입니다.



== 구문

[source, cli, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
(addDrives=pass:quotes[[_trayID1_,_drawerID1_,_slotID1_ ... _trayIDn_,_drawerIDn_,_slotIDn_]] |
addCapacity=pass:quotes[(_diskPoolCapacity_))]
[owner=(a| b)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
디즈크풀
 a| 
수정할 디스크 풀의 이름입니다. 디스크 풀 이름은 대괄호([ ])로 묶어야 합니다. 디스크 풀 이름에 특수 문자가 있거나 숫자로만 구성된 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'addDrives'입니다
 a| 
디스크 풀에 추가할 드라이브입니다. 고용량 드라이브 트레이의 경우, 추가할 드라이브의 트레이 ID 값, 서랍 ID 값 및 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우 추가할 드라이브의 트레이 ID 값과 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지. 슬롯 ID 값은 1에서 24까지 입니다. 트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

[NOTE]
====
이 기능에는 드라이브 12개가 제한됩니다.

====


 a| 
'addCapacity'
 a| 
디스크 풀에 추가할 추가 스토리지 용량입니다. 이 매개 변수는 추가할 용량을 충족하는 드라이브를 자동으로 선택합니다. 용량은 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.



 a| 
오너
 a| 
디스크 풀을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 소유자를 지정하지 않으면 컨트롤러 펌웨어가 소유자를 결정합니다.

|===


== 참고

새 드라이브를 추가하는 동안 디스크 풀에 이미 있는 볼륨은 온라인 상태로 유지되고 입출력 작업에 사용할 수 있습니다. 용량을 추가하기 전에 디스크 풀이 완료 상태여야 합니다. 디스크 풀이 완료 상태가 아니면 새 드라이브를 추가하기 전에 'show diskpool complete' 명령을 실행합니다.

용량을 추가하려면 addDrives 매개 변수를 사용하여 개별 드라이브를 지정하거나 addCapacity 매개 변수를 사용하여 드라이브 용량을 지정합니다. addDrives를 사용하는 경우, 호스트는 작업을 실행하기 전에 드라이브 세트를 확인해야 합니다. addCapacity 매개변수를 사용하면 사용자가 지정하는 용량이 추가할 최소 용량으로 사용됩니다. 응시자가 서비스 품질에 가장 적합한 드라이브를 사용하고 지정된 용량보다 크거나 같은 용량을 사용합니다. 최소 일치 항목이 있는 후보가 없거나 지정된 드라이브 목록을 사용할 수 없거나 속성 불일치를 감지할 경우 작업이 실패합니다.

이 명령을 사용하여 스토리지 배열의 한 컨트롤러에서 다른 컨트롤러로 디스크 풀의 소유권을 변경할 수도 있습니다. 이 명령을 사용하여 소유권을 변경하면 명령을 사용하여 드라이브를 추가하거나 용량을 추가하는 것이 상호 배타적입니다.



== 최소 펌웨어 레벨입니다

7.83
