---
permalink: commands-a-z/set-storagearray-securitykey.html 
sidebar: sidebar 
keywords: set, internal, storage, array, security key 
summary: set storageArray securityKey 명령은 드라이브 보안 기능을 구현하기 위해 스토리지 배열 전체에서 사용되는 보안 키를 설정합니다. 
---
= 내부 스토리지 배열 보안 키를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'et storageArray securityKey' 명령어는 Drive Security 기능을 구현하기 위해 스토리지 배열 전체에서 사용되는 보안 키를 설정합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

스토리지 배열의 보안 가능 드라이브가 보안 볼륨 그룹 또는 디스크 풀에 할당된 경우, 해당 드라이브는 보안 키를 사용하여 보안이 설정됩니다. 보안 키를 설정하려면 먼저 "create storageArray securityKey" 명령을 사용하여 보안 키를 만들어야 합니다.

[NOTE]
====
이 명령은 내부 키 관리에만 적용됩니다.

====


== 구문

[source, cli]
----
set storageArray securityKey
----


== 매개 변수

없음.



== 참고

보안 지원 드라이브에는 암호화 처리를 가속화하는 하드웨어가 있으며, 각 드라이브에는 고유한 드라이브 키가 있습니다. 보안 가능 드라이브는 보안 볼륨 그룹에 추가될 때까지 다른 드라이브처럼 동작하며, 보안 가능 드라이브는 보안이 설정된 드라이브가 됩니다.

보안 지원 드라이브의 전원을 켤 때마다 데이터를 읽거나 쓰려면 컨트롤러에서 올바른 보안 키가 필요합니다. 따라서 보안이 활성화된 드라이브는 두 개의 키를 사용합니다. 하나는 데이터를 암호화하고 해독하는 드라이브 키와 암호화 및 해독 프로세스를 승인하는 보안 키입니다. set storageArray securityKey 명령은 스토리지 배열의 모든 컨트롤러와 보안 지원 드라이브에 보안 키를 커밋합니다. 전체 디스크 암호화 기능은 보안 지원 드라이브를 스토리지 어레이에서 물리적으로 제거할 경우 보안 키를 알 수 없는 한 다른 장치에서 해당 데이터를 읽을 수 없도록 합니다.



== 최소 펌웨어 레벨입니다

7.50
