---
permalink: commands-a-z/set-controller-ntpservers.html 
sidebar: sidebar 
keywords: set, controller, ntp 
summary: 'set controller NTPServers 명령은 컨트롤러의 NTP 설정을 설정하므로 컨트롤러가 SNTP(Simple Network Time Protocol)를 사용하여 외부 호스트와 시계를 자동으로 동기화할 수 있습니다.' 
---
= 컨트롤러 NTP 설정을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set controller NTPServers 명령은 컨트롤러의 NTP 설정을 설정하여 컨트롤러가 SNTP(Simple Network Time Protocol)를 사용하여 외부 호스트와 시계를 자동으로 동기화할 수 있도록 합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

이 기능이 활성화되면 컨트롤러는 구성된 NTP 서버를 주기적으로 쿼리한 다음 결과를 사용하여 내부 시간 클럭을 업데이트합니다. 하나의 컨트롤러에만 NTP가 활성화되어 있는 경우 대체 컨트롤러는 NTP가 활성화된 컨트롤러와 해당 시계를 정기적으로 동기화합니다. 어떤 컨트롤러도 NTP를 활성화하지 않으면 컨트롤러가 주기적으로 시계를 서로 동기화합니다.

[NOTE]
====
이 명령은 컨트롤러에만 적용됩니다. 두 컨트롤러 모두에서 NTP를 구성할 필요는 없지만 그렇게 하면 하드웨어 또는 통신 장애 시 어레이의 동기화 상태를 유지할 수 있습니다.

====
[NOTE]
====
정규화된 도메인 이름을 사용하여 NTP를 구성하는 경우 작업이 성공하려면 해당 컨트롤러에서 DNS도 구성해야 합니다. 을 참조하십시오 xref:set-controller-dnsservers.adoc[컨트롤러 DNS 설정을 지정합니다] 를 참조하십시오.

====


== 구문

[source, cli]
----
set controller(a|b) NTPServers=(disabled|auto|(Address1 [Address2]))
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
NTP 설정을 변경할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a 또는 b입니다



 a| 
“NTPServers”를 선택합니다
 a| 
이 매개변수는 컨트롤러의 NTP 서버를 구성합니다.

* NTP 지원을 해제하려면 '사용 안 함'을 지정합니다.
* DHCP 서버에서 제공하는 NTP 서버 주소를 사용하려면 auto를 지정합니다.
+
[NOTE]
====
이 옵션은 컨트롤러에 DHCP를 통해 인터페이스 매개변수를 가져오도록 설정된 관리 포트가 하나 이상 있고 DHCP 서버에 하나 이상의 NTP 서버가 구성되어 있는 경우에만 사용해야 합니다.

====
* 그렇지 않으면 하나 또는 두 NTP 서버의 공백으로 구분된 목록을 지정하십시오. 주소는 도메인 이름, IPv4 주소 또는 IPv6 주소일 수 있습니다. 둘 이상의 주소를 지정하는 경우 주소 유형이 일치하지 않아도 됩니다. 둘 이상의 주소가 지정된 경우 지정된 순서대로 사용됩니다(첫 번째는 기본, 두 번째는 백업).


[NOTE]
====
예제 섹션에 나와 있는 것처럼 NTP 서버 이름을 따옴표로 묶습니다.

====


 a| 
주소
 a| 
"DomainName" | IPv4Address | IPv6Address

[NOTE]
====
도메인 이름이 지정된 경우, 컨트롤러가 서버 IP 주소를 확인할 수 있도록 DNS 서버도 구성해야 합니다.

====
|===


== 예

[listing]
----
set controller[a] NTPServers=disabled;
set controller[a] NTPServers=auto;
set controller[a] NTPServers=("0.pool.ntp.org" "1.us.pool.ntp.org");
set controller[b] NTPServers=(192.168.1.105 "1.us.pool.ntp.org");
set controller[b] NTPServers=(2001:0db8:85a3:0000:0000:8a2e:0370:7334);
----


== 최소 펌웨어 레벨입니다

8.25

8.42는 NTP 인증에 대한 주요 자격 증명 매개 변수를 추가합니다.
