---
permalink: commands-a-z/set-storagearray-resourceprovisionedvolumes.html 
sidebar: sidebar 
keywords: set, storage, array, resource, provisioned, volumes 
summary: set storageArray resourceProvisionedVolumes 명령은 DULBE 기능을 비활성화합니다. 
---
= 스토리지 어레이 리소스 프로비저닝 볼륨 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'et storageArray resourceProvisionedVolumes' 명령은 DULBE 기능을 비활성화합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 어레이를 비롯한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

EF600 및 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

리소스 프로비저닝은 대용량 볼륨을 빠르게 초기화할 수 있는 사용 가능한 기능입니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록은 할당 해제(매핑 해제)됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Deallocated or UnWritten Logical Block Error Enable) 오류 복구 기능이 지원됩니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.



== 구문

[source, cli]
----
set storageArray resourceProvisionedVolumes=(enable|disable)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'resourceProvisionedVolumes'입니다
 a| 
리소스 프로비저닝 기능이 설정되어 있는지 여부를 지정하는 설정입니다. 리소스 프로비저닝을 비활성화하려면 이 매개 변수를 사용 안 함으로 설정합니다. 기본값은 'enable'입니다.

[NOTE]
====
이 값을 변경하면 나중에 생성되는 볼륨 그룹 및 풀에만 적용됩니다. 기존 볼륨 그룹 및 풀의 값은 변경되지 않습니다.

====
|===


== 최소 펌웨어 레벨입니다

8.63
