---
permalink: commands-a-z/set-syncmirror.html 
sidebar: sidebar 
keywords: set, synchronous, mirror 
summary: set SyncMirror 명령은 원격 미러링 쌍의 속성을 정의합니다. 
---
= 동기식 미러링 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Set SyncMirror' 명령은 원격 미러링 쌍의 속성을 정의합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800 및 E5700 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령의 이전 버전에서는 기능 식별자가 'remoteMirror'였습니다. 이 기능 식별자는 더 이상 유효하지 않으며 SyncMirror로 대체됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
set syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1 ... volumeNameN_]])
[role=(primary | secondary)]
[syncPriority=(highest | high | medium | low | lowest)]
[autoResync=(enabled | disabled)]
[writeOrder=(preserved | notPreserved)]
[writeMode=(synchronous | asynchronous)]
[force=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'localVolume'
 a| 
속성을 정의할 로컬 볼륨의 이름입니다. 기본 볼륨 이름은 대괄호([])로 묶어야 합니다. 기본 볼륨 이름에 특수 문자나 숫자가 있는 경우 기본 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
로컬볼륨
 a| 
속성을 정의하려는 여러 로컬 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자가 있거나 숫자만 포함된 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
역할
 a| 
로컬 볼륨이 기본 볼륨 또는 보조 볼륨으로 작동하도록 설정합니다. 볼륨을 기본 볼륨으로 정의하려면 이 매개변수를 "primary"로 설정합니다. 볼륨을 보조 볼륨으로 정의하려면 이 매개변수를 '2차'로 설정합니다. 이 매개 변수는 볼륨이 미러 관계의 일부인 경우에만 적용됩니다.



 a| 
'두 우선 순위'입니다
 a| 
전체 동기화가 호스트 I/O 작업과 관련된 우선 순위입니다. 유효한 값은 '가장 높음', '높음', '중간', '낮음' 또는 '가장 낮음'입니다.



 a| 
자동 재동기화
 a| 
운영 볼륨과 원격 미러링된 페어의 보조 볼륨 간의 자동 재동기화를 위한 설정입니다. 이 매개 변수에는 다음 값이 있습니다.

* "활성화됨" -- 자동 재동기화가 켜져 있습니다. 기본 볼륨과 보조 볼륨을 다시 동기화하기 위해 더 이상 수행할 작업은 없습니다.
* 비활성화 -- 자동 재동기화가 해제됩니다. 기본 볼륨과 보조 볼륨을 재동기화하려면 'RESSUME SyncMirror' 명령을 실행해야 합니다.




 a| 
"쓰기 순서"
 a| 
이 매개변수는 기본 볼륨과 보조 볼륨 간의 데이터 전송에 대한 쓰기 순서를 정의합니다. 유효한 값은 '보존' 또는 'notPreserved'입니다.



 a| 
"쓰기 모드"
 a| 
이 매개 변수는 운영 볼륨이 2차 볼륨에 쓰는 방식을 정의합니다. 유효한 값은 '동기식' 또는 '비동기식'입니다.



 a| 
"힘"
 a| 
스토리지 시스템 간의 통신 링크가 다운되고 로컬 측의 상향 이동 또는 하향 이동이 이중 1차 상태 또는 2차 상태를 초래하면 역할 반전이 강제 적용됩니다. 역할 반전을 강제하려면 이 매개 변수를 "true"로 설정합니다. 기본값은 'false'입니다.

[NOTE]
====
role 파라미터를 사용하는 경우에만 force 파라미터를 사용한다.

====
|===


== 참고

이 명령을 사용할 때 하나 이상의 선택적 매개 변수를 지정할 수 있습니다.

동기화 우선 순위는 운영 볼륨과 미러 관계의 보조 볼륨 간에 데이터를 동기화하는 데 사용되는 시스템 리소스의 양을 정의합니다. 가장 높은 우선 순위 수준을 선택하면 데이터 동기화는 대부분의 시스템 리소스를 사용하여 전체 동기화를 수행하므로 호스트 데이터 전송 성능이 저하됩니다.

writeOrder 매개 변수는 비동기 쓰기 모드에만 적용되며 이를 일관성 그룹의 일부로 만듭니다. "writeOrder" 매개 변수를 "Preserved"로 설정하면 원격 미러링 쌍이 운영 볼륨에 쓰는 순서와 동일한 순서로 운영 볼륨에서 보조 볼륨으로 데이터를 전송합니다. 전송 링크에 오류가 발생하면 전체 동기화가 발생할 때까지 데이터가 버퍼링됩니다. 이 작업을 수행하려면 버퍼링된 데이터를 유지 관리하기 위한 추가적인 시스템 오버헤드가 필요하며 이로 인해 작업이 느려집니다. "writeOrder" 매개 변수를 "notPreserved"로 설정하면 시스템이 버퍼에 있는 데이터를 유지 관리할 필요가 없지만 보조 볼륨이 기본 볼륨과 동일한 데이터를 가지도록 전체 동기화를 수행해야 합니다.



== 최소 펌웨어 레벨입니다

6.10
