---
permalink: commands-a-z/set-storagearray-pqvalidateonreconstruct.html 
sidebar: sidebar 
keywords: set, storage, array, pq validation, reconstruct 
summary: set storageArray pqValidateOnReconstruct 명령은 재구성 시 스토리지 배열 P/Q 검증 상태를 설정합니다. 이 기능이 활성화되면 데이터 +P 및 데이터 +Q를 사용하여 데이터가 재구성되고 진행 방법을 결정하기 전에 일관성 여부를 확인하기 위해 결과가 검사됩니다. 
---
= 재구성 시 스토리지 배열 PQ 검증을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'et storageArray pqValidateOnReconstruct' 명령어는 재구성 시 스토리지 배열 P/Q 검증 상태를 설정합니다. 이 기능이 활성화되면 데이터 +P 및 데이터 +Q를 사용하여 데이터가 재구성되고 진행 방법을 결정하기 전에 일관성 여부를 확인하기 위해 결과가 검사됩니다.



== 지원되는 어레이

이 명령은 개별 E2800, E5700, EF600 또는 EF300 스토리지 어레이에 적용됩니다. E2700 또는 E5600 스토리지 어레이에서는 작동하지 않습니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 기능은 이중 패리티가 있는 디스크 풀 및 RAID 6 볼륨 그룹에 적용됩니다. 이 경우 드라이브 장애가 발생하더라도 볼륨 그룹 또는 디스크 풀에 중복성이 있으므로 재구성 중 데이터 및 패리티 일관성을 확인할 수 있습니다. 재구성 중에 불일치가 발견되고 볼륨에 대해 Data Assurance가 활성화된 경우, 나머지 드라이브를 사용하여 데이터를 재구성할 수 있도록 비일관성의 소스를 식별할 수 있습니다. 이 기능이 활성화되어 있고 볼륨에 대해 Data Assurance가 활성화되어 있지 않거나 비일관성을 단일 드라이브로 격리할 수 없는 경우 재구성되는 블록이 읽을 수 없는 것으로 표시됩니다.

검증을 통해 SSD 드라이브의 재구성 시간이 증가할 수 있으므로 미디어 유형에 따라 이 기능을 사용하거나 사용하지 않도록 설정할 수 있습니다. 특정 미디어 유형에 대해 활성화된 경우 이 기능은 해당 미디어 유형을 사용하는 모든 풀과 RAID 6 볼륨 그룹에 적용됩니다.



== 구문

[listing]
----
set storageArray pqValidateOnReconstruct (enable | disable) driveMediaType=(hdd | ssd | allMedia)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
pqValidateOnReconstruct
 a| 
재구성 기능에 대한 P/Q 검증을 수정합니다.



 a| 
"활성화" 또는 "비활성화"
 a| 
재구성 시 P/Q 검증을 활성화 또는 비활성화합니다.



 a| 
"MediaType"입니다
 a| 
P/Q 검증 기능을 설정할 드라이브 미디어 유형입니다. 지원되는 드라이브 미디어 유형은 다음과 같습니다.

* HDD는 하드 디스크 드라이브의 유효성 검사 상태를 설정하고자 함을 나타냅니다
* 'SSD'는 솔리드 스테이트 디스크의 검증 상태를 설정하고자 함을 나타냅니다
* "allMedia"는 스토리지 배열의 모든 미디어에 대해 검증 상태를 설정하려고 함을 나타냅니다.


|===


== 하드 디스크 드라이브로 지정된 드라이브 미디어 유형의 예

[listing]
----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct enable driveMediaType=hdd;"

SMcli completed successfully.
----


== 솔리드 스테이트 드라이브로 지정된 드라이브 미디어 유형의 예

[listing]
----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct disable driveMediaType=ssd;"

SMcli completed successfully.
----


== 최소 펌웨어 레벨입니다

8.42
