---
permalink: commands-a-z/set-host.html 
sidebar: sidebar 
keywords: set, host 
summary: set host 명령은 호스트를 호스트 그룹에 할당하거나 호스트를 다른 호스트 그룹으로 이동합니다. 
---
= 호스트 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Set host 명령은 호스트 그룹에 호스트를 할당하거나 호스트를 다른 호스트 그룹으로 이동합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

또한 이 명령을 사용하여 새 호스트 그룹을 생성하고 호스트를 새 호스트 그룹에 할당할 수도 있습니다. 이 명령으로 수행되는 작업은 호스트에 개별 매핑이 있는지 아니면 개별 매핑이 없는지 여부에 따라 달라집니다.



== 구문

[source, cli, subs="+macros"]
----
set host [hostName]
hostGroup=pass:quotes[("_hostGroupName_"] | none | defaultGroup)
userLabel=pass:quotes["_newHostName_"]
hostType=pass:quotes[(_hostTypeIndexLabel_ | _hostTypeIndexNumber_)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
호스트
 a| 
호스트 그룹에 할당할 호스트의 이름입니다. 호스트 이름은 대괄호([ ])로 묶어야 합니다. 호스트 이름에 특수 문자나 숫자가 있는 경우 호스트 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트그룹
 a| 
호스트를 할당할 호스트 그룹의 이름입니다. 다음 표에서는 호스트가 개별 매핑을 가지고 있거나 없는 경우 명령이 실행되는 방법을 정의합니다. 호스트 그룹 이름은 큰따옴표(" ")로 묶어야 합니다. "defaultGroup" 옵션은 볼륨이 매핑되는 호스트가 포함된 호스트 그룹입니다.



 a| 
'사용자 레이블'
 a| 
새 호스트 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트 유형
 a| 
호스트 포트에 대한 호스트 유형의 인덱스 레이블 또는 번호입니다. 사용 가능한 호스트 유형 식별자 목록을 생성하려면 'show storageArray hostTypeTable' 명령을 사용합니다. 호스트 유형에 특수 문자가 있는 경우 호스트 유형을 큰따옴표(" ")로 묶습니다.

|===
[cols="3*"]
|===
| 호스트 그룹 매개 변수입니다 | 호스트에 개별 매핑이 있습니다 | 호스트에 개별 매핑이 없습니다 


 a| 
"_hostGroupName _"
 a| 
호스트는 현재 호스트 그룹에서 제거되고 "_hostGroupName_"에 의해 정의된 새 호스트 그룹 아래에 배치됩니다.
 a| 
호스트는 현재 호스트 그룹에서 제거되고 "_hostGroupName_"에 의해 정의된 새 호스트 그룹 아래에 배치됩니다.



 a| 
"없음"
 a| 
호스트가 호스트 그룹에서 독립 파티션으로 제거되고 루트 노드 아래에 배치됩니다.
 a| 
호스트는 현재 호스트 그룹에서 제거되고 기본 그룹 아래에 배치됩니다.



 a| 
defaultGroup을 선택합니다
 a| 
명령이 실패합니다.
 a| 
호스트는 현재 호스트 그룹에서 제거되고 기본 그룹 아래에 배치됩니다.

|===


== 참고

이 명령을 사용할 때 하나 이상의 선택적 매개 변수를 지정할 수 있습니다.

이름의 경우 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.



== 최소 펌웨어 레벨입니다

6.10
