---
permalink: commands-a-z/set-volumes.html 
sidebar: sidebar 
keywords: set, volume, attributes, disk pool 
summary: set volumes 명령은 디스크 풀의 볼륨에 대한 속성을 정의합니다. 
---
= 디스크 풀의 볼륨에 대한 볼륨 특성을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Set volumes' 명령은 디스크 풀의 볼륨에 대한 속성을 정의합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
디스크 풀이 32개 이상의 볼륨으로 구성된 구성에서는 작업이 완료되기 전에 제한 시간이 만료되어 호스트 I/O 오류가 발생하거나 내부 컨트롤러가 재부팅될 수 있습니다. 호스트 I/O 오류 또는 내부 컨트롤러 재부팅이 발생한 경우 호스트를 대기 상태로 되돌리거나 작업을 다시 시도하십시오.

====


== 구문

[listing, subs="+macros"]
----
set (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]] | volume <"wwID">)
pass:quotes[addCapacity = _capacityValue_][KB|MB|GB|TB|Bytes] |
pass:quotes[cacheFlushModifier=_cacheFlushModifierValue_] |
cacheReadPrefetch = (TRUE | FALSE) |
cacheWithoutBatteryEnabled=(TRUE | FALSE) |
mediaScanEnabled=(TRUE | FALSE) |
mirrorCacheEnabled=(TRUE | FALSE) |
preReadRedundancyCheck = (TRUE | FALSE) |
readCacheEnabled=(TRUE | FALSE) |
redundancyCheckEnabled = (TRUE | FALSE) |
pass:quotes[segmentSize = _segmentSizeValue_]
pass:quotes[userLabel = _userlabelValue_]
writeCacheEnabled=(TRUE | FALSE) |
dataAssuranceDisabled=(TRUE | FALSE)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'올볼륨'
 a| 
이 매개 변수는 스토리지 배열의 모든 볼륨에 대한 속성을 설정합니다.



 a| 
'볼륨'
 a| 
속성을 정의할 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자나 숫자가 있는 경우 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
속성을 정의할 볼륨의 WWID(World Wide Identifier)입니다. WWID는 큰따옴표(" ")로 꺽쇠 괄호(<>)로 묶습니다.

[NOTE]
====
이 명령을 실행할 때 WWID에 콜론 구분 기호를 사용하지 마십시오.

====


 a| 
'볼륨'
 a| 
속성을 정의하려는 여러 볼륨의 이름입니다. 모든 볼륨의 속성이 동일합니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자나 숫자가 있으면 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
'addCapacity'
 a| 
속성을 정의하는 볼륨의 스토리지 크기(용량)를 증가시키는 설정입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다. 기본값은 '바이트'입니다.

이 매개 변수는 씬 볼륨에 사용할 수 없습니다.



 a| 
'캐시 플러시한정자'
 a| 
데이터가 물리적 스토리지로 플러시되기 전에 볼륨에 대한 데이터가 캐시에 유지되는 최대 시간입니다. 유효한 값은 참고 섹션에 나열되어 있습니다.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다.



 a| 
"cacheWithoutBatteryEnabled"
 a| 
배터리 없이 캐싱을 켜거나 끄는 설정입니다. 배터리 없이 캐싱을 켜려면 이 매개 변수를 "true"로 설정합니다. 배터리 없이 캐싱을 끄려면 이 매개변수를 '거짓'으로 설정합니다.



 a| 
'메디스캔 사용'을 선택합니다
 a| 
볼륨에 대한 미디어 스캔을 켜거나 끄는 설정입니다. 미디어 스캔을 켜려면 이 매개변수를 "TRUE"로 설정합니다. 미디어 스캔을 끄려면 이 매개변수를 "false"로 설정합니다. (스토리지 어레이 레벨에서 미디어 검사가 비활성화된 경우 이 매개 변수는 영향을 주지 않습니다.)



 a| 
'mirorCacheEnabled'를 선택합니다
 a| 
미러 캐시를 설정하거나 해제하는 설정입니다. 미러 캐시를 켜려면 이 매개 변수를 "true"로 설정합니다. 미러 캐시를 해제하려면 이 매개 변수를 "false"로 설정합니다.



 a| 
오너
 a| 
볼륨을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 slotA의 컨트롤러이고 b는 B 슬롯의 컨트롤러입니다 볼륨 소유자를 변경하려는 경우에만 이 매개 변수를 사용합니다.



 a| 
미리 ReadRedundancyCheck를 선택합니다
 a| 
사전 읽기 중복 검사를 설정하거나 해제하는 설정입니다. 사전 읽기 중복 검사를 설정하면 읽기 데이터가 포함된 스트라이프에 대한 RAID 중복 데이터의 일관성이 확인됩니다. 사전 읽기 이중화 검사는 읽기 작업에만 수행됩니다. 사전 읽기 이중화 검사를 켜려면 이 매개변수를 "true"로 설정합니다. 사전 읽기 중복 검사를 해제하려면 이 매개변수를 "false"로 설정합니다.

[NOTE]
====
RAID 0 볼륨과 같은 비중복 볼륨에는 이 매개변수를 사용하지 마십시오.

====


 a| 
"다시 캐시 사용"을 선택합니다
 a| 
읽기 캐시를 설정하거나 해제하는 설정입니다. 읽기 캐시를 설정하려면 이 매개 변수를 "true"로 설정합니다. 읽기 캐시를 해제하려면 이 매개변수를 "false"로 설정합니다.



 a| 
리던ancyCheckEnabled를 선택합니다
 a| 
미디어 검사 중에 중복 검사를 켜거나 끄는 설정입니다. 중복 검사를 켜려면 이 매개변수를 "TRUE"로 설정합니다. 중복 검사를 해제하려면 이 매개변수를 'false'로 설정합니다.



 a| 
'사용자 레이블'
 a| 
기존 볼륨에 지정할 새 이름입니다. 새 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"쓰기 캐시 활성화"
 a| 
쓰기 캐시 기능을 설정하는 설정입니다.

|===


== 참고

이 명령을 사용할 때 하나 이상의 선택적 매개 변수를 지정할 수 있습니다.

이러한 매개변수는 한 번에 하나의 볼륨에만 적용할 수 있습니다.

* 'addCapacity'
* '크기'
* '사용자 레이블'




== 용량 및 세그먼트 크기 추가

addCapacity 매개 변수 또는 'egmentSize' 매개 변수를 설정하면 중지할 수 없는 장기 실행 작업이 시작됩니다. 이러한 장기 실행 작업은 백그라운드에서 수행되며 다른 명령을 실행하지 못하도록 차단하지 않습니다. 장시간 실행 작업의 진행률을 표시하려면 'show volume actionProgress' 명령을 사용합니다.



== 캐시 플러시 한정자입니다

이 표에는 캐시 플러시 한정자에 대한 유효한 값이 나와 있습니다.

[cols="2*"]
|===
| 값 | 설명 


 a| 
'즉각'
 a| 
데이터가 캐시에 배치되면 데이터가 플러시됩니다.



 a| 
25
 a| 
데이터가 250ms 후에 플러시됩니다.



 a| 
5
 a| 
데이터가 500ms 후에 플러시됩니다.



 a| 
'.75'
 a| 
데이터가 750ms 후에 플러시됩니다.



 a| 
"1"
 a| 
데이터는 1초 후에 플러시됩니다



 a| 
1.5입니다
 a| 
데이터는 1500ms 후에 플러시됩니다.



 a| 
2
 a| 
데이터는 2초 후에 플러시됩니다



 a| 
5
 a| 
데이터는 5초 후에 플러시됩니다



 a| 
10입니다
 a| 
데이터는 10초 후에 플러시됩니다



 a| 
20세
 a| 
데이터는 20초 후에 플러시됩니다



 a| 
60세
 a| 
데이터는 60초(1분) 후에 플러시됩니다.



 a| 
120입니다
 a| 
데이터는 120초(2분) 후에 플러시됩니다.



 a| 
300입니다
 a| 
데이터는 300초(5분) 후에 플러시됩니다.



 a| 
1200입니다
 a| 
데이터는 1200초(20분) 후에 플러시됩니다.



 a| 
3600입니다
 a| 
데이터는 3600초(1시간) 후에 플러시됩니다.



 a| 
무한대다
 a| 
캐시의 데이터는 사용 기간 또는 시간 제한을 받지 않습니다. 데이터는 컨트롤러가 관리하는 다른 기준에 따라 플러시됩니다.

|===


== 배터리가 활성화되지 않은 캐시

배터리가 없는 쓰기 캐싱은 컨트롤러 배터리가 완전히 방전되었거나 완전히 충전되지 않았거나 존재하지 않을 경우 쓰기 캐싱을 계속할 수 있도록 합니다. 무정전 전원 공급 장치(UPS) 또는 기타 백업 전원을 사용하지 않고 이 매개변수를 "참"으로 설정하면 스토리지 배열에 대한 전원이 장애가 발생하면 데이터가 손실될 수 있습니다. 이 매개 변수는 쓰기 캐시를 사용하지 않으면 효과가 없습니다.



== 수정 우선 순위

수정 우선 순위는 볼륨 속성을 수정할 때 사용되는 시스템 리소스의 양을 정의합니다. 가장 높은 우선 순위 수준을 선택하면 볼륨 수정 시 대부분의 시스템 리소스가 사용되므로 호스트 데이터 전송 성능이 저하됩니다.



== 캐시 읽기 프리페치

"cacheReadPrefetch" 매개 변수를 사용하면 컨트롤러가 호스트에서 요청한 데이터 블록을 드라이브에서 캐시로 읽고 복사하는 동안 컨트롤러가 추가 데이터 블록을 캐시에 복사할 수 있습니다. 이 작업을 수행하면 캐시에서 향후 데이터 요청을 처리할 수 있는 가능성이 높아집니다. 캐시 읽기 프리페치는 순차 데이터 전송을 사용하는 멀티미디어 응용 프로그램에 중요합니다. 사용하는 스토리지 배열의 구성 설정에 따라 컨트롤러가 캐시로 읽는 추가 데이터 블록의 수가 결정됩니다. cacheReadPrefetch 파라미터의 유효한 값은 TRUE나 FALSE입니다.



== 세그먼트 크기

세그먼트 크기에 따라 다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 블록 수가 결정됩니다. 각 데이터 블록에는 512바이트의 데이터가 저장됩니다. 데이터 블록은 가장 작은 스토리지 단위입니다. 세그먼트의 크기에 따라 포함된 데이터 블록의 수가 결정됩니다. 예를 들어 8KB 세그먼트에는 16개의 데이터 블록이 있습니다. 64KB 세그먼트에는 128개의 데이터 블록이 있습니다.

세그먼트 크기에 대한 값을 입력하면 이 값은 런타임에 컨트롤러에서 제공하는 지원되는 값과 비교하여 확인됩니다. 입력한 값이 유효하지 않으면 컨트롤러가 유효한 값 목록을 반환합니다. 단일 요청에 단일 드라이브를 사용하면 다른 드라이브를 사용할 수 있어 다른 요청을 동시에 처리할 수 있습니다.

볼륨이 단일 사용자가 대용량 데이터(예: 멀티미디어)를 전송하는 환경에 있는 경우 단일 데이터 전송 요청을 단일 데이터 스트라이프로 처리할 때 성능이 극대화됩니다. (데이터 스트라이프는 세그먼트 크기로, 볼륨 그룹의 데이터 전송에 사용되는 드라이브 수를 곱합니다.) 이 경우 여러 드라이브가 동일한 요청에 사용되지만 각 드라이브는 한 번만 액세스됩니다.

다중 사용자 데이터베이스 또는 파일 시스템 스토리지 환경에서 최적의 성능을 얻으려면 세그먼트 크기를 설정하여 데이터 전송 요청을 충족하는 데 필요한 드라이브 수를 최소화하십시오.



== 최소 펌웨어 레벨입니다

7.83
