---
permalink: commands-a-z/set-snapvolume-converttoreadwrite.html 
sidebar: sidebar 
keywords: set, read-only, snapshot, volume, read/write, volume 
summary: set snapVolume convertToReadWrite 명령은 읽기 전용 볼륨인 스냅샷 볼륨을 읽기/쓰기 볼륨인 스냅샷 볼륨으로 변경합니다. 
---
= 읽기 전용 스냅샷 볼륨을 읽기/쓰기 볼륨으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set snapVolume convertToReadWrite 명령을 실행하면 읽기 전용 볼륨인 스냅샷 볼륨이 읽기/쓰기 볼륨인 스냅샷 볼륨으로 변경됩니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

또한 이 명령을 사용하여 읽기/쓰기 볼륨의 새 저장소 볼륨을 식별하거나 저장소 볼륨에 대한 전체 제한 경고 수준을 설정할 수 있습니다.



== 구문

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapImageVolumeName_"]] convertToReadWrite
[(repositoryVolume="repos_xxxx" |
repositoryVolume=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]])
repositoryVolume=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'냅볼륨'
 a| 
읽기 전용에서 읽기/쓰기로 변경할 스냅샷 볼륨의 이름입니다. 스냅숏 볼륨 식별자를 대괄호([ ]) 안에 큰따옴표(" ")로 묶습니다.



 a| 
재량권
 a| 
읽기/쓰기 볼륨에 사용할 저장소 볼륨의 이름입니다.

저장소 볼륨의 이름을 정의하는 두 가지 옵션이 있습니다.

* 기존 리포지토리 볼륨 사용: 이름
* 이 명령을 실행할 때 새 저장소 볼륨을 생성합니다


기존 저장소 볼륨의 이름은 다음 두 부분으로 구성됩니다.

* 용어 "Repos"
* 저장소 관리 소프트웨어가 저장소 볼륨 이름에 할당하는 4자리 숫자 식별자입니다


기존 저장소 볼륨의 이름은 큰따옴표(" ")로 묶어야 합니다.

이 명령을 실행할 때 새 저장소 볼륨을 만들려면 저장소 볼륨을 만들 볼륨 그룹 또는 디스크 풀의 이름을 입력해야 합니다. 필요에 따라 저장소 볼륨의 용량을 정의할 수도 있습니다. 용량을 정의하려면 다음 값을 사용합니다.

* 기본 볼륨 용량의 백분율을 나타내는 정수 값입니다
* 기본 볼륨 용량의 백분율을 나타내는 10진수 분수입니다
* 저장소 볼륨의 특정 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.


용량 옵션을 사용하지 않으면 스토리지 관리 소프트웨어가 기본 볼륨 용량의 20%로 용량을 설정합니다.

이 명령을 실행하면 스토리지 관리 소프트웨어가 스냅샷 볼륨의 저장소 볼륨을 생성합니다.



 a| 
재허용 FullLimit
 a| 
스냅샷 이미지 저장소 볼륨이 거의 꽉 찼다는 경고가 표시되는 저장소 볼륨 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 기본값은 75입니다.

|===


== 참고

사용자 레이블에는 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 사용자 레이블은 최대 30자까지 가능합니다.

저장소 볼륨 이름은 새 스냅샷 그룹을 생성할 때 스토리지 관리 소프트웨어 및 펌웨어에 의해 자동으로 생성됩니다. 저장소 볼륨의 이름을 바꾸면 스냅샷 이미지와의 연결이 끊어지므로 저장소 볼륨의 이름을 바꿀 수 없습니다.

스냅샷 그룹 저장소 볼륨은 최대 16개의 표준 볼륨 엔터티로 구성된 확장 가능한 볼륨입니다. 처음에는 확장 가능한 저장소 볼륨에 단일 요소만 있습니다. 확장 가능한 저장소 볼륨의 용량은 정확히 단일 요소의 용량입니다. 추가 표준 볼륨을 연결하여 확장 가능한 저장소 볼륨의 용량을 늘릴 수 있습니다. 그런 다음 확장 가능한 복합 저장소 볼륨 용량이 연결된 모든 표준 볼륨의 용량을 합한 용량이 됩니다.

스냅샷 그룹 저장소 볼륨은 다음 합계의 최소 용량 요구 사항을 충족해야 합니다.

* 32MB로 스냅샷 그룹 및 쓰기 시 복사 처리에 대한 고정 오버헤드를 지원합니다.
* 기본 볼륨 용량의 1/5000th, 롤백 처리를 위한 용량입니다.


최소 용량은 컨트롤러 펌웨어 및 스토리지 관리 소프트웨어에 의해 적용됩니다.



== 최소 펌웨어 레벨입니다

7.83
