---
permalink: commands-a-z/set-snapvolume-increase-decreaserepositorycapacity.html 
sidebar: sidebar 
keywords: set, snapshot, volume, repository, capacity 
summary: set snapVolume crease/줄어들면 eRepositoryCapacity 명령은 스냅샷 볼륨 저장소 볼륨의 용량을 늘리거나 줄입니다. 
---
= 스냅샷 볼륨 저장소 볼륨 용량 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅 볼륨 증가/감소 eRepositoryCapacity 설정 명령은 스냅샷 볼륨 저장소 볼륨의 용량을 늘리거나 줄입니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 용량 증가를 위한 구문

[source, cli, subs="+macros"]
----
set snapVolume[“snapVolumeName”] increaseRepositoryCapacity
(repositoryVolumes="repos_xxxx" |
repositoryVolumes=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]] |
repositoryVolumes=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]])
----


== 용량을 줄이는 구문

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] decreaseRepositoryCapacity
count=pass:quotes[_numberOfVolumes_]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'냅볼륨'
 a| 
속성을 설정할 스냅샷 볼륨의 이름입니다. 스냅숏 볼륨 식별자를 대괄호([ ]) 안에 큰따옴표(" ")로 묶습니다.



 a| 
재량권
 a| 
용량을 늘리려는 저장소 볼륨의 이름입니다. 저장소 볼륨의 용량을 늘리기 위해 저장소 볼륨에 사용 가능한 표준 볼륨이 추가됩니다.

저장소 볼륨의 이름을 정의하는 두 가지 옵션이 있습니다.

* 기존 리포지토리 볼륨 사용: 이름
* 이 명령을 실행할 때 새 저장소 볼륨을 생성합니다


기존 저장소 볼륨의 이름은 다음 두 부분으로 구성됩니다.

* 용어 "Repos"
* 리포지토리 볼륨 이름에 할당한 4자리 숫자 식별자입니다


기존 저장소 볼륨의 이름은 큰따옴표(" ")로 묶어야 합니다.

이 명령을 실행할 때 새 저장소 볼륨을 만들려면 저장소 볼륨을 만들 볼륨 그룹 또는 디스크 풀의 이름을 입력해야 합니다. 필요에 따라 저장소 볼륨의 용량을 정의할 수도 있습니다. 용량을 정의하려면 다음 값을 사용합니다.

* 기본 볼륨 용량의 백분율을 나타내는 정수 값입니다
* 기본 볼륨 용량의 백분율을 나타내는 10진수 분수입니다
* 저장소 볼륨의 특정 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.


용량 옵션을 사용하지 않으면 스토리지 관리 소프트웨어가 기본 볼륨 용량의 20%로 용량을 설정합니다.

새 저장소 볼륨의 이름은 괄호로 묶습니다.



 a| 
카운트
 a| 
제거할 볼륨 수입니다. 정수 값을 사용합니다.

|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

스냅샷 저장소 볼륨은 최대 16개의 표준 볼륨 엔터티로 구성된 확장 가능한 볼륨입니다. 처음에는 확장 가능한 저장소 볼륨에 단일 요소만 있습니다. 확장 가능한 저장소 볼륨의 용량은 정확히 단일 요소의 용량입니다. 추가 표준 볼륨을 연결하여 확장 가능한 저장소 볼륨의 용량을 늘릴 수 있습니다. 그런 다음 확장 가능한 복합 저장소 볼륨 용량이 연결된 모든 표준 볼륨의 용량을 합한 용량이 됩니다.

스냅샷 그룹 저장소 볼륨은 다음 합계의 최소 용량 요구 사항을 충족해야 합니다.

* 32MB로 스냅샷 그룹 및 쓰기 시 복사 처리에 대한 고정 오버헤드를 지원합니다.
* 기본 볼륨 용량의 1/5000th, 롤백 처리를 위한 용량입니다.


최소 용량은 컨트롤러 펌웨어 및 스토리지 관리 소프트웨어에 의해 적용됩니다.



== 최소 펌웨어 레벨입니다

7.83
