---
permalink: commands-a-z/set-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: set, asynchronous, mirror, group 
summary: set asyncMirrorGroup 명령은 동기화 설정 및 경고 임계값을 변경하여 비동기식 미러 그룹의 운영 측에서 초기 동기화 또는 재동기화를 수행할 때 컨트롤러 소유자가 사용합니다. 
---
= 비동기식 미러 그룹을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set asyncMirrorGroup 명령은 비동기식 미러 그룹의 운영 측 컨트롤러 소유자가 초기 동기화 또는 재동기화를 수행할 때 사용하는 동기화 설정 및 경고 임계값을 변경합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 지원 관리자 역할이 있어야 합니다.



== 상황

동기화 설정을 변경하면 비동기식 미러 그룹 내의 모든 미러링된 쌍의 동기화 작업에 영향을 줍니다.



== 구문

[listing, subs="+macros"]
----
set asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
[volume="repos_xxxx" increaseRepositoryCapacity (repositoryVolume=("repos_xxxx")]
[syncInterval=pass:quotes[_integer_] (minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_] (minutes | hours | days)]
[warningRecoveryThreshold=integer (minutes | hours | days)]
[userLabel=pass:quotes["_New_asyncMirrorGroupName_"]]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[role=(primary | secondary)]
[autoResync=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
아인치마그룹
 a| 
수정할 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
용량을 늘릴 비동기식 미러 그룹 저장소 볼륨의 이름입니다.

저장소 볼륨의 이름은 다음 두 부분으로 구성됩니다.

* 용어 "Repos"
* 저장소 관리 소프트웨어가 저장소 볼륨 이름에 할당하는 4자리 숫자 식별자입니다


저장소 볼륨의 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
'동기화 간격'
 a| 
로컬 스토리지 시스템에서 원격 스토리지 시스템으로 수정된 데이터의 업데이트를 자동으로 보내는 시간 간격을 지정합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.



 a| 
"warningSyncThreshold"를 선택합니다
 a| 
비동기식 미러 그룹 내의 모든 볼륨의 동기화가 정의된 시간보다 오래 걸리는 경우 경고가 트리거될 때까지 대기하는 시간을 지정합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.



 a| 
'warningRecoveryThreshold'
 a| 
원격 스토리지 배열의 특정 시점 이미지에 대한 자동 데이터 업데이트가 정의된 시간보다 오래된 경우 경고가 트리거될 때까지 대기하는 시간을 지정합니다. 이전 업데이트 종료 시 임계값을 정의합니다. 시간 길이를 분, 시간 또는 일 단위로 지정할 수 있습니다.

[NOTE]
====
복구 지점 임계값 을 동기화 간격 임계값의 두 배로 설정해야 합니다.

====


 a| 
'사용자 레이블'
 a| 
비동기식 미러 그룹에 지정할 새 이름입니다. 비동기식 미러 그룹의 이름을 바꾸려면 이 매개 변수를 사용합니다. 새 비동기식 미러 그룹 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
"warningThresholdPercent"를 참조하십시오
 a| 
미러 저장소 볼륨의 용량이 정의된 비율에 도달할 때 경고가 트리거되는 시기를 결정하는 백분율 값을 지정합니다. 남은 용량의 백분율(%)을 기준으로 임계값을 정의합니다.



 a| 
역할
 a| 
이 매개 변수를 사용하여 비동기식 미러 그룹을 운영 역할로 프로모션하거나 비동기식 미러 그룹을 보조 역할로 하향 이동합니다. 비동기식 미러 그룹을 기본 역할로 정의하려면 이 매개 변수를 "primary"로 설정합니다. 비동기식 미러 그룹을 2차 역할로 정의하려면 이 매개 변수를 '2차'로 설정합니다.



 a| 
자동 재동기화
 a| 
비동기식 미러 그룹 내에 있는 비동기식 미러링된 쌍의 보조 볼륨과 운영 볼륨 간의 자동 재동기화를 위한 설정입니다. 이 매개 변수에는 다음 값이 있습니다.

* "활성화됨" -- 자동 재동기화가 켜져 있습니다. 기본 볼륨과 보조 볼륨을 다시 동기화하기 위해 더 이상 수행할 작업은 없습니다.
* 비활성화 -- 자동 재동기화가 해제됩니다. 운영 볼륨과 보조 볼륨을 재동기화하려면 'asyncMirrorGroup 시작' 명령을 실행해야 합니다.


|===


== 참고

이름에 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

이 명령을 사용할 때 하나 이상의 매개 변수를 지정할 수 있습니다. 그러나 모든 매개 변수를 사용할 필요는 없습니다.

비동기 미러 그룹 저장소 볼륨은 최대 16개의 표준 볼륨 엔터티로 구성된 확장 가능한 볼륨입니다. 처음에는 확장 가능한 저장소 볼륨에 단일 볼륨만 있습니다. 확장 가능한 저장소 볼륨의 용량은 정확히 단일 볼륨의 용량입니다. 사용하지 않는 저장소 볼륨을 추가로 연결하여 확장 가능한 저장소 볼륨의 용량을 늘릴 수 있습니다. 그런 다음 확장 가능한 복합 저장소 볼륨 용량이 연결된 모든 표준 볼륨의 용량을 합한 용량이 됩니다.



== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
