---
permalink: commands-a-z/set-volume-logicalunitnumber.html 
sidebar: sidebar 
keywords: set, volume, map 
summary: 'set volume logicalUnitNumber 명령은 볼륨과 호스트 또는 호스트 그룹 간의 LUN(Logical Unit Number) 또는 NSID(Namespace ID) 매핑을 정의합니다.' 
---
= 볼륨 매핑을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Set volume logicalUnitNumber' 명령어는 볼륨과 호스트 또는 호스트 그룹 간의 LUN(Logical Unit Number) 또는 NSID(Namespace ID) 매핑을 정의합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 볼륨 그룹 또는 디스크 풀의 볼륨에 적용할 수 있습니다.

[NOTE]
====
온라인 볼륨 복사본에 사용되는 스냅샷 볼륨에는 이 명령을 사용할 수 없습니다.

====


== 구문

[listing, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] | volume <"wwID"> | accessVolume)
pass:quotes[logicalUnitNumber=_lun_]
pass:quotes[(host="_hostName_"] |
hostGroup=pass:quotes[("_hostGroupName_"] | defaultGroup)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
논리 단위 번호를 정의할 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자나 숫자가 있는 경우 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
논리 단위 번호를 정의하려는 볼륨의 WWID(World Wide Identifier)입니다. WWID는 큰따옴표(" ")로 꺽쇠 괄호(<>)로 묶습니다.



 a| 
'accessVolume'
 a| 
액세스 볼륨의 논리 단위 번호입니다. 논리 단위 번호는 액세스 볼륨에 설정할 수 있는 유일한 속성입니다.



 a| 
LogicalUnitNumber입니다
 a| 
특정 호스트에 매핑하는 데 사용할 논리 단위 번호 또는 네임스페이스 ID입니다. 또한 이 매개 변수는 호스트를 호스트 그룹에 할당합니다.

[NOTE]
====
지정한 논리 단위 번호 또는 네임스페이스 ID는 이미 사용 중인 것은 아니며 호스트 운영 체제에서 지원하는 범위 내에 있어야 합니다. 호스트에서 지원하지 않는 논리 유닛 번호 또는 네임스페이스 ID에 볼륨을 매핑하면 오류가 발생하지 않지만 호스트는 볼륨에 액세스할 수 없습니다.

====


 a| 
호스트
 a| 
볼륨이 매핑되는 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
호스트그룹
 a| 
볼륨이 매핑되는 호스트 그룹의 이름입니다. 호스트 그룹 이름은 큰따옴표(" ")로 묶어야 합니다. defaultGroup은 볼륨이 매핑된 호스트가 포함된 호스트 그룹입니다.

|===


== 참고

호스트 그룹은 동일한 볼륨에 대한 액세스를 공유하는 호스트 컬렉션을 지정할지 여부를 정의할 수 있는 선택적 토폴로지 요소입니다. 호스트 그룹은 논리적 엔터티입니다. 동일한 볼륨에 대한 액세스를 공유할 수 있는 호스트가 두 개 이상 있는 경우에만 호스트 그룹을 정의합니다.

이름에 영숫자, 하이픈 및 밑줄을 조합하여 사용할 수 있습니다. 이름에는 최대 30자를 사용할 수 있습니다.

액세스 볼륨은 스토리지 관리 소프트웨어와 스토리지 어레이 컨트롤러 간의 대역 내 통신에 사용되는 SAN 환경의 볼륨입니다. 이 볼륨은 LUN 또는 NSID 주소를 사용하며 애플리케이션 데이터 스토리지에 사용할 수 없는 20MB의 스토리지 공간을 사용합니다. 액세스 볼륨은 대역내 관리형 스토리지 어레이에만 필요합니다. "accessVolume" 매개 변수를 지정하면 설정할 수 있는 유일한 속성은 "logicalUnitNumber" 매개 변수입니다.



== 최소 펌웨어 레벨입니다

7.83은 디스크 풀의 스냅샷 볼륨을 추가합니다.
