---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: set volumeGroup 명령은 볼륨 그룹의 속성을 정의합니다. 
---
= 볼륨 그룹 설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'볼륨 그룹 설정' 명령은 볼륨 그룹의 속성을 정의합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
명령당 하나의 작업(드라이브 추가, RAID 레벨 변경 또는 볼륨 그룹 소유권 변경)만 수행해야 합니다. 단일 명령으로 두 개 이상의 작업을 수행할 수 없습니다.

====


== 구문

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
볼륨그룹
 a| 
속성을 설정할 볼륨 그룹의 이름입니다. 볼륨 그룹 이름은 대괄호([])로 묶어야 합니다.



 a| 
'addDrives'입니다
 a| 
볼륨 그룹에 추가할 드라이브의 위치입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
레이드레벨
 a| 
볼륨 그룹의 RAID 레벨입니다. 유효한 값은 0, 1, 3, 5, 6입니다.



 a| 
오너
 a| 
볼륨 그룹을 소유하는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 볼륨 그룹 소유자를 변경하려는 경우에만 이 매개 변수를 사용합니다.

|===


== 참고

호스트 I/O 오류로 인해 32개 이상의 볼륨이 있는 볼륨 그룹이 생성될 수 있습니다. 볼륨 그룹 정의가 설정되기 전에 시간 초과 기간이 종료되므로 이 작업으로 인해 내부 컨트롤러가 재부팅될 수도 있습니다. 이 문제가 발생하면 호스트 I/O 작업을 중지하고 명령을 다시 시도하십시오.

이 명령을 사용하면 매개 변수 중 하나만 지정할 수 있습니다.

[NOTE]
====
addDrives 매개 변수 또는 raidLevel 매개 변수를 지정하면 중지할 수 없는 오래 실행되는 작업이 시작됩니다.

====
addDrives 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 문제 해결

DCE(동적 용량 확장)라고도 하는 드라이브를 추가하여 큰 볼륨 그룹을 확장하려고 하면 다음 메시지와 함께 실패할 수 있습니다.

'리턴 코드: 오류 26 - 볼륨 그룹의 드라이브 수와 관련 볼륨의 세그먼트 크기 때문에 수정 작업을 완료할 수 없습니다. Change Segment Size(세그먼트 크기 변경) 옵션을 사용하여 볼륨 그룹의 모든 볼륨에서 세그먼트 크기를 128KB 이하로 줄입니다. 그런 다음 작업을 다시 시도하십시오

7.35.xx.xx 펌웨어를 실행하는 시스템은 위에 언급된 메시지 대신 다음 메시지와 함께 실패할 수 있습니다.

"리턴 코드: 오류 462 - 펌웨어가 충분한 캐시 메모리를 할당할 수 없기 때문에 기호 절차를 수행할 수 없습니다. 오류가 발생한 경우의 작업: PROC_startVolum'

위의 메시지 외에도 DCE 작업을 완료하는 데 사용할 수 있는 캐시가 부족함을 나타내는 MEL(Major Event Log) 이벤트가 발생할 수 있습니다.

7.xx 펌웨어를 실행하는 모든 컨트롤러에 이 문제가 발생할 수 있습니다.

DCE에서는 원본 볼륨에서 읽은 데이터와 확장 볼륨에 쓸 데이터를 버퍼링하기에 충분한 메모리가 필요합니다. 확장 작업에서 드라이브 수, 스트라이프 크기 및 미러 작업 활성화 여부에 따라 DCE 작업을 완료하는 데 사용할 수 있는 메모리가 부족할 수 있습니다.

위의 상황이 발생하면 가능한 해결 방법은 다음과 같습니다.

* 할당되지 않은 다른 드라이브를 사용하여 원하는 크기의 볼륨 그룹을 생성합니다.
* 현재 볼륨 그룹을 삭제한 다음 원하는 수의 드라이브로 볼륨 그룹을 다시 생성합니다.
* 사용 중인 세그먼트 크기를 줄이고 작업을 재시도하십시오.
* 가능하면 컨트롤러에 메모리를 추가한 다음 작업을 재시도하십시오.




== 최소 펌웨어 레벨입니다

7.10은 RAID 6 기능을 추가합니다.

7.30은 가용성 매개 변수를 제거합니다.

7.60은 drawerID 사용자 입력을 추가합니다.
