---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: set drive securityID 명령은 FIPS 드라이브를 원래 제조업체 설정으로 재설정하는 데 사용됩니다. 
---
= FIPS 드라이브 보안 식별자를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Set drive securityID' 명령은 FIPS 드라이브를 원래 제조업체 설정으로 재설정하는 데 사용됩니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령은 FIPS 드라이브를 원래 제조업체 설정으로 다시 설정하고 기존의 모든 드라이브 데이터를 지웁니다. 이 작업은 완전히 되돌릴 수 없습니다. 유효하지 않거나 누락된 보안 키 파일 또는 알 수 없는 암호 구문으로 인해 드라이브가 잠겨 있는 경우 이 기능이 필요할 수 있습니다. 기존의 모든 드라이브 데이터가 지워집니다.

====
FDE 드라이브를 지우려면 'secureErase 시작' 명령을 사용합니다.



== 구문

[source, cli, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
"내가 한 일"이라고 말했습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
'생태ID'입니다
 a| 
지울 드라이브의 보안 ID(문자열 형식)입니다. 이 문자열은 최대 32자까지 입력할 수 있습니다. 보안 ID의 형식은 제조업체에 따라 다릅니다.

[NOTE]
====
보안 ID를 찾으려면 드라이브를 분리하고 캐니스터 레이블에 있는 보안 ID를 읽습니다.

====
|===


== 참고

"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 예

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== 최소 펌웨어 레벨입니다

8.25
