---
permalink: commands-a-z/set-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool 
summary: set diskpool 명령은 지정된 매개 변수를 기반으로 디스크 풀과 관련된 속성을 설정합니다. 
---
= 디스크 풀을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'디스크 풀 설정' 명령은 지정된 매개 변수를 기반으로 디스크 풀과 관련된 속성을 설정합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
set (diskPool pass:quotes[[_diskPoolName_]] |
diskPools pass:quotes[[_diskPoolName1_ ... _diskPoolNameN_]] | allDiskPools)
[reservedDriveCount=pass:quotes[_reservedDriveCountValue_]]
[warningThreshold=(warningThresholdValue | default)]
[criticalThreshold=(criticalThresholdValue | default)]
[criticalPriority=(highest | high | medium |low |lowest)]
[degradedPriority=(highest |high |medium |low |lowest)]
[backgroundPriority=(highest | high | medium |low |lowest)]
[userLabel=pass:quotes[_diskPoolName_]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
디즈크풀
 a| 
속성을 설정할 디스크 풀의 이름입니다. 디스크 풀 이름은 대괄호([ ])로 묶어야 합니다. 디스크 풀 이름에 특수 문자가 있거나 숫자만 포함된 경우 디스크 풀 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
디즈카스
 a| 
속성을 설정할 여러 디스크 풀의 이름입니다. 다음 규칙을 사용하여 디스크 풀의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


디스크 풀 이름에 특수 문자나 숫자가 있는 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
'allDiskPools'
 a| 
이 매개 변수는 스토리지 배열의 모든 디스크 풀에 대한 특성을 설정합니다.



 a| 
다시\nDedDriveCount'를 선택합니다
 a| 
이 매개 변수는 디스크 풀의 모든 드라이브에서 장애 드라이브 재구성에 사용할 공간을 예약합니다. 이 카운트의 각 단위는 장애가 발생한 드라이브를 디스크 풀의 나머지 부분에 재구성할 용량을 나타냅니다.



 a| 
'warningThreshold'
 a| 
디스크 풀이 거의 꽉 찼다는 경고 알림을 받는 디스크 풀 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 최상의 작동을 위해서는 이 파라미터의 값이 'critalThreshold' 파라미터의 값보다 작아야 합니다.

유효한 값은 0에서 100 사이입니다.

기본값은 50입니다.

이 매개변수를 '0'으로 설정하면 경고 경고가 비활성화됩니다.

이를 '기본값'으로 설정하면 컨트롤러 펌웨어에 의해 경고 경고 임계값이 결정됩니다.



 a| 
비판역치
 a| 
디스크 풀이 거의 꽉 찼다는 심각한 경고를 수신하는 디스크 풀 용량의 비율입니다. 정수 값을 사용합니다. 예를 들어 값이 70이면 70%를 의미합니다. 최상의 작동을 위해서는 이 파라미터의 값이 'warningThreshold' 파라미터의 값보다 커야 합니다.

유효한 값은 0에서 100 사이입니다.

기본값은 85%입니다.

이 매개 변수를 '0'으로 설정하면 경고 알림과 중요 경고가 모두 비활성화됩니다.

이를 '기본값'으로 설정하면 컨트롤러 펌웨어에 의해 위험 경고 임계값이 결정됩니다.



 a| 
비판우선
 a| 
디스크 풀의 중요 이벤트에 대한 재구성 작업의 우선순위 예를 들어, 드라이브 장애가 2개 이상 발생한 이후에 디스크 풀을 재구성합니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 '가장 높음'입니다.



 a| 
"우선 순위"를 선택합니다
 a| 
디스크 풀의 성능 저하 이벤트에 대한 재구성 작업의 우선순위 예를 들어, 한 드라이브 장애 후 디스크 풀 재구성을 수행할 수 있습니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 'high'입니다.



 a| 
백그라운드 우선 순위
 a| 
디스크 풀의 백그라운드 작업에 대한 우선 순위입니다.

유효한 값은 '가장 높음', '높음', '중간', '낮음', '가장 낮음'입니다. 기본값은 'low'(낮음)입니다.



 a| 
'사용자 레이블'
 a| 
디스크 풀에 지정할 새 이름입니다. 디스크 풀 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

각 디스크 풀 이름은 고유해야 합니다. 사용자 레이블에는 영숫자, 밑줄(_), 하이픈(-) 및 파운드(#)를 조합하여 사용할 수 있습니다. 사용자 레이블은 최대 30자까지 가능합니다.

임의의 디스크 풀 세트를 지정할 수 있습니다. 여러 개의 디스크 풀을 선택할 경우 userLabel 값을 설정하면 오류가 발생합니다.

선택적 매개 변수의 값을 지정하지 않으면 기본값이 할당됩니다.



== 디스크 풀 경고 임계값

각 디스크 풀에는 디스크 풀의 스토리지 용량이 거의 다 찼을 때 사용자에게 알리기 위해 2개의 점진적으로 심각한 수준의 경고가 있습니다. 알림의 임계값은 디스크 풀의 총 가용 용량에 사용된 용량의 백분율 중 입니다. 경고는 다음과 같습니다.

* 경고 -- 디스크 풀에서 사용된 용량이 거의 다 찼다는 경고의 첫 번째 수준입니다. 경고 경고의 임계값에 도달하면 Needs Attention(주의 필요) 조건이 생성되고 스토리지 관리 소프트웨어에 이벤트가 게시됩니다. 경고 임계값이 위험 임계값으로 대체됩니다. 기본 경고 임계값은 50%입니다.
* 심각 -- 디스크 풀에서 사용된 용량이 거의 다 찼다는 가장 심각한 수준의 알림입니다. 중요 알림 임계값에 도달하면 Needs Attention(주의 필요) 조건이 생성되고 이벤트가 스토리지 관리 소프트웨어에 게시됩니다. 경고 임계값이 위험 임계값으로 대체됩니다. 중요 경고의 기본 임계값은 85%입니다.


경고 알림 값이 항상 위험 알림 값보다 작아야 합니다. 경고 알림 값이 위험 알림 값과 같으면 중요 알림만 전송됩니다.



== 디스크 풀 백그라운드 작업입니다

디스크 풀은 다음과 같은 백그라운드 작업을 지원합니다.

* 재구성
* 인스턴트 가용성 형식(iaf)
* 형식
* 동적 용량 확장(DCE)
* 동적 용량 감소(DCR)
* DVE(Dynamic Volume Expansion)(디스크 풀의 경우 DVE는 백그라운드 작업이 아니라 동기식 작업으로 지원됩니다.)


디스크 풀은 백그라운드 명령을 대기열에 넣지 않습니다. 여러 개의 백그라운드 명령을 순차적으로 시작할 수 있지만 한 번에 두 개 이상의 백그라운드 작업을 시작하면 이전에 시작한 명령의 완료가 지연됩니다. 지원되는 백그라운드 작업의 상대적 우선 순위 수준은 다음과 같습니다.

. 재구성
. 형식
. iaf
. DCE/DCR




== 최소 펌웨어 레벨입니다

7.83
