---
permalink: commands-a-z/set-storagearray-learncycledate-controller.html 
sidebar: sidebar 
keywords: set, storage, array, controller, battery, learn, cycle 
summary: set storageArray learnCycleDate 컨트롤러 명령은 컨트롤러 배터리 학습 주기를 설정합니다. 
---
= 스토리지 어레이 컨트롤러 배터리 학습 주기를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
세트 storageArray learnCycleDate 컨트롤러 명령은 컨트롤러 배터리 학습 사이클을 설정합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
스토리지 어레이에서 각 컨트롤러에 대한 개별 학습 사이클을 설정하려면 이 명령을 두 컨트롤러 모두에 보내십시오.

====
[NOTE]
====
학습 사이클은 서로 연결되지 않으므로 하나의 컨트롤러 배터리 학습 주기에서 중단이 다른 컨트롤러의 배터리에 대한 학습 사이클에 영향을 미치지 않습니다.

====
[NOTE]
====
학습 사이클을 완료하는 데 몇 시간이 걸릴 수 있습니다.

====


== 구문

[listing, subs="+macros"]
----
set storageArray learnCycleDate (controller[(a| b)] )
pass:quotes[(daysToNextLearnCycle=_numberOfDays_ |
day=_dayOfTheWeek_)] pass:quotes[time=_HH:MM_]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
' * controller * '
 a| 
배터리 학습 주기를 지정할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 컨트롤러 펌웨어가 구문 오류를 반환합니다.

[NOTE]
====
이 매개 변수를 생략하면 이중 컨트롤러 어레이의 두 컨트롤러 배터리에 대한 학습 사이클이 설정됩니다.

====


 a| 
'DaysToNextLearnCycle'을 선택합니다
 a| 
유효한 값은 0부터 7까지, 0은 즉시, 7은 7일 이내. 'DaysToNextLearnCycle' 매개변수는 다음 예정된 런 주기 이후 최대 7일 후에 발생합니다.



 a| 
다
 a| 
'데이' 매개 변수의 유효값에는 해당 요일('당일', '몬데이', '화요일', '수요일', '목요일', '목요일' 등)이 포함됩니다. 금요일, '어타데이'). 요일을 설정하면 현재 예정된 런 주기 이후에 지정된 날짜에 다음 런 사이클이 예약됩니다.



 a| 
시간
 a| 
24시간 형식의 시간(예: 오전 8:00 08:00으로 입력된다. 오후 9시 21:00, 9:30으로 입력된다 21:30으로 입력된다.

|===


== 예

[listing]
----
set storageArray learnCycleDate controller [a] daysToNextLearnCycle=4 time=08:30;
----


== 참고

학습 사이클이 7일 동안 한 번만 발생하도록 설정할 수 있습니다.

'시간' 매개변수는 학습 사이클을 실행할 특정 시간을 선택합니다. 값을 입력하지 않으면 00:00(자정)의 기본값을 사용합니다.

지정한 날짜 및 시간이 지난 경우 다음 런 주기는 지정된 다음 가능한 일에 수행됩니다.



== 최소 펌웨어 레벨입니다

7.15

8.30 - controller 파라미터를 추가했다.
