---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: 'set drive nativeState 명령은 손실된(외부) 드라이브를 원래 볼륨 그룹에 다시 추가하고 새 스토리지 배열의 볼륨 그룹에 포함되게 합니다.' 
---
= 외부 드라이브를 네이티브 드라이브로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Set drive nativeState' 명령은 누락된(외부) 드라이브를 원래 볼륨 그룹에 다시 추가하고 새 스토리지 배열의 볼륨 그룹에 포함되게 합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

드라이브는 스토리지 배열의 볼륨 그룹에 속하는 경우 네이티브 드라이브로 간주됩니다. 드라이브가 스토리지 배열의 볼륨 그룹에 속하지 않거나 새 스토리지 배열에 전송된 볼륨 그룹의 드라이브로 가져오지 못한 경우 외부 드라이브로 간주됩니다. 마지막 장애가 발생하면 새 스토리지 어레이에 불완전한 볼륨 그룹이 생성됩니다.

비상 복구에만 이 작업을 사용합니다. 하나 이상의 드라이브를 외부 드라이브 상태에서 변경하고 원래 볼륨 그룹 내의 기본 상태로 되돌려야 하는 경우

[NOTE]
====
* 데이터 손상 또는 데이터 손실 가능성 * -- 이전에 설명한 것 이외의 이유로 이 명령을 사용하면 알림 없이 데이터가 손실될 수 있습니다.

====


== 구문

[source, cli, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'늑대'나 '늑대'가 있습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800, E5700, EF600 및 EF300 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호를 가집니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
'allDrives'(allDrives)
 a| 
모든 드라이브를 선택하는 설정입니다.

|===


== 참고

"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 최소 펌웨어 레벨입니다

7.10

7.60은 drawerID 사용자 입력을 추가합니다.
