---
permalink: commands-a-z/show-volume.html 
sidebar: sidebar 
keywords: show, thin, volume 
summary: show volume 명령은 지정된 씬 볼륨에 대해 사용된 용량 또는 확장 기록을 반환합니다. 
---
= 씬 볼륨을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'show volume' 명령은 지정된 씬 볼륨에 대해 사용된 용량 또는 확장 기록을 반환합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 스토리지 모니터 역할이 있어야 합니다.



== 구문

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]])
(consumedCapacity |
(expansionHistory pass:quotes[[file=_fileName_]]))
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'올볼륨'
 a| 
이 매개 변수는 스토리지 배열의 모든 씬 볼륨에 대한 정보를 반환합니다.



 a| 
'볼륨'
 a| 
정보를 검색할 씬 볼륨의 이름입니다. 씬 볼륨 이름은 대괄호([])로 묶어야 합니다. 씬 볼륨 이름에 특수 문자나 숫자가 있는 경우 씬 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
정보를 검색할 여러 씬 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자나 숫자가 있으면 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
"콘수medCapacity"
 a| 
씬 볼륨의 사용된 용량에 대한 간략한 정보 목록을 반환하는 설정입니다.



 a| 
팽창사
 a| 
씬 볼륨의 확장 내역에 대한 간략한 정보 목록을 반환하는 설정입니다.



 a| 
'파일'
 a| 
file 매개 변수는 expensionHistory 매개 변수의 출력을 기록할 파일을 지정합니다. 파일(file)은 expensionHistory 매개변수와 함께 사용할 때만 유효합니다. 잘못된 파일 이름으로 인해 명령이 실패합니다.

|===


== 참고

expensionHistory 매개 변수를 사용하면 명령이 아래 예와 유사한 정보를 반환합니다.

'씬 볼륨 이름: volume-nameRepository 볼륨 이름: Repos_NNNN'

[cols="4*"]
|===
| 로깅된 시간입니다 | 확장 유형 | 시작 용량 | 종료 용량 


 a| 
MM/DD/YYYY HH:MM:SS(MM/DD/YYYY HH:MM:SS)
 a| 
수동 | 자동
 a| 
nnnnnnnn 바이트
 a| 
nnnnnnnn 바이트

|===
'consumedCapacity' 파라미터를 사용하면 명령어가 아래 예와 유사한 정보를 리턴한다.

[cols="5*"]
|===
| 볼륨 | 프로비저닝된 용량 | 사용된 용량 | 할당량 | 소비 비율 


 a| 
'VolumeName'
 a| 
500,000GB
 a| 
230.000GB
 a| 
700.000GB
 a| 
46%

|===


== 최소 펌웨어 레벨입니다

7.83
