---
permalink: commands-a-z/show-controller-cacertificate.html 
sidebar: sidebar 
keywords: show, installed, root, intermediate, ca, certificates, summary 
summary: show controller caCertificate 명령은 지정된 컨트롤러의 설치된 CA 인증서 요약을 표시합니다. 이 명령은 삭제할 인증서의 별칭 이름을 알 수 있도록 컨트롤러 caCertificate 삭제 명령을 수행하기 전에 를 사용하는 데 유용합니다. 
---
= 설치된 루트/중간 CA 인증서 요약을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show controller caCertificate' 명령어는 지정된 controller의 설치된 CA certificates summary를 출력한다. 이 명령은 삭제할 인증서의 별칭 이름을 알 수 있도록 'Delete controller caCertificate' 명령을 수행하기 전에 를 사용하는 데 유용합니다.



== 지원되는 어레이

이 명령은 개별 E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에 적용됩니다. E2700 또는 E5600 스토리지 어레이에서는 작동하지 않습니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
show controller [(a|b)] caCertificate [all | aliases=pass:quotes[("_alias1_" ... "_aliasN_")]] summary
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
사용자가 루트/중간 인증서를 검색할 컨트롤러를 지정할 수 있습니다. 유효한 컨트롤러 식별자는 a 또는 b이며, 여기서 a는 슬롯 A의 컨트롤러이고 b는 슬롯 B의 컨트롤러입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다.



 a| 
모두
 a| 
사용자가 모든 루트/중간 인증서의 검색을 지정할 수 있습니다.



 a| 
'별칭'
 a| 
사용자가 별칭으로 검색할 루트/중간 인증서를 지정할 수 있습니다. 모든 별칭을 괄호로 묶습니다. 둘 이상의 별칭을 입력하는 경우 공백으로 구분하십시오.

|===


== 예

[listing, subs="+macros"]
----

SMcli -n Array1 -c "show controller[a] caCertificate all summary;"

SMcli -n Array1 -c "show controller[b] caCertificate alias=("myAlias" "anotherAlias") summary;"
============================
Controller A Authority Certificates
============================
Alias:        19527b38-8d26-44e5-8c7f-5bf2ca9db7cf
Subject DN:   CN=My Corp Issuing CA 1
Issuer DN:    CN=My Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]
---------------------
Alias:        myAliasName
Subject DN:   CN=My Corp Issuing CA 1
Issuer DN:    CN=My Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]

SMcli completed successfully.
----


== 최소 펌웨어 레벨입니다

8.40
