---
permalink: commands-a-z/show-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: show, ssd, cache, statistics 
summary: show ssdCache 명령은 SSD 캐시 사용량에 대한 데이터를 표시합니다. 
---
= SSD 캐시 통계 표시 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show ssdCache' 명령은 SSD 캐시 사용량에 대한 데이터를 표시합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 지원 관리자 역할이 있어야 합니다.



== 구문

[source, cli, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'ssdCache'입니다
 a| 
정보를 검색할 SSD 캐시의 이름입니다. SSD 캐시 이름은 대괄호([ ])로 묶어야 합니다. SSD 캐시 이름에 특수 문자나 숫자가 있으면 SSD 캐시 이름을 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'ssdCacheStatistics
 a| 
캐시 통계를 검색할 것을 나타내는 'show ssdCache' 명령에 대한 선택적 매개 변수입니다.



 a| 
컨트롤러
 a| 
각 컨트롤러는 소유한 볼륨의 SSD 캐시 메타데이터를 저장합니다. 따라서 SSD 캐시 통계는 컨트롤러당 유지되고 표시됩니다. 유효한 컨트롤러 식별자는 a, b, both이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기이며, both는 모두 제어기이다. 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 기본값은 "both"입니다.



 a| 
'파일'
 a| 
SSD 캐시 통계를 저장할 파일 경로 및 파일 이름입니다. 통계를 파일에 저장할 때 추가 통계를 사용할 수 있습니다.

파일 이름은 큰따옴표(" ")로 묶어야 합니다. 예를 들면 다음과 같습니다.

"file="C:\Program Files\CLI\logs\ssdcachestats.csv".

파일 이름은 사용할 수 있지만 확장명은 .csv여야 합니다.

|===


== 참고

다음 통계가 화면에 표시됩니다.

* * 읽기 * -- SSD 캐시 지원 볼륨의 총 호스트 읽기 수입니다.
+
쓰기에 상대적인 읽기를 비교합니다. 유효 SSD 캐시 작업을 위해서는 읽기 용량이 쓰기 작업보다 커야 합니다. 읽기/쓰기의 비율이 클수록 캐시 작업이 향상됩니다.

* * Writes * -- SSD 캐시 사용 볼륨에 대한 호스트의 총 쓰기 수입니다.
* * 캐시 적중 횟수 * -- 캐시 적중 횟수.
* * 캐시 적중 횟수(%) * -- 캐시 적중 횟수/총 읽기에서 파생
+
효과적인 SSD 캐시 작업을 위해서는 캐시 적중률이 50% 이상이어야 합니다. 작은 숫자는 몇 가지 사항을 나타낼 수 있습니다.

+
** 쓰기대비 읽기 비율이 너무 작습니다.
** 읽기는 반복되지 않습니다.
** 캐시 용량이 너무 작습니다.
+
[NOTE]
====
이상적인 SSD 캐시 용량을 확인하려면 'start ssdCache[ssdCacheName] performanceModeling' 명령을 사용하여 성능 모델링 도구를 실행할 수 있습니다.

====


* * 캐시 할당(%) * -- 할당된 SSD 캐시 스토리지의 양으로, 이 컨트롤러에서 사용할 수 있는 SSD 캐시 스토리지의 백분율로 표시됩니다. 할당된 바이트/사용 가능한 바이트에서 파생됩니다.
+
캐시 할당 비율은 일반적으로 100%로 표시됩니다. 이 값이 100% 미만인 경우 캐시가 준비되지 않았거나 SSD 캐시 용량이 액세스 중인 모든 데이터보다 크다는 것을 의미합니다. 후자의 경우, SSD 캐시 용량이 작으면 동일한 수준의 성능을 제공할 수 있습니다. 이는 캐싱된 데이터가 SSD 캐시에 저장되었음을 나타내는 것이 아니라 데이터를 SSD 캐시에 저장하기 위한 준비 단계일 뿐입니다.

* * 캐시 활용률(%) * -- 활성 볼륨의 데이터가 포함된 SSD 캐시 스토리지의 양으로, 할당된 SSD 캐시 스토리지의 백분율로 표시됩니다. 이 값은 SSD 캐시의 사용률 또는 밀도를 나타냅니다. 사용자 데이터 바이트/할당된 바이트에서 파생됩니다.
+
일반적으로 캐시 활용률 백분율은 100%보다 낮으며, 이보다 훨씬 낮을 수 있습니다. 이 숫자는 캐시 데이터로 채워진 SSD 캐시 용량의 비율을 나타냅니다. 이 수치가 100%보다 낮은 이유는 SSD 캐시의 각 할당 유닛인 SSD 캐시 캐시 블록이 약간 독립적인 서브블록이라는 작은 유닛으로 분리되기 때문입니다. 일반적으로 숫자가 클수록 좋지만 숫자가 적더라도 성능이 크게 향상될 수 있습니다.



데이터를 파일에 저장할 때 다음과 같은 추가 통계가 포함됩니다.

* * 읽기 블록 * -- 호스트 읽기의 블록 수입니다.
* * 쓰기 블록 * -- 호스트 쓰기의 블록 수입니다.
* * 전체 적중 블록 * -- 블록 캐시 적중 횟수.
+
전체 적중 블록은 SSD 캐시에서 완전히 읽은 블록 수를 나타냅니다. SSD 캐시는 전체 캐시 적중률이 높은 작업의 성능에만 유용합니다.

* * Partial Hits * -- SSD 캐시에 블록이 하나 이상 있지만 모든 블록이 있는 호스트 읽기 수입니다. 기본 볼륨에서 읽기가 처리된 SSD 캐시 * Miss * 입니다.
+
부분 캐시 적중 및 부분 캐시 적중 블록은 SSD 캐시에 데이터 중 일부만 있는 작업으로 인해 발생합니다. 이 경우 작업은 캐시된 HDD 볼륨에서 데이터를 검색해야 합니다. SSD Cache는 이러한 유형의 적중에는 성능 이점이 없습니다. 부분 캐시 적중 블록 수가 전체 캐시 적중 블록보다 많을 경우 다른 입출력 특성 유형(파일 시스템, 데이터베이스 또는 웹 서버)으로 인해 성능이 향상될 수 있습니다.

* * 부분 조회수 -- 블록 * -- 부분 조회수 블록 수.
+
부분 캐시 적중 및 부분 캐시 적중 블록은 SSD 캐시에 데이터 중 일부만 있는 작업으로 인해 발생합니다. 이 경우 작업은 캐시된 HDD 볼륨에서 데이터를 검색해야 합니다. SSD Cache는 이러한 유형의 적중에는 성능 이점이 없습니다. 부분 캐시 적중 블록 수가 전체 캐시 적중 블록보다 많을 경우 다른 입출력 특성 유형(파일 시스템, 데이터베이스 또는 웹 서버)으로 인해 성능이 향상될 수 있습니다.

* * Misses * -- SSD 캐시에 블록이 하나도 없는 호스트 읽기 수입니다. 이는 SSD 캐시 누락으로, 기본 볼륨에서 읽기가 충족되었습니다.
* * 실패 횟수 -- 블록 * -- 비적중 블록 수입니다.
* * 작업 채우기(호스트 읽기) * -- 기본 볼륨에서 SSD 캐시로 데이터가 복사된 호스트 읽기 수.
* * 작업 채우기(호스트 읽기) -- 블록 * -- 작업 채우기(호스트 읽기)의 블록 수입니다.
* * 작업 채우기(호스트 쓰기) * -- 데이터가 기본 볼륨에서 SSD 캐시로 복사되는 호스트 쓰기 수입니다.
+
쓰기 입출력 작업의 결과로 캐시를 채우지 않는 캐시 구성 설정에 대해 작업 채우기(호스트 쓰기) 수는 0일 수 있습니다.

* * 작업 채우기(호스트 쓰기) -- 블록 * -- 작업 채우기(호스트 쓰기)의 블록 수입니다.
* * Invalidate Actions * -- 데이터가 SSD 캐시에서 무효화되거나 제거된 횟수입니다. 캐시 무효화 작업은 모든 호스트 쓰기 요청, FUA(Forced Unit Access)가 있는 모든 호스트 읽기 요청, 모든 확인 요청 및 기타 상황에 대해 수행됩니다.
* * Recycle Actions * -- SSD 캐시 블록이 다른 기본 볼륨 및/또는 다른 LBA 범위에 다시 사용된 횟수입니다.
+
효과적인 캐시 작업을 위해서는 읽기 및 쓰기 작업의 조합 수에 비해 재활용 횟수가 적다는 것이 중요합니다. 재활용 작업 수가 결합된 읽기 및 쓰기 수에 근접하면 SSD 캐시는 스래싱(thrashing)됩니다. 캐시 용량을 늘려야 하거나 워크로드를 SSD 캐시에 사용하는 것이 적합하지 않습니다.

* * Available Bytes * -- SSD 캐시에서 이 컨트롤러에서 사용할 수 있는 바이트 수입니다.
+
사용 가능한 바이트, 할당된 바이트 및 사용자 데이터 바이트는 캐시 할당 % 및 캐시 사용률 %를 계산하는 데 사용됩니다.

* * Allocated Bytes * -- 이 컨트롤러가 SSD 캐시에서 할당한 바이트 수입니다. SSD 캐시에서 할당된 바이트가 비어 있거나 기본 볼륨의 데이터를 포함할 수 있습니다.
+
사용 가능한 바이트, 할당된 바이트 및 사용자 데이터 바이트는 캐시 할당 % 및 캐시 사용률 %를 계산하는 데 사용됩니다.

* * 사용자 데이터 바이트 * -- SSD 캐시에서 기본 볼륨의 데이터를 포함하는 할당된 바이트 수입니다.
+
사용 가능한 바이트, 할당된 바이트 및 사용자 데이터 바이트는 캐시 할당 % 및 캐시 사용률 %를 계산하는 데 사용됩니다.





== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
