---
permalink: commands-a-z/show-snapimage.html 
sidebar: sidebar 
keywords: show, snapshot, image 
summary: show SnapImage 명령은 사용자가 이전에 생성한 스냅샷 이미지에 대한 정보를 반환합니다. 
---
= 스냅샷 이미지를 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'SnapImage 표시' 명령은 사용자가 이전에 생성한 스냅샷 이미지에 대한 정보를 반환합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 특정 스냅샷 이미지를 표시하는 구문

[listing, subs="+macros"]
----
show (allSnapImages | snapImage pass:quotes[["_snapImageName_"]] |
snapImages pass:quotes[["_snapImageName1_" ... "_snapImageNamen_"]])
[summary]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
올스냅이미지
 a| 
스토리지 배열의 모든 스냅샷 이미지에 대한 정보를 반환하는 매개 변수입니다.



 a| 
'냅이미지'
 a| 
정보를 검색할 스냅샷 이미지의 이름입니다. 스냅샷 이미지의 이름은 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' -- 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' -- 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 대괄호([ ]) 안에 묶어야 합니다.



 a| 
"냅이미지"
 a| 
정보를 검색할 여러 스냅샷 이미지의 이름입니다. 다음 규칙을 사용하여 스냅샷 이미지의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
양호실
 a| 
이 매개 변수는 스냅샷 이미지에 대한 간략한 정보 목록을 반환합니다.

|===


== 참고

스냅샷 이미지의 이름은 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 식별자입니다
* 스냅샷 이미지의 식별자입니다


예를 들어 snapGroup1 이라는 이름의 스냅샷 그룹에 스냅샷 이미지 12345를 표시하려면 다음 명령을 사용합니다.

[listing]
----
show snapImage ["snapGroup1:12345"];
----
snapGroup1 이라는 이름의 스냅샷 그룹에 최신 스냅샷 이미지를 표시하려면 다음 명령을 사용합니다.

[listing]
----
show snapImage ["snapGroup1:newest"];
----
스냅샷 이미지를 snapGroup1, snapGroup2 및 snapGroup3이라는 이름이 있는 여러 스냅샷 정합성 보장 그룹에 표시하려면 다음 명령을 사용합니다.

[listing]
----
show snapImages ["snapGroup1:12345 snapGroup2:newest snapGroup3:oldest"];
----


== 최소 펌웨어 레벨입니다

7.83
