---
permalink: commands-a-z/show-volume-summary.html 
sidebar: sidebar 
keywords: show, volume 
summary: show volume summary 명령은 볼륨에 대한 정보를 반환합니다. 
---
= 볼륨 표시
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'show volume summary' 명령은 볼륨에 대한 정보를 반환합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 스토리지 모니터 역할이 있어야 합니다.



== 상황

스토리지 배열의 볼륨에 대해 이 명령은 다음 정보를 반환합니다.

* 볼륨 수입니다
* 이름
* 상태
* 용량
* RAID 레벨
* 볼륨이 있는 볼륨 그룹입니다
* 세부 정보:
+
** 볼륨 ID입니다
** 하위 시스템 ID입니다
** 드라이브 유형(SAS)
** 트레이 손실 방지
** 선호하는 소유자
** 현재 소유자
** 세그먼트 크기
** 수정 우선 순위입니다
** 읽기 캐시 상태(설정 또는 해제)
** 쓰기 캐시 상태(설정 또는 해제)
** 배터리가 없는 쓰기 캐시 상태(활성화 또는 비활성화)
** 미러 상태(설정 또는 해제)가 있는 쓰기 캐시
** 시간이 지나면 쓰기 캐시를 플러시합니다
** 캐시 읽기 프리페치 설정(TRUE 또는 FALSE)
** 백그라운드 미디어 검사 활성화 상태(활성화 또는 비활성화)
** 중복성 검사 상태(활성화 또는 비활성화)로 미디어 검사


* 미러 저장소 볼륨




== 구문

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'올볼륨'
 a| 
이 매개 변수는 스토리지 배열의 모든 볼륨에 대한 성능 통계를 반환합니다.



 a| 
'볼륨'
 a| 
정보를 검색할 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자나 숫자가 있는 경우 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'볼륨'
 a| 
정보를 검색할 여러 볼륨의 이름입니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자나 숫자가 있으면 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
양호실
 a| 
볼륨에 대한 간략한 정보 목록을 반환하는 설정입니다.

|===