---
permalink: commands-a-z/show-asyncmirrorgroup-summary.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, groups 
summary: show asyncMirrorGroup summary 명령은 하나 이상의 비동기식 미러 그룹에 대한 구성 정보를 표시합니다. 
---
= 비동기식 미러 그룹을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show asyncMirrorGroup summary' 명령은 하나 이상의 비동기식 미러 그룹에 대한 구성 정보를 표시합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

또한 이 명령은 불완전한 비동기 미러링 쌍을 포함하여 각 비동기 미러 그룹과 연결된 비동기 미러링된 쌍을 표시합니다.

또한 이 명령을 사용하여 비동기식 미러 그룹 내의 모든 미러링된 쌍에서 주기적 데이터 동기화 진행률을 표시할 수 있습니다.



== 구문

[source, cli, subs="+macros"]
----
show (allAsyncMirrorGroups |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_asyncMirrorGroupName1_ ... _asyncMirrorGroupNameN_]])
[summary]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
알AsyncMirrorGroups
 a| 
모든 비동기식 미러 그룹의 속성을 표시하려면 이 매개 변수를 사용합니다.



 a| 
아인치마그룹
 a| 
구성 정보를 표시할 비동기식 미러 그룹의 이름과 주기적 데이터 동기화 진행률을 표시합니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 비동기 미러 그룹 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
asyncMirrorGroups라는 두 그룹이 있습니다
 a| 
정보를 검색할 여러 비동기식 미러 그룹의 이름입니다. 다음 규칙을 사용하여 비동기식 미러 그룹의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


비동기식 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
양호실
 a| 
이 매개 변수는 하나 이상의 비동기식 미러 그룹의 동기화 진행 상황에 대한 간략한 정보 목록을 표시합니다.

|===


== 최소 펌웨어 레벨입니다

7.84

11.80은 EF600 및 EF300 어레이 지원을 추가합니다
