---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: show allDrives 명령은 스토리지 배열의 드라이브에 대한 정보를 반환합니다. 
---
= 드라이브 표시 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show allDrives' 명령은 스토리지 배열의 드라이브에 대한 정보를 반환합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

스토리지 배열의 각 드라이브에 대해 이 명령은 다음 정보를 반환합니다.

* 총 드라이브 수입니다
* 드라이브 유형(SAS 또는 NVMe4K)
* 기본 드라이브에 대한 정보:
+
** 용지함 위치 및 슬롯 위치
** 상태
** 용량
** 데이터 전송 속도입니다
** 제품 ID입니다
** 펌웨어 버전입니다


* SSD 드라이브의 마모 수명 정보(어레이에 SSD 드라이브가 없는 경우 이 정보는 표시되지 않음):
+
** 평균 지우기 횟수.
** 여유 스페어 블록입니다.
** 사용된 내구성 비율(11.41 릴리스의 새로운 기능). 사용된 내구성 비율은 현재까지 SSD 드라이브에 기록된 데이터의 양을 이론적인 총 쓰기 한계로 나눈 값입니다.


* 드라이브 채널에 대한 정보:
+
** 용지함 위치 및 슬롯 위치
** 기본 채널입니다
** 중복 채널입니다


* 핫 스페어 커버리지
* 각 드라이브에 대한 세부 정보입니다
+
[NOTE]
====
NVMe 드라이브에는 제조 날짜 정보를 사용할 수 없습니다.

====




== 구문

[source, cli, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'allDrives'(allDrives)
 a| 
스토리지 배열의 모든 드라이브에 대한 정보를 반환하는 설정입니다.



 a| 
"MediaType"입니다
 a| 
정보를 검색할 드라이브 미디어의 유형입니다. 다음 값은 유효한 드라이브 미디어 유형입니다.

* HDD -- 드라이브 트레이에 하드 드라이브가 있는 경우 이 옵션을 사용합니다
* 'SD' -- 드라이브 트레이에 솔리드 스테이트 드라이브가 있는 경우 이 옵션을 사용합니다
* 알 수 없음 -- 드라이브 트레이에 어떤 유형의 드라이브 미디어가 있는지 확실하지 않으면 이 옵션을 사용합니다
* AllMedia -- 드라이브 트레이에 있는 모든 유형의 드라이브 미디어를 사용하려면 이 옵션을 사용합니다




 a| 
'driveType'입니다
 a| 
정보를 검색할 드라이브 유형입니다. 드라이브 유형을 혼합할 수 없습니다.

유효한 드라이브 유형은 다음과 같습니다.

* 'AS'입니다
* '아메네4K'


드라이브 유형을 지정하지 않으면 명령이 기본적으로 모든 유형으로 설정됩니다.



 a| 
'늑대'나 '늑대'가 있습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
양호실
 a| 
상태, 용량, 데이터 전송 속도, 제품 ID 및 지정된 드라이브의 펌웨어 버전을 반환하는 설정입니다.

|===


== 참고

스토리지 배열의 모든 드라이브의 유형과 위치에 대한 정보를 확인하려면 "allDrives" 매개 변수를 사용합니다.

스토리지 배열의 SAS 드라이브에 대한 정보를 확인하려면 "드라이브 유형" 매개 변수를 사용합니다.

특정 위치의 드라이브 유형을 확인하려면 "드라이브" 매개변수를 사용하고 트레이 ID와 드라이브의 슬롯 ID를 입력하십시오.

"드라이브" 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 최소 펌웨어 레벨입니다

5.43

7.60은 'drawerID' 사용자 입력과 'drivMediaType' 파라미터를 추가한다.

8.41은 E2800, E5700 또는 EF570 시스템의 SSD 드라이브에 사용되는 내구성의 백분율로 마모 수명 보고 정보를 추가합니다.
