---
permalink: commands-a-z/show-controller-nvsram.html 
sidebar: sidebar 
keywords: show, controller, nvsram 
summary: show controller NVSRAM 명령은 NVSRAM 바이트 값에 대한 정보를 반환합니다. 
---
= 컨트롤러 NVSRAM 표시 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show controller NVSRAM' 명령어는 NVSRAM 바이트 값에 대한 정보를 반환합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 지정된 호스트 유형에 대한 NVSRAM 바이트 값 목록을 반환합니다. 선택적 매개 변수를 입력하지 않으면 이 명령은 모든 NVSRAM 바이트 값 목록을 반환합니다.



== 구문

[source, cli, subs="+macros"]
----
show (allControllers | controller [(a|b)])
NVSRAM pass:quotes[[hostType=_hostTypeIndexLabel_ | host="_hostName_"]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
올컨트롤러
 a| 
스토리지 배열의 두 컨트롤러에 대한 정보를 반환하는 설정입니다.



 a| 
컨트롤러
 a| 
스토리지 배열의 특정 컨트롤러에 대한 정보를 반환하는 설정입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다.



 a| 
호스트 유형
 a| 
호스트 유형의 인덱스 레이블 또는 번호입니다. 사용 가능한 호스트 유형 식별자 목록을 생성하려면 'show storageArray hostTypeTable' 명령을 사용합니다.



 a| 
호스트
 a| 
컨트롤러에 연결된 호스트의 이름입니다. 호스트 이름은 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

'show controller NVSRAM' 명령어를 이용하여 NVSRAM의 일부 또는 전체를 보여주는 것은 'Set controller' 명령어를 이용하여 NVSRAM 값을 변경한다. NVSRAM을 변경하기 전에 기술 지원 부서에 문의하여 수정할 수 있는 NVSRAM 영역을 확인하십시오.
