---
permalink: commands-a-z/show-storagearray-autoconfiguration.html 
sidebar: sidebar 
keywords: show, storage, array, auto, configuration 
summary: show storageArray autoConfiguration 명령은 autoConfigure storageArray 명령을 실행할 경우 스토리지 배열이 생성하는 기본 자동 구성을 표시합니다. 
---
= 스토리지 어레이 자동 구성 표시 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show storageArray autoConfiguration' 명령어는 'autoConfigure storageArray' 명령어를 실행하면 스토리지 배열이 생성하는 기본 자동 구성을 보여 줍니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 스토리지 모니터 역할이 있어야 합니다.



== 상황

스토리지 배열이 특정 속성을 지원할 수 있는지 여부를 확인하려면 이 명령을 실행할 때 속성에 대한 매개 변수를 입력합니다. 구성 정보를 반환하기 위해 이 명령에 대한 매개 변수를 입력할 필요가 없습니다.



== 구문

[source, cli, subs="+macros"]
----
show storageArray autoConfiguration
[driveType=(SAS | NVMe4K)
driveMediaType=(HDD | SSD | unknown | allMedia)
raidLevel=(0 | 1 | 3 | 5 | 6)
pass:quotes[volumeGroupWidth=_numberOfDrives_]
pass:quotes[volumeGroupCount=_numberOfVolumeGroups_]
pass:quotes[volumesPerGroupCount=_numberOfVolumesPerGroup_]
pass:quotes[hotSpareCount=_numberOfHotspares_]
pass:quotes[segmentSize=_segmentSizeValue_]
cacheReadPrefetch=(TRUE | FALSE)
securityType=(none | capable | enabled)
secureDrives=(fips | fde)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'driveType'입니다
 a| 
스토리지 배열에 사용할 드라이브 유형입니다.

스토리지 배열에 한 가지 유형의 드라이브만 있는 경우 driveType 매개 변수는 필요하지 않습니다. 스토리지 배열에 둘 이상의 드라이브 유형이 있는 경우 이 매개변수를 사용해야 합니다.

유효한 드라이브 유형은 다음과 같습니다.

* 'AS'입니다
* '아메네4K'




 a| 
"MediaType"입니다
 a| 
미러 저장소 볼륨 그룹에 사용할 드라이브 미디어의 유형입니다. 유효한 드라이브 미디어는 다음과 같습니다.

* HDD -- 드라이브 트레이에 하드 드라이브가 있는 경우 이 옵션을 사용합니다
* 'SD' -- 드라이브 트레이에 솔리드 스테이트 드라이브가 있는 경우 이 옵션을 사용합니다
* 알 수 없음 -- 드라이브 트레이에 어떤 유형의 드라이브 미디어가 있는지 확실하지 않은 경우 사용합니다
* AllMedia -- 드라이브 트레이에 있는 모든 유형의 드라이브 미디어를 사용하려면 이 옵션을 사용합니다


RepositoryDriveCount' 매개 변수를 사용할 때 이 매개 변수를 사용합니다.

스토리지 배열에 둘 이상의 드라이브 미디어 유형이 있는 경우 이 매개변수를 사용해야 합니다.



 a| 
레이드레벨
 a| 
스토리지 배열의 드라이브가 포함된 볼륨 그룹의 RAID 레벨입니다. 유효한 RAID 레벨은 0, 1, 3, 5, 6입니다.



 a| 
볼륨그룹 너비
 a| 
스토리지 배열의 볼륨 그룹에 있는 드라이브 수로, 드라이브 용량에 따라 다릅니다. 정수 값을 사용합니다.



 a| 
볼륨그룹 카운트
 a| 
스토리지 배열의 볼륨 그룹 수입니다. 정수 값을 사용합니다.



 a| 
볼륨그룹 카운트
 a| 
볼륨 그룹당 동일한 용량의 볼륨 수입니다. 정수 값을 사용합니다.



 a| 
핫SpareCount
 a| 
스토리지 배열에서 원하는 핫 스페어의 수입니다. 정수 값을 사용합니다.



 a| 
'크기'
 a| 
다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 양(KB)입니다. 유효한 값은 8인치, 16인치, 32인치, 64인치, 128입니다. 256, 512.



 a| 
"cacheReadPrefetch"
 a| 
캐시 읽기 프리페치를 설정하거나 해제하는 설정입니다. 캐시 읽기 프리페치를 해제하려면 이 매개 변수를 "false"로 설정합니다. 캐시 읽기 프리페치를 설정하려면 이 매개 변수를 "true"로 설정합니다.



 a| 
'생태형'을 선택합니다
 a| 
볼륨 그룹 및 연결된 모든 볼륨을 생성할 때 보안 수준을 지정하는 설정입니다. 다음 설정이 유효합니다.

* "없음" -- 볼륨 그룹과 볼륨이 안전하지 않습니다.
* "Capable(기능)" -- 볼륨 그룹과 볼륨에 보안 설정이 가능하지만 보안이 활성화되지 않았습니다.
* "활성화됨" -- 볼륨 그룹과 볼륨에 보안이 설정되어 있습니다.




 a| 
'괴상드라이브'
 a| 
볼륨 그룹에서 사용할 보안 드라이브 유형입니다. 다음 설정이 유효합니다.

* FIPS는 FIPS 호환 드라이브만 사용합니다.
* FDE -- FDE 호환 드라이브를 사용합니다.


[NOTE]
====
이 파라미터는 'ecurityType' 파라미터와 함께 사용한다. 'ecurityType' 매개 변수에 'none'을 지정하면 비보안 볼륨 그룹에 지정된 보안 드라이브 유형이 필요하지 않으므로 'ecureDrives' 매개 변수의 값이 무시됩니다.

====
|===


== 참고

속성을 지정하지 않으면 이 명령은 각 드라이브 유형에 대해 RAID 레벨 5 후보를 반환합니다. RAID 레벨 5 후보를 사용할 수 없는 경우 이 명령은 RAID 레벨 6, RAID 레벨 3, RAID 레벨 1 또는 RAID 레벨 0에 대한 후보를 반환합니다. 자동 구성 속성을 지정하면 컨트롤러가 펌웨어가 속성을 지원할 수 있는지 확인합니다.



== 드라이브 및 볼륨 그룹

볼륨 그룹은 스토리지 어레이의 컨트롤러에 의해 논리적으로 그룹화되는 드라이브 세트입니다. 볼륨 그룹의 드라이브 수는 RAID 레벨 및 컨트롤러 펌웨어의 제한 사항입니다. 볼륨 그룹을 생성할 때 다음 지침을 따르십시오.

* 펌웨어 버전 7.10부터 빈 볼륨 그룹을 만들어 나중에 사용할 수 있도록 용량을 예약할 수 있습니다.
* 단일 볼륨 그룹 내에서는 SAS 및 파이버 채널과 같은 드라이브 유형을 혼합할 수 없습니다.
* 볼륨 그룹의 최대 드라이브 수는 다음 조건에 따라 달라집니다.
+
** 컨트롤러의 유형입니다
** RAID 레벨


* RAID 레벨에는 0, 1, 10, 3, 5, 및 6.
+
** CDE3992 또는 CDE3994 스토리지 어레이에서 RAID 레벨 0과 RAID 레벨 10이 있는 볼륨 그룹은 최대 112개의 드라이브를 가질 수 있습니다.
** CE6998 스토리지 어레이에서 RAID 레벨 0과 RAID 레벨 10이 있는 볼륨 그룹은 최대 224개의 드라이브를 가질 수 있습니다.
** RAID 레벨 3, RAID 레벨 5 또는 RAID 레벨 6이 있는 볼륨 그룹은 30개 이상의 드라이브를 가질 수 없습니다.
** RAID 레벨 6을 사용하는 볼륨 그룹은 최소 5개의 드라이브를 포함해야 합니다.
** RAID 레벨 1이 있는 볼륨 그룹에 4개 이상의 드라이브가 있는 경우 스토리지 관리 소프트웨어는 자동으로 볼륨 그룹을 RAID 레벨 1 + RAID 레벨 0인 RAID 레벨 10으로 변환합니다.


* 볼륨 그룹에 용량이 다른 드라이브가 포함된 경우 볼륨 그룹의 전체 용량은 가장 작은 용량의 드라이브를 기준으로 합니다.
* 용지함/서랍 손실 방지를 활성화하려면 다음 표에서 추가 기준을 참조하십시오.


[cols="3*"]
|===
| 레벨 | 트레이 손실 방지 기준 | 필요한 최소 용지함 수입니다 


 a| 
"디스크 풀"
 a| 
디스크 풀에는 하나의 트레이에 두 개 이상의 드라이브가 포함되어 있지 않습니다
 a| 
6



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 트레이에 두 개 이상의 드라이브를 포함하지 않습니다
 a| 
3



 a| 
RAID 3, RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 트레이에 있습니다
 a| 
3



 a| 
RAID 1
 a| 
RAID 1 쌍의 각 드라이브는 별도의 트레이에 있어야 합니다
 a| 
2



 a| 
RAID 0
 a| 
트레이 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===
[cols="3*"]
|===
| 레벨 | 서랍 손실 방지 기준 | 필요한 최소 드로어 수입니다 


 a| 
"디스크 풀"
 a| 
이 풀에는 5개의 드로어 모두에서 드라이브가 포함되며 각 드로어에 동일한 수의 드라이브가 있습니다. 디스크 풀에 15, 20, 25, 30, 35가 포함된 경우 60개 드라이브 트레이가 드로어 손실 방지를 달성할 수 있습니다. 40, 45, 50, 55 또는 60개 드라이브.
 a| 
5



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다.
 a| 
3



 a| 
RAID 3, RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 드로어에 있습니다.
 a| 
3



 a| 
RAID 1
 a| 
미러링된 쌍의 각 드라이브는 별도의 드로어에 위치해야 합니다.
 a| 
2



 a| 
RAID 0
 a| 
문서함 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===


== 핫 스페어

볼륨 그룹의 경우, 데이터를 보호하기 위한 중요한 전략은 스토리지 어레이에서 사용 가능한 드라이브를 핫 스페어 드라이브로 할당하는 것입니다. 핫 스페어는 RAID 1, RAID 3, RAID 5 또는 RAID 6 볼륨 그룹에서 드라이브 장애가 발생할 경우 스토리지 어레이에서 대기 역할을 하는 데이터가 없는 드라이브입니다. 핫 스페어는 스토리지 어레이에 또 다른 수준의 이중화를 추가합니다.

일반적으로 핫 스페어 드라이브의 용량은 보호 중인 드라이브의 사용된 용량과 같거나 더 커야 합니다. 핫 스페어 드라이브는 보호 중인 드라이브와 동일한 미디어 유형, 인터페이스 유형 및 용량이 동일해야 합니다.

스토리지 배열의 드라이브에 오류가 발생하면 일반적으로 핫 스페어는 사용자의 개입 없이 장애가 발생한 드라이브에 대해 자동으로 대체됩니다. 드라이브에 오류가 발생할 때 핫 스페어를 사용할 수 있는 경우 컨트롤러는 중복 데이터 패리티를 사용하여 핫 스페어에 데이터를 재구성합니다. 또한 데이터 대피 지원을 통해 소프트웨어가 드라이브를 "실패"로 표시하기에 앞서 핫 스페어에 데이터를 복사할 수 있습니다.

장애가 발생한 드라이브를 물리적으로 교체한 후 다음 옵션 중 하나를 사용하여 데이터를 복원할 수 있습니다.

장애가 발생한 드라이브를 교체하면 핫 스페어의 데이터가 교체 드라이브로 다시 복사됩니다. 이 동작을 카피백이라고 합니다.

핫 스페어 드라이브를 볼륨 그룹의 영구 구성원으로 지정하는 경우 카피백 작업이 필요하지 않습니다.

볼륨 그룹에 대한 트레이 손실 방지 및 드로어 손실 보호는 볼륨 그룹을 구성하는 드라이브의 위치에 따라 달라집니다. 드라이브 장애 및 핫 스페어 드라이브의 위치 때문에 트레이 손실 방지 및 드로어 손실 보호가 손실될 수 있습니다. 트레이 손실 방지 및 서랍 손실 보호가 영향을 받지 않도록 하려면, 카피백 프로세스를 시작하기 위해 고장난 드라이브를 교체해야 합니다.

스토리지 시스템은 DA 지원 볼륨의 핫 스페어 적용 범위를 위해 DA(Data Assurance) 가능 드라이브를 자동으로 선택합니다.

DA 지원 볼륨의 핫 스페어 적용 범위를 위해 스토리지 어레이에 DA 지원 드라이브가 있는지 확인합니다. DA 지원 드라이브에 대한 자세한 내용은 Data Assurance 기능을 참조하십시오.

보안 가능(FIPS 및 FDE) 드라이브는 보안 기능과 비보안 기능 드라이브 모두를 위한 핫 스페어로 사용할 수 있습니다. 비보안 가능 드라이브는 보안이 설정되지 않은 다른 드라이브와 볼륨 그룹에 보안 기능이 활성화되어 있지 않은 경우 보안 기능이 있는 드라이브에 적용 범위를 제공할 수 있습니다. FIPS 볼륨 그룹은 FIPS 드라이브만 핫 스페어로 사용할 수 있지만, FIPS 핫 스페어를 사용하여 비보안, 보안 기능 및 보안 지원 볼륨 그룹에 적용할 수 있습니다.

핫 스페어가 없는 경우에도 스토리지 어레이가 작동하는 동안 장애가 발생한 드라이브를 교체할 수 있습니다. 드라이브가 RAID 1, RAID 3, RAID 5 또는 RAID 6 볼륨 그룹의 일부인 경우 컨트롤러는 중복 데이터 패리티를 사용하여 데이터를 교체 드라이브에 자동으로 재구성합니다. 이 동작을 재구성 이라고 합니다.



== 세그먼트 크기

세그먼트 크기에 따라 다음 드라이브에 데이터를 쓰기 전에 컨트롤러가 볼륨의 단일 드라이브에 쓰는 데이터 블록 수가 결정됩니다. 각 데이터 블록에는 512바이트의 데이터가 저장됩니다. 데이터 블록은 가장 작은 스토리지 단위입니다. 세그먼트의 크기에 따라 포함된 데이터 블록의 수가 결정됩니다. 예를 들어 8KB 세그먼트에는 16개의 데이터 블록이 있습니다. 64KB 세그먼트에는 128개의 데이터 블록이 있습니다.

세그먼트 크기에 대한 값을 입력하면 이 값은 런타임에 컨트롤러에서 제공하는 지원되는 값과 비교하여 확인됩니다. 입력한 값이 유효하지 않으면 컨트롤러가 유효한 값 목록을 반환합니다. 단일 요청에 단일 드라이브를 사용하면 다른 드라이브를 사용할 수 있어 다른 요청을 동시에 처리할 수 있습니다. 볼륨이 단일 사용자가 대용량 데이터(예: 멀티미디어)를 전송하는 환경에 있는 경우 단일 데이터 전송 요청을 단일 데이터 스트라이프로 처리할 때 성능이 극대화됩니다. (데이터 스트라이프는 세그먼트 크기로, 볼륨 그룹의 데이터 전송에 사용되는 드라이브 수를 곱합니다.) 이 경우 여러 드라이브가 동일한 요청에 사용되지만 각 드라이브는 한 번만 액세스됩니다.

다중 사용자 데이터베이스 또는 파일 시스템 스토리지 환경에서 최적의 성능을 얻으려면 세그먼트 크기를 설정하여 데이터 전송 요청을 충족하는 데 필요한 드라이브 수를 최소화하십시오.



== 캐시 읽기 프리페치

캐시 읽기 프리페치를 사용하면 컨트롤러는 추가 데이터 블록을 캐시로 복사하는 한편, 컨트롤러는 호스트에서 요청한 데이터 블록을 드라이브에서 캐시로 읽고 복사합니다. 이 작업을 수행하면 캐시에서 향후 데이터 요청을 처리할 수 있는 가능성이 높아집니다. 캐시 읽기 프리페치는 순차 데이터 전송을 사용하는 멀티미디어 응용 프로그램에 중요합니다. cacheReadPrefetch 파라미터의 유효한 값은 TRUE나 FALSE입니다. 기본값은 true입니다.



== 보안 유형입니다

'ecurityType' 매개 변수를 사용하여 스토리지 배열의 보안 설정을 지정합니다.

'ecurityType' 매개 변수를 'enabled'로 설정하려면 먼저 스토리지 배열 보안 키를 생성해야 합니다. 스토리지 배열 보안 키를 생성하려면 "create storageArray securityKey" 명령을 사용합니다. 이러한 명령은 보안 키와 관련이 있습니다.

* 스토리지 배열 보안 키 만들기
* securityKey 내보내기
* 스토리지 배열 보안 키 가져오기
* 'et storageArray securityKey'를 선택합니다
* 볼륨그룹 [volumeGroupName] 보안 활성화
* 'diskpool [diskPoolName] 보안 설정'




== 드라이브 보안

보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. 'ecureDrives' 매개 변수를 사용하여 사용할 보안 드라이브 유형을 지정합니다. 사용할 수 있는 값은 FIPS와 FDE입니다.



== 명령 예

[listing]
----
show storageArray autoConfiguration securityType=capable secureDrives=fips;
----


== 최소 펌웨어 레벨입니다

7.10은 RAID 레벨 6 기능을 추가하고 핫 스페어 제한을 제거합니다.

7.50은 'ecurityType' 파라미터를 추가한다.

7.75는 '다카Assurance' 파라미터를 추가합니다.

8.25는 'ecureDrives' 파라미터를 추가한다.
