---
permalink: commands-a-z/show-asyncmirrorgroup-synchronizationprogress.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, group, synchronization, progress 
summary: show asyncMirrorGroup SynchronizationProgress 명령은 로컬 스토리지와 원격 스토리지 시스템 간에 비동기 미러 그룹을 주기적으로 동기화하는 진행률을 표시합니다. 
---
= 비동기식 미러 그룹 동기화 진행률을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'show asyncMirrorGroup SynchronizationProgress' 명령은 로컬 스토리지와 원격 스토리지 시스템 간의 비동기식 미러 그룹의 _PERIODIC_SYNLOCY 진행률을 표시합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800 및 E5700 어레이를 포함한 개별 스토리지 어레이에 적용됩니다. 모든 SMcli 패키지가 설치된 경우



== 역할

E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령은 비동기식 미러 그룹 내의 모든 미러링된 쌍에서 데이터 동기화 진행률을 반환합니다. 이 명령은 완료된 데이터 동기화의 백분율로 진행률을 표시합니다.

[NOTE]
====
동기화에는 초기 동기화와 주기적 동기화의 두 가지 유형이 있습니다. 초기 비동기 미러 그룹 동기화 진행률은 * long running Operations * 대화 상자와 'show storageArray longRunningOperations' 명령을 실행하여 표시됩니다.

====


== 구문

[listing, subs="+macros"]
----
show asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
[synchronizationProgress]
[summary]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
아인치마그룹
 a| 
로컬 스토리지와 원격 스토리지 시스템 간에 비동기식 미러 그룹의 동기화를 표시할 비동기식 미러 그룹의 이름입니다. 비동기 미러 그룹 이름은 대괄호([ ])로 묶어야 합니다. 비동기 미러 그룹 이름에 특수 문자나 숫자가 있는 경우 비동기 미러 그룹 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'동기화 진행률'
 a| 
이 매개 변수는 비동기식 미러 그룹의 주기적 동기화 진행률을 표시합니다.



 a| 
양호실
 a| 
이 매개 변수는 로컬 스토리지와 원격 스토리지 시스템 간의 비동기식 미러 그룹 동기화에 대한 간략한 정보 목록을 표시합니다.

|===


== 최소 펌웨어 레벨입니다

7.84
