---
permalink: commands-a-z/show-diskpool.html 
sidebar: sidebar 
keywords: show, disk pool 
summary: show diskpool 명령은 디스크 풀에 대한 정보를 반환합니다. 
---
= 디스크 풀 표시 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'show diskpool' 명령은 디스크 풀에 대한 정보를 반환합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령어는 디스크 풀에 대한 다음 정보를 반환합니다.

* 상태(예: 최적, 성능 저하, 실패, 누락)
* 총 용량입니다
* 보존 용량, 가용 용량 및 사용할 수 없는 용량입니다
* 사용된 용량, 사용 가능한 용량 및 전체 백분율입니다
* 현재 소유자(슬롯 A의 컨트롤러 또는 슬롯 B의 컨트롤러)
* 드라이브 미디어(SAS)
* 드라이브 미디어 유형(HDD 또는 SSD)
* 드라이브 인터페이스 유형(파이버 채널, iSCSI, InfiniBand, SAS)
* 트레이 손실 방지(예 또는 아니요)
* Secure Capable - 디스크 풀이 모든 보안 가능 드라이브로 구성되어 있는지 여부를 나타냅니다. FDE 드라이브 또는 FIPS 드라이브일 수 있습니다.
* 보안 - 디스크 풀에 드라이브 보안이 설정되어 있는지 여부를 나타냅니다(이것을 보안 활성화라고 함).
* 남은 용량 알림 설정(위험 및 조기 경고)
* 우선 순위 설정
* 연결된 볼륨 및 사용 가능한 용량입니다
* 연결된 드라이브
* Data Assurance 기능 및 Data Assurance가 지원되는 볼륨 존재
* 리소스 프로비저닝 기능




== 구문

[source, cli, subs="+macros"]
----
pass:quotes[show diskPool [_diskPoolName_]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
디즈크풀
 a| 
정보를 검색할 디스크 풀의 이름입니다. 디스크 풀 이름은 대괄호([ ])로 묶어야 합니다. 디스크 풀 이름에 특수 문자나 숫자가 있는 경우 디스크 풀 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.

|===


== 참고

스토리지 배열 프로파일의 디스크 풀 내용을 표시하려면 이 명령을 사용합니다.



== 최소 펌웨어 레벨입니다

7.83
