---
permalink: commands-a-z/show-storagearray.html 
sidebar: sidebar 
keywords: show, storage, array 
summary: show storageArray 명령어는 스토리지 배열에 대한 구성 정보를 반환합니다. 
---
= 스토리지 배열을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'show storageArray' 명령어는 스토리지 배열에 대한 구성 정보를 반환합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 또는 스토리지 모니터 역할이 있어야 합니다.



== 상황

매개 변수는 스토리지 배열의 구성 요소와 기능에 대한 값 목록을 반환합니다. 단일 매개 변수 또는 둘 이상의 매개 변수를 사용하여 명령을 입력할 수 있습니다. 매개 변수 없이 명령을 입력하면 전체 스토리지 배열 프로파일이 표시됩니다(' * profile *' 매개 변수를 입력한 것과 동일한 정보).



== 구문

[listing]
----
show storageArray
[autoSupport| autoSupportConfig | profile |
batteryAge | connections | defaultHostType | healthStatus |
hostTypeTable | hotSpareCoverage | features | time |
volumeDistribution | longRunningOperations | summary | preferredVolumeOwners |
iscsiNegotiationDefaults | unconfiguredIscsiInitiators | autoLoadBalancingEnable |
cacheMirrorDataAssuranceCheckEnable | hostConnectivityReporting]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'autoLoadBalancingEnable'
 a| 
자동 로드 밸런싱 기능의 활성화 상태를 반환하는 매개 변수입니다.

[NOTE]
====
자동 로드 밸런싱 기능이 활성화되면 호스트 연결 보고 기능도 활성화됩니다.

====


 a| 
'AutoSupport'입니다
 a| 
[NOTE]
====
이 매개 변수는 'https' 클라이언트 유형으로 실행되는 E2800 또는 E5700 스토리지 어레이에만 유효합니다. 클라이언트 유형으로 실행되는 E2800 또는 E5700 스토리지 어레이의 경우 'autoSupportConfig' 매개 변수를 사용하십시오.

====


 a| 
자동 지원 구성
 a| 
지원 데이터를 자동으로 수집하는 작업의 현재 상태에 대한 정보를 반환하는 매개 변수입니다. 다음 정보가 반환됩니다.

* 작업의 활성화 또는 비활성화 여부를 나타냅니다
* 지원 데이터 파일이 있는 폴더의 위치입니다


[NOTE]
====
이 매개 변수는 '심볼' 클라이언트 유형으로 실행되는 E2800 또는 E5700 스토리지 어레이에만 유효합니다. 'https' 클라이언트 유형으로 실행되는 E2800 또는 E5700 스토리지 어레이의 경우 ' * AutoSupport * ' 매개 변수를 사용합니다.

====


 a| 
'배터리 시대'
 a| 
상태, 배터리 수명(일) 및 배터리 교체가 필요한 날짜 수를 표시하는 매개 변수입니다. 두 배터리에 대한 정보가 표시됩니다.



 a| 
"cacheMirrorDataAssuranceCheckEnable"을 참조하십시오
 a| 
캐시 미러 데이터 보증 기능의 사용 상태를 반환하는 매개 변수입니다.



 a| 
'연결'을 선택합니다
 a| 
드라이브 채널 포트의 위치 및 드라이브 채널이 연결되는 위치를 보여 주는 매개 변수입니다.



 a| 
"defaultHostType"입니다
 a| 
기본 호스트 유형과 호스트 유형 인덱스를 표시하는 매개 변수입니다.



 a| 
기능
 a| 
스토리지 배열의 기능 구성을 표시하는 매개 변수입니다.



 a| 
건강상태
 a| 
스토리지 배열의 상태, 논리 속성 및 물리적 구성 요소 속성을 표시하는 매개 변수입니다.



 a| 
호스트연결보고
 a| 
호스트 연결 보고 기능의 활성화 상태를 반환하는 매개 변수입니다.



 a| 
'hostTypeTable'입니다
 a| 
컨트롤러에 알려진 모든 호스트 유형의 테이블을 표시하는 매개 변수입니다. 표의 각 행은 호스트 유형 인덱스와 호스트 유형 인덱스가 나타내는 플랫폼을 보여 줍니다.



 a| 
핫스파레커버리지
 a| 
핫 스페어 범위가 있는 스토리지 어레이 볼륨과 그렇지 않은 볼륨에 대한 정보를 표시하는 매개 변수입니다.



 a| 
iscsiNegotiationDefaults를 선택합니다
 a| 
이니시에이터-타겟 협상에 영향을 받는 연결 레벨 설정에 대한 정보를 반환하는 매개 변수입니다.



 a| 
롱런닝운영
 a| 
매개 변수는 스토리지 배열의 각 볼륨 그룹 및 각 볼륨에 대해 오래 실행되는 작업을 나타냅니다.

longRunningOperation 매개 변수는 다음 정보를 반환합니다.

* 볼륨 그룹 또는 볼륨의 이름입니다
* 긴 작동
* 상태
* % 완료
* 남은 시간




 a| 
우선적 볼륨 소유자
 a| 
스토리지 어레이의 각 볼륨에 대해 선호하는 컨트롤러 소유자를 표시하는 매개 변수입니다.



 a| 
프로필
 a| 
스토리지 배열을 구성하는 물리적 구성 요소와 논리적 구성 요소의 모든 속성을 표시하는 매개 변수입니다. 정보가 여러 화면에 나타납니다.

[NOTE]
====
profile 매개 변수는 스토리지 배열에 대한 자세한 정보를 반환합니다. 이 정보는 디스플레이의 여러 화면에 적용됩니다. 모든 정보를 보려면 디스플레이 버퍼의 크기를 늘려야 할 수 있습니다. 이 정보는 매우 상세하므로 이 매개 변수의 출력을 파일에 저장할 수 있습니다.

====
다음 명령을 사용하여 프로파일 출력을 파일에 저장합니다.

[listing]
----
c:\...\smX\client>smcli 123.45.67.88
123.45.67.89 -c "show storagearray profile;"
-o "c:\folder\storagearray
profile.txt"
----


 a| 
양호실
 a| 
스토리지 배열 구성에 대한 정보를 간략하게 보여 주는 매개 변수입니다.



 a| 
시간
 a| 
매개 변수는 스토리지 배열의 두 컨트롤러가 모두 설정된 현재 시간을 나타냅니다.



 a| 
'unconfiguredIscsiInitiators'
 a| 
스토리지 배열에 의해 감지되었지만 아직 스토리지 배열 토폴로지로 구성되지 않은 이니시에이터 목록을 반환하는 매개 변수입니다.



 a| 
'볼륨 분포'
 a| 
스토리지 배열의 각 볼륨에 대한 현재 컨트롤러 소유자를 표시하는 매개 변수입니다.

|===


== 참고

profile 매개 변수는 스토리지 배열에 대한 자세한 정보를 표시합니다. 이 정보는 디스플레이 모니터의 여러 화면에 나타납니다. 모든 정보를 보려면 디스플레이 버퍼의 크기를 늘려야 할 수 있습니다. 이 정보는 매우 상세하므로 이 매개 변수의 출력을 파일에 저장할 수 있습니다. 출력을 파일로 저장하려면 이 예제와 같은 'show storageArray' 명령을 실행합니다.

[listing]
----
-c "show storageArray profile;" -o "c:\\folder\\storageArrayProfile.txt"
----
이전 명령 구문은 Windows 운영 체제를 실행하는 호스트를 위한 것입니다. 실제 구문은 운영 체제에 따라 다릅니다.

정보를 파일에 저장할 때 해당 정보를 구성 기록으로 사용하고 복구 과정에서 보조 도구로 사용할 수 있습니다.

[NOTE]
====
스토리지 어레이 프로필은 모두 명확하게 레이블이 지정된 많은 양의 데이터를 반환하지만, 8.41 릴리즈의 새로운 기능은 E2800 또는 E5700 스토리지 어레이에서 SSD 드라이브에 대한 추가 마모 수명 보고 정보입니다. 이전의 마모 수명 보고에는 평균 지우기 횟수 및 남은 스페어 블록에 대한 정보가 포함되었지만, 이제 사용된 내구성이 퍼센트로 표시됩니다. 사용된 내구성 비율은 현재까지 SSD 드라이브에 기록된 데이터의 양을 이론적인 총 쓰기 한계로 나눈 값입니다.

====
batteryAge 매개변수는 이 형식으로 정보를 반환합니다.

[listing]
----
Battery status: Optimal
    Age: 1 day(s)
    Days until replacement: 718 day(s)
----
최신 컨트롤러 트레이는 batteryAge 매개변수를 지원하지 않습니다.

defaultHostType 매개 변수는 이 형식으로 정보를 반환합니다.

[listing]
----
Default host type: Linux (Host type index 6)
----
healthStatus 매개 변수는 이 형식으로 정보를 반환합니다.

[listing]
----
Storage array health status = optimal.
----
hostTypeTable 매개 변수는 이 형식으로 정보를 반환합니다.

[listing]
----
NVSRAM HOST TYPE INDEX DEFINITIONS
HOST TYPE                         ALUA/AVT STATUS   ASSOCIATED INDEXS
AIX MPIO                          Disabled          9
AVT_4M                            Enabled           5
Factory Default                   Disabled          0
HP-UX                             Enabled           15
Linux (ATTO)                      Enabled           24
Linux (DM-MP)                     Disabled          6
Linux (Pathmanager)               Enabled           25
Mac OS                            Enabled           22
ONTAP                             Disabled          4
SVC                               Enabled           18
Solaris (v11 or Later)            Enabled           17
Solaris (version 10 or earlier)   Disabled          2
VMWare                            Enabled           10 (Default)
Windows                           Enabled           1
----
hotSpareCoverage 매개변수는 이 형식으로 정보를 반환합니다.

[listing]
----
The following volume groups are not protected: 2, 1
Total hot spare drives: 0
   Standby: 0
   In use: 0
----
features 매개 변수는 사용 가능, 사용 안 함, 평가 및 사용 가능한 기능을 보여 주는 정보를 반환합니다. 이 명령은 다음과 유사한 형식으로 기능 정보를 반환합니다.

[listing]
----
PREMIUM FEATURE           STATUS

asyncMirror               Trial available
syncMirror                Trial available/Deactivated
thinProvisioning          Trial available
driveSlotLimit            Enabled (12 of 192 used)
snapImage                 Enabled (0 of 512 used) - Trial version expires m/d/y
snapshot                  Enabled (1 of 4 used)
storagePartition          Enabled (0 of 2 used)
volumeCopy                Enabled (1 of 511 used)
SSDSupport                Disabled (0 of 192 used) - Feature Key required
driveSecurity             Disabled - Feature Key required
enterpriseSecurityKeyMgr  Disabled - Feature Key required
highPerformanceTier       Disabled - Feature Key required
----
시간 매개 변수는 이 형식으로 정보를 반환합니다.

[listing]
----
Controller in Slot A

Date/Time: Thu Jun 03 14:54:55 MDT 2004
Controller in Slot B

Date/Time: Thu Jun 03 14:54:55 MDT 2004
----
longRunningOperations 매개 변수는 다음 형식으로 정보를 반환합니다.

[listing]
----
LOGICAL DEVICES  OPERATION         STATUS        TIME REMAINING
Volume-2         Volume Disk Copy  10% COMPLETED  5 min
----
longRunningOperations 매개변수가 반환하는 정보 필드는 다음과 같은 의미를 갖습니다.

* 이름(name)은 현재 오래 실행 중인 볼륨의 이름입니다. 볼륨 이름에 "Volume"이 접두사로 있어야 합니다.
* '작동'은 볼륨 그룹 또는 볼륨에 대해 수행되는 작업을 나열합니다.
* "*% 완료 * "는 장시간 동안 실행된 작업을 얼마나 수행했는지 보여줍니다.
* '상태'는 다음 의미 중 하나일 수 있습니다.
+
** 보류 중 -- 장기 실행 작업이 시작되지 않았지만 현재 작업이 완료된 후 시작됩니다.
** 진행 중 -- 오래 실행되는 작업이 시작되었으며 사용자 요청에 의해 완료되거나 중지될 때까지 실행됩니다.


* 남은 시간 은 현재 장기 실행 작업을 완료하는 데 남은 기간을 나타냅니다. 시간은 "시간 분" 형식입니다. 1시간 미만이 남아 있는 경우 분 만 표시됩니다. 1분 미만이 남으면 "[.code] ""1분 미만"" 메시지가 표시됩니다.


volumeDistribution 매개변수는 이 형식으로 정보를 반환합니다.

[listing]
----
volume name: 10
     Current owner is controller in slot: A

volume name: CTL 0 Mirror Repository
     Current owner is controller in slot: A

volume name: Mirror Repository 1
     Current owner is controller in slot:A

volume name: 20
     Current owner is controller in slot:A

volume name: JCG_Remote_MirrorMenuTests
     Current owner is controller in slot:A
----


== 최소 펌웨어 레벨입니다

5.00은 defaultHostType 매개변수를 추가합니다.

5.43은 '요약' 파라미터를 추가합니다.

6.10은 'volumeDistribution' 파라미터를 추가합니다.

6.14는 연결 매개변수를 추가합니다.

7.10은 autoSupportConfig 매개변수를 추가한다.

7.77은 longRunningOperations 매개 변수를 추가합니다.

7.83은 스토리지 관리 소프트웨어 버전 10.83에서 릴리스된 새로운 기능에 대한 지원이 포함된 정보를 반환합니다. 또한 반환된 정보가 확장되어 스토리지 시스템의 기능 상태를 표시합니다.

8.30은 autoLoadBalancingEnable 매개 변수를 추가합니다.

8.40은 AutoSupport 파라미터를 추가한다.

8.40은 'https' 클라이언트 유형으로 실행되는 E2800 또는 E5700 스토리지 어레이에 대한 'autoSupportConfig' 매개 변수를 사용하지 않습니다.

8.41은 SSD 드라이브의 마모 수명 모니터링을 스토리지 어레이 프로필에 추가합니다. 이 정보는 E2800 및 E5700 스토리지 어레이에만 표시됩니다.

8.42는 hostConnectivityReporting 매개변수를 추가합니다.

8.63은 "profile" 매개 변수 결과에 Resource-provisioned Volumes 항목을 추가합니다.
