---
permalink: commands-a-z/smcli-autosupportconfig-test.html 
sidebar: sidebar 
keywords: test, autosupport, configuration 
summary: SMcli -autoSupportConfig 테스트 명령을 사용하여 테스트 메시지를 전송하여 AutoSupport 구성을 테스트합니다. 이 명령은 관리 도메인에서 작동합니다. 스토리지 관리 소프트웨어는 테스트 메시지에 포함할 예시 데이터를 위해 관리 도메인에서 자동 지원 가능 어레이를 선택합니다. 
---
= AutoSupport 구성 테스트 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'SMcli -autoSupportConfig test' 명령어를 이용하여 AutoSupport 설정을 테스트한다. 이 명령은 관리 도메인에서 작동합니다. 스토리지 관리 소프트웨어는 테스트 메시지에 포함할 예시 데이터를 위해 관리 도메인에서 자동 지원 가능 어레이를 선택합니다.



== 지원되는 어레이

이 명령은 관리 도메인에 있는 모든 E2700 및 E5600 스토리지 어레이에 동시에 적용됩니다. E2800 또는 E5700 스토리지 어레이에는 적용되지 않습니다.



== 상황

[NOTE]
====
이 명령은 스크립트 명령이 아니라 SMcli 명령입니다. 명령줄에서 이 명령을 실행해야 합니다. 스토리지 관리 소프트웨어의 스크립트 편집기에서 이 명령을 실행할 수 없습니다.

====
[NOTE]
====
관리 스테이션에서 영구 모니터가 실행되고 있어야 예약 또는 이벤트 트리거 AutoSupport 메시지를 보낼 수 있습니다. 이 명령을 사용하기 전에 서비스를 시작하십시오.

====


== 구문

[source, cli]
----
SMcli -autoSupportConfig test reply-toEmail<address>
----


== 매개 변수

다음 표에는 AutoSupport 테스트 메시지 전송을 위한 매개 변수가 나와 있습니다.

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
"테스트"
 a| 
명령에 필요한 매개 변수입니다. 값이 필요하지 않습니다.



 a| 
e-메일 보내기
 a| 
사용자가 SMTP 배달 유형의 AutoSupport 메시지에 대한 회신 이메일 주소를 지정할 수 있습니다.

|===


== 최소 펌웨어 레벨입니다

8.25



== HTTP/HTTPS 전송을 사용한 테스트의 예

다음은 HTTP 또는 HTTPS 전달 유형을 사용할 때 전달할 전자 메일 주소를 지정하지 않는 이 명령의 사용 예입니다.

[listing]
----
SMcli -autoSupportConfig test
The sample AutoSupport message was successfully sent to the ASUP gateway.

SMcli completed successfully.
----


== SMTP 전달을 사용한 테스트의 예

다음은 이 명령의 사용 예입니다. SMTP 배달 방법을 사용할 때 "reply-toEmail" 매개 변수를 사용하여 대상 주소를 지정할 수 있습니다.

[listing]
----
SMcli -autoSupportConfig test reply-toEmail:user@netapp.com
The sample AutoSupport message was successfully sent to the ASUP gateway.

An email has been sent to 'user@netapp.com', please check the mailbox
for delivery confirmation.

SMcli completed successfully.
----