---
permalink: commands-a-z/smcli-autosupportlog.html 
sidebar: sidebar 
keywords: capture, view, autosupport, log 
summary: SMcli -autoSupportLog 명령을 사용하면 AutoSupport 로그 파일을 볼 수 있습니다. 이 파일은 상태, 전송 작업 기록 및 AutoSupport 메시지 전송 중 발생한 오류에 대한 정보를 제공합니다. 이 로그는 AutoSupport가 지원되는 모든 스토리지 어레이에서 사용할 수 있습니다. 
---
= AutoSupport 로그 캡처 또는 보기 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'smcli -autoSupportLog' 명령을 사용하면 AutoSupport 로그 파일을 볼 수 있습니다. 이 파일은 상태, 전송 작업 기록 및 AutoSupport 메시지 전송 중 발생한 오류에 대한 정보를 제공합니다. 이 로그는 AutoSupport가 지원되는 모든 스토리지 어레이에서 사용할 수 있습니다.



== 지원되는 어레이

이 명령은 관리 도메인에 있는 모든 E2700 및 E5600 스토리지 어레이에 동시에 적용됩니다. E4000, E2800 또는 E5700 스토리지 어레이에는 적용되지 않습니다.



== 상황

이 명령을 사용하면 두 가지 유형의 로그를 볼 수 있습니다.

* 현재 로그 - 이 시점에서 캡처한 로그를 봅니다.
* 아카이브 로그 - 아카이빙된 파일에서 로그를 봅니다.


[NOTE]
====
이 명령은 스크립트 명령이 아니라 SMcli 명령입니다. 명령줄에서 이 명령을 실행해야 합니다. 스토리지 관리 소프트웨어의 스크립트 편집기에서 이 명령을 실행할 수 없습니다.

====


== 구문

[source, cli, subs="+macros"]
----
SMcli -autoSupportLog pass:quotes[(all|-n "_storageArrayName_" | -w "_wwID_")]
pass:quotes[inputArchive=_n_] pass:quotes[outputLog=_filename_]
----


== 매개 변수

다음 표에는 명령 매개 변수가 나와 있습니다.

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
모두
 a| 
AutoSupport 기능이 AutoSupport 활성화된 관리 도메인의 모든 스토리지 시스템에 대한 전송 로그를 생성하려면 이 매개 변수를 사용합니다.



 a| 
'_n_'
 a| 
AutoSupport 로그를 보려는 스토리지 배열의 이름입니다.



 a| 
'_w_'
 a| 
AutoSupport 로그를 보려는 스토리지 어레이의 WWID(World Wide Identifier)입니다.



 a| 
인퍼아카이브
 a| 
아카이브 파일이 0 ~ 5의 정수인 `_n_'인 보관된 AutoSupport 로그를 지정할 수 있습니다.

[NOTE]
====
이 매개 변수를 생략하면 현재 AutoSupport 로그(이 시점에 캡처됨)를 선택할 수 있습니다.

====


 a| 
아웃퍼로그
 a| 
출력 AutoSupport 로그 파일 이름을 지정할 수 있습니다.

[NOTE]
====
이 매개 변수는 필수입니다.

====
|===


== 최소 펌웨어 레벨입니다

8.25



== 예

[listing]
----
SMcli -autosupportLog -n StorageArrayName inputArchive=0 outputLog=ASUPTransmissionLog
----


== 검증

스토리지 관리 소프트웨어가 설치된 클라이언트 디렉토리에 있는 요청한 AutoSupport 로그를 확인합니다.
