---
permalink: commands-a-z/smcli-autosupportschedule-reset.html 
sidebar: sidebar 
keywords: reset, autosupport, message, collection, schedule 
summary: SMcli autoSupportSchedule reset 명령은 AutoSupport 메시지가 전송되는 요일과 주 단위 시간 및 일을 재설정합니다. 관리 소프트웨어에서 생성된 기본 임의 값을 그대로 사용하거나 이 명령을 사용하여 값을 지정할 수 있습니다. 
---
= AutoSupport 메시지 수집 일정 재설정 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'smcli autoSupportSchedule reset' 명령어는 AutoSupport 메시지 발송 요일과 주단위 시간, 일을 리셋한다. 관리 소프트웨어에서 생성된 기본 임의 값을 그대로 사용하거나 이 명령을 사용하여 값을 지정할 수 있습니다.



== 지원되는 어레이

이 명령은 관리 도메인에 있는 모든 E2700 및 E5600 스토리지 어레이에 동시에 적용됩니다. E4000, E2800 또는 E5700 스토리지 어레이에는 적용되지 않습니다.



== 상황

[NOTE]
====
이 명령은 스크립트 명령이 아니라 SMcli 명령입니다. 명령줄에서 이 명령을 실행해야 합니다. 스토리지 관리 소프트웨어의 스크립트 편집기에서 이 명령을 실행할 수 없습니다.

====
* AutoSupport가 활성화된 경우 관리 소프트웨어는 일별 AutoSupport 메시지와 주별 AutoSupport 메시지를 모두 전송합니다.
* 관리 소프트웨어는 일별 및 주별 메시지의 시간과 주별 메시지의 요일을 무작위로 선택합니다. 관리 소프트웨어는 관리 도메인 내의 두 스토리지 시스템이 예약된 AutoSupport 메시지를 동시에 전송하지 않도록 모든 시도를 합니다.
* 매일 전송할 시기와 관리 도메인의 스토리지 시스템에 대해 주간 메시지를 보낼 시점을 시간 단위로 지정할 수 있습니다.
* 주별 스케줄의 경우 AutoSupport 수집 및 전송에 대해 원하는 요일을 선택합니다.




== 구문

[source, cli]
----
SMcli -autoSupportSchedule reset | (dailyTime=<startTime>-<endTime>
   dayOfWeek=[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
   weeklyTime=<startTime>-<endTime>)
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
다시 설정합니다
 a| 
24시간 및 7일 주(일요일~토요일) 시간 간격을 사용하여 새 일정을 재설정 및 생성합니다.



 a| 
'일일일일일일시간'
 a| 
''sttTime''>-<'endtime'> 모든 스토리지 배열에 대한 AutoSupport 데이터 수집을 시작하고 종료할 시간을 지정합니다. startTime과 종료 시간은 HH:MM[am|pm}이어야 합니다.



 a| 
다예OfWeek
 a| 
[일요일 | 월요일 | 화요일 | 수요일 | 목요일 | 금요일 | 토요일] 모든 스토리지 어레이에 대한 AutoSupport 번들 수집 데이터를 수집할 요일의 기본 설정 일(일요일~토요일)을 지정합니다. '_dayOfWeek_' 매개 변수는 대괄호로 묶고 공백으로 구분해야 합니다.



 a| 
주간 시간
 a| 
''sttTime''>-<'endtime'> 사용자가 선택한 요일의 AutoSupport bundle 수집 데이터 수집을 시작하고 종료할 시간을 지정합니다. '_startTime_'과 '_endtime_'은 HH:MM[am|pm] 형식이어야 합니다.

|===


== 최소 펌웨어 레벨입니다

8.25



== 예

[listing]
----
 SMcli -autoSupportSchedule dailyTime=10:00am-11:00am
dayOfWeek=[Monday Thursday Friday] weeklyTime=2:00am-3:00am
----
Smcli -autoSupportSchedule dailyTime = 10:00am - 11:00am dayOfWeek = [월요일 목요일 금요일] 주간 시간 = 2:00am - 3:00am



== 검증

관리 도메인의 스케줄에 대한 변경 결과를 확인하려면 'smcli -autoSupportSchedule show' 명령을 사용합니다.
