---
permalink: commands-a-z/smcli-enable-autosupportfeature.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, emw, management, domain, level, smcli 
summary: 'SMcli enable autoSupportFeatature 명령은 모든 관리형 스토리지 어레이에 대한 AutoSupport(ASUP) 기능을 켜고 메시지를 기술 지원 사이트로 전송할 수 있도록 합니다. ASUP 기능을 활성화하면 모든 ASUP 지원 스토리지 어레이가 자동으로 준비되어 기술 지원을 위해 지원 관련 데이터를 전송합니다. 그런 다음 데이터를 원격 문제 해결 및 문제 분석에 사용할 수 있습니다.' 
---
= EMW 관리 도메인 수준에서 AutoSupport 활성화 또는 비활성화(SMcli만 해당)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'SMcli enable autoSupportFeatature' 명령은 모든 관리형 스토리지 어레이에 대해 AutoSupport(ASUP) 기능을 설정하고 기술 지원 사이트로 메시지를 전송할 수 있도록 합니다. ASUP 기능을 활성화하면 모든 ASUP 지원 스토리지 어레이가 자동으로 준비되어 기술 지원을 위해 지원 관련 데이터를 전송합니다. 그런 다음 데이터를 원격 문제 해결 및 문제 분석에 사용할 수 있습니다.



== 지원되는 어레이

이 명령은 관리 도메인에 있는 모든 E2700 및 E5600 스토리지 어레이에 동시에 적용됩니다. E2800 또는 E5700 스토리지 어레이에는 적용되지 않습니다.



== 상황

[NOTE]
====
이 명령은 스크립트 명령이 아니라 SMcli 명령입니다. 명령줄에서 이 명령을 실행해야 합니다. 스토리지 관리 소프트웨어의 스크립트 편집기에서 이 명령을 실행할 수 없습니다.

====
[NOTE]
====
AutoSupport 기능이 작동하려면 영구 모니터가 활성화되어 있어야 합니다.

====
[NOTE]
====
고객 데이터는 기술 지원 사이트로 전송되지 않습니다.

====
이 명령은 관리 도메인의 모든 ASUP 지원 스토리지 어레이에 영향을 줍니다. 관리 도메인에 대해 이 기능을 설정한 후에는 각 스토리지 어레이에 대한 기능 지원을 제어할 수 있습니다.

이 기능을 활성화한 후 필요에 따라 AutoSupport OnDemand 기능을 활성화한 다음 AutoSupport 원격 진단 기능을 활성화할 수 있습니다(필요한 경우).

다음 순서대로 세 가지 기능을 활성화해야 합니다.

. * AutoSupport 사용 *
. * AutoSupport OnDemand를 활성화합니다
. * AutoSupport 원격 진단 활성화 *




== 구문

[listing]
----
SMcli enable|disable autoSupportFeature
----


== 매개 변수

없음.



== 검증

'smcli -autoSupportConfig show' 명령을 사용하여 이 기능을 활성화했는지 확인합니다. 표시된 출력의 초기 줄은 활성화 상태를 나타냅니다.

[listing]
----
The AutoSupport feature is activated on this storage management station.
----


== 최소 펌웨어 레벨입니다

7.86
