---
permalink: commands-a-z/start-volume-initialize.html 
sidebar: sidebar 
keywords: initialize, thin volume 
summary: 시작 볼륨 초기화 명령은 씬 볼륨을 초기화하거나 다시 초기화합니다. 
---
= 씬 볼륨 초기화 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Start volume initialize' 명령어는 씬 볼륨을 초기화 또는 초기화 한다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 작업은 사용되는 매개 변수에 따라 달라집니다.

* 선택적 매개 변수 없이 사용되는 이 명령은 씬 볼륨의 데이터를 삭제합니다. 저장소 볼륨 용량은 영향을 받지 않습니다.
* 선택적 매개 변수와 함께 사용되는 이 명령은 재초기화 및 저장소 볼륨 작업을 야기합니다.


[NOTE]
====
씬 볼륨을 초기화하면 중지할 수 없는 장기 실행 작업이 시작됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
pass:quotes[[existingRepositoryLabel=_existingRepositoryName_]]
pass:quotes[[diskPool=_diskPoolName_ capacity=_capacityValue_]]
[retainRepositoryMembers=(TRUE|FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
초기화를 시작하는 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자나 숫자가 포함되어 있으면 볼륨 이름을 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
기존 리포지터리 라벨
 a| 
이 매개 변수는 지정된 대상 볼륨으로 저장소 볼륨을 대체합니다.

* 지정된 값은 기존 저장소 볼륨 사용자 레이블입니다. 지정된 볼륨은 올바른 형식의 이름을 가진 사용되지 않는 저장소 볼륨이어야 합니다.
* 새로 지정된 저장소 볼륨이 다른 디스크 풀에 있는 경우 씬 볼륨은 해당 풀에 대한 소유권을 변경합니다.
* 이전 저장소 볼륨은 기본적으로 삭제됩니다.


기존 저장소 볼륨 이름에 특수 문자가 포함되어 있거나 숫자만 포함된 경우 볼륨 이름을 큰따옴표(" ")로 묶어야 합니다.



 a| 
디즈크풀
 a| 
지정된 용량으로 새 저장소 볼륨을 생성할 디스크 풀의 이름입니다. 디스크 풀 이름에 특수 문자가 포함되어 있거나 숫자만 포함된 경우 디스크 풀 이름은 큰따옴표(" ")로 묶어야 합니다.

이 매개 변수를 'capacity' 매개 변수와 함께 사용하여 지정된 용량의 새 저장소 볼륨을 생성해야 합니다.



 a| 
용량
 a| 
생성 중인 저장소 볼륨에 대해 설정할 크기입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다.

최소 물리적 용량은 4GB입니다.

최대 물리적 용량은 257TB입니다.

이 매개 변수를 diskPool 매개 변수와 함께 사용하여 지정된 용량의 새 저장소 볼륨을 생성해야 합니다.



 a| 
RetainRepositoryMembers(리포지토리 구성원)
 a| 
이 매개 변수를 true로 설정하면 이전 리포지토리가 유지됩니다. 기본적으로 이전 리포지토리는 삭제됩니다. 기존 리포지토리를 재사용하는 경우 이 매개 변수는 무시됩니다.

|===


== 참고

"volume" 매개 변수를 사용하여 볼륨을 지정하지 않으면 이 명령은 리포지토리의 메타데이터를 재설정하고 실제로 씬 볼륨이 호스트에 빈 상태로 표시됩니다. ' * volume * ' 매개 변수를 사용하여 볼륨을 지정하는 경우 해당 볼륨은 새로 생성된 볼륨으로 대체되거나 'existingRepositoryLabel' 매개 변수를 사용하여 볼륨을 지정하는 경우 기존 볼륨으로 대체됩니다. 다른 디스크 풀에 있는 'existingRepositoryLabel' 매개 변수를 사용하여 기존 볼륨을 지정하면 씬 볼륨의 소유권이 새 디스크 풀로 변경됩니다.

가상 용량, 할당량 및 경고 임계값과 같은 씬 볼륨의 볼륨 매개 변수는 씬 볼륨을 다시 초기화한 후 이전 값을 유지합니다.

[NOTE]
====
iaf(Immediate Availability Format)은 64TB 이상의 볼륨에는 적용되지 않습니다.

====
다음 표에는 씬 볼륨의 용량 제한이 나와 있습니다.

[cols="2*"]
|===
| 용량 유형입니다 | 크기 


 a| 
최소 가상 용량입니다
 a| 
32MB



 a| 
최대 가상 용량
 a| 
256TB



 a| 
최소 물리적 용량
 a| 
4GB



 a| 
최대 물리적 용량입니다
 a| 
257TB

|===
씬 볼륨은 표준 볼륨에서 수행하는 다음과 같은 작업을 모두 지원합니다.

* 씬 볼륨의 세그먼트 크기는 변경할 수 없습니다.
* 씬 볼륨에 대한 사전 읽기 이중화 검사는 활성화할 수 없습니다.
* 볼륨 복사본의 타겟 볼륨으로 씬 볼륨을 사용할 수 없습니다.
* 동기 미러링 작업에서는 씬 볼륨을 사용할 수 없습니다.


씬 볼륨을 표준 볼륨으로 변경하려면 볼륨 복사 작업을 사용하여 씬 볼륨의 복사본을 생성합니다. 볼륨 복사본의 대상은 항상 표준 볼륨입니다.



== 최소 펌웨어 레벨입니다

7.83

8.30은 씬 볼륨의 최대 용량을 256TB로 늘립니다.
