---
permalink: commands-a-z/start-controller.html 
sidebar: sidebar 
keywords: start, controller, trace 
summary: start controller 명령은 디버그 추적 정보를 압축된 파일에 저장하는 작업을 시작합니다. 
---
= 컨트롤러 추적 시작 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'tart controller' 명령어는 debug trace 정보를 압축된 파일에 저장하는 작업을 시작한다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

기술 지원 부서에서는 디버그 추적 정보를 사용하여 스토리지 배열의 실행 상태를 분석할 수 있습니다.



== 구문

[source, cli, subs="+macros"]
----
start controller [(a
 | b
 | both)] trace
dataType=(current | flushed | currentFlushed | all)
forceFlush=(TRUE | FALSE)
pass:quotes[file="_fileName_]"
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
추적 디버그 정보를 수집할 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 또한 both를 입력하여 두 컨트롤러에 대한 DEBUG를 동시에 수집할 수도 있습니다. 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.



 a| 
다타타입
 a| 
수집할 데이터 유형:

* Current(현재) -- 현재 DQ 추적을 검색합니다
* Flushed -- 모든 Flushed DQ Trace를 조회한다
* currentFlushed -- 현재 DQ Trace와 Flushed DQ Trace를 모두 검색합니다
* 모두 -- 현재 DQ Trace, Flushed DQ Trace, 모든 Platform DQ Trace를 조회한다


[NOTE]
====
dataType=flushed와 forceFlush=True인 경우, 조회 시 활성 트레이스만 버퍼로 플러시될 수 있음을 나타내는 오류 메시지가 반환됩니다.

====


 a| 
' * forceFlush * '
 a| 
dataType 파라미터에 정의된 DQ Trace 정보를 조회할 때 현재 버퍼의 DQ 정보를 flushed buffer로 이동하도록 설정 강제 플러시를 활성화하려면 이 매개변수를 "TRUE"로 설정합니다. 강제 송기를 비활성화하려면 이 매개변수를 "false"로 설정합니다.

[NOTE]
====
dataType=flushed와 forceFlush=True인 경우, 조회 시 활성 트레이스만 버퍼로 플러시될 수 있음을 나타내는 오류 메시지가 반환됩니다.

====


 a| 
'파일'
 a| 
DQ 추적 정보를 저장할 파일 경로 및 파일 이름입니다. 파일 이름은 큰따옴표(" ")로 묶어야 합니다.

파일 이름 지정에 대한 자세한 내용은 참고 섹션을 참조하십시오.

|===


== 참고

DQ 추적 정보는 .zip 확장자로 압축된 파일에 기록됩니다. 파일 이름은 사용자 정의 파일 이름과 스토리지 배열 식별자(예:)의 조합입니다. "DQ"의 상수도 파일 이름에 추가됩니다. 전체 파일 이름에는 다음 형식이 있습니다.

[listing]
----
user_defined_file_name-SAID-dq.zip
----
압축된 파일에는 이 표에 나열된 정보가 들어 있습니다.

[cols="3*"]
|===
| 파일 이름 | 디렉토리 | 설명 


 a| 
'user_provided_file_name-sa.dq'
 a| 
'보조/타임스탬프/'
 a| 
컨트롤러 A에서 검색된 DQ 트레이스 데이터



 a| 
'user_provided_file_name-s.b.dq'
 a| 
'보조/타임스탬프/'
 a| 
컨트롤러 B에서 검색된 DQ 트레이스 데이터



 a| 
'user_provided_file_name-s.trace_description.xm
 a| 
'보조/타임스탬프/'
 a| 
향후 데이터 마이닝을 위한 DQ 파일 특성을 설명하는 XML 형식의 설명 파일입니다.

|===


== 최소 펌웨어 레벨입니다

7.75
