---
permalink: commands-a-z/start-cgsnapimage-rollback.html 
sidebar: sidebar 
keywords: start, consistency, group, snapshot, rollback 
summary: start cgSnapImage rollback 명령은 스냅샷 정합성 보장 그룹의 구성원 기본 볼륨에 대한 롤백 작업을 시작합니다. 
---
= 일관성 그룹 스냅샷 롤백 시작 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'tart cgSnapImage rollback' 명령은 스냅샷 정합성 보장 그룹의 구성원 기본 볼륨에 대한 롤백 작업을 시작합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

기본 볼륨의 컨텐츠는 정합성 보장 그룹 스냅샷 볼륨의 시점 컨텐츠와 일치하도록 즉시 변경됩니다. 롤백 작업이 성공적으로 완료된 후 기본 볼륨을 읽기/쓰기 요청에 즉시 사용할 수 있게 됩니다.

정합성 보장 그룹 스냅샷 볼륨과 연결된 저장소 볼륨은 롤백 작업이 완료된 후 발생하는 기본 볼륨과 정합성 보장 그룹 스냅샷 볼륨 간의 새로운 변경 사항을 계속 추적합니다.

멤버 기본 볼륨에 대한 롤백 작업을 중지하려면 'top cgSnapImage rollback' 명령을 사용합니다.



== 구문

[source, cli, subs="+macros"]
----
start cgSnapImage pass:quotes[["_snapCGID:imageID_"]] rollback
memberVolumeSet pass:quotes[("_memberVolumeName1_" ... "_memberVolumeNameN_")]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'cgSnapImage'
 a| 
롤백 작업을 시작할 정합성 보장 그룹 스냅샷 이미지의 이름입니다. 스냅샷 이미지의 이름은 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다.


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' -- 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' -- 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 대괄호([ ]) 안에 묶어야 합니다.



 a| 
엠베볼륨 세트
 a| 
롤백할 일관성 그룹에 있는 하나 이상의 구성원 기본 볼륨의 이름입니다. 각 멤버 기본 볼륨 이름은 큰따옴표(" ")로 괄호 안에 묶습니다.

둘 이상의 볼륨 이름을 입력할 수 있습니다. 모든 볼륨 이름은 대괄호([]) 한 세트로 묶습니다. 각 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다. 각 볼륨 이름은 공백으로 구분합니다.

memberVolumeSet 매개변수를 사용하지 않으면 정합성 보장 그룹의 모든 구성원 볼륨에 롤백 프로세스가 적용됩니다.

|===


== 참고

스냅샷 이미지의 이름은 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 식별자입니다
* 스냅샷 이미지의 식별자입니다


예를 들어 cg1이라는 이름의 전체 일관성 그룹에서 최신 스냅샷 이미지에 대한 롤백 작업을 시작하려면 다음 명령을 사용합니다.

[listing]
----
start cgSnapImage ["CG1:newest"] rollback;
----
cg2라는 일관성 그룹의 기본 볼륨 멤버 memVol1, memVol2 및 memVol3에 대한 스냅샷 이미지 12345의 롤백 작업을 시작하려면 다음 명령을 사용합니다.

[listing]
----
start cgSnapImage ["CG2:12345"] rollback memberVolumeset=("memVol1 memVol2 memVol3");
----


== 최소 펌웨어 레벨입니다

7.83
