---
permalink: commands-a-z/start-storagearray-controllerhealthimage-controller.html 
sidebar: sidebar 
keywords: start, storage, array, controller, health, image 
summary: start storageArray controllerHealthImage 컨트롤러 명령은 컨트롤러 상태 이미지 기능을 지원하는 스토리지 어레이에서 스토리지 어레이 컨트롤러 상태 이미지를 생성합니다. 
---
= 스토리지 배열 컨트롤러 상태 이미지를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'tart storageArray controllerHealthImage controller' 명령은 컨트롤러 상태 이미지 기능을 지원하는 스토리지 어레이에서 스토리지 어레이 컨트롤러 상태 이미지를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
펌웨어 버전 8.20에서는 코어 덤프 매개변수가 controllerHealthImage 매개 변수로 대체됩니다.

====
[NOTE]
====
이 명령은 기술 지원 부서의 지시에 따라서만 사용할 수 있습니다.

====
스토리지 어레이에서 컨트롤러 상태 이미지 기능을 지원하지 않으면 명령을 실행하면 오류가 반환됩니다.



== 구문

[source, cli]
----
start storageArray controllerHealthImage controller [(a|b)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러
 a| 
이 매개 변수는 컨트롤러 상태 이미지를 생성할 컨트롤러를 지정합니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다. 컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.

|===


== 참고

이 명령은 선택된 컨트롤러가 캐시에 코어 데이터를 덤프하도록 합니다. 캐시 데이터의 복제본을 호스트 파일에 저장하려면 'Save storageArray controllerHealthImage' 명령을 사용합니다.



== 최소 펌웨어 레벨입니다

7.83

8.20은 '코어 덤프' 매개변수를 'controllerHealthImage' 매개변수로 대체합니다.
