---
permalink: commands-a-z/start-secureerase-drive.html 
sidebar: sidebar 
keywords: start, fde, secure, drive, erase 
summary: 'start secureErase drive 명령을 사용하면 하나 이상의 FDE(전체 디스크 암호화) 드라이브에서 모든 데이터가 지워지므로 FDE 드라이브로 다시 사용할 수 있습니다.' 
---
= FDE 보안 드라이브 지우기 시작 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Start secureErase drive" 명령을 사용하면 하나 이상의 FDE(전체 디스크 암호화) 드라이브에서 모든 데이터가 삭제되므로 FDE 드라이브로 다시 사용할 수 있습니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 보안 관리자 역할이 있어야 합니다.



== 상황

FDE 드라이브가 더 이상 보안 볼륨 그룹 또는 디스크 풀에 속하지 않거나 보안 키를 알 수 없는 경우에만 이 명령을 실행합니다.

[NOTE]
====
드라이브가 잠겨 있고 잠금 해제할 보안 키를 사용할 수 없는 경우 FIPS 드라이브를 지우려면 'Set drive securityID' 명령을 사용합니다.

====


== 구문

[source, cli, subs="+macros"]
----
[start secureErase (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'늑대'나 '늑대'가 있습니다
 a| 
고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

[NOTE]
====
드라이브 목록에 스토리지 배열의 모든 드라이브가 포함될 수 없거나 명령이 거부됩니다. 모든 드라이브를 안전하게 지우려면 이 명령을 두 번 실행하여 두 개의 별도 그룹에 드라이브 목록을 지정합니다.

====
|===


== 참고

컨트롤러 펌웨어는 FDE 드라이브에 대한 액세스를 제한하는 잠금을 생성합니다. FDE 드라이브는 Security Capable이라는 상태를 가집니다. 보안 키를 생성할 때 상태가 보안 사용으로 설정되고, 이는 스토리지 어레이 내에 있는 모든 FDE 드라이브에 대한 액세스를 제한합니다.



== 최소 펌웨어 레벨입니다

7.40
