---
permalink: commands-a-z/start-volumegroup-export.html 
sidebar: sidebar 
keywords: start, volume, group, export 
summary: start volumeGroup export 명령은 볼륨 그룹을 내보낸 상태로 이동합니다. 
---
= 볼륨 그룹 내보내기를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Start volumeGroup export 명령은 볼륨 그룹을 Exported 상태로 이동합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

그런 다음 볼륨 그룹을 구성하는 드라이브를 제거하고 다른 스토리지 배열에 드라이브를 재설치할 수 있습니다.

[CAUTION]
====
에 나열된 단계를 먼저 수행하지 않으면 이 단계를 수행하지 마십시오 xref:../get-started/learn-about-volume-group-migration.html[볼륨 그룹 마이그레이션에 대해 알아보십시오.]

====
[NOTE]
====
볼륨 그룹 내에서는 기능과 연결된 볼륨을 한 스토리지 어레이에서 다른 스토리지 어레이로 이동할 수 없습니다.

====


== 구문

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] export
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
볼륨그룹
 a| 
내보낼 볼륨 그룹의 이름입니다. 볼륨 그룹 이름은 대괄호([])로 묶어야 합니다.

|===


== 참고

이 명령이 성공하면 'Start volumeGroup import' 명령을 실행하여 볼륨 그룹을 전체 상태로 이동을 완료하면 볼륨 그룹이 새 스토리지 어레이에 사용할 수 있게 됩니다.

하드웨어 문제로 인해 내보내기가 완료되지 않아 이 명령이 실패하는 경우 'Set volumeGroup forceState' 명령어를 사용한다. '볼륨 그룹 forceState' 명령을 사용하면 볼륨 그룹을 가져올 때 '볼륨 그룹 가져오기 시작' 명령을 사용할 수 있습니다.

볼륨 그룹이 Exported 상태 또는 Forced 상태에 있으면 스토리지 배열에서 볼륨 그룹을 구성하는 드라이브를 제거할 수 있습니다. 다른 스토리지 배열에 드라이브를 재설치할 수 있습니다.



== 최소 펌웨어 레벨입니다

7.10
