---
permalink: commands-a-z/start-increasevolumecapacity-volume.html 
sidebar: sidebar 
keywords: increase, capacity, volume, disk pool, volume, group 
summary: start increeVolumeCapacity volume 명령은 디스크 풀 또는 볼륨 그룹의 표준 볼륨 또는 저장소 볼륨 용량을 늘립니다. 
---
= 디스크 풀 또는 볼륨 그룹에서 볼륨의 용량을 늘립니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'start increeVolumeCapacity volume' 명령은 디스크 풀 또는 볼륨 그룹의 표준 볼륨 또는 저장소 볼륨 용량을 늘립니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

이 명령에서 표준 볼륨을 일반 볼륨이라고도 합니다.

[NOTE]
====
이 명령을 사용하여 씬 볼륨의 용량을 늘릴 수 없습니다.

====


== 구문

[listing, subs="+macros"]
----
pass:quotes[start increaseVolumeCapacity volume="_volumeName_"
incrementalCapacity=_volumeCapacity_]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'볼륨'
 a| 
용량을 늘리려는 디스크 풀 또는 볼륨 그룹의 볼륨 이름입니다. 볼륨 이름은 큰따옴표(" ")로 묶어야 합니다.



 a| 
믿을 수 없습니다
 a| 
볼륨에 대한 스토리지 크기(용량)를 증가시키는 설정입니다. 크기는 바이트, KB, MB, GB 또는 TB 단위로 정의됩니다. 기본값은 '바이트'입니다.



 a| 
'addDrives'입니다
 a| 
볼륨에 새 드라이브를 추가하는 설정입니다. 고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.

[NOTE]
====
addDrives 매개변수는 볼륨 그룹의 용량을 늘리는 데만 사용할 수 있습니다. 매개 변수를 사용하여 디스크 풀의 용량을 늘릴 수 없습니다.

====
|===


== 참고

경우에 따라 'drive' 매개 변수가 명령 구문에 대한 올바른 입력으로 나타날 수 있습니다. 그러나 이 명령에는 drive 매개변수를 사용할 수 없습니다.

'증가 용량' 매개 변수를 설정하면 중지할 수 없는 장기 실행 작업이 시작됩니다. 장기 실행 작업은 백그라운드에서 수행되며 다른 명령을 실행하지 못하도록 차단하지 않습니다. 장시간 실행 작업의 진행률을 표시하려면 'show volume actionProgress' 명령을 사용합니다.

addDrives 매개변수는 고용량 드라이브 트레이와 저용량 드라이브 트레이를 모두 지원합니다. 고용량 드라이브 트레이에는 드라이브를 보관하는 서랍이 있습니다. 드로어는 드라이브 트레이에서 밀어 드라이브에 액세스할 수 있도록 합니다. 저용량 드라이브 트레이에는 서랍이 없습니다. 고용량 드라이브 트레이의 경우 드라이브 트레이의 ID, 드로어의 ID 및 드라이브가 상주하는 슬롯의 ID를 지정해야 합니다. 저용량 드라이브 트레이의 경우 드라이브 트레이의 ID와 드라이브가 있는 슬롯의 ID만 지정하면 됩니다. 저용량 드라이브 트레이의 경우 드라이브 트레이 ID를 지정하고 드로어의 ID를 0으로 설정한 다음 드라이브가 상주하는 슬롯의 ID를 지정하는 방법도 있습니다.



== 최소 펌웨어 레벨입니다

7.83
