---
permalink: commands-a-z/start-storagearray-configdbdiagnostic.html 
sidebar: sidebar 
keywords: start, storage, array, configuration, database, diagnostic 
summary: start storageArray configDbDiagnostic 명령은 구성 데이터베이스에 대해 일관성 검사를 실행합니다. 
---
= 스토리지 배열 구성 데이터베이스 진단을 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'tart storageArray configDbDiagnostic' 명령은 구성 데이터베이스에 대해 일관성 검사를 실행합니다.



== 지원되는 어레이

이 명령은 E2700, E5600, E2800, E5700, 기타 스토리지 어레이를 포함한 모든 개별 스토리지 어레이에 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 스토리지가 제공됩니다.



== 역할

E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 구문

[listing]
----
start storageArray configDbDiagnostic
[sourceLocation=(disk | onboard) |
diagnosticType=(fileSystem | mirror) |
controller[(a|b)]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'소스 위치'
 a| 
이 매개 변수는 데이터베이스의 위치를 지정합니다.

* "디스크"는 데이터가 드라이브의 데이터베이스에서 직접 나온다는 것을 나타냅니다
* 'Onboard'는 RPA 메모리 위치에서 데이터가 제공됨을 나타냅니다


기본 위치는 "디스크"입니다.



 a| 
진단 유형
 a| 
데이터베이스에서 실행할 진단 테스트 수준입니다. 다음 테스트 레벨 중 하나를 실행할 수 있습니다.

파일 시스템 -- 이 옵션은 데이터베이스의 구조적 무결성을 검사합니다.

대칭 복사 -- 이 옵션을 사용하여 실행되는 테스트는 '소스 위치' 매개 변수의 값에 따라 달라집니다.

* '* sourceLocation*' 파라미터를 disk로 설정하면 peer controller가 블록 점검을 시작한다.
* '* sourceLocation*' 파라미터를 'Onboard'로 설정하면 peer controller는 record check를 시작한다.


[NOTE]
====
'대칭 복사' 옵션은 명령줄 또는 스크립트 편집기에서만 실행할 수 있습니다. 이 옵션은 스토리지 관리 소프트웨어 GUI를 통해 사용할 수 없습니다. '미러' 옵션은 중지할 수 없는 긴 실행 작업을 시작합니다.

====
기본값은 파일 시스템입니다.



 a| 
컨트롤러
 a| 
진단 테스트를 실행할 데이터베이스가 있는 컨트롤러입니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다.

|===


== 참고

이 명령은 구성 데이터베이스에 대해 일관성 검사를 실행합니다. 모든 데이터베이스 레코드가 선택됩니다. 오류 데이터는 디스크의 데이터 폴더에 있는 파일에 자동으로 기록됩니다. 출력 파일을 지정할 필요가 없습니다.

[NOTE]
====
'Mirror'로 설정된 'diagnosticType' 파라미터에 대한 정합성 검사를 수행하고 '온보드'로 설정된 '소스 위치' 파라미터에 대해 장기간 작업을 실행할 수 있습니다. 이 경우 호스트 I/O 처리에 부정적인 영향을 미칠 수 있습니다. 이 작업은 지원 조직의 지시에 따라서만 수행해야 합니다.

====
진단 테스트가 완료되면 컨트롤러 펌웨어가 다음 결과 중 하나를 반환합니다.

* 진단 완료 시 오류가 발생하지 않습니다. ZIP 파일이 생성되지 않았습니다
* 오류 진단 완료. "에 생성된 ZIP 파일을 참조하십시오
+
'+...\Install_dir\data\FirmwareUpgradeReports\timestamp_buildNo.zip+'



구성 데이터베이스에서 진단 테스트가 불일치를 감지하면 컨트롤러 펌웨어가 다음 작업을 수행합니다.

* 비일관성에 대한 설명을 반환합니다
* 원시 이진 데이터가 포함된 ZIP 파일을 저장합니다


컨트롤러 펌웨어는 ZIP 파일을 다음 위치에 저장합니다.

'+...\Install_dir\data\FirmwareUpgradeReports\timestamp_buildNo.zip+'

이진 데이터를 사용하여 문제의 원인을 확인하거나 이진 데이터가 포함된 파일을 기술 지원 부서에 보낼 수 있습니다.

데이터베이스 구성 진단 테스트를 중지하려면 'sTOP storageArray configDbDiagnostic' 명령을 사용합니다.

또한 스토리지 관리 소프트웨어 GUI를 통해 데이터베이스 구성 진단 테스트를 시작할 수 있지만 스토리지 관리 소프트웨어 GUI를 통해 데이터베이스 구성 진단 테스트를 중지할 수는 없습니다. 실행 중인 진단 테스트를 중지하려면 'sTOP storageArray configDbDiagnostic' 명령을 사용해야 합니다.



== 최소 펌웨어 레벨입니다

7.75

7.83은 다음과 같은 매개 변수를 추가합니다.

* '소스 위치'
* 진단 유형
* 컨트롤러

