---
permalink: commands-a-z/start-volumegroup-fullprovisioning.html 
sidebar: sidebar 
keywords: start, volume, group, full provision 
summary: start volumeGroup fullProvisioning 명령은 디스크 풀의 모든 볼륨에서 전체 프로비저닝 작업을 시작하고 필요에 따라 볼륨 그룹에서 리소스 프로비저닝을 비활성화합니다. 
---
= 볼륨 그룹 전체 프로비저닝을 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'Start volumeGroup fullProvisioning' 명령은 디스크 풀의 모든 볼륨에 대해 전체 프로비저닝 작업을 시작하고 필요에 따라 볼륨 그룹의 리소스 프로비저닝을 비활성화합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치된 경우 EF600 및 EF300 어레이를 비롯한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

EF600 및 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

리소스 프로비저닝 기능은 표준 볼륨보다 할당되지 않은 상태에서 드라이브 블록의 더 큰 부분을 남겨 두어 SSD 마모 수명을 향상시키고 쓰기 성능을 향상합니다. 리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 드라이브 용량이 할당(볼륨에 할당)되지만 드라이브 블록은 볼륨 생성 중에 할당 해제(매핑 해제)됩니다. 필요한 경우 드라이브 블록이 할당되어 호스트 쓰기 입출력을 완료합니다. 호스트 매핑 해제 작업은 드라이브 블록을 다시 할당되지 않은 상태로 반환할 수 있습니다. 또한 리소스 프로비저닝을 통해 시간 제한이 있는 백그라운드 초기화가 제거되므로 큰 볼륨을 빠르게 초기화할 수 있습니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Deallocated or UnWritten Logical Block Error Enable) 오류 복구 기능이 지원됩니다. 성능 향상은 드라이브 모델 및 용량에 따라 다릅니다.

전체 프로비저닝 형식을 사용하면 볼륨 그룹의 볼륨에 필요한 모든 블록이 드라이브에 완전히 매핑됩니다. 이 명령은 리소스 프로비저닝된 볼륨 그룹에만 적용할 수 있습니다. 'disableResourceProvisioning' 옵션이 'false'로 설정되어 있지 않으면 볼륨이 리소스 프로비저닝되고 볼륨 그룹에서 생성된 새 볼륨이 리소스 프로비저닝됩니다. 리소스 프로비저닝을 사용하지 않도록 설정하는 옵션이 "true"로 설정되어 있으면 볼륨은 더 이상 리소스를 프로비저닝하지 않으며 볼륨 그룹에서 생성된 새 볼륨은 리소스를 프로비저닝하지 않습니다.



== 구문

[listing]
----
start volumeGroup[volumeGroupName] fullProvisioning [disableResourceProvisioning=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
볼륨그룹
 a| 
전체 프로비저닝 작업을 시작할 볼륨 그룹입니다. 볼륨 그룹 이름은 대괄호([])로 묶어야 합니다.



 a| 
dissableResourceProvisioning
 a| 
전체 프로비저닝 작업이 완료된 후 리소스 프로비저닝을 해제해야 하는지 여부를 지정하는 설정입니다. 리소스 프로비저닝을 사용하지 않도록 설정하려면 이 옵션을 "false"로 설정합니다. 기본값은 "true"입니다.

[NOTE]
====
볼륨 그룹 및 연결된 모든 볼륨에서 리소스 프로비저닝을 다시 설정하려면 'Start Volume Group Resource Provisioning' 명령을 사용합니다.

====
|===


== 최소 펌웨어 레벨입니다

11.72
