---
permalink: commands-a-z/start-ioclog.html 
sidebar: sidebar 
keywords: start, input, output, controller, ioc, dump 
summary: start IOCLog 명령은 호스트와 컨트롤러 간의 데이터 전송 IOC 로그의 덤프를 생성합니다. 
---
= 입출력 컨트롤러(IOC) 덤프 시작 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'IOCLog 시작' 명령은 호스트와 컨트롤러 간의 데이터 전송 IOC 로그 덤프를 생성합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

컨트롤러는 "a" 또는 "b"로 식별됩니다. 각 컨트롤러에는 최대 8개의 호스트 채널이 포함될 수 있습니다. 각 채널은 1부터 4까지의 숫자로 고유하게 식별됩니다.



== 구문

[source, cli]
----
start IOCLog [(a1 | a2 | a3 | a4 | a5 | a6 | a7 | a8 | b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)]
[overwrite=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
컨트롤러-채널 식별자
 a| 
이 매개변수는 IOC 덤프를 생성할 컨트롤러 및 호스트 채널을 지정합니다. 유효한 컨트롤러 식별자는 a나 b이며, 여기서 a는 A 슬롯의 제어기이고 b는 B 슬롯의 제어기입니다 호스트 채널에는 숫자 식별자가 있습니다. 컨트롤러 식별자 및 호스트 채널 식별자는 대괄호([ ])로 묶어야 합니다.

유효한 컨트롤러 식별자 및 호스트 채널 값은 , , , , , 입니다 `a1` `a2` `a3` `a4` `a5`. `a6` `a7`, , `a8`, , , , `b1` `b2` `b3` `b4`, , `b5`, , , , `b6` `b7` `b8`또는.

컨트롤러를 지정하지 않으면 스토리지 관리 소프트웨어에서 구문 오류를 반환합니다.



 a| 
덮어쓰기를 선택합니다
 a| 
이 매개 변수는 새 IOC 로그 덤프가 기존 덤프를 덮어쓰도록 합니다. 기존 덤프를 덮어쓰려면 이 매개변수를 "true"로 설정합니다. 기본값은 'false'입니다.

|===


== 참고

이 명령은 선택한 컨트롤러의 IOC에서 디버그 로그를 생성하고 압축된 형식으로 데이터를 컨트롤러의 영구 메모리 버퍼에 저장합니다. 'IOCLog 저장' 명령어를 이용하여 디버그 로그에서 데이터를 조회할 수 있다. 컨트롤러가 다음 조건에 대해 오류를 반환합니다.

* 컨트롤러 플랫폼 및 HIC는 IOC 덤프를 지원하지 않습니다.
* 지정된 컨트롤러에 미해결 IOC 덤프가 있으며 덮어쓰기 매개 변수는 FALSE입니다.
* 지정된 컨트롤러 식별자 또는 채널 식별자가 유효한 범위를 벗어났습니다.




== 최소 펌웨어 레벨입니다

8.20
