---
permalink: commands-a-z/start-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: start, drive channel, fault, isolation, diagnostics 
summary: start driveChannel defaultDiagnostics 명령은 드라이브 채널 장애 격리 진단을 실행하고 결과를 저장합니다. 
---
= 드라이브 채널 오류 격리 진단 시작 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'tart driveChannel defaultDiagnostics' 명령은 드라이브 채널 장애 격리 진단을 실행하고 결과를 저장합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
펌웨어 버전 8.10에서는 'tart driveChannel defaultDiagnostics' 명령이 사용되지 않습니다.

====


== 구문

[source, cli, subs="+macros"]
----
start driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)]
controller [(a|b)] faultDiagnostics
testDevices=[all |
controller=(a|b) |
esms=pass:quotes[[_trayID1_ (left | right), ... , _trayIDN_] (left | right)] |
drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]
|[dataPattern=(fixed | pseudoRandom) |
patternNumber=[pass:quotes[(_0xhexadecimal_ | _number_)]] |
pass:quotes[maxErrorCount=_integer_] |
pass:quotes[testIterations=_integer_] |
pass:quotes[timeout=_timeInterval_]]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'시리채널'
 a| 
찾을 드라이브 채널의 식별자 번호입니다. 드라이브 채널의 ID 번호는 1, 2, 3, 4, 5입니다. 6, 7, 8. 드라이브 채널 식별자 번호는 대괄호([ ])로 묶어야 합니다.



 a| 
컨트롤러
 a| 
테스트할 컨트롤러의 식별자 문자입니다. 유효한 컨트롤러 식별자 값은 a나 b이며, 여기서 a는 A 슬롯의 컨트롤러이고 b는 B 슬롯의 컨트롤러입니다 컨트롤러 식별자를 대괄호([ ])로 묶습니다.



 a| 
테스트기기
 a| 
테스트할 장치(컨트롤러, 환경 서비스 모듈[ESM] 또는 드라이브)의 식별자입니다. 진단하려는 장치에 대한 모든 식별자를 지정하거나 입력할 수 있습니다. 컨트롤러 식별자는 A 또는 b이며 여기서 a는 슬롯 A의 RAID 컨트롤러 모듈이고 b는 슬롯 B의 RAID 컨트롤러 모듈입니다

"esms" 식별자는 트레이 ID와 왼쪽 또는 오른쪽으로, 트레이 ID는 0에서 99 사이의 값이며, 왼쪽 또는 오른쪽은 후면에서 드라이브 트레이를 볼 때 결정됩니다.

'드라이브' 식별자에는 트레이 식별자, 용지함에 서랍이 있는 문서함 식별자 및 슬롯 식별자가 포함됩니다.

고용량 드라이브 트레이의 경우 트레이 ID 값, 서랍 ID 값 및 드라이브의 슬롯 ID 값을 지정합니다. 저용량 드라이브 트레이의 경우, 트레이 ID 값과 드라이브의 슬롯 ID 값을 지정합니다. 용지함 ID 값은 0 ~ 99입니다. 문서함 ID 값은 1에서 5까지.

모든 슬롯 ID 최대값은 24입니다. 슬롯 ID 값은 용지함 모델에 따라 0 또는 1에서 시작합니다. E2800 및 E5700 컨트롤러와 호환되는 드라이브 트레이는 0부터 시작하는 슬롯 ID 번호가 있습니다. E2700 및 E5600 컨트롤러와 호환되는 드라이브 트레이는 슬롯 ID 번호가 1부터 시작합니다.

트레이 ID 값, 문서함 ID 값 및 슬롯 ID 값은 대괄호([])로 묶습니다.



 a| 
다타패턴
 a| 
테스트할 반복성 방법입니다.



 a| 
pattern Number
 a| 
테스트를 실행하는 데 사용할 16진수 데이터 패턴입니다. 이 숫자는 0000-FFFF의 16진수일 수 있습니다. 16진수를 나타내려면 앞에 0x 를 배치해야 합니다.



 a| 
'maxErrorCount'입니다
 a| 
검사를 종료하기 전에 허용할 오류 수입니다.



 a| 
'테스트 반복'
 a| 
검사를 반복할 횟수.



 a| 
'시간 초과'입니다
 a| 
테스트를 실행할 시간(분)입니다.

|===


== 참고

테스트할 장치 유형을 두 개 이상 입력할 수 있으며 실행할 테스트 유형을 두 개 이상 입력할 수 있습니다.

'드라이브 채널 기본 진단 시작' 명령을 사용하여 '드라이브 채널 기본 진단' 명령과 '최상위 드라이브 채널 기본 진단' 명령을 사용합니다. 진단 테스트 결과를 파일에 저장하고 진단 테스트를 중지하려면 이러한 명령이 필요합니다.

유효한 'pattern Number' 항목은 0xA5A5, 0x3C3C, 8787, 1234 등입니다.

언제든지 Ctrl+C를 눌러 이 명령을 중지할 수도 있습니다.



== 최소 펌웨어 레벨입니다

7.15
