---
permalink: commands-a-z/stop-snapimage-rollback.html 
sidebar: sidebar 
keywords: stop, snapshot, image, rollback 
summary: SnapImage 롤백 중지 명령은 SnapImage 롤백 시작 명령에 의해 시작된 스냅샷 이미지 롤백 작업을 중지합니다. 
---
= 스냅샷 이미지 롤백을 중지합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'SnapImage rollback 시작' 명령은 'SnapImage 롤백 시작' 명령으로 시작된 스냅샷 이미지 롤백 작업을 중지합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800, E5700, EF600 및 EF300 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800, E5700, EF600 또는 EF300 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
스냅샷 이미지 롤백 작업을 취소하면 기본 볼륨이 유효하지 않거나 일관되지 않은 데이터가 있을 수 있는 결정되지 않은 상태가 됩니다. 관련 스냅샷 이미지 볼륨이 비활성화되고 사용할 수 없게 됩니다.

====


== 구문

[source, cli, subs="+macros"]
----
pass:quotes[stop snapImage [_snapCGID:imageID_] rollback]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
'냅이미지'
 a| 
롤백 작업을 중지하려는 스냅샷 이미지의 이름입니다. 스냅샷 이미지의 이름은 다음 두 부분으로 구성됩니다.

* 스냅샷 그룹의 이름입니다
* 스냅샷 그룹의 스냅샷 이미지에 대한 식별자입니다


스냅샷 이미지의 식별자는 다음 중 하나일 수 있습니다.

* 스냅샷 그룹에 있는 스냅샷의 시퀀스 번호인 정수 값입니다.
* '최신' -- 스냅샷 그룹에서 생성된 최신 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.
* '가장 오래된 항목' -- 스냅샷 그룹에서 생성된 가장 빠른 스냅샷 이미지를 표시하려면 이 옵션을 사용합니다.


스냅샷 이미지 이름은 큰따옴표(" ")로 대괄호([ ]) 안에 묶어야 합니다.

|===


== 참고

스냅샷 이미지의 이름은 콜론(:)으로 구분된 두 부분으로 구성됩니다.

* 스냅샷 그룹의 식별자입니다
* 스냅샷 이미지의 식별자입니다


예를 들어 snapGroup1 이라는 이름의 스냅샷 그룹에서 스냅샷 이미지 12345에 대한 롤백 작업을 중지하려면 다음 명령을 사용합니다.

[listing]
----
stop snapImage ["snapGroup1:12345"] rollback;
----
이름이 snapGroup1인 스냅샷 그룹에서 가장 최근의 스냅샷 이미지에 대한 롤백 작업을 중지하려면 다음 명령을 사용합니다.

[listing]
----
stop snapImage ["snapGroup1:newest"] rollback;
----


== 최소 펌웨어 레벨입니다

7.83
