---
permalink: commands-a-z/suspend-syncmirror-primaries.html 
sidebar: sidebar 
keywords: suspend, synchronous, mirror 
summary: suspend SyncMirror 운영 명령은 동기 미러링 작업을 일시 중단합니다. 
---
= 동기식 미러링 일시 중단 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SyncMirror 운영 중단 명령은 동기 미러링 작업을 일시 중단합니다.



== 지원되는 어레이

이 명령은 모든 SMcli 패키지가 설치되어 있는 경우 E4000, E2700, E5600, E2800 및 E5700 어레이를 포함한 모든 개별 스토리지 어레이에 적용됩니다.



== 역할

E4000, E2800 또는 E5700 스토리지 어레이에서 이 명령을 실행하려면 스토리지 관리자 역할이 있어야 합니다.



== 상황

[NOTE]
====
이 명령의 이전 버전에서는 기능 식별자가 'remoteMirror'였습니다. 이 기능 식별자는 더 이상 유효하지 않으며 SyncMirror로 대체됩니다.

====


== 구문

[source, cli, subs="+macros"]
----

suspend syncMirror (primary pass:quotes[[_primaryVolumeName_]]
primaries pass:quotes[[_primaryVolumeName1_ ... _primaryVolumeNameN_])]
[writeConsistency=(TRUE | FALSE)]
----


== 매개 변수

[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
1차
 a| 
작업을 일시 중단하려는 운영 볼륨의 이름입니다. 볼륨 이름은 대괄호([ ])로 묶어야 합니다. 볼륨 이름에 특수 문자나 숫자가 있는 경우 볼륨 이름은 대괄호 안에 큰따옴표(" ")로 묶어야 합니다.



 a| 
'경선대회'
 a| 
작업을 일시 중단하려는 여러 운영 볼륨의 이름입니다. 모든 볼륨의 속성이 동일합니다. 다음 규칙을 사용하여 볼륨의 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.


볼륨 이름에 특수 문자나 숫자가 있으면 다음 규칙을 사용하여 이름을 입력합니다.

* 모든 이름은 대괄호([ ])로 묶어야 합니다.
* 각 이름은 큰따옴표(" ")로 묶어야 합니다.
* 각 이름을 공백으로 구분합니다.




 a| 
쓰기 일관성
 a| 
이 매개 변수는 이 명령에서 식별된 볼륨이 쓰기 정합성 보장 그룹에 있는지 또는 분리되어 있는지 여부를 정의합니다. 동일한 쓰기 정합성 보장 그룹의 볼륨에 대해 이 매개 변수를 "true"로 설정합니다. 분리된 볼륨의 경우 이 매개변수를 "false"로 설정합니다.

|===


== 참고

"writeConsistency" 매개 변수를 "true"로 설정하면 볼륨은 쓰기 정합성 보장 그룹(또는 그룹)에 있어야 합니다. 이 명령은 볼륨을 포함하는 모든 쓰기 정합성 보장 그룹을 일시 중단합니다. 예를 들어, 볼륨 A, B 및 C가 쓰기 정합성 보장 그룹에 있고 원격 상대 A, B, C가 있는 경우 다음 명령을 사용합니다.

[listing]
----
suspend syncMirror volume ["A"] writeConsistency=TRUE
----
A-A', B-B', C-C''를 일시 중단합니다. 쓰기 일관성 그룹 1={A, B, C} 및 쓰기 일관성 그룹 2={D, E, F}가 있는 경우 명령은 다음과 같습니다.

[listing]
----
suspend syncMirror volumes ["A" "D"] writeConsistency=TRUE
----
두 쓰기 정합성 보장 그룹을 모두 일시 중지합니다.



== 최소 펌웨어 레벨입니다

6.10
